<a href="https://colab.research.google.com/github/Yanzhi-002/Yanzhi/blob/main/Create_spreadsheet_Factiva_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Collecting news data from Factiva and saving it in a Dataframe

**For detailed instructions on how to collect Factiva data, review this [step by step guide with images](https://docs.google.com/document/d/1C9crxk6kdYJZqU0bEx1UZMxFZpowQe3ESQO_hA1wUK0/edit?usp=sharing)**

* Step 1: Locate the `Factiva database` on the `Columbia University website`

* Step 2: Enter your search term(s) and click `Search`

* Step 3: Click `Display Options` and select `Full Article/Report plus Indexing`

* Step 4: Select `Duplicates: Identical`

* Step 5: Click the ✅ to select the articles you want to save

* Step 6: Click the `print` icon, then select `Article Format`

* Step 7: If your `print dialogue opens`, click `cancel`

* Step 8: From the `print preview page`, type `command` + `u` from your keyboard. An HTML view should open

* Step 9: From the HTML view, `select all` the text and then `copy` it

* Step 10: `Paste` the HTML code into the `html_code` variable in the `Google Colab worksheet`

In [1]:
html_code = """
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<title>Factiva</title>
<script>window.ddjskey='D428D51E28968797BC27FB9153435D';window.ddoptions={enableCookieDomainFallback:true};</script><script type='text/javascript' src='/datadome/tags.js' async></script>
<link rel="stylesheet" type="text/css" media="all" href="/css/ui.dotcom1392700ui4sr.ashx" />
<link rel="stylesheet" type="text/css" media="all" href="/css/DotComHeadlines1392700ui4sr.ashx" />
<link rel="stylesheet" type="text/css" media="all" href="/css/fcp/print1392700ui4sr.ashx" />

<script type="text/javascript" src="/gen/modernizr.underscore0392700ui4sr.ashx"></script>
<script type="text/javascript" src="/jquery/jquery.bundle0392700ui4sr.ashx"></script>
<script type="text/javascript" src="/xlib/x_combined0392700ui4sr.ashx"></script>
<script type="text/javascript" src="/gen/RecordGenericOD0392700ui4sr.ashx"></script>
<script type="text/javascript" src="/gen/ui.dotcom0392700ui4sr.ashx"></script>
<script type="text/javascript" src="/controls/search/jquery.overlay.1.30392700ui4sr.ashx"></script>

</head>
<body class=''><a id="skip-main" class="skip-main"  href="#PageBaseForm">Skip to main content</a>
<form name="LinkForm" id="LinkForm" method="post"><input type="hidden" id="_XFORMSTATE" name="_XFORMSTATE" value="" /><input type="hidden" id="_XFORMSESSSTATE" name="_XFORMSESSSTATE" value="" /><div id="LinkFormExElem"></div></form>
<script type="text/javascript" src="../gen/funcTwo.js"></script>
<div id="navcontainer" class="fcpNavContainer">
<table cellpadding="0" cellspacing="0" border="0" width="100%">
<tr>
<td class="factivalogo"><h1>Dow Jones Factiva</h1></td>
<td class="djrlogo" align="right"><span>Dow Jones</span></td>
</tr>
</table>
</div>
<form name="PageBaseForm" method="post" action="/hp/printsavews.aspx?ppstype=Article&amp;pp=Print&amp;hc=All" id="PageBaseForm">
<div>
<input type="hidden" name="PageScriptManager_HiddenField" id="PageScriptManager_HiddenField" value="" />
<input type="hidden" name="_XFORMSESSSTATE" id="_XFORMSESSSTATE" value="H4sIAAAAAAAEAHWSW3OiMBTHv0onz9iehIRL9mVBQVu7KqKu9jIdEVS6Klax1grffU+wO9OXJcDk3PP/wRnkeSjJzXJ7s92lm3w/fU+O++vpfvtBNGqZ8kwlmRu6ZSc8rk3BMGucUasWzTmvUZpE3IzAgEQQzZAk2RCtKqHKokZl4QQhQQMVzo/7163GsLUkcb7ONhr8cL3bu7GGCSqbAFgGKVXcBKMBXFie7rsAzDAdYYFluw6vM4+Bp4POwac2CB8w4joAFAqGjyjg2xKFgOJ/S6Uy4FZBAadySWaHVW2T7H7OstVhHaXT6yQ+EE1I4hndLmuN6kFr1PObwV3IJw9md9IYBkSzKpUUxZYas5XxeGaS2ESpjrN8lq2VZFY+l5qNLCitgGAeRTdFuVxSW2NCueDi4hJbgKZXmcoH2NuoanBjqijVvhow9FiSIM6rGiBsKKh2leHHYPpXAcVwJ8vDfLrLkxgPo0virFaYwf/NhLLCrnvADQDwEDZSR6iWZRWAXIHB94tS9fraq5temBKlkVT8Dqs0whF4SBxHh6GjgEDFOVRQHwnlnDwjP1A162iNPwGyIOem15HncCCfyKRXh559+E0ncAimy9SJV/rsLdhCvTXMfqWiGTQHKTt1Jp+cdmbvC9b+Q/PV2/CuPw2c9zh7PbVfmAv3cSMNxnd1t2e+Cb3LRavtcTofLaJbvx2Pj9371+V+Fxwxd9JPg/283el1HjYjl7Mo6sKgbYdxZB2htdiF8TgWNPR16iyW/FSPeqIfNWngw8Os24eo7ovjIPlobOip4S4+X5i//yjYEylLFAcXmTW4oCjLvwPqQ6OCAwAA" />
<input type="hidden" name="_XFORMSTATE" id="_XFORMSTATE" value="H4sIAAAAAAAEALVd627jxpJ+lY734BjIqm2RutpBMPDYHtuT8eXYmhiTzeKgRbZEjnkLL5blTIC8w54f5wC7wO7vfYtd7IvkSbaqmqRI8TLSxAkyM5Zot/qrrq766tLtn7XDn+H/Xv9Q62j9w25nfLjjzS07iv3QNoQTSREallhEwU7n4HDnzft3tzsdXTvcmXySjjRi2/fY5JMnF/D30g8f4B/Djpfs+tNe+uef4S0RxrbhSPhqZsM/15868GUoAz+M0xcLOQ3EPHsU2EachNmrqePP6curTzMXf8DAYWEaA5hvD/5oI5w9fDE81OCdAb7qHR50tMHhv/ys3t9h7DLx7IhFsRTmssPsKEqEZ0g2E44Tsdhnf9L29Nc7HRxrcLhjht4hQrcf5R7Ai1IIe69ffzi97Xa7elcfaJquSWfqw8vuiOQznS5luNPRNJyCDp+sH+5Ibwdm+XP3cOdIjbHzSwdeNA/0S2c16UmYuAETnskuhWsKz2Zzn81C32XCfJQhTMuWNHtAgV+JWSxDdm/ZsWTnfhJJ5koZ294cgenrwFKp790f9/uDwSCbiw5zcXEucwK1MOgpwerWwLqX0xsYZQffteI4iA739xeLxZ5je4bveKawnSWKcM/w3f2r0/u7fXz1V7kXWbHrKGk0z6AqDUCLoNgujOfiosa7IB3QPubP2BWo4gdUxGNUwx98KxReLjsRl0QDuvsmtE2xROH0moUzGI3GlalpViocerq1cGzPtEX8mMsFv9hf+KFj7seIksc+R5Q8B8ldxMj9GYfv5bjZOG41/kwY4Slh5CLmC8TILcTIHRFL+NkkMPELjiC4psG/XOtqY0CUyb8JZEn+llRrwDOJRpa/YCi+ftumub85vr5c6TqO7uDqakqEAWDcbNM0D1S/acraoARIdmtdM2awHswSoet7S8bZDJTJ8xcIbNAG7O74kia0rrY9AhYZ7sbImkcqIlN6eyJdZnssCH2uoJqgHmCuYxbKRynInAVk4SQhAXPOpiKOHTkP/QSAPvpgJSJEN2wxCXq3ohA9KTOTgE+31vqZ/5RrfOA7Nggg2veW3JSub4SouiL0Ii6f4lC6duRyR85iHtpzC/72hcnDxPZyi9EwwXWNvZd2CPZzCaY/XKKNuHbsR1uwq+T52f7t139EbCKlh97nBsR2GgoUzKht2a+Obm7vupXFGjgkHE8EKNxNVr15oCKImySywISz69kMpzZundqHyZvT05O1EfXugZraMp5JaW44ucahqpstCIUdgf/J9hOo5/WjcHDKtpE7IfbjzgWLAcsDg3UBrZz7+C4Y9CgJgxBGYJHvSmb4XiTDRxEDOhZIP3BkhwngBODllp0fd2AMWKxQRrYpvZhFwjb3UDIHLdqsacPq7vIybcanW2uzlurynve8jyPva9q+rqf2O5VIbpdtj/sgEbDfKBGeueVMlxumV5T0kR2SQfsBtjgaN0NMQcxGCG+hBMECPEgU/Ik0pDsFGnCkdrumD7rslMX/99/FHxFG6EcRSdL2YGd4AsmccDrMhCWIQA86ZEJDOaf32cyBKUdsYTvO3h6JG8jWlvI2/gh5Czskl/is5MIJJEeQ6ESVXFD8ZiqXdpkbZe32PdBJy54BcpDcvaCdGPveYYPiVwlYLJyHqAM2dwHsMwmI9KJVFuy3X/8eiZnMvRTYIhJrhYAWxNob9EYVL53zNHy6tVhBBaIY2YErPLLMRRqSqW+RU6S6CwKNgdtlpGLQ7Q20wag/3ivRuoYJl73aYs0f70bs6sMxewSf5oPNNvzEMcF9g34LZvkxS5w4FNxJnpIQ3Xr4AHQQFRscCqyFgxvh0hauzcAfevgTMdJyEG2FApe4/cUPF1d3FZUYK583tZ9tb0O73jxSEfethE+XsJGB4tmxC6bscMVYznzg9x7oyXcitpYgI8NKHLaQjoHbc42GFUi+1kZkh6NRheP1gozI4tOttIf2IwxPZFbTeysmm4o02r8nXco+cr/fGw8HulZSkaZZVbxMDveyALdCPIsMRj+ohhR6zmDg6dabxZhGRc6ONHwf6ITMGPbatsm2SnH7ZPR9xWPqp1nEn/NtUPQs/lnYsVXwginrLYc4sQ/hzRoNvmymwRggf+YTMttf4cXFeKk7Pmi0/fT0ReROmrYW/gTZbLlaiDq7RUJZxT31ky1K/94SMZgkkC0YSuVk40oolI7+ClgkEVtwmQL85jICoW61AHZMXMn0F97aCmSyb2Ht9XAO/hjZK3wYcIo4wsiTxIO+tnYXtIu8hlauy1aZepNNlxlhpDd9NJ0RMnvljaubAkNB8CctgrcEUE0rCR0YHkIlYTzQekthWJnUKyHB56Tu/TFSL8t2as/nGOEHQKVhEfxZyjzr2GZxN7QvhlfR/5pUFMkMyTcTUz9RwmI+7AwgN5YUJq5ITSqqsjyWiICZOij6tVX5ccddgjvH0DVbhUr085lV0PQ/chXWrA96ctRFTgLhKBBOAmmVtla29bmxuJXBHrtagm9l30vnf//r+adEPrOF7+2CIZLyAbh5noQFkwSjDgvf2GEjvQPLswSTAsYKeTv8QGyHMiWpuE7aEOwLvKCEglKWPXZn5dJuiajqofT+GGmHMuAeSoI/SkcQPo7QOEDjIBEwPSAQHkqeSaRd4uW0ygSslligpCi1WtX0R7A0QM5ew1qCFntsDs4RI9WY4nJY4CVbCC/usLPrG+b4GBAIFiSeQc+nQqVf28Kl/kGvV9mFVp5/hafb83obiCIssnBMEmgeMmlrJiTO4K9ysfWzqWEknVRalEBD9QddTLNMZhIi+pkdRnG+98v85D2RJpPpwNGTEIQ290lSbREQsKV1Yt1z3QKp2y6wFFNj5C3TjFQU73tLgxcShes7fMUvTIyKzdTTIXyu4HMFnyv4nODXGeB9bawddIfasMgD65CVcgAqYo8XPnPAwsoQKxq+bwJlA52Exc7Ww8fahpgL2NahnMkwlPg99MPgBZHHeCbsdzaV8UKCRl8ghSedvxEPNj4m2wFz7mDWJrUHemsJ4aBf2WjTx5UK97e3BxCyGwJ2Ueh7FKGtolPhSixQZXYY7INEDmJz0za5pIQhvAOuz8SEKLpFCCK9GMslwE8MJzFxOShw4Zg0CFLUXDvQxmNdK2yFWlTFRXkno4hl6cwO8BEwsRisJsEhCTzxQvCUDqo/eERMNrLv/XmCD2AF0wXT97ok4Ur4VoxQz25PrrqVfKEefCQpz0PT2yw+bR6niOtYOPbMDz1QjGPQNtC1G4hFKXlxZs/Zew/MLGWR9dbs/+1pJWlfCMRCuXGOvHmg30dWfvv1b7hOHn2/lxY09NbEf00hAqaiJT+9QEUjHaiCCcLpCAQOVMmDbYv7P/RgV5PLaglHeB6GEKxK7FCE9fbmbnJ6VZHwk0mwPgZRLDfUsOaRqsnjueML5O+PtBZ/j4G/xn7426//YJeTM0rQgx0ADwyuBUzYT4kdM2CMl0dnRwzrA0SDshJna97+4urk+qaqQJEq3oIx8IPN0DUPVEQHWI4tKZUXpDqMC2gO2XdAF+IaypGvXVP9tjXzf/T26IcaiUvFyMRH8bzp2jWPVLZ6sxhMJgRWpcIa7iG1rJSv8zD9j5nTAqTemrdvIZmjweBgWNnwWRGKnm7lVKRpIznccx9TP9IfdofdV+Aiv7WAz6Xl0sz4N316ia2nefMs7I927yWsMriAvLhhSSfAxd9Nk8adVTpHJe1n4JY80wGtwHRzmSLdGaEdBJRCiNgZUIuAqtUtXHKkdQdV9vaUyQyfbu2IH8L4sVy1oxgCok9MrXJDuIGw51ncjw41I0yRjPNadrk2nUu5Yb5FKeNTduY7wLzYJAkf5DL6n/8kQbRQxVFf71e9xSgTBD7dvqlBPmE/yjqhphT4nObHYzW/HF7DLEp28PyU3Z6esKObm3en7BP74Zreen1xlr51/YadX9yx0w+n30AU4pmptYS9RxmiExUBRpZvPIDSgSbRvrs/JxG1Jr2vPtxcV6lA1vvhLQN/02ph0zjr9di7rNZ36pnpDqm6r9eJaS7Zpf9owz4Aa38ObDdid4Hteak17LUypfriZXcevFQdFIcqIruTVGFP2QVgwhjx6sNuBMzDBbJKmyKyjQf4njiEb8ZEAcTavmEDzYpcTP2BUqFAlmAdIZ5UbSmt+e2aAviqaed3V+h9kDbYtv1IQUuTGoALQvGIV2DxHBaPMlRcQeIIiS9WWdemqRclunux6zjIdIw1J4p29DMR+25UyBA6WEEKgek7RW/aa8lgj/q9Xr+xckBPt5bsPBSBZRso2b25tV8qupZfcUp52I7Dp5Jn4DmA5wB+Fa1zhF61uBEvIucp8iwCLVVemmDW+jd0QFVaTXWCcrWfAkeVFJliwsQQYbYtxAxQmGJqgxNZHkWkJhj/Y0aQ6GmvrSFlMBpVZ2tn6o5Pt8+RoOOaiqU+XtWuystQ9WjkyjDHbZWTrCpcxreXHIFzBJ5umhLwfBM0ACrVRkUY+gHVBUGNiWJV06QQuIYxtQGacoYUhkTZkq/uj0e9CrHRhpko8en2uTvfSdypndaQSXbkID3/Eav0FgFBmYJSpjjWkysKB9KFDEcmqYb5lszFvVRBHnIolZjDkjDlZKrM69GnrglM9DtyrT5jWJiM9ubUWanSKiTQltRzf6CPq75vlusmPP2SuvxCyoc92yt2BxYaHxZApAAwB8CcAKNWpkmocoYP0KJUFdq1/sEVWp6hLVfwG6AVZf8aPhz8AdBX5qmuHUo3TzG2l+TdPfkUqzgBcyCpsySptqWYu6Nq80A3TzHj062lOk0CO5AmuCq3UK5OUOdC4LRcG3V7+9qop4/1PIXcMI2y9iHgW4FF+jOwFpZNBAChu2DbYCavQAlfv70Bz/TRnhLLn8Ce8P1wt66aD0EtFruotbLC9YtE5/xqclmTypGq3Gp58YaJiOZxqgG7m3YCgXHHsloh/KP5tlDywVAfjxsdKz3deEXTBXVlHPqhMG2fXKuVVgzS5pQ9EQVPr47Blsz9cHklXPkt6DpQE+vP6NAuzG+zyWhDvdcb/xkn+m131ZtQP99Se17oR9IADQqpKhNhF6YNBgWszwxDYBIMPDRERBrfb0miHvS6fa1RPvR0a433ko/AvsChNbg4LoKFHcqiZQlySFRXibiChPYFIfEUEidIqaiapr6WEXkjIsOOYgiRX1GCJGtvpjfeYF+Ux44wtvR83+tgwLBk9xIYxNskipnOzhIgfW+Q9P0lkdKLKC/d/5JYYDp4sVgAhqruEkc8gpqBE0mr0mAccz9TrEQXutMXInSbsj/9tkhg0KsUbCCqzt1P7wvKR1lGnLolaGsFD9U2xwxkXnX2Vu6lWEYptqcDyLq+jJXDqQfT3B5Q02p6yPrrOTawxXZYDgtI3vIJXKA3V3uzJSgY6gejqiNcpkKmp9vlopQd2nNFbIXJ1Epcu/4oQCa7uop+vxIPIMpyCEACz1ByZ7H0D8ZGXiBtglVn9tOWoEyNwXNdJpFju0UXcKikbYk4rTmp7FZk2SpyQGKHndgk7tZs9NWbi6vj0/W5DaYqg+PNbM+QG27bxpEqKDuVTpG8guA7Jpisf3/ENnKwkGZiINX57df/YLgyafm8tGVbKPhIP+hVzKWW1THp6VbaFEsHlleAZc/2a6o96wXNTJsQDkcsfIWlrUW5acIlFqQU5SJiRyw19Eh7bumoF3YkRw95q+w3qVbd4QbdvcAc1i4I2/bMXZJdC9se9TS96pXzxB4+3ZZFhDJIpo5t0L5b1RlVDLj0EyLYDymthhhbgCMkfDxMwXEB4FY1dfpGalGwsVTMQfBYI16I2LBykTbgKGfMbKBa2O0BfGKawJYGOnkI8kXbiUFOgIGSSCDScRzblCkvQy96AUxEOCqikYbikhW2Xdxwb+4mxzU5vKkKDGdRbGy23ZrHqetpFJ7nJ7CVI9xcAczFkyFaC9xYhMWiHMECm4A5MGfTNmKBhIr0h87otGTDD/R+zbmyTFfo6daucREtoj0/nIMJX3W6Flyj+yyfuafrpTiqaSJFkZxZfqQ62W6B0OL5S3YjIjCpVAAEw0TVMDS/6sDbMSzzO6wDKpurd7UBOwulNMiZDVpPMl4dTc7xBOLajPTH9BCLCns3O8XSNNLvP8pYsKaD1jz23eRmUqNzA18dxYqDeMODWI3jFMFceHlHC6noWjdM2o7ADEeAc7TwWIvzSJ3e3szBg1rNbReEtKWHewjTqvYzjXMWAk+3jxDkgjohIEjH/pao0GdBWn2lUjjA/vM+FgC9ZuuyFgzCzC3JFWaeYeYp5rqmC31FRurRlXpgQpVSCG3DolMpuArpAtD+uBSehT2c3it25cdMGJQDXVUaTBELChsGrX0L7++OJtdX79ZnEyYk6yQCG+Q5mylV81BFYBD9uKDy3yOLWPVIfidc4QhKBNoRFsWnvv8AUJIwqxcArDswBCc2xLhZIyDBa+vRPhhXBd3NMoD0dGs1imBNcQ4JVg3i0J4mniwVyrTR/oww8kckGKteqgfCyC3CyBEgR4BZ9QCP8YCW0OAYgxLALEJvAFIU7Am1aqV7U/VomlF+uqRwahgIbcsh0bXe+qJpaktba9qgOsG8tQ+fbi3p0HtOz0EVgoXB6GA4Hu2X+tIysDwFWzo+HLU1uq2dI66eV6sFVSKDJ7bJxozasBi1YWVp2Nw+hr5D3QFkBnlmApkhRSRn2Kma9hCuNbV8kxpWV5hSFUKHXUbtjrQYrT0gk+uLbo19Hz3QgsS+vdmObh6mpbG0WuZs0qcW8jsc64NqU0LuAPDplzgAEYrpKvxcBZWfPQaWm+6GedVRPuClEGOEbsTOxLNgc+n5BlgCaktU/SK7GLTuFvKNmWRa0sX1M9BeVjKZJHIIfA4QeAaBKwgq5k5lt4mctCrph//xdH16NtpYYnkfz8HBbn/owKNA0rlPSdWOKN9Gh1lemTkiMetyy3TwuzWpfHM7ub2odAAZtpJlEIJx37CXqHmkUqch+msbWRUG369xz0fsO2xdFpgd97EX4A4Qs+PEoZtBJj5EQGeOP4W4+y4WKnkzbOe7J5PvqzPRuqq3zTPjx00xNY9UMn8f/IQ5MmZJRGd5vsq0eSY8zBFPpaMadKOY5Z5QWbPsGAEsLPicXSBOoaqosikYRgqPhy1J5OFA71UzOiLbB/h0e48jFngnTDGxgDg44eA468xG5HreMIuNEqVA4VpcbnqsAbwXc+GjQSoGMiJ04+jFST4tFLo/6HWby0r0dCv5LCHInnpp4XOTDKmr0DX4WJU1AHAcwXEEhwwoPQ/xKondv0ZAjgz5bRhFf8aXrjTtxM1fZt1Y3/4hEyikaWuluEa8QPfpNIQ27h4yVPb0YBB2taFrB46VHo7G3lws0HA8C0RnBSAsiq2QmAIeSxS4Rwpx4Zp2fIO9ux1mxxQECDa1n4FPgnaA6xWeComHrYz/6kNdWzQE1WmhYNP26uZx1oohF8xc50jUIZrGytS+D0T4C5kSAW5tY768vjo9nlQmmoY4ru9RSW8TyM0jlZpJ0gyGi1kw6uhJkInPEomHv4oxXJQYRtoTMmxPEtfLOiVEv3vN1ggMLQxNEGbimBYevcDGUQZqGGUn0bFN6U/6Xu8y1dU/Dbrd78Die/4j1d0IVFt3Rk1zlD7PCg1f3NeVJQ/LfZxkIyBqz+Bw6oNFOFzBocYjnfdceP3RRzP/IMne/0T1NzAL9tya+iH+cFt7FyIo9bQLO97DxJYQ8auvDmH1QxjeBt8ulg4eMQhheMn+kqBkj31vjpkJ2DT/lu6Od5nXuCl4DaX8n9j90eSYmh+HbecFu8PKgZtie8Fwy6NEMglhcBKvm4LhMYHhcwKz7iKbJlAU02l2wu/6EU/3vJGJSV9+VY5qL6kkv5uXU9m7BIu8xu56EIsl1jd0JGsCAZMqtWLKgUJhrhKNJ2iyL2IYVHivSIotrBvpbDUUzNqN6elWUnxGSS0idUNWIROVHexTZGMGclBfleJd6kwo3JnlKCmsB7eo0upgFkaNXPUyZyEynmbm6LUw5x/x7DK8kqe0BFa0sBTuSsxfHYxHB4NRKd/bJJcq/5mGCSkynscCpzDLK+Tso5jiUQcgfsW8qSmnApzeRRQK5JDwBKMourWo7YjhQIdtuT6fj6sWpb6+tVVZejLO20VTi7xvacMkcYTz7PwT9tUETqHts2EOJR/hh7HFjtT5Lo+9xb53zCGGPtDj9Mi38GLY8i5YsMgl3G0HBms/8/HlcH+UCzBEPD2XlgohfPCXcho6i02FUE6W356+n5ze3jG8Lo/dHZ+fnrx/d8qOJgwn2mViz91jZ5eTfTbMX55OSBKtSfJ3r49qshZiqI4tOVOxma9sHqbUF2PP50t2hnaJzkYQARt9QaeGPnh+sdurYKjfUZQgBK0U8uT83Ukd9VNRpmk5G06/eZxyvfVziYLdQwic8daiPCuAN3bWpgRGrVTx+Or18eT7ak1PcWPDmxrx42bQmkcqHS/yMfGLJ9PndBMOBsQUAvues8R6ShKnB8Jc4DV424ZhCVvdajdqZYx3l+fn1+8q4ftYpWQj17L8DdP6zSO1nJQOgOrOKXWD65N3mBJrLPWhEpL2e+hq2xr6g/4LNUjgSEUkZSqR1iKfYnakGv9GrQ2yB1rlkM901aF0oG3eoYQ3Dy1doQ7hYOc87M25BKxhbn7L/h5J6lPMhRGTh24JodXBhb8Kw4jLoTQaHo7F6ZUVrwdUDn+xpwD81Ym/wBvD/GB1gyPdd6jyGDPfSCLclxYwaRaA36Na+N/FlNRcgr7nZ8nAE0KInsj0rrBR25V3dSS81/u9YUT1AkczhckxzcXB2aUkKb/VkfIJhJIjRK4g8hU+Tvh4Bq41jOj1PmPBSx1e7TXm+msK6ZLF1vzo6ftbiHevGnLNEAdA5Lxh3Nk8VO2dIHWNSaE0JMyweOQlS6WtTsd8/fXXbHJ7dHX37mhyesLgJcFsTZneTegM77p9e0otZbzxaeDmgV4WJIWHP+6cy92N7paMftxpEMtnWg1q0STBC4klKZ8sUyHaEUQJQczOhRN30D3YzxB8Y0/dsQxhn3mozlgZf4250Gs6Dvg+oHv9crkSss/yrxrW0Z/l/Gtz8lU/TuvW3U2PuUK0PwNUYNGxd0yYaeFMeBEehiVfM/5MIq/+8+UL4aheMqtC6kthCrdQu7+I2F2MBwOOqZBNE29lWQ0f2NNfZuK9cjs2lSgwyPqIvdV4amspV0XaOW23j2LBzdBXyVpYgYUkCqmCVBf3V7p4XxG6VuZ1NLl4XXctoiLHsCWnm16w2DxSEV/Lf2ukuKlURsUGLLVFxM8i27UdETLDfqSTXIWiG/jrz5Lx1GmPW0ldQyZVdl8qJyu75QTTUyDDODpkb0IpVVpTHdmzVTVuJkVkTx35TW6KIZj1svukfkow+Ty150y1FxP/HrdeVHAyuawLbXSVMjJjd9MQqXGc8uWiwYPtRYVb+ejeEqY67dJUSnpoF/bxLKH6It4lB/NdUncl9qwoXK3dk+/vL25r5vOgErfJwt6wna55nFLJND1uRw7NppuA5FMg1JFqulhmHgozQXTSC33HoQBqumQJ3aCvdxksuwHv0cXJrWynaULmCwErb9rzi7Pzd/BnckczayUo9dXlwdPTC9WpcaRSWsZfquvVsaWZ+oXBIv72699O8WYUPO9jOzJSpxBhMfwIr2cRiRMzBzPv2Z3LgY9G1LBD7BslkK10Y3J+CrNr2i+gtIBzw6aVxpG+yGpit5Q620bGMcvRv0L6UTWlHXZ5o+Kd3fizWQuSSitVqT+vpk3NFzn3huO0Rxl3EuJeKkie2LOUrUSMc3Z/95Zm354meltfIVTdqubHTatWzeMUZ/9+726PmNXhFkA4O2oovgO/xct4wOCIKK/HQuhmUeeym+A97ZiiFXOgpSpBe9DKet52uzX5RHiprh3a8MahxkFqznisXBklYwwfXHxIxbn2X6Fy0MpvJjfvr46rU0gvkI7xQsANN2rjQK1K2WGOT9ckyKjDpAsuIA2O8tv3okIi86CVhtzf1Iozu2t8w4uSmkdZ66ZOEaS/0KIo/ctM7Y7gS0+VwmbrdfDjtMmYcLWyj8nF5dX1fVW06h6B2Hbp935stEiNI9X9fgSJxxZW98Sn56ORNuIhDcxUYKODaj/F0g+lA4F+wZKZCV7vj2VaoijUor1+p5KDnRozvLsIJdDKUxour+oGL3QLVrfm6u70piNsyyjE73jdUdrLY+MFy/4DhCAIPJMSJrxAOHjph7ovf1Ub22P32ETAHsFy+eq3EbSnbI5hvWomq65GxtLihg6jeaBf/rWj46+Pwt+jpR3AX70hfoV/6fie3sX39EO9o43xQRe+0ukpfiLM/e41fISm9fFD9V9++eX/AYKEgUieawAA" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="" />
</div>

<script type="text/javascript">
<!--
if((typeof RootNewWindowDirectory == 'undefined') && (!RootNewWindowDirectory)){RootNewWindowDirectory = 'https://global-factiva-com.ezproxy.cul.columbia.edu/en';}
isPostProcessing = true;
languageCode = 'en';
logOmniture = true;
// -->
</script><script type="text/javascript">
<!--
function translate(t) {
var r={"yes":"Yes","no":"No","ok":"OK","djheaderaWNPLikeLink":"${djheaderaWNPLikeLink}","djheaderDontShowMe":"Don\'t show me this again","djheaderFirstView":"${djheaderFirstView}","djheaderLoremipsum":"Factiva is powered by the most comprehensive collection of business information in the world.","djheaderGetStarted":"Get Started","djheaderTryitlater":"Try it later","snapShotPrd":"Homepage","snapShotNavBeta":"${snapShotNavBeta}","nameIsRequired":"Please enter a 1-25 character name.","snapShotBeta":"Homepage","tryItNow":"Try It Now!","whatsNewPopUpTitle":"What\'s New","invalidEmail":"You have entered an invalid e-mail address.","profValidEmail":"Please enter a valid e-mail address.","sSun":"Sun","sMon":"Mon","sTue":"Tue","sWed":"Wed","sThu":"Thu","sFri":"Fri","sSat":"Sat","sunday":"Sunday","monday":"Monday","tuesday":"Tuesday","wednesday":"Wednesday","thursday":"Thursday","friday":"Friday","saturday":"Saturday","sJan":"Jan","sFeb":"Feb","sMar":"Mar","sApr":"Apr","sMay":"May","sJun":"Jun","sJul":"Jul","sAug":"Aug","sSep":"Sep","sOct":"Oct","sNov":"Nov","sDec":"Dec","january":"January","february":"February","march":"March","april":"April","may":"May","june":"June","july":"July","august":"August","september":"September","october":"October","november":"November","december":"December","smallAm":"${smallAm}","smallPm":"${smallPm}","capitalAm":"${capitalAm}","capitalPm":"${capitalPm}"};
return (r && t && r[t] || r[t] === '')? r[t] : t || null;
}
// -->
</script>
<script src="/ScriptResource.axd?d=na9ThF35vypYMd7Jk_rxYO38HjXffKotc0wvG_70TpcLVKfZBZPIM8kH05SebEymwP8VMdB5A4PWnvSTWMpmgkzkPMRWw3LUebC7IY1-RzB_CjMRRSx8x83UUIIagDyIsgi9fBsYewhw-mD8wu8dSyqNoNY1&amp;t=5c0e0825" type="text/javascript"></script><link href="/WebResource.axd?d=NhJjFR_XCMs18rNVWoDInluTIB_uBACnN1nBI-8xV6GiPce6R6t2x0Iz5ENz8Px7hAME9tFr3xqyYeeLelCj5XdG2swm5QVvr04cmRtyfAQYQSvyeyzPxiKMkscYlRJ3KlT37g2&amp;t=638484482820000000" type="text/css" rel="stylesheet" /><div id="contentWrapper"><div id="contentLeft" class="carryOverOpen"><span></span><div id="article-BBYER00020251121elbo00007" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/bbyerLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Munis steady, issuance falls to $1.2B</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Christina Baker </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1182 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>24 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The Bond Buyer</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>BBYER</td></tr><tr><td align="right" valign="top" class="index"><b>VOL</b>&nbsp;</td><td>Vol.397, No.36411</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© 2025 Arizent. All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Municipals were steady Friday ahead of a paltry new-issue calendar, as <span class="companylink">U.S. Treasury</span> yields fell slightly and equities ended up.</p>
<p class="articleParagraph enarticleParagraph" >The two-year muni-UST ratio Friday was at 70%, the five-year at 67%, the 10-year at 68% and the 30-year at 88%, according to Municipal Market Data's 3 p.m. EDT read. ICE Data Services had the two-year at 69%, the five-year at 66%, the 10-year at 68% and the 30-year at 87% at a 4 p.m. read.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The muni market is slowing, <span class="companylink">Barclays</span> analysts wrote, but not enough to cause concern.</p>
<p class="articleParagraph enarticleParagraph" >The market is winding down from "a long period of outperformance," Mikhail Foux and other strategists wrote in <span class="companylink">Barclays</span>' Municipal Weekly.</p>
<p class="articleParagraph enarticleParagraph" >Issuance has been robust, at $11 billion this week , while inflows slowed as of late, with nearly $1 billion of outflows this week, they said.</p>
<p class="articleParagraph enarticleParagraph" >"Muni-UST ratios have been moving sideways for several weeks in the front-end and the belly, while long ratios have continued slowly moving lower," <span class="companylink">Barclays</span> strategists wrote, "but it finally felt like the market has hit a wall, at least in the near term."</p>
<p class="articleParagraph enarticleParagraph" >Investors should get a break thanks to next week's light calendar and healthy December redemptions, so they are "not overly concerned," and still expect the market to outperform for the rest of the year.</p>
<p class="articleParagraph enarticleParagraph" >The long end of the curve is under pressure, but demand for 15- to 20-year bonds remains strong, according to <span class="companylink">Barclays</span> strategists.</p>
<p class="articleParagraph enarticleParagraph" >"This part of the curve is extremely steep both outright and versus Treasury, and investors benefit from a very steep roll-down," they wrote. "This part of the yield curve remains our favorite for investors who are not overly afraid of being long duration."</p>
<p class="articleParagraph enarticleParagraph" >Investors are finally receiving economic data that the federal shutdown had delayed.</p>
<p class="articleParagraph enarticleParagraph" >"September nonfarm payrolls increased 119,000, with the downward two-month revision," <span class="companylink">Barclays</span> strategists wrote. "Meanwhile, the unemployment rate and initial jobless claims have been inching higher."</p>
<p class="articleParagraph enarticleParagraph" >Investors are less hopeful of a Fed rate cut next month.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="companylink">Barclays</span> economists still expect a cut in December, although they view it as a toss-up.</p>
<p class="articleParagraph enarticleParagraph" >The minutes from the Federal Open Market Committee's last meeting show that several policymakers opposed lowering the benchmark rate, although nearly all of them supported halting "the runoff of securities from the Fed's balance sheet," according to <span class="companylink">Barclays</span> strategists. Plus, the <span class="companylink">Bureau of Labor Statistics</span> will release October jobs data after the Fed's December decision.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="companylink">Barclays</span> sees the future of the Affordable Care Act subsidies as "one of the most pressing items on the policy agenda for the remainder of the year." There will be a vote on the subsidies in the Senate, but the Republican-controlled body is unlikely to save the subsidies, and the president opposes them. If the issue is not resolved, there may be another shutdown in 2026, <span class="companylink">Barclays</span> strategists wrote.</p>
<p class="articleParagraph enarticleParagraph" >The muni default rate for 2025 is 0.8%, below <span class="companylink">Barclays</span>' forecast; defaults have dropped significantly in the second half of the year.</p>
<p class="articleParagraph enarticleParagraph" >"For 2026, we expect a 1%-1.5% default rate for the [high-yield] index, excluding Brightline from the consideration," <span class="companylink">Barclays</span> strategists said.</p>
<p class="articleParagraph enarticleParagraph" >The prepay gas sector has underperformed the rest of the muni market this fall, they said..</p>
<p class="articleParagraph enarticleParagraph" >"For more attractive spread pickup, investors should consider 4% bonds, some of the older deals, and bonds backed by non-traditional guarantors," <span class="companylink">Barclays</span> strategists wrote.</p>
<p class="articleParagraph enarticleParagraph" >Spreads for New York City paper have not displayed any weakness in the wake of the mayoral election. But this week, NYC GO spreads started widening, which <span class="companylink">Barclays</span> strategists attribute to heavier supply and "profit-taking by fast money investors."</p>
<p class="articleParagraph enarticleParagraph" >Although the spreads are more attractive, they suggest waiting to see if they widen by another 10 basis points to 15 basis points.</p>
<p class="articleParagraph enarticleParagraph" >"We do not expect to see immediate credit developments that should negatively affect this credit," they said. "However, investors should remain tactical, as we will likely see more volatility for NYC spreads in 2026."</p>
<p class="articleParagraph enarticleParagraph" >New-issue calendar</p>
<p class="articleParagraph enarticleParagraph" >The new-issue calendar falls to an estimated $1.154 billion, with $939.1 million negotiated deals on tap and $214.8 million of competitives.</p>
<p class="articleParagraph enarticleParagraph" >The <span class="companylink">Pennsylvania Housing Finance Agency</span> leads the negotiated calendar with $275.54 million of single-family mortgage revenue bonds.</p>
<p class="articleParagraph enarticleParagraph" >The competitive calendar is led by Bloomingdale, Illinois, with $50.4 million of GOs.</p>
<p class="articleParagraph enarticleParagraph" >AAA scales</p>
<p class="articleParagraph enarticleParagraph" >MMD's scale was unchanged: 2.52% in 2026 and 2.46% in 2027. The five-year was 2.41%, the 10-year was 2.75% and the 30-year was 4.16% at 3 p.m.</p>
<p class="articleParagraph enarticleParagraph" >The ICE AAA yield curve was little changed: 2.50% (-1) in 2026 and 2.46% (unch) in 2027. The five-year was at 2.43% (+1), the 10-year was at 2.77% (+1) and the 30-year was at 4.11% (unch) at 4 p.m.</p>
<p class="articleParagraph enarticleParagraph" >The <span class="companylink">S&P Global Market Intelligence</span> municipal curve was unchanged: The one-year was at 2.51% in 2025 and 2.45% in 2026. The five-year was at 2.40%, the 10-year was at 2.75% and the 30-year yield was at 4.13% at 3 p.m.</p>
<p class="articleParagraph enarticleParagraph" >Bloomberg BVAL was unchanged: 2.51% in 2025 and 2.46% in 2026. The five-year at 2.39%, the 10-year at 2.72% and the 30-year at 4.06% at 4 p.m.</p>
<p class="articleParagraph enarticleParagraph" >Treasuries saw small gains.</p>
<p class="articleParagraph enarticleParagraph" >The two-year UST was yielding 3.513% (-2), the three-year was at 3.501% (-3), the five-year at 3.618% (-3), the 10-year at 4.062% (-2), the 20-year at 4.677% (-1) and the 30-year at 4.714% (-1) near the close.</p>
<p class="articleParagraph enarticleParagraph" >Primary to come</p>
<p class="articleParagraph enarticleParagraph" >The <span class="companylink">Pennsylvania Housing Finance Agency</span> (Aa1///) is set to price Tuesday $275.54 million of single-family mortgage revenue bonds, consisting of $254.2 million of non-AMT social bonds, Series 2025-151A, and $21.34 million of taxable, Series 2025-151B. <span class="companylink">Barclays</span>.</p>
<p class="articleParagraph enarticleParagraph" >The <span class="companylink">New York State Mortgage Agency</span> (Aa1///) is set to price Tuesday $107.805 million of social non-AMT homeowner mortgage revenue bonds, Series 273. <span class="companylink">Jefferies LLC</span>.</p>
<p class="articleParagraph enarticleParagraph" >The Los Angeles Housing Authority (Aa1///) is set to price Tuesday $78.697 million of multifamily housing revenue bonds (Victory Blvd), Series 2025A. <span class="companylink">RBC Capital Markets</span>.</p>
<p class="articleParagraph enarticleParagraph" >The Jersey City Redevelopment Agency is set to price Tuesday $69.87 million of bonds from the Bayfront Redevelopment Project, consisting of $60.3 million of Series A and $9.57 million of Series B. <span class="companylink">Stifel Nicolaus</span>.</p>
<p class="articleParagraph enarticleParagraph" >Competitive</p>
<p class="articleParagraph enarticleParagraph" >Bloomingdale, Illinois, is set to sell $50.435 million of GOs at 11 a.m. Eastern Monday.</p>
<p class="articleParagraph enarticleParagraph" >Farmington Area Public Schools, Minnesota, (Aa1///) is set to sell $40.39 million of GO school building refunding bonds, Series 2025A, at 10:30 a.m. Monday.</p>
<p class="articleParagraph enarticleParagraph" >New Rochelle, New York, is set to sell $40.874 million of bond anticipation notes at 11 a.m. Eastern Tuesday.</p>
<p class="articleParagraph enarticleParagraph" >Jessica Lerner contributed to this report.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>m12 : Debt/Bond Markets | mcat : Commodity/Financial Market News | mgvdbt : Government Debt/Bond Markets | mmuni : Municipal Debt/Bond Markets | ncat : Content Types | nfact : Factiva Filters | nfce : C&E Exclusion Filter</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Arizent</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document BBYER00020251121elbo00007</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC44555020251122elbm0000g"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump and Mamdani go from adversaries to allies after White House meeting</b><div class="leadFields"><a href="javascript:void(0)">Lincoln Daily News</a>, 12:08 PM, 22 November 2025, 1151 words,  MICHELLE L. PRICE, (English)</div><div class="snippet ensnippet"> WASHINGTON (AP) — President Donald Trump on Friday met the man who had proudly proclaimed himself “Donald Trump&#39;s worst nightmare,” but he seemed to find the opposite.</div>
<div>(Document WC44555020251122elbm0000g)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC57785020251122elbm0001h"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump to meet 'communist' Mayor of New York City Zohran Mamdani at White House on Friday</b><div class="leadFields"><a href="javascript:void(0)">India TV News</a>, 12:08 PM, 22 November 2025, 437 words, (English)</div><div class="snippet ensnippet"> Mamdani emerged victorious in the closely-watched battle for New York City Mayor, becoming the first South Asian and Muslim to be elected to sit at the helm of the largest city in the US.</div>
<div>(Document WC57785020251122elbm0001h)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-WPCOM00020251122elbl00001" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/wpcomLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Editorial-Opinion</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>The Trump-Mamdani show </span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Editorial Board </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>786 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>washingtonpost.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>WPCOM</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025, The Washington Post Co. All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >What are a few deportation threats among friends? President Donald Trump has called Zohran Mamdani a "100% Communist lunatic" who "needs to be DEPORTED." Mamdani called the president a "despot," promising to "Trump-proof" New York. Yet they couldn't have been chummier in their Oval Office meeting on Friday. What's happening here?</p>
<p class="articleParagraph enarticleParagraph" >Trump loves populists and winners, and Mamdani is both. A bust-up would have made for great television, but their effusiveness toward one another made for viewing more fantastical.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >"The better he does, the happier I am," Trump declared. "I will say there is no difference in party. There's no difference in anything." Mamdani said he is "looking forward" to working with Trump. The president replied that he expects Mamdani to make "a really great mayor."</p>
<p class="articleParagraph enarticleParagraph" >About those nasty insults? "I've been called much worse than a despot," Trump said, optimistic Mamdani would come around. When a reporter pressed the mayor-elect on whether he still thinks Trump is a fascist, the president patted him on the arm: "That's okay, you can just say yes. It's easier than explaining it." When another reporter gave Mamdani a hard time for flying to D.C. rather than taking the <span class="companylink">Amtrak</span>, a strike against the mayor's climate credentials, Trump interjected to say Mamdani is too busy to take the slower train.</p>
<p class="articleParagraph enarticleParagraph" >Acting like grown-up governing partners, the pair repeatedly brought the conversation back to affordability, housing and crime, which is when Trump offered the mayor-elect — who in 2021 called violence an "artificial construction" — the endorsement of the century: He said he will feel "very, very comfortable" in New York under Mayor Mamdani.</p>
<p class="articleParagraph enarticleParagraph" >This surreal scene is no bad thing for voters who have been told that the other side is the mortal enemy, though they might wonder how sincere each side was in their election insults. In reality, Mamdani and Trump have some shared interests, and it's not just about building more apartments and tackling inflation. Both men are looking to seize more executive power, deepen the reach of the state into people's everyday lives and bring government to bear on businesses and entrepreneurs who won't fall in line.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani knew he had much to lose walking into the Oval Office, including $7.4 billion of federal funding the Big <span class="companylink">Apple</span> relies on to keep services running. That's why the mayor-elect astutely focused on their shared affinity for state capitalism and protectionist rackets. Trump said that "we have to get <span class="companylink">Con Edison</span> to start lowering their rates." Mamdani nodded.</p>
<p class="articleParagraph enarticleParagraph" >The blurring of the public and private sectors reflected Trump's treatment of Intel, which handed over a 10 percent stake to the federal government, and earlier musings from Vice President JD Vance, who claimed in 2023: "there is no meaningful distinction between the public and the private sector in the American regime." For Mamdani, what's not to like about the state exerting more control over the means of production?</p>
<p class="articleParagraph enarticleParagraph" >The extraordinary meeting ends a week in which Mamdani showed a promising pragmatic streak. He confirmed that he will keep the tough-on-crime Jessica Tisch in her role as New York City police commissioner. And he rejected New York council member Chi Osse's primary challenge against House Minority Leader Hakeem Jeffries (D-New York). Not to worry, disaffected leftists: At the Democratic Socialists of America meeting where he announced his opposition, Mamdani still opened by announcing his "he/him" pronouns.</p>
<p class="articleParagraph enarticleParagraph" >Alas, what hasn't changed is Mamdani's disquieting posture toward Jewish New Yorkers. Following ugly protests outside Park East Synagogue, the mayor-elect issued a statement that said he thinks "every New Yorker should be free to enter a house of worship without intimidation, and that these sacred spaces should not be used to promote activities in violation of international law."</p>
<p class="articleParagraph enarticleParagraph" >The false implication is that the synagogue is violating international law. Still unable to condemn antisemitism without caveat, the mayor-elect adopted a both-sides strategy. Then again, this is not worlds away from his new friend in the White House, whose party is also struggling to call out blatant antisemitism in its own ranks.</p>
<p class="articleParagraph enarticleParagraph" >The mayor-elect's actions this week seem to hint he is inclined to work within traditional institutions rather than tear them down, but if anyone can teach Mamdani how to shatter norms, it's the president. "Some of his ideas are really the same ideas that I have," Trump said. If the country's left and right extremes were dismayed by the Trump-Mamdani bromance, the center has plenty of reason to worry, too.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | greg : Regional Politics | ncat : Content Types | nedc : Commentaries/Opinions | nfact : Factiva Filters | nfcpex : C&E Executive News Filter</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Editorial | Opinion | opinions | the-posts-view</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Washington Post</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document WPCOM00020251122elbl00001</td></tr></table><br/></div></div><br/><span></span><div id="article-SCMCOM0020251122elbm00003" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/scmcomLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>News</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump and New York City mayor-elect Zohran Mamdani find harmony - for now</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Khushboo Razdan </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>617 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>scmp.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>SCMCOM</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>(c) 2025  scmp.com. All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Their first meeting brought unexpected warmth, with Trump praising Mamdani as both leaders signalled willingness to work together</p>
<p class="articleParagraph enarticleParagraph" >After weeks of traded insults, New York City’s <span class="colorLinks">newly elected democratic socialist mayor [https://www.scmp.com/news/world/united-states-canada/article/3331564/zohran-mamdani-wins-new-york-city-mayors-race-capping-stunning-ascent]</span>, Zohran Mamdani, and US President Donald Trump concluded their first in-person meeting on Friday. The duo praised each other and pledged cooperation, with the “America first” leader sounding unexpectedly impressed with the young New York politician.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >“Some of his ideas are the same as my ideas,” Trump said after what may ultimately go down as one of the more unexpected political encounters of the decade.</p>
<p class="articleParagraph enarticleParagraph" >“He wants to see housing go up, see a lot of housing created, apartments built … People would be shocked, but I want to see the same thing,” he added, saying “I expect to be helping him, not hurting him”.</p>
<p class="articleParagraph enarticleParagraph" >Do you have questions about the biggest topics and trends from around the world? Get the answers with <span class="colorLinks">SCMP Knowledge [https://www.scmp.com/knowledge]</span>, our new platform of curated content with explainers, FAQs, analyses and infographics brought to you by our award-winning team.</p>
<p class="articleParagraph enarticleParagraph" >The 34-year-old Mamdani made history earlier this month, becoming the first democratic socialist, the first Muslim and the youngest person ever elected mayor of New York City in a victory over former New York governor Andrew Cuomo, who <span class="colorLinks">earned Trump’s endorsement [https://www.scmp.com/news/world/united-states-canada/article/3331403/trump-backs-cuomo-threatens-cut-funds-new-york-city-if-mamdani-wins-mayoral-race]</span> just days before the November 4 election.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani is scheduled to succeed Democratic incumbent Eric Adams on January 1, 2026.</p>
<p class="articleParagraph enarticleParagraph" >In the tense lead-up to the meeting, Trump spent weeks criticising Mamdani as a “Marxist” and “communist”, accusing him of wanting to remake New York in the image of “Caracas with better bagels”. Mamdani, responding on election night, told the president, “Donald Trump, since I know you’re watching … turn the volume up.”</p>
<p class="articleParagraph enarticleParagraph" >While Trump has also called Mamdani “lunatic” and “radical”, on Friday he rejected his ally Elise Stefanik’s description of Mamdani as a “jihadist”.</p>
<p class="articleParagraph enarticleParagraph" >When asked about Mamdani calling him a “despot”, Trump brushed it off, saying: “I’ve been called much worse than a despot, so it’s not that insulting.”</p>
<p class="articleParagraph enarticleParagraph" >“I think he’s different, and that can be in a very positive way, but I think he’s different,” Trump added.</p>
<p class="articleParagraph enarticleParagraph" >Standing next to the president, Mamdani described their meeting as “productive” for the city they both “love”.</p>
<p class="articleParagraph enarticleParagraph" >“We spoke about rent, we spoke about groceries, we spoke about utilities, we spoke about the different ways in which people are being pushed out,” he said.</p>
<p class="articleParagraph enarticleParagraph" >Trump also joked with Mamdani, patting his arm as one reporter asked the mayor-elect if he thought the president was a fascist. “That’s OK, you can just say yes; it’s easier,” the president said.</p>
<p class="articleParagraph enarticleParagraph" >Just hours before the talks, both sides struck a more measured tone. Trump told reporters before the meeting that he believed the two would “get along fine” and praised Mamdani for running a “very good race”.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani described the visit as an opportunity to underscore the needs of New York City’s 8.5 million residents and discuss federal support for housing, transit and public safety.</p>
<p class="articleParagraph enarticleParagraph" >“I’m not concerned about this meeting. I view this meeting as an opportunity to make my case,” he said, adding, “It behoves me to leave no stone unturned in making the city more affordable.”</p>
<p class="articleParagraph enarticleParagraph" >Born in Kampala, Uganda, to Indian filmmaker Mira Nair and scholar Mahmood Mamdani, he moved to the US as a child, grew up in Manhattan, worked as a housing counsellor and hip-hop artist, and built his profile in Queens politics before his rapid rise to the mayor’s office.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | greg : Regional Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>South China Morning Post Publishers Limited</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document SCMCOM0020251122elbm00003</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC42085020251122elbm003ee"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  House Dem in pro-Trump district reveals top issue for his battleground voters</b><div class="leadFields"><a href="javascript:void(0)">FOXNews.com</a>, 12:01 PM, 22 November 2025, 898 words, (English)</div><div class="snippet ensnippet"> This material may not be published, broadcast, rewritten, or redistributed. &#169;2025 FOX News Network, LLC. All rights reserved. Quotes displayed in real-time or delayed by at least 15 minutes. Market data provided by Factset. Powered and ...</div>
<div>(Document WC42085020251122elbm003ee)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-NAPRS00020251122elbm0005l" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/naprsLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Music</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>The Weird Mystery of Olivia Nuzzi’s Teenage Pop Era</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Rob Sheffield </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1502 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Rolling Stone</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NAPRS</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Rolling Stone is a part of Penske Media Corporation. © 2025 Rolling Stone, LLC. All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The controversial journalist reportedly had a secret life as a Gaga-wannabe pop singer. Her 2009 song "Jailbait" is ghastly -- but is it real?</p>
<p class="articleParagraph enarticleParagraph" >
                        <span class="colorLinks">View image. [https://www.rollingstone.com/wp-content/uploads/2025/11/sheff-on-nuzzi-song.jpg?w=150&h=150&crop=1]</span>
                     </p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Olivia Nuzzi is no stranger to controversy. The ex-New York magazine reporter became notorious in the 2024 scandal over her alleged sexting affair with a presidential candidate she was writing about — Robert F. Kennedy Jr., now the Secretary of Health. It looked like the end of her journalism career, yet she landed on her feet with her new gig at Vanity Fair and her new memoir American Canto. But now Nuzzi’s story is taking an even more bizarre turn, with reports that she once had a secret life — as an <span class="colorLinks">aspiring teenage pop star [https://nypost.com/2025/11/19/us-news/olivia-nuzzi-once-recorded-a-song-called-jailbait/]</span>, under the name Livvy. In 2009 when she was 16, she dropped a faux-Britney banger called “Jailbait.”</p>
<p class="articleParagraph enarticleParagraph" >Subtle, it’s not. “16 will get you 20,” Livvy sings. “A teenage queen right in front of you/Illegal dream, killer to pursue.” She pants about “craving sin,” over the synth-disco beats, boasting, “Bad things happen when you hear my name/Deny your attraction but I’ve got no shame.” In the chorus she belts, “Jailbait! You try too stay away, but you can’t obey!”</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Jailbait - Livvy (old Olivia Nuzzi myspace song) [https://www.youtube.com/embed/39Uk_dts_EQ?feature=oembed]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Yes, the song is ghastly, much worse than you’d expect. Is it real? Too soon to tell. Is this whole story crazy? No doubt. So let’s dig into the bizarre mystery of that insanely bad, quite possibly fake Olivia Nuzzi song.</p>
<p class="articleParagraph enarticleParagraph" >You have to take Livvy with a grain of salt, since this story is so sketchily sourced, even the New York Post had a spasm of conscience and put “apparently” in the lede. (And this from the paper that just gave us the instant-classic headline “The Red Apple” after Zohran Mamdani’s election, with the tag, “On your Marx, get set, Zo!”) Nuzzi made a strangely equivocal statement to the Post, with her spokesperson saying, “This was a satirical prank from when Olivia was a child actor and was never meant to be taken seriously.”</p>
<p class="articleParagraph enarticleParagraph" >On her supposed <span class="colorLinks">MySpace profile [https://x.com/damintoell/status/1990824047916020012]</span>, from 2009, she’s glammed up in the style of an American Apparel ad: purple headband, black bracelets, tank dress, thigh-high boots. Another photo shows her in a white lace chemise over a black bra and leather pants, with a pair of handcuffs dangling from her wrist. She describes herself as “a visual, conceptual artist with an addiction to pop music.”</p>
<p class="articleParagraph enarticleParagraph" >Any trace of Livvy has been wiped from the internet — the only digital footprint is an item in the music blog <span class="colorLinks">PopJustice, [https://www.popjustice.com/briefing/thats-livvy-alright/]</span> from February 2010. “‘Jailbait’ is about the role of the underaged, hyper-sexualized girl in society,” Livvy explains. “That girl who takes half naked photos of herself in the mirror with her camera phone. It’s about pornographic ideals infiltrating our collective consciousness — this obsession with youth and beauty. I’m not saying that any of this is wrong, I’m simply stating that it is. This song is me coming to a societal realization.”</p>
<p class="articleParagraph enarticleParagraph" >The MySpace page is a hell of an artistic manifesto, explaining the whole Livvy concept. “Creating a multi-media character for herself, Livvy has dreamed up ‘Emockative: the Life of a Pop Object,’ a short film series shot on the streets of downtown New York City.” She portrays “the life of a loyal disciple of pop culture who has given up conventional life and engulfed herself in a world made of plastic.”</p>
<p class="articleParagraph enarticleParagraph" >There’s excellent reason to have doubts about how real this is. The recording doesn’t exactly scream “2009” at you (no AutoTune!) and it sounds like a post-collegiate adult singing. The Livvy photos look more like a Real Housewife than a ninth-grader. Listen to a song made by an actual teenager in that era, like Rebecca Black’s “Friday,” and it sounds out of time.</p>
<p class="articleParagraph enarticleParagraph" >Nobody can say for sure how authentic this is, since it’s incredibly easy to make up a hoax like this. You could invent the Livvy character in a coffee break, with an AI track and faked screen shots from a conveniently deleted MySpace. (No Livvy <span class="companylink">Twitter</span> — in 2009? Dubious.) In a blindfold test, you’d have to admit, you would not guess “Jailbait” was by an authentic teenager. You’d figure it was a comedy-minded adult trying to do a ham-fisted sketch about sexed-up teen-pop stars. I mean, this was almost a decade after Andy Dick was on MTV with his brilliant Britney/Xtina parody character Daphne Aguilera. “Jailbait” sounds exactly like Daphne’s TRL anthem, “Naughty Baby Did a No-No.”</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Daphne Aguilera Naughty Baby Did a No No [https://www.youtube.com/embed/CujhovwPjh8?feature=oembed]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >“Jailbait” is purportedly from late 2009 or early 2010, taking a ride on a disco stick, heavily influenced by Lady Gaga (the year’s big breakout artist, with hits like “Poker Face” and “LoveGame”) and Britney (in her Circus era, with “Womanizer,” “3,” and “If U Seek Amy”). PopJustice quips that she “makes Ke$ha sound sentient. If this were a NYC wanna-be club kid making her own single at the end of the 2000s, you might expect to hear the influence of LaRoux (“Bulletproof”) or the Ting Tings (“That’s Not My Name”) or the Knife (“Heartbeat”), the music playing in the parties she was fantasizing about getting into, though there’s no trace on “Jailbait.” The music sounds like a terrible Brooklyn electro indie-sleaze band opening for Crystal Castles or Yachts at Studio B, then rushing home to make sure the Tivo caught Gossip Girl.</p>
<p class="articleParagraph enarticleParagraph" >The PopJustice piece doesn’t interview Livvy, and makes no claim to verify her identity. It just quotes the email she sent them. “‘Offensive,’ ‘vapid,’ ‘frothy,’ ‘bubblegum,’ ‘outrageous,’ ‘morally bankrupt’ and ‘undeniably infectious’,” she wrote. “These are just some of the words that have been used to describe ‘Jailbait,’ and the not-yet-legal mind behind it, sixteen year old singer/songwriter, Livvy.”</p>
<p class="articleParagraph enarticleParagraph" >“Jailbait” seems to prophesize her future persona, which has been well-documented in the gossip columns. Nuzzi was profiling Kennedy for New York when their alleged sextingship began, during his ridiculous presidential campaign, which led to his current gig as Secretary of Health, at which he sucks. She was 31, he was 71 and married to Cheryl Hines (yes, Larry David’s ex). Kennedy denied the whole thing, but Hines has a new memoir discussing the scandal. Meanwhile, Nuzzi has her own memoir American Canto, with her poetic musings on their bad romance. “He desired,” she writes. “He desired desiring. He desired being desired. He desired desire itself.” Oh, it goes on.</p>
<p class="articleParagraph enarticleParagraph" >“Jailbait” also seems to prefigure her alleged relationships with TV journalist Keith Olbermann, who met her in her teens and put her through college, and disgraced South Carolina governor Mark Sanford, most famous for disappearing on the job and showing up a week later in Buenos Aires with his side squeeze. “Jailbait” seems to foreshadow the gossip when Livvy sings, “Bad things happen to those who prey/A basic instinct to die another day/16 will get you 20, lust criminally/Irresistible, that’s whey they call me…jailbait!”</p>
<p class="articleParagraph enarticleParagraph" >On her MySpace page, she compares herself to legends from all over pop history. “The day that Madonna released ‘Erotica.’ The day that Andy Warhol made his first film. The day that Freddie Mercury sang his last note. The day that Judy Garland conceived Liza Minnelli. The day that Britney Spears told you to hit it one more time. The day that Cher first met a sequin. The day that Candy Darling took her last breath. The day that Mick Jagger first strut across a stage. The day that Pamela Anderson was introduced to silicone. The day that David Bowie sang ‘Lady Stardust.’ The day that Michael Jackson first slipped on a white glove… was the day that Livvy was born.”</p>
<p class="articleParagraph enarticleParagraph" >So who is she? “Livvy is a sixteen year old singer, songwriter and actress. A former Wilhelmina model, she has appeared in various commercials, films, television programs and print ads since her start in the business at the age of five. Influenced by pop stars, rock stars, rap stars, movie stars and tabloid stars – Livvy is prepared to explode onto the music scene and dominate the pop world.”</p>
<p class="articleParagraph enarticleParagraph" >LIVVY is a pop chorus.</p>
<p class="articleParagraph enarticleParagraph" >LIVVY is a rock ballad.</p>
<p class="articleParagraph enarticleParagraph" >LIVVY is a hip hop beat.</p>
<p class="articleParagraph enarticleParagraph" >LIVY is the past.</p>
<p class="articleParagraph enarticleParagraph" >LIVVY is the future.</p>
<p class="articleParagraph enarticleParagraph" >LIVVY is now… and she’s about to blow your mind.</p>
<p class="articleParagraph enarticleParagraph" >Pop gave me life</p>
<p class="articleParagraph enarticleParagraph" >Olivia Nuzzi definitely went on to fame, though maybe not the kind she was aiming for as a teenage pop star or actress. We may never learn who exactly Livvy is or where she came from. But for Nuzzi, who knows — it just might be a career highlight.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Olivia Nuzzi (Alexander Tamargo/Getty Images) [https://www.rollingstone.com/wp-content/uploads/2025/11/sheff-on-nuzzi-song.jpg]</span>
                  </p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>c16 : Bankruptcy | cactio : Corporate Actions | ccat : Corporate/Industrial News | ccfd : Corporate Financial Difficulty | gcat : Political/General News | gent : Arts/Entertainment | gmusic : Music | ncat : Content Types | nfact : Factiva Filters | nfcpin : C&E Industry News Filter</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Britney Spears | Lady Gaga | Music | Music Features | Olivia Nuzzi</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Penske Media Corporation</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NAPRS00020251122elbm0005l</td></tr></table><br/></div></div><br/><span></span><div id="article-NYTFEED020251122elbm00209" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nytfeedLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Briefing</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Pushing Off</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Melissa Kirsch </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>2118 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>06:22 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>nytimes.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NYTFEED</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. The New York Times Company. All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Thanksgiving’s this coming week. How can we keep a busy holiday season from overwhelming us?</p>
<p class="articleParagraph enarticleParagraph" >We’re on the precipice of The Holidays now, again: where has the time gone, where has the year gone, where is my life going, etc. If you’re traveling for Thanksgiving, perhaps you’re already gone, reading this in the security line at an airport less crowded than you expected. Do you dare admit some optimism, that this trip could go off without incident? But this is just the beginning of your travels, of course. Who knows if the good luck and the good weather will hold — here’s hoping.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The holiday season has its own engine, one that’s been gaining momentum since Halloween and will shift into ever higher gears as we hit the straightaway that leads to the year’s end. There’s an urgency that can feel both exciting and overwhelming. There’s a tension in all the stock holiday scenes: cheery and/or awkward gatherings, delicious and/or overcooked proteins, snowy and/or soggy backdrops. Not many days left, and so even in moments of abundance, there’s a scarcity underneath.</p>
<p class="articleParagraph enarticleParagraph" >How much of this is real, and how much of it is just our acceptance of the fiction that the end of the calendar year is a deadline by which certain things must be accomplished? Remember when marketers tried to scare you by announcing there were only so many “shopping days until Christmas” left? In the era of “buy it now” and same-day shipping, a shopping day seems quaint. Yes, vacation days and insurance deductibles must be exploited or lost, but otherwise, there’s a comfort in knowing the end of the year isn’t really a finish line in any meaningful way.</p>
<p class="articleParagraph enarticleParagraph" >An old friend wrote me a month or two ago suggesting coffee, asking for dates that worked this fall. I forgot to respond, and this week she followed up: “Frankly you could suggest Jan. dates — I get how time is compressing right now!” My immediate response was one of shame. I’d dropped the ball! And then that feeling of scarcity: Yes, time is compressing, and there’s not enough of it, and let me count exactly how many days are left in the year so I can really feel the squeeze. (After today, 40!) And then gratitude for the reminder: Some things can wait until January.</p>
<p class="articleParagraph enarticleParagraph" >Most things, really, can wait until January, and maybe they should. If your holiday season already feels too packed, here, on the Saturday before Thanksgiving, then see what might be shifted. If you’re dreading that post-holiday lull when Christmas trees lie felled on the curb and you have no reason to wear your “fun” sweaters, then now’s the time to joyously, eagerly move what you can to next year. Your holiday to-dos and celebrations need to stay put (although, if your family is flexible, no one’s stopping you from moving them, too), but the optional stuff — the coffee dates and catch-ups, the movies and books you keep meaning to get to — won’t expire.</p>
<p class="articleParagraph enarticleParagraph" >Every first weekend of January, I go away with the same group of friends. It’s a tradition that feels defiant: In the severe landscape of the Northeastern winter, when December’s merrymaking is receding to memory, there’s a reprieve, a reminder that we don’t have to get all our fun in before the clock strikes midnight.</p>
<p class="articleParagraph enarticleParagraph" >What things are you trying to squeeze in before the end of the year that, if you moved them to January, would make the next few weeks a little less stressful? <span class="colorLinks">Let’s talk about it in the comments [https://www.nytimes.com/2025/11/22/briefing/pushing-off.html#commentsContainer]</span>.</p>
<p class="articleParagraph enarticleParagraph" >THE LATEST NEWS</p>
<p class="articleParagraph enarticleParagraph" >* President Trump <span class="colorLinks">heaped praise on Zohran Mamdani, [https://www.nytimes.com/live/2025/11/21/us/trump-news/heres-the-latest?smid=url-share]</span> New York City’s mayor-elect, during his visit to the White House. “I feel very confident that he can do a very good job,” Trump said.</p>
<p class="articleParagraph enarticleParagraph" >* The meeting seemed to <span class="colorLinks">change Trump’s view of Mamdani [https://www.nytimes.com/2025/11/21/us/politics/trump-mamdani-scene.html]</span>, a democratic socialist whom he had previously described as a “lunatic.”</p>
<p class="articleParagraph enarticleParagraph" >* After a reporter asked Mamdani about his calling Trump a “despot” on election night, Trump said, “I’ve been called much worse than a despot, so it’s not that insulting.”</p>
<p class="articleParagraph enarticleParagraph" >* Representative Marjorie Taylor Greene of Georgia announced she would <span class="colorLinks">resign from Congress [https://www.nytimes.com/2025/11/21/us/politics/marjorie-taylor-greene-resigns.html]</span> in January. Greene, long one of Trump’s fiercest defenders, had recently drawn the president’s ire after breaking from him on a number of issues.</p>
<p class="articleParagraph enarticleParagraph" >* The Supreme Court temporarily <span class="colorLinks">reinstated Texas’ new, Republican-friendly congressional map [https://www.nytimes.com/2025/11/21/us/politics/supreme-court-texas-congressional-map.html]</span>, which a lower court had blocked earlier in the week.</p>
<p class="articleParagraph enarticleParagraph" >* Health Secretary Robert F. Kennedy Jr. said he personally instructed the <span class="companylink">C.D.C.</span> to <span class="colorLinks">abandon its longstanding position [https://www.nytimes.com/2025/11/21/us/politics/rfk-jr-cdc-vaccines-autism-website.html]</span> that vaccines do not cause autism.</p>
<p class="articleParagraph enarticleParagraph" >* A judge said prosecutors could <span class="colorLinks">fall back on local grand juries to approve serious charges [https://www.nytimes.com/2025/11/20/us/politics/judge-trump-washington-grand-juries.html]</span> when they failed to persuade a federal grand jury, sanctioning a recent such attempt by the Justice Department.</p>
<p class="articleParagraph enarticleParagraph" >* Ukraine’s president said his country’s <span class="colorLinks">relationship with the U.S. could be at a breaking point [https://www.nytimes.com/2025/11/21/world/europe/ukraine-russia-us-peace-plan.html]</span> over a peace plan proposed by the White House that favors Russia.</p>
<p class="articleParagraph enarticleParagraph" >* A Times investigation into the <span class="companylink">U.S. Navy</span>’s positions in the Caribbean suggests that the Trump administration is more interested in <span class="colorLinks">pressuring the Venezuelan government [https://www.nytimes.com/2025/11/21/world/americas/us-navy-venezuela-satellite-data.html?]</span> than in fighting drug traffickers.</p>
<p class="articleParagraph enarticleParagraph" >* <span class="companylink">Eli Lilly</span>, the maker of hugely popular weight loss drugs, has reached <span class="colorLinks">$1 trillion in value [https://www.nytimes.com/2025/11/21/health/eli-lilly-one-trillion-value-pharmaceuticals.html]</span>. It’s the first health care company to hit that milestone.</p>
<p class="articleParagraph enarticleParagraph" >* A series of storms moving across the country could complicate Thanksgiving travel. Here’s a look at <span class="colorLinks">weather around the U.S. [https://www.nytimes.com/2025/11/20/weather/thanksgiving-forecast-snow-cold.html]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >THE WEEK IN CULTURE</p>
<p class="articleParagraph enarticleParagraph" >* “Wicked: For Good” features two new songs that help Glinda and Elphaba grapple with the choices that change their destinies. Director Jon M. Chu insists the songs were <span class="colorLinks">added for plot development [https://www.nytimes.com/2025/11/21/movies/wicked-for-good-new-songs.html?]</span> and not for a shot at an Oscar nomination.</p>
<p class="articleParagraph enarticleParagraph" >* A new documentary featuring senior members of the government claims that the U.S. is <span class="colorLinks">hiding what it knows about U.F.O.s [https://www.nytimes.com/2025/11/20/movies/the-age-of-disclosure-congress.html]</span>. The filmmaker screened it for House members this week.</p>
<p class="articleParagraph enarticleParagraph" >* The <span class="companylink">British government</span> is <span class="colorLinks">taking on ticket scalpers [https://www.nytimes.com/2025/11/19/arts/music/uk-tickets-resale-ban.html]</span>. New legislation backed by Coldplay, Dua Lipa and Radiohead would make it illegal to resell entertainment or sports tickets for more than face value.</p>
<p class="articleParagraph enarticleParagraph" >* More than 30 years after finding two unsigned compositions for organ in a Belgian library, a Harvard researcher has announced that <span class="colorLinks">he knows who composed them [https://www.nytimes.com/2025/11/19/arts/music/bach-newly-discovered-works.html]</span>: Johann Sebastian Bach.</p>
<p class="articleParagraph enarticleParagraph" >* This <span class="colorLinks">new version of “Oedipus” [https://www.nytimes.com/2025/11/17/theater/oedipus-play-broadway.html]</span> on Broadway casts Sophocles’s tragic king as a politician in an age where elected officials can get away with almost anything.</p>
<p class="articleParagraph enarticleParagraph" >* A theater director in Switzerland recruited amateur actors that had anorexia. One of the performers called it empowering. But <span class="colorLinks">was it unethical? [https://www.nytimes.com/2025/11/19/theater/anorexia-play-eating-disorder.html]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >* The hero of San Francisco Opera’s latest world premiere isn’t a handsome prince, but an ancient monkey king who was hatched from a magic rock. Our reviewer <span class="colorLinks">had effusive praise for the production [https://www.nytimes.com/2025/11/17/arts/music/the-monkey-king-opera-review.html]</span>, which will be available on streaming services.</p>
<p class="articleParagraph enarticleParagraph" >* Daniele Rustioni, the Metropolitan Opera’s new principal guest conductor, is only 42. But he has been called a <span class="colorLinks">“maestro of the old school,” [https://www.nytimes.com/2025/11/18/arts/music/daniele-rustioni-conductor-met-opera.html]</span> following in the footsteps of Italian luminaries like Arturo Toscanini.</p>
<p class="articleParagraph enarticleParagraph" >* <span class="companylink">Netflix</span>
                     <span class="colorLinks">opened its first permanent IRL location [https://www.nytimes.com/2025/11/20/arts/television/netflix-house-philadelphia-king-of-prussia.html]</span> near Philadelphia. Its immersive exhibits include “Bridgerton” balls and a “Money Heist” escape room.</p>
<p class="articleParagraph enarticleParagraph" >* Groups are <span class="colorLinks">declining grants [https://www.nytimes.com/2025/11/20/arts/design/dei-arts-groups-grants-nea.html]</span> from the <span class="companylink">National Endowment for the Arts</span> rather than comply with the Trump administration’s anti-D.E.I. policies.</p>
<p class="articleParagraph enarticleParagraph" >* <span class="companylink">The Louvre</span>’s first female president is trying to <span class="colorLinks">hold on to her job [https://www.nytimes.com/2025/11/20/world/europe/louvre-director-theft-renovation.html]</span> following the October heist.</p>
<p class="articleParagraph enarticleParagraph" >* A self-portrait by Frida Kahlo that shows her sleeping underneath a skeleton sold for $55 million at an auction at <span class="companylink">Sotheby’s</span>, <span class="colorLinks">setting a record [https://www.nytimes.com/2025/11/20/arts/design/kahlo-portrait-auction-art-sothebys.html]</span> for the artist.</p>
<p class="articleParagraph enarticleParagraph" >* <span class="companylink">Roblox</span>, the online gaming platform that is enormously popular with kids, this week introduced a system to <span class="colorLinks">assess users’ ages by scanning their faces [https://www.nytimes.com/2025/11/21/business/roblox-age-verification.html]</span>. (The company’s C.E.O. went on <span class="colorLinks">Hard Fork, The Times’s tech podcast [https://www.nytimes.com/2025/11/21/podcasts/hardfork-roblox-child-safety.html]</span>, to talk about child safety.)</p>
<p class="articleParagraph enarticleParagraph" >CULTURE CALENDAR</p>
<p class="articleParagraph enarticleParagraph" > “Hamnet”: In 1596, William Shakespeare’s son, Hamnet, died at the age of 11. Little is known of him beyond those basic facts. But Maggie O’Farrell’s 2020 novel bearing the boy’s name conjured an entire world around him and imagined the devastation that his death brought onto his family. Now Chloé Zhao, who won an Oscar for directing “Nomadland,” has adapted the story for the screen, with Paul Mescal and Jessie Buckley starring. When the film premiered at the Telluride Film Festival, The Times’s Nicole Sperling <span class="colorLinks">described it [https://www.nytimes.com/2025/09/01/movies/telluride-springsteen-biopic.html]</span> as “a 10-hanky weepie.”</p>
<p class="articleParagraph enarticleParagraph" >Limited release next week; in theaters everywhere Dec. 5.</p>
<p class="articleParagraph enarticleParagraph" >For more: T Magazine interviewed Buckley, who described how she <span class="colorLinks">had connected with her character through dreams [https://www.nytimes.com/2025/08/05/t-magazine/jessie-buckley-hamnet-the-bride.html]</span>.</p>
<p class="articleParagraph enarticleParagraph" >RECIPE OF THE WEEK</p>
<p class="articleParagraph enarticleParagraph" >Pumpkin Soup</p>
<p class="articleParagraph enarticleParagraph" >This is a good weekend to keep things simple as far as dinner is concerned. Simmering up a pot of Lidey Heuck’s <span class="colorLinks">pumpkin soup [https://cooking.nytimes.com/recipes/1021618-pumpkin-soup?algo=cooking_search_relevance_metric_ios_and_web&fellback=false&imp_id=5035298679360922&req_id=2865617658046320&surface=cooking-search&variant=0_relevance_reranking]</span> is not only easy and satisfying, it will make good use of all the pumpkin purée that’s taken over the canned vegetable aisle at the supermarket. Creamy yet light, scented with curry powder and sweetened with a touch of maple syrup and apple cider, it’s a fragrant, warming kickoff to this hectic holiday week.</p>
<p class="articleParagraph enarticleParagraph" >REAL ESTATE</p>
<p class="articleParagraph enarticleParagraph" >The Hunt: After wandering through a series of short-term rentals in France, Turkey and Morocco, a young family decided to settle in Portland. What did they choose for their forever home? <span class="colorLinks">Play our game [https://www.nytimes.com/interactive/2025/11/20/realestate/portland-oregon-home-sale.html]</span>.</p>
<p class="articleParagraph enarticleParagraph" >What you get for $900,000: An <span class="colorLinks">Eastlake Victorian in New Orleans [https://www.nytimes.com/2025/11/19/realestate/900000-dollar-homes-minneapolis-new-orleans-rapid-city.html]</span>, a Queen Anne Revival in Rapid City, S.D., and an American <span class="companylink">Foursquare</span> in Minneapolis.</p>
<p class="articleParagraph enarticleParagraph" >A peek inside: The actor F. Murray Abraham <span class="colorLinks">opened up his home to the Times [https://www.nytimes.com/interactive/2025/11/18/realestate/f-murray-abraham-home-tour.html]</span>. Find out where he keeps his Oscar and what he got at Marlon Brando’s estate sale.</p>
<p class="articleParagraph enarticleParagraph" >LIVING</p>
<p class="articleParagraph enarticleParagraph" >The home of cacao: Brazil’s craft chocolatiers aren’t just making great sweets — <span class="colorLinks">they’re also preserving the Amazon [https://www.nytimes.com/2025/11/21/climate/cop30-belem-chocolate.html]</span>.</p>
<p class="articleParagraph enarticleParagraph" >Top of your head: You’ve only got one scalp. No wonder people are <span class="colorLinks">seeking out pricey treatments to care for theirs [https://www.nytimes.com/2025/11/20/style/scalp-care-beauty-trends-2025.html]</span>.</p>
<p class="articleParagraph enarticleParagraph" >Put it away: New York City nightclubs are starting to <span class="colorLinks">ban phones on the dance floor [https://www.nytimes.com/2025/11/21/nyregion/nyc-nightlife-no-phones.html]</span>. Said one reveler: “I’d rather live in the moment and feel the joy.”</p>
<p class="articleParagraph enarticleParagraph" >ADVICE FROM WIRECUTTER</p>
<p class="articleParagraph enarticleParagraph" >How to win at white elephant</p>
<p class="articleParagraph enarticleParagraph" >Played right, a <span class="colorLinks">white elephant gift swap [https://www.nytimes.com/wirecutter/gifts/white-elephant-ideas/]</span> can be better than spiked punch at upping the humor and excitement of holiday gatherings. But it does require a clear code of conduct. First, before invitations go out, settle on a monetary limit. Then, to keep things fun, fair and relatively peaceful, decide how many times each gift can be stolen before it’s off limits. And determine whether the person who drew first gets to steal or unwrap a final gift at the end. Game aside, the true golden rule is something I stand by in all areas of my life: Bring a good gift. What that means will change depending on the guests, but here are a few of <span class="colorLinks">the most-stolen gifts from my own white elephant parties [https://www.nytimes.com/wirecutter/reviews/the-gift-white-elephant-20251121/]</span> over the years. — Samantha Schoech</p>
<p class="articleParagraph enarticleParagraph" >For handpicked gift ideas and expert advice, <span class="colorLinks">sign up for the Gift newsletter from Wirecutter [https://www.nytimes.com/newsletters?newsletter_signup=true&product_code=WCGG]</span>.</p>
<p class="articleParagraph enarticleParagraph" >GAME OF THE WEEK</p>
<p class="articleParagraph enarticleParagraph" >Gotham F.C. vs. Washington Spirit, N.W.S.L. final: “Underdog, my ass.” That was Jaedyn Shaw, a star of Gotham F.C., after her squad — the lowest seed in the playoffs — defeated top-seeded Kansas City in the first round. Gotham then took down last year’s champs, the Orlando Pride, thanks to a <span class="colorLinks">goal by Shaw [https://bsky.app/profile/nwslsoccer.com/post/3m5rrhu4tx226]</span> in the game’s final moments.</p>
<p class="articleParagraph enarticleParagraph" >Now, in the championship, Gotham will face the Spirit. As The Athletic’s Emily Olsen <span class="colorLinks">writes in her preview of the match [https://www.nytimes.com/athletic/6816338/2025/11/18/nwsl-championship-preview-full-time/]</span>, the teams have a good rivalry cooking; over the N.W.S.L.’s 12 seasons, they have played against each other more than any other two teams. The Spirit, for their part, would benefit from an appearance by Trinity Rodman, <span class="colorLinks">one of the world’s best players [https://www.nytimes.com/athletic/6810930/2025/11/15/trinity-rodman-contract-nwsl-salary-cap/]</span>, who has been recovering from a knee injury and played just a few minutes in the semifinal.</p>
<p class="articleParagraph enarticleParagraph" >Tonight, 8 p.m. Eastern on <span class="companylink">CBS</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >NOW TIME TO PLAY</p>
<p class="articleParagraph enarticleParagraph" >Here is <span class="colorLinks">today’s Spelling Bee [https://www.nytimes.com/puzzles/spelling-bee]</span>. Yesterday’s pangrams were grandpop and propaganda.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Take the news quiz [https://www.nytimes.com/interactive/2025/11/21/briefing/trump-saudi-arabia-jeffrey-epstein-wicked-quiz.html]</span> to see how well you followed this week’s headlines.</p>
<p class="articleParagraph enarticleParagraph" >And here are <span class="colorLinks">today’s Mini Crossword [https://www.nytimes.com/crosswords/game/mini]</span>, <span class="colorLinks">Wordle [https://www.nytimes.com/games/wordle/index.html]</span>, <span class="colorLinks">Sudoku [https://www.nytimes.com/puzzles/sudoku]</span>, <span class="colorLinks">Connections [https://www.nytimes.com/games/connections]</span> and <span class="colorLinks">Strands [https://www.nytimes.com/games/strands]</span>.</p>
<p class="articleParagraph enarticleParagraph" >Thanks for spending part of your weekend with The Times. — Melissa</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Sign up here to get this newsletter in your inbox [https://www.nytimes.com/newsletters/morning-briefing]</span>. Reach our team at <span class="colorLinks">themorning@nytimes.com [mailto:themorning@nytimes.com]</span>.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | glife : Living/Lifestyle | gtour : Travel</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Autumn (Season) | briefing | Christmas | Holidays and Special Occasions | internal-storyline-no | Pumpkins | Thanksgiving Day</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>The New York Times Company</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NYTFEED020251122elbm00209</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC41160020251122elbm0000n"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump praises Mamdani in Oval Office meeting "I think he is going to surprise some conservative people, actually," the President said.</b><div class="leadFields"><a href="javascript:void(0)">TVNZ</a>, 11:45 AM, 22 November 2025, 13654 words, (English)</div><div class="snippet ensnippet"> President Donald Trump has called New York City&#39;s Mayor-elect Zohran Mamdani a &quot;100% Communist Lunatic&quot; and a &quot;total nut job.&quot; Mamdani has called Trump’s administration &quot;authoritarian&quot; and described himself as &quot;Donald Trump’s worst ...</div>
<div>(Document WC41160020251122elbm0000n)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC41160020251122elbm0000c"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Air New Zealand cabin crew to strike in December Around 1250 E tū cabin crew across the international, domestic, and regional fleets will...</b><div class="leadFields"><a href="javascript:void(0)">TVNZ</a>, 11:45 AM, 22 November 2025, 11797 words, (English)</div><div class="snippet ensnippet"> Air NZ cabin crew will strike on next month after months of negotiations failed to secure a fair deal on pay and conditions.Around 1250 E tū cabin crew across the international, domestic, and regional fleets will stop work for 24 hours on ...</div>
<div>(Document WC41160020251122elbm0000c)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC43537020251122elbm0001g"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Tone shifts in Washington: Trump praises Mamdani after White House talks, vows support for a ‘safe New York’</b><div class="leadFields"><a href="javascript:void(0)">The Statesman</a>, 02:51 AM, 22 November 2025, 490 words, (English)</div><div class="snippet ensnippet"> US President Donald Trump struck a noticeably calmer tone on Friday as he welcomed New York City mayor-elect Zohran Mamdani to the White House. The meeting marked a shift from the tense exchanges that defined the long and bitter mayoral ...</div>
<div>(Document WC43537020251122elbm0001g)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-BIZINS0020251122elbm0008e" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/bizinsLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>How Zohran Mamdani's NYC victory could make a hot ultra-luxury market in cities like Miami even hotter</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Alex Nicoll </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1136 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>07:46 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Business Insider</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>BIZINS</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. Insider Inc </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >* Incoming NYC Mayor Mamdani's embrace of socialism has some predicting the wealthy will flee</p>
<p class="articleParagraph enarticleParagraph" >* In luxury hotspots like Miami, there's anticipation that this will unleash a buying spree.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >* This comes after a banner year for ultra-luxury purchases in locales popular with ex-New-Yorkers.</p>
<p class="articleParagraph enarticleParagraph" >Zohran Mamdani won a resounding mayoral victory by <span class="colorLinks">promising to make it cheaper to live in New York City. [https://www.businessinsider.com/zohran-mamdani-proposals-how-much-they-will-cost-affordability-childcare-2025-10]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >However, his victory earlier this month may have the unintended effect of making it even more expensive for the <span class="colorLinks">ultrawealthy to afford their homes [https://www.businessinsider.com/top-20-cities-the-ultrawealthy-buy-second-homes-in-2025-2025-8]</span> in favorite ex-New Yorker haunts like Greenwich, Palm Beach, and the <span class="colorLinks">Hamptons [https://www.businessinsider.com/hamptons-summer-wall-street-guide-restaurants-bars-music-clubs-2025-7]</span>, top real estate agents told <span class="companylink">Business Insider</span>. Real estate agents in these elite zip codes say that the "Mamdani effect" is already creeping into prices or causing some to pull the trigger to buy, as locals anticipate another migration wave.</p>
<p class="articleParagraph enarticleParagraph" >2025 was already a "banner year" for Dina Goldentayer, a Miami-based real estate agent who, with more than $3 billion in sales since 2021, is the top earner at real estate firm <span class="companylink">Douglas Elliman</span>. Even as prices are dropping in Miami at the median-home level, they're growing for ultra-luxury buyers. As of September, the median home price for Miami was down about 4% year-over-year, while it was up <span class="colorLinks">8.4% for luxury homes in Miami [https://www.redfin.com/news/luxury-homes-market-september-2025/]</span>, according to <span class="companylink">Redfin</span>.</p>
<p class="articleParagraph enarticleParagraph" >"Every year, our price points get higher and higher," she said. Referencing million-dollar listings, she added: "30 is the new 20."</p>
<p class="articleParagraph enarticleParagraph" >This dynamic mimics <span class="colorLinks">a broader consumer dynamic, with wealthy Americans spending more [https://www.businessinsider.com/wealthy-americans-spend-lower-income-cut-back-affordability-earnings-consumers-2025-8]</span> while the rest cut back.</p>
<p class="articleParagraph enarticleParagraph" >She has not had any New York to Miami transplant clients say they were moving because of Mamdani, but she said Miamians believe the "election results will flood the market with New Yorkers."</p>
<p class="articleParagraph enarticleParagraph" >"I've had some sellers in Miami say, 'Let's raise my price,'" Goldentayer said, though she has cautioned them to wait until he actually rolls out policies before raising it.</p>
<p class="articleParagraph enarticleParagraph" >Socialist Mamdani, who will take office in 2026, has proposed raising taxes on those making more than $1 million a year, and criticized the <span class="companylink">New York Police Department</span>. His campaign left <span class="colorLinks">ultrawealthy New Yorkers concerned [https://www.businessinsider.com/list-of-billionaires-spending-stop-zohran-mamdani-new-york-2025-10]</span> he's going to target their wealth and make the city less safe.</p>
<p class="articleParagraph enarticleParagraph" >While sellers are salivating at steep price jumps, buyers are worried that New Yorkers will drive prices up, Goldentayer said.</p>
<p class="articleParagraph enarticleParagraph" >"I had one client use the expression 'The Mamdani effect is being baked into the price,'" Goldentayer said.</p>
<p class="articleParagraph enarticleParagraph" >Heading down to Florida</p>
<p class="articleParagraph enarticleParagraph" >Nancy Batchelor, a top Miami real estate agent who heads her own group with Compass, wrote to BI that she's had "a handful of buyers mention the election," but that it's never the "sole reason."</p>
<p class="articleParagraph enarticleParagraph" >"What we're seeing is more subtle; people who were on the fence are now exploring their options with more urgency," Bachelor wrote. "Many are waiting it out to see if anything changes in New York City before making a decision."</p>
<p class="articleParagraph enarticleParagraph" >That might mean buying a second home in Miami for now, but not actually moving their family south in the middle of the school year, she said.</p>
<p class="articleParagraph enarticleParagraph" >And in markets like Palm Beach, which has been a magnet for Manhattanites, what started as a pandemic trend is turning into a "full lifestyle shift," Samantha Curry, a top Palm Beach real estate agent, wrote to BI.</p>
<p class="articleParagraph enarticleParagraph" >South Florida has attracted a number of billionaires like legendary investor <span class="colorLinks">Carl Icahn [https://www.businessinsider.com/carl-icahn-moving-hedge-fund-to-miami-from-new-york-2019-9]</span> and <span class="colorLinks">Citadel's Ken Griffin, who moved his firm's Chicago headquarters to Miami [https://www.businessinsider.com/citadel-headquarters-in-miami-work-life-balance-2024-3]</span>. Steven Ross, former CEO of Related, which developed the upscale Hudson Yards neighborhood in NYC, spun out the <span class="colorLinks">firm's Palm Beach operations to form Related Ross. [https://www.businessinsider.com/office-construction-demand-upcoming-shortage-real-estate-2024-10]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Curry has heard from ex-New Yorkers who said the potential tax implications and safety concerns of Mamdani have been a reason for their searches. Right now, it's mostly "driving conversations," especially with the top tier of clients, but actual increases in taxes will really change things.</p>
<p class="articleParagraph enarticleParagraph" >"If that happens, we expect to see another wave of buyers from the north heading to Palm Beach," she wrote.</p>
<p class="articleParagraph enarticleParagraph" >A record year for Greenwich</p>
<p class="articleParagraph enarticleParagraph" >While Miami and Palm Beach have become destinations for financial types, a more traditional post-Wall Street destination, <span class="colorLinks">Greenwich, CT [https://www.businessinsider.com/left-nyc-moved-to-coastal-town-east-coast-greenwich-connecticut-2025-9]</span>, is actually seeing some post-election sales.</p>
<p class="articleParagraph enarticleParagraph" >Ultra-luxury Greenwish home sales jumped after Mamdani's June primary victory, with more homes sold in a shorter period, and at higher prices, with an average of $19.7 million per home after the nomination compared to $14.9 million before, according to the mid-November analysis by Mark Pruner, a top Greenwich agent for Compass.</p>
<p class="articleParagraph enarticleParagraph" >Pruner said the town has seen three large sales go into contract since the election, ranging from $14 million to $28 million. He has had some clients say that Mamdani is a factor behind their move, but that the evidence is "anecdotal."</p>
<p class="articleParagraph enarticleParagraph" >What is certain is that Greenwich is having a record year, he said, saying that it's on track for more than 50 sales over $10 million, compared to a prior high of 19 in 2007.</p>
<p class="articleParagraph enarticleParagraph" >"A significant portion of it is the concern about the stock market," Pruner said. "We're at record highs, people are sitting at lots of unrealized profits, and there are people who are taking money out of their stock investments and putting it into high-end real estate here in Greenwich."</p>
<p class="articleParagraph enarticleParagraph" >If a Mamdani wave continues, home hunters will have slim pickings in Greenwich. Inventory is down 82% from where it was pre-COVID, according to Pruner, pushing prices higher before any Mamdani effect became part of the equation.</p>
<p class="articleParagraph enarticleParagraph" >So far, the numbers don't match the chatter. Despite all the talk of wealthy fleeing, and that penthouses and brownstones would be going for bargain rates, luxury home sales surged in the city following the election. The week of the election saw 41 contracts signed at $4 million and above, the most in a single week since late May, according to the <span class="companylink">Olshan</span> Luxury Market Report.</p>
<p class="articleParagraph enarticleParagraph" >New York's continued strength is a result of "multi-market living," said Miami's Batchelor.</p>
<p class="articleParagraph enarticleParagraph" >"Many aren't choosing between New York and Miami, they're choosing both," she said.</p>
<p class="articleParagraph enarticleParagraph" >Now that's not to say there won't be some ultrawealthy people selling properties in New York, but many of the ultrawealthy will buy in Florida and change their domicile to shake off the tax man while keeping their pad on Billionaire's Row.</p>
<p class="articleParagraph enarticleParagraph" >"The nice thing is, if you can afford an over $10 million house, you generally can afford two, or three, or four," said Pruner.</p>
<p class="articleParagraph enarticleParagraph" >Read the original article on <span class="colorLinks">Business Insider [https://www.businessinsider.com/miami-greenwich-brace-mamdani-luxury-real-estate-wave-2025-11]</span>
                  </p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IN</b>&nbsp;</td><td><br/>i834 : Real Estate Agents/Brokers | i85 : Real Estate Services/Transactions | icre : Real Estate/Construction | ireest : Real Estate</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>miami : Miami | namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usfl : Florida | usny : New York State | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Finance | luxury-real-estate | Real Estate | zohran-mamdani</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Insider Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document BIZINS0020251122elbm0008e</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC56775020251122elbm0003p"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Renewed commitment: New York Governor Kathy Hochul welcomes Trump-Mamdani meeting</b><div class="leadFields"><a href="javascript:void(0)">WebIndia123.com</a>, 10:47 PM, 21 November 2025, 419 words, (English)</div><div class="snippet ensnippet"> New York Governor Kathy Hochul on Friday issued a strongly worded statement after President Donald Trump met Mayor-Elect Zohran Mamdani, voicing approval of the President&#39;s &quot;renewed commitment&quot; to the state while condemning Islamophobic ...</div>
<div>(Document WC56775020251122elbm0003p)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC42295020251122elbm00002"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump-Mamdani Meeting</b><div class="leadFields"><a href="javascript:void(0)">KPIX-TV5</a>, 11:39 AM, 22 November 2025, 3246 words,  Renee Anderson, (English)</div><div class="snippet ensnippet"> Jesse Zanger is the managing editor of CBSNewYork.com. Jesse has previously worked for the Fox News Channel and Spectrum News NY1. He covers regional news around the Tri-State Area, with a particular focus on breaking news and extreme ...</div>
<div>(Document WC42295020251122elbm00002)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC57089020251122elbm0000c"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Mamdani set to meet with President Trump at White House today New York City Mayor-elect Zohran Mamdani is set to meet with President Trump...</b><div class="leadFields"><a href="javascript:void(0)">WCBS TV</a>, 11:35 AM, 22 November 2025, 635 words, (English)</div><div class="snippet ensnippet"> Christina Fan joined CBS News New York as a general assignment reporter in spring of 2019.Jessica Moore is an Emmy Award-winning anchor for the weekend evening newscasts on CBS News New York and New York 55. Moore joined the stations in ...</div>
<div>(Document WC57089020251122elbm0000c)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC57089020251122elbm00009"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  What's at stake in the Trump-Mamdani meeting? Political analysis New York City Mayor-elect Zohran Mamdani is sitting down with President...</b><div class="leadFields"><a href="javascript:void(0)">WCBS TV</a>, 11:35 AM, 22 November 2025, 806 words, (English)</div><div class="snippet ensnippet"> Jesse Zanger is the managing editor of CBSNewYork.com. Jesse has previously worked for the Fox News Channel and Spectrum News NY1. He covers regional news around the Tri-State Area, with a particular focus on breaking news and extreme ...</div>
<div>(Document WC57089020251122elbm00009)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC57089020251122elbm0000n"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump-Mamdani meeting marked by surprising moments of praise President Trump and NYC Mayor-elect Zohran Mamdani have hurled attacks at each...</b><div class="leadFields"><a href="javascript:void(0)">WCBS TV</a>, 11:36 AM, 22 November 2025, 1077 words, (English)</div><div class="snippet ensnippet"> Joe Walsh is a senior editor for digital politics at CBS News. Joe previously covered breaking news for Forbes and local news in Boston.President Trump&#39;s meeting with incoming New York City Mayor Zohran Mamdani on Friday was not expected to...</div>
<div>(Document WC57089020251122elbm0000n)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC57089020251122elbm00012"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  What Trump and Mamdani have said about each other ahead of White House meeting President Trump has called Zohran Mamdani "my little...</b><div class="leadFields"><a href="javascript:void(0)">WCBS TV</a>, 11:36 AM, 22 November 2025, 1404 words, (English)</div><div class="snippet ensnippet"> Kathryn Watson is a politics reporter for CBS News Digital, based in Washington, D.C.Update: President Trump and Mayor-elect Mamdani struck a positive tone in their meeting. Read the latest here. Our earlier story is below.</div>
<div>(Document WC57089020251122elbm00012)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC57089020251122elbm00013"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  New York Rep. Nydia Velázquez won't seek reelection in 2026 Velázquez, 72, says she will retire after her 16th term in office. She...</b><div class="leadFields"><a href="javascript:void(0)">WCBS TV</a>, 11:36 AM, 22 November 2025, 395 words, (English)</div><div class="snippet ensnippet"> Jesse Zanger is the managing editor of CBSNewYork.com. Jesse has previously worked for the Fox News Channel and Spectrum News NY1. He covers regional news around the Tri-State Area, with a particular focus on breaking news and extreme ...</div>
<div>(Document WC57089020251122elbm00013)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC44933020251122elbm0000h"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Takeaways from Trump and Mamdani visit: Both men get something they want, GOP loses a punching bag</b><div class="leadFields"><a href="javascript:void(0)">The Times Herald</a>, 07:20 PM, 21 November 2025, 963 words, (English)</div><div class="snippet ensnippet"> Trump seemed thoroughly impressed with Mamdani, describing him as “a very rational man” who “wants to see New York be great again.”The two had called each other “fascist” and “communist,” but when President Donald Trump and New York City ...</div>
<div>(Document WC44933020251122elbm0000h)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC42290020251122elbm003mm"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Mamdani, Trump find common ground during first meeting at White HouseUpdated 2 hours ago</b><div class="leadFields"><a href="javascript:void(0)">ABC 7</a>, 05:47 AM, 22 November 2025, 734 words,  the Associated Press, (English)</div><div class="snippet ensnippet"> NEW YORK (WABC) -- New York City Mayor-elect Zohran Mamdani is heading home on Saturday after his highly anticipated meeting with President Donald Trump at the White House.</div>
<div>(Document WC42290020251122elbm003mm)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC44949020251122elbm000bv"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  As the two leaders stood together, Trump once again referred to the May standoff between India and Pakistan, saying, "I...</b><div class="leadFields"><a href="javascript:void(0)">Deccan Chronicle</a>, 05:10 AM, 22 November 2025, 457 words, (English)</div><div class="snippet ensnippet"> Washington: US President Donald Trump again repeated his long-standing claim that he played a central role in helping ease the conflict between India and Pakistan. He made the remarks during his meeting with New York City Mayor-elect Zohran...</div>
<div>(Document WC44949020251122elbm000bv)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-GRDN000020251122elbm002pj" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/grdnLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Fashion</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Less politics, more makeup: the unraveling of Teen Vogue under Trump 2.0</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Carter Sherman </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1786 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>11:03 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The Guardian</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>GRDN</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© Copyright 2025.  The Guardian.  All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The folding of the progressive youth-focused magazine into Vogue comes at turbulent time for journalism and the crumbling of feminist media</p>
<p class="articleParagraph enarticleParagraph" >In late 2016, just a few weeks after Donald Trump won his first presidential election,Teen Vogue published a story that set the internet ablaze: “Donald Trump Is Gaslighting America.”</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The story garnered more than 1.3m hits, making it the magazine’s most-read story of the year. Elaine Welteroth, then the editor-in-chief, <span class="colorLinks">told NPR [https://www.npr.org/2019/06/18/733737360/elaine-welteroth-on-transforming-teen-vogue-and-knowing-your-worth]</span> that the day it published, Teen Vogue sold “in that month, more copies of the magazine than we had that entire year”. It was a transformative moment for the publication: proof that a magazine long associated with <span class="companylink">Disney</span> child stars and headlines like “Prom Fever!” could shine light on the political dimensions of young people’s lives.</p>
<p class="articleParagraph enarticleParagraph" >Over the following years, Teen Vogue deepened its coverage of politics and identity, becoming an unlikely hearth for progressive, even radical, feminism within the manicured offices of its publisher Condé Nast.</p>
<p class="articleParagraph enarticleParagraph" >Now, nearly a decade since that “Gaslighting America” story, Trump is once again in the White House and Teen Vogue as it was once known is gone.</p>
<p class="articleParagraph enarticleParagraph" >Earlier this month, a Vogue Business article announced that Condé Nast was folding Teen Vogue into its flagship property, Vogue, to “provide a more unified reader experience across titles”. Although the article promised that Teen Vogue would “keep its unique editorial identity and mission”, it also said the outlet would now focus on “career development” and “cultural leadership” while its editor-in-chief would be stepping down. Condé Nast also laid off six unionized Teen Vogue employees, including its politics editor. Most of the laid-off employees were “BIPOC women or trans”, <span class="colorLinks">according to the Condé Nast union [https://x.com/condeunion]</span>.</p>
<p class="articleParagraph enarticleParagraph" >After Condé staffers questioned the head of HR over the layoffs, <span class="colorLinks">the company fired four of them [https://www.thewrap.com/conde-nast-fires-union-staffers-video/]</span>, prompting pushback from the union and a pledge from New York’s attorney general, Letitia James: “Condé Nast, I’ll see you in court.”</p>
<p class="articleParagraph enarticleParagraph" >A Condé Nast spokesperson told the Guardian that changes to Teen Vogue were driven solely by business concerns, not by politics, and added: “The employment terminations were lawful and based on clear violations of company policies.”</p>
<p class="articleParagraph enarticleParagraph" >Teen Vogue’s unraveling comes at a time of intensifying turbulence for journalism, particularly of the progressive variety. Many of the blogs that once studded the feminist media universe and made “gaslighting” a mainstream term – Jezebel, Feministing, the Hairpin, the Toast – now lay dead or dying. Several of their staid older sisters, the women’s magazines, have started publishing fewer print issues a year or going digital-only. Youth-oriented websites once believed to be the future of media, like Vice and Vox, have shed jobs at astonishing rates. (Note: I worked at Vice for years before quitting in 2023, after the company laid off wide swathes of the newsroom and filed for bankruptcy.)</p>
<p class="articleParagraph enarticleParagraph" >These outlets frequently focused on the people whose lives have fallen under the glare of the Trump administration’s microscope:women, people of color, LGBTQ+ folks, anybody to the left of Ben Shapiro. Taken together, their downfall can feel like an industry-wide retreat from covering long-marginalized voices.</p>
<p class="articleParagraph enarticleParagraph" >“People change their policies based on reading the vibe in the room, if you will,” said Christina Bellantoni, director of Annenberg’s Media Center at the <span class="companylink">University of Southern California</span>. (Bellantoni is friends with Teen Vogue’s outgoing editor-in-chief.) “We’ve got three more years of this administration making clear its priorities do not lay with having newsrooms that are reflective of the diverse world we cover.”</p>
<p class="articleParagraph enarticleParagraph" >The dismal economics of trying to make money off the internet have decimated outlets of all political stripes. Between 2008 and 2024, <span class="colorLinks">74% of newsroom jobs vanished [https://www.cjr.org/business_of_news/reality-layoffs-behind-national-jobs-numbers-reynolds-lewis.php]</span>. Condé is a part of that trend, having endured multiple rounds of layoffs over the last several years.</p>
<p class="articleParagraph enarticleParagraph" >But it’s a unique set of pressures that have been responsible for crushing feminist publications. During the reign of the 2010s #girlboss, the feminist blogosphere generated takes on everything from Christmas songs to Edward Snowden’s girlfriend. Women’s magazines took note and started publishing uncomplicated odes to “the notorious RBG” and the Wing, a now-shuttered women-focused club and co-working space.</p>
<p class="articleParagraph enarticleParagraph" >That type of coverage evaporated after the 2016 election, which saw most white women vote for Trump instead of voting for Hillary Clinton to shatter “the highest and hardest glass ceiling.” During that same time, social media algorithms became increasingly opaque, sending feminist media’s online traffic plummeting at the same moment that Trump’s policies started to <span class="colorLinks">threaten long-held feminist victories [https://www.theguardian.com/world/2022/jun/24/roe-v-wade-overturned-abortion-summary-supreme-court]</span>.</p>
<p class="articleParagraph enarticleParagraph" >Now, under Trump 2.0, <span class="colorLinks">all journalism is more fraught [https://www.theguardian.com/commentisfree/2025/nov/19/trump-khashoggi-killing-new-low]</span>, particularly for women. Earlier this month, Trump <span class="colorLinks">told a female journalist [https://www.theguardian.com/us-news/2025/nov/18/trump-calls-reporter-piggy-bloomberg]</span>: “<span class="colorLinks">Quiet, piggy [https://www.theguardian.com/commentisfree/2025/nov/19/trump-khashoggi-killing-new-low]</span>.”</p>
<p class="articleParagraph enarticleParagraph" >“These glossy magazines are generally wary of political coverage, because they say advertisers don’t want to sponsor it,” said Amy Odell, an independent journalist who runs the fashion news <span class="companylink">Substack</span> Back Row and closely covers Vogue.</p>
<p class="articleParagraph enarticleParagraph" >“This cuts deep with women’s publications because they probably get that feedback more than men’s publications do. With women’s publications, it’s like: ‘Just do lip liner tutorials and we’ll sell those to beauty advertisers’.”</p>
<p class="articleParagraph enarticleParagraph" >Condé outlets like Wired, the New Yorker and Vanity Fair have continued to cover politics; Glamour, a Condé women’s magazine, also sometimes covers it. But some ex-employees have said that they felt company brass undermined Teen Vogue’s political coverage. Alma Avalle, a Bon Appetit journalist fired after the confrontation with Condé leadership, <span class="colorLinks">told the New York City local news outlet Hell Gate [https://hellgatenyc.com/conde-nast-fired-four-teen-vogue-nlrb/]</span> that she had heard that “an executive said something to the effect of: ‘The company is trying to avoid the attention of the Trump administration, and trying to avoid the attention and the scrutiny of the right.’”</p>
<p class="articleParagraph enarticleParagraph" >Allegra Kirkland, Teen Vogue’s former politics director, <span class="colorLinks">wrote in Talking Points Memo [https://talkingpointsmemo.com/cafe/what-we-lost-when-conde-nast-unceremoniously-shuttered-teen-vogue]</span> that ahead of Trump’s second inauguration, she was told that Anna Wintour – Condé’s global chief content officer and artistic director – didn’t want to hear the word “politics” during Teen Vogue’s annual strategy meeting.</p>
<p class="articleParagraph enarticleParagraph" >In response to questions for this story, a Condé spokesperson said in an email: “Teen Vogue has faced ongoing challenges around scale and audience reach for some time. Rather than continuing to operate independently, bringing Teen Vogue under the Vogue umbrella allows it to tap into a larger audience, stronger distribution and more resources.”</p>
<p class="articleParagraph enarticleParagraph" >They added: “This was a business decision, not a political one.”</p>
<p class="articleParagraph enarticleParagraph" >Some staff from folded feminist publications have gone independent, writing for platforms like <span class="companylink">Substack</span>. But many of the most popular outlets covering the intersection of politics, identity and women are now on the right.</p>
<p class="articleParagraph enarticleParagraph" >As feminist and progressive outlets have receded, a <span class="colorLinks">conservative “womanosphere” has blossomed [https://www.theguardian.com/us-news/2025/apr/24/womanosphere-conservative-women]</span>, peopled by podcasts like Culture Apothecary, a Turning Point USA production hosted by Maga influencer Alex Clark, and the wannabe “conservative Cosmo” magazine Evie, which recently put <span class="colorLinks">tradwife royalty Hannah Neeleman [https://www.theguardian.com/lifeandstyle/ng-interactive/2024/jul/24/tradwives-tiktok-women-gender-roles]</span> on the cover. The denizens of the womanosphere tend to thread their talk of style, wellness and beauty with antifeminist rhetoric and support for traditional gender roles.</p>
<p class="articleParagraph enarticleParagraph" >One recent Evie email blast, entitled “5 Ways Single Girls Are Repelling Good-Hearted Masculine Men”, advised: “An empowered woman who is overflowing with joy about her career, and knows that it won’t ever be as important as being a wife and mother, does not need to turn a date into a staff meeting where she is respected for her ideas.”</p>
<p class="articleParagraph enarticleParagraph" >Shara Crookston, an associate professor of women’s and gender studies at the <span class="companylink">University of Toledo</span> who has studied Teen Vogue, said that the rise of the womanosphere is easily explained: “I read that as a backlash to feminist progress.”</p>
<p class="articleParagraph enarticleParagraph" >Crookston fears that it is young people, Teen Vogue’s core audience, who seem set to pay the highest price for these changes in media. Not only are they the inheritors of whatever the Trump administration leaves behind, but they are increasingly and uniquely restricted by the harshest of rightwing policies, such as bans on gender-affirming care, access to internet porn and interstate travel for abortions.</p>
<p class="articleParagraph enarticleParagraph" >“I worry that young girls are going to have less options for media content that helps them explore different aspects of their life, and I think that could be pretty damaging,” she continued. “What if you are a teenage girl who knows that you don’t want to get married and have kids and all that you’re seeing is: ‘This is why this is important to be straight, to get married, to have kids’? What options are going to be available to her?”</p>
<p class="articleParagraph enarticleParagraph" >Over the last three years, I interviewed <span class="colorLinks">more than 100 Americans under 30 [https://www.simonandschuster.com/books/The-Second-Coming/Carter-Sherman/9781668052457]</span> about their sexual and romantic lives, their political leanings and the forces that shaped both. While influencers may make up the bulk of young people’s media diet, my interviewees often relied on – and longed for – information from factchecked publications.</p>
<p class="articleParagraph enarticleParagraph" >Paxton Smith, a 20-year-old Texan, was once riveted by a <span class="companylink">Snapchat</span> story from Cosmopolitan that had emphasized that women have the right to choose how to style their body hair. Smith had never realized she had a choice; she just wanted to do what she thought boys wanted.</p>
<p class="articleParagraph enarticleParagraph" >“That was a crazy thing for me to see,” she recalled. “No one had ever framed a woman’s body – especially in a sexual way – as being [able to be] whatever floated their boat. It didn’t have anything to do with what anybody else thought.”</p>
<p class="articleParagraph enarticleParagraph" >From that <span class="companylink">Cosmo</span> story, Smith said she learned that “what’s sexy is what’s sexy to you and you should prioritize you”. It was part of her political awakening. Years later, <span class="colorLinks">Smith went viral [https://www.vice.com/en/article/this-teens-defiant-speech-abou-at-her-graduation-is-going-viral/]</span> for giving a speech at her Dallas area high school about the importance of abortion rights.</p>
<p class="articleParagraph enarticleParagraph" >Lex McMenamin, a Teen Vogue staffer who was laid off when the outlet was folded into Vogue, said they thought about the future of young people “every day, on weekends, at night, for years”.</p>
<p class="articleParagraph enarticleParagraph" >“Feminist media is not dead,” McMenamin said. “Young people are so smart. I lack the nihilism that people have about young people and learning and self-development, including for marginalized people. There’s more trans people and more queer people every day, even though they’re doing their damnedest to make us want to die. It doesn’t matter. Our readers will always exist.”</p>
<p class="articleParagraph enarticleParagraph" >• This story was updated on 20 November 2025 to add a post-publication statement from Condé Nast on staff terminations at Teen Vogue.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>CO</b>&nbsp;</td><td><br/>cnast : Conde Nast Publications Inc | newhse : Advance Publications, Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IN</b>&nbsp;</td><td><br/>i475 : Printing/Publishing | i4752 : Magazine Publishing | imed : Media/Entertainment | ipubl : Publishing</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gcom : Society/Community | gfas : Fashion | ghum : Human Rights/Civil Liberties | glife : Living/Lifestyle | gpir : Politics/International Relations | gpol : Domestic Politics | gsoc : Social Issues | gvote : Elections | gwori : Gender Equality | redit : Selection of Top Stories/Trends/Analysis | reqr : Suggested Reading – Industry News | reqrme : Suggested Reading – Media</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Guardian News & Media Limited</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document GRDN000020251122elbm002pj</td></tr></table><br/></div></div><br/><span></span><div id="article-RECOM00020251122elbm00002" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/recomLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>California Clears Path for Gig Unions</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>C. Jarrett Dieterle </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>699 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Reason.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>RECOM</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© 2025 Reason Foundation </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Even after the Prop 22 rebuke, California is pushing a system that could standardize schedules and undermine gig work.</p>
<p class="articleParagraph enarticleParagraph" >
                        <span class="colorLinks">zumaamericasfortyfour439513 | Bryan Smith/ZUMAPRESS/Newscom [https://d2eehagpk5cl65.cloudfront.net/img/c800x450-w800-q60/uploads/2025/11/zumaamericasfortyfour439513-scaled-e1763759519248-800x450.jpg]</span>
                     </p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >In October, California lawmakers passed a <span class="colorLinks">bill [https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202520260AB1340]</span> allowing rideshare drivers to unionize. Under the law, a unionization election can be triggered when just <span class="colorLinks">10 percent [https://www.nytimes.com/2025/10/03/business/uber-lyft-drivers-unionize-california-newsom.html]</span> of the state's rideshare drivers submit forms expressing preference for a union—and a union can be certified with support from as little as <span class="colorLinks">30 percent [https://www.laborrelationsupdate.com/2025/09/fast-track-to-union-representation-california-uber-lyft-and-seiu-unite-behind-driver-union-bill/]</span> of active drivers.</p>
<p class="articleParagraph enarticleParagraph" >This is a new tactic from union-friendly lawmakers, but the end result is likely to be the same: less flexibility for the very workers who say flexibility is what keeps them in these jobs.</p>
<p class="articleParagraph enarticleParagraph" >This saga began in 2018, when the California Supreme Court adopted the so-called <span class="colorLinks">ABC test [https://www.labor.ca.gov/employmentstatus/abctest/]</span> for delivery couriers, a far stricter standard for classifying workers as independent contractors. Lawmakers expanded the test to all sectors through the now-infamous <span class="colorLinks">Assembly Bill (A.B.) 5 [https://www.ftb.ca.gov/file/business/industries/worker-classification-and-ab-5-faq.html]</span> law, making it dramatically harder for Californians to continue working as contractors.</p>
<p class="articleParagraph enarticleParagraph" >The fallout to A.B. 5 was swift and overwhelming, and backlash followed. In 2020, California's electorate overturned the law's application to gig work by voting to approve <span class="colorLinks">Proposition 22 [https://ballotpedia.org/California_Proposition_22,_App-Based_Drivers_as_Contractors_and_Labor_Policies_Initiative_(2020)]</span>.</p>
<p class="articleParagraph enarticleParagraph" >The defeat of A.B. 5 should have settled the question, but lawmakers have simply changed tactics.</p>
<p class="articleParagraph enarticleParagraph" >Under the new law, any certified union would get a one-year challenge-free window within which all ridesharing companies in the state must bargain with it in good faith—effectively creating a form of sectoral bargaining, which is rare in U.S. labor law. Gig companies <span class="colorLinks">accepted [https://www.nytimes.com/2025/10/03/business/uber-lyft-drivers-unionize-california-newsom.html]</span> this approach as less bad than reclassification, but the result will likely still be the same for companies and workers.</p>
<p class="articleParagraph enarticleParagraph" >While theoretically better than forcible reclassification, unionizing gig workers would still reduce worker flexibility and autonomy and raise costs for the platforms. Sectoral bargaining by necessity requires uniform standards across an entire industry, which is most doable with traditional employment models, such as in the fast-food arena, where California has <span class="colorLinks">already introduced [https://www.ocregister.com/2023/09/26/unions-governor-and-fast-food-industry-agree-to-a-detente/]</span> aspects of sectoral bargaining in recent years.</p>
<p class="articleParagraph enarticleParagraph" >Sector-wide negotiations would force a one-size-fits-all approach, pushing platforms toward standardized schedules and undermining the <span class="colorLinks">log-in-anytime flexibility [https://www.nationalaffairs.com/publications/detail/a-flexible-worker-agenda]</span> gig workers typically enjoy.</p>
<p class="articleParagraph enarticleParagraph" >Elements of this shift are already visible in places that have enacted other one-size-fits-all rules for gig work, such as minimum wage mandates. After New York City passed a minimum-wage mandate for rideshare drivers in 2019, <span class="companylink">Uber</span> and <span class="companylink">Lyft</span> began <span class="colorLinks">locking drivers out [https://www-bloomberg-com.ezproxy.cul.columbia.edu/graphics/2024-uber-lyft-nyc-drivers-pay-lockouts/]</span> of their accounts to manage the fallout. A 2023 law extending the minimum wage to app-based delivery workers produced similar results: <span class="colorLinks">driver deactivations [https://nypost.com/2024/07/14/business/nyc-food-delivery-workers-losing-jobs-after-minimum-wage-hike-report/]</span> and a waitlist, as platforms tried to manage sharply increased labor costs.</p>
<p class="articleParagraph enarticleParagraph" >This impacts real people. Consider a single mom who wants to log a few rides on a weeknight when she unexpectedly gets a window of free time. If platforms adopt regimented schedules, she may be blocked from logging in when both she—and potential riders—could benefit.</p>
<p class="articleParagraph enarticleParagraph" >A major concern following California's adoption is that this model will almost certainly spread to other states. California has a track record of exporting its labor-policy experiments: After A.B. 5's passage, <span class="colorLinks">several states [https://www.discoursemagazine.com/p/ending-the-independent-contractor]</span> pursued their own restrictive ABC tests.</p>
<p class="articleParagraph enarticleParagraph" >This could even become a bipartisan push. Given Republicans like Vice President J.D. Vance and Sen. Josh Hawley (R–Mo.) <span class="colorLinks">embracing [https://www-newyorker-com.ezproxy.cul.columbia.edu/news/the-lede/josh-hawley-and-the-republican-effort-to-love-labor]</span> organized labor, others on the right could be moved to support gig worker unionization.</p>
<p class="articleParagraph enarticleParagraph" >It's also clear that the political left will not be content to merely stop at unionization. Progressives like former California assemblymember (and sponsor of A.B. 5) Lorena Gonzalez (D–San Diego) have described unionization as "<span class="colorLinks">a step forward [https://www.nytimes.com/2025/10/03/business/uber-lyft-drivers-unionize-california-newsom.html]</span>" but not "the limit of what's possible." Teamster President Sean O'Brien—whose GOP-convention speech highlighted Republicans' shift toward unions—has <span class="colorLinks">dismissed [https://www.politico.com/news/2025/09/14/california-uber-lyft-union-00562680]</span> a similar Massachusetts unionization effort for gig workers, saying it supports "greedy corporations that want to deny full employment rights to workers."</p>
<p class="articleParagraph enarticleParagraph" >Gig-worker unionization isn't full reclassification—but it pushes the system toward the same endgame.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Bryan Smith/ZUMAPRESS/Newscom [https://d2eehagpk5cl65.cloudfront.net/img/q60/uploads/2025/11/zumaamericasfortyfour439513-scaled-e1763759519248-1200x675.jpg]</span>
                  </p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>CO</b>&nbsp;</td><td><br/>ubrib : Uber International B.V. | ubrti : Uber Technologies Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IN</b>&nbsp;</td><td><br/>i722 : Taxi/Limousine Services | iecom : E-commerce | iint : Online Service Providers | irailtr : Land Transport | iridhps : Ride-Hailing Platforms/Services | itech : Technology | itnsv : Sharing/On-demand Economy Services | itsp : Transportation/Logistics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>c42 : Staff/Personnel | ccat : Corporate/Industrial News | gcat : Political/General News | gjob : Labor Issues | gmini : Minimum/Living Wage | ncat : Content Types | nfact : Factiva Filters | nfcpin : C&E Industry News Filter</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States | usca : California | usw : Western U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Big Government | California | Collective Bargaining | Gavin Newsom | Labor | Labor Unions | Legislation | Minimum Wage | ridesharing | State Governments | Technology | Uber</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Reason Foundation</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document RECOM00020251122elbm00002</td></tr></table><br/></div></div><br/><span></span><div id="article-WPCOM00020251122elbm001uq" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/wpcomLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>National-Politics</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>What Trump and Mamdani have said about each other — then and now </span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Victoria Bisset </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1297 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>washingtonpost.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>WPCOM</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025, The Washington Post Co. All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >For months, President Donald Trump repeatedly referred to Zohran Mamdani, a self-described democratic socialist and now the mayor-elect of New York City, as a "communist" and even threatened to have him arrested. Mamdani, meanwhile, condemned what he called Trump's "fascist agenda."</p>
<p class="articleParagraph enarticleParagraph" >But their apparently cordial meeting in the White House on Friday surprised many — with their comments to the press often lingering on shared points of interest, rather than their opposing politics.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Here's what Trump and Mamdani have previously said about each other and how it compares to their meeting Friday.</p>
<p class="articleParagraph enarticleParagraph" >1. Mamdani's ability and ideology Then: Trump had described Mamdani as "a 100% Communist Lunatic" and a "total nut job."</p>
<p class="articleParagraph enarticleParagraph" >"We've had Radical Lefties before, but this is getting a little ridiculous," he wrote on Truth Social after Mamdani's victory in the Democratic primary in June. "He looks TERRIBLE, his voice is grating, he's not very smart."</p>
<p class="articleParagraph enarticleParagraph" >Now: Following his meeting with Mamdani at the White House on Friday, Trump told reporters Mamdani "ran an incredible race against a lot of smart people" and is "a very rational person" who wants to make New York City "greater than ever before."</p>
<p class="articleParagraph enarticleParagraph" >Trump admitted there are still areas of difference but emphasized that he could find common ground with Mamdani. "There will be topics that we disagree on and I think we'll probably come to a conclusion. … I don't care about affiliations or parties or anything else. I want to see — if this city could be unbelievable, if he could be a spectacular success, I would be very happy."</p>
<p class="articleParagraph enarticleParagraph" >Trump also appeared pleased at the amount of press interest in their meeting, saying: "The press has eaten this thing up" and that Mamdani's win "out of nowhere" was "amazing."</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, for his part, said he had been "very open" about his own democratic socialist beliefs and focused many of his comments on how he and Trump could cooperate on lowering the cost of living in New York. While he and Trump might have "differences about ideology … the place of agreement is the work that needs to be done to make New York City affordable," he said.</p>
<p class="articleParagraph enarticleParagraph" >2. Cooperation Then: During the mayoral race, Trump regularly threatened to withhold federal funding for New York City if Mamdani won. Mamdani would be "one of the best things to ever happen to our great Republican Party," Trump wrote in September. "Remember, he needs the money from me, as President, in order to fulfill all of his FAKE Communist promises. He won't be getting any of it, so what's the point of voting for him?"</p>
<p class="articleParagraph enarticleParagraph" >During the campaign, meanwhile, Mamdani pledged to "fight back" against the president and described himself as "Donald's Trump's worst nightmare, as a progressive Muslim immigrant who actually fights for the things I believe in."</p>
<p class="articleParagraph enarticleParagraph" >Now: "I think you're going to have, hopefully, a really great mayor. The better he does, the happier I am," Trump said in the Oval Office. "I will say, there's no difference in party … and we're going to be helping him to make everybody's dream come true."</p>
<p class="articleParagraph enarticleParagraph" >"He has a chance to really do something great for New York," Trump went on to say. "New York is at a very critical point. And he does need the help of the federal government to really succeed. We're going to be helping him."</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, meanwhile, argued that making New York affordable was in the interests of them both.</p>
<p class="articleParagraph enarticleParagraph" >"When we spoke to those voters who voted for President Trump, we heard them speak about cost of living," Mamdani said. "We focused on that same cost of living, and that's where I am really looking forward to delivering for New Yorkers in partnership with the president."</p>
<p class="articleParagraph enarticleParagraph" >"I can tell you that there were more New Yorkers who voted for President Trump in the most recent presidential election because of that focus on cost of living," he added.</p>
<p class="articleParagraph enarticleParagraph" >3. Living in New York Then: After Mamdani's electoral victory, Trump told a business forum in Miami: "Now the Democrats are so extreme that Miami will soon be the refuge for those fleeing communism in New York City."</p>
<p class="articleParagraph enarticleParagraph" >Now: Asked Friday if he would feel comfortable living in New York while Mamdani is mayor, Trump responded: "Yeah, I would. I really would. Especially after the meeting," and said he had found that he and Mamdani "agree on a lot more than I would have thought."</p>
<p class="articleParagraph enarticleParagraph" >4. ICE Then: In June, Mamdani described <span class="companylink">Immigration and Customs Enforcement</span> as a "rogue agency" that "has no interest in laws, no interest in order."</p>
<p class="articleParagraph enarticleParagraph" >Over the summer, Trump said that if Mamdani blocked ICE raids in New York, "we'll have to arrest him," and suggested that the naturalized U.S. citizen was "here illegally."</p>
<p class="articleParagraph enarticleParagraph" >Now: One reporter asked Friday how the two leaders would reconcile their differences on ICE agents in New York City. Trump responded that they would "work them out."</p>
<p class="articleParagraph enarticleParagraph" >"We've discussed this at great length actually, maybe more than anything else. He wants to have a safe New York. Ultimately, a safe New York is going to be a great New York," Trump said, while Mamdani nodded.</p>
<p class="articleParagraph enarticleParagraph" >Trump also said they wanted "known murderers and known drug dealers" out and that "we're going to make sure that if they are horrible people, then we want to get them out. I think he wants to get them out, maybe more than I do."</p>
<p class="articleParagraph enarticleParagraph" >Mamdani did not directly respond to that claim but said that he had spoken to Trump about "our desire to not only follow the laws of our own city, laws that protect New Yorkers, but also a desire for consistency in our politics across the board."</p>
<p class="articleParagraph enarticleParagraph" >Trump added that they had "discussed crime more than ICE per se … he doesn't want to see crime and I don't want to see crime" — something Mamdani nodded in agreement to.</p>
<p class="articleParagraph enarticleParagraph" >5. Trump's position and views Then: Mamdani previously called Trump "a despot" and said he would defeat "Trump's fascism."</p>
<p class="articleParagraph enarticleParagraph" >During his mayoral primary victory speech, Mamdani said he would "use his power to reject Donald Trump's fascism." On a separate occasion, he said: "We are in a period of political darkness: Donald Trump and his ICE agents are snatching our immigrant neighbors from our city right before our eyes. His authoritarian administration is waging a scorched-earth campaign of retribution against any who dared oppose him."</p>
<p class="articleParagraph enarticleParagraph" >During his victory speech this month, Mamdani said: "If anyone can show a nation betrayed by Donald Trump how to defeat him, it is the city that gave rise to him. And if there is any way to terrify a despot, it is by dismantling the very conditions that allowed him to accumulate power."</p>
<p class="articleParagraph enarticleParagraph" >Now: Asked about some of those comments, Mamdani responded: "I think both President Trump and I, we are very clear about our positions and our views. And what I really appreciate about the president is the meeting that we had focused not on places of disagreement, which there are many, and also focused on the shared purpose that we have in serving New Yorkers."</p>
<p class="articleParagraph enarticleParagraph" >"And I've been called much worse than a despot, so it's not that insulting," Trump added. "Maybe — I think he'll change his mind after we get to working together."</p>
<p class="articleParagraph enarticleParagraph" >When Mamdani was later pressed on whether he believed Trump is a fascist, the president jumped in.</p>
<p class="articleParagraph enarticleParagraph" >"That's okay, you can just say yes. That's easier. It's easier than explaining it, I don't mind."</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Washington Post</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document WPCOM00020251122elbm001uq</td></tr></table><br/></div></div><br/><span></span><div id="article-JPSTEN0020251122elbm000xd" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/jpstenLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>What lessons can be learned from the Trump-Mamdani meeting? - analysis</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>943 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>jpost.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>JPSTEN</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© 2025, Jpost.com (The Jerusalem Post online edition), All rights Reserved - Provided by SyndiGate Media Inc. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >United States President Donald Trump met with the newly elected mayor of New York, Zohran Mamdani, on Friday, a meeting arranged after Mamdani's election. It also occurs before he takes office.</p>
<p class="articleParagraph enarticleParagraph" >The goal of the meeting was to ease the upcoming post-mayoral-election transition and enable New York City to thrive, an issue that matters for Native New Yorker, Trump. It matters to Mamdani because a fight with the White House could lead to problems with federal funding and support. No mayor wants to take office in chaos.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >For some observers of Trump and Mamdani, the meeting was expected. Trump likes winners, and he is often open to taking risks. Mamdani was often open to listening to voters, and he knew that many of them were also Trump supporters.</p>
<p class="articleParagraph enarticleParagraph" >In many ways, the Trump-Mamdani meeting represents the best of America, where people can come together and speak and share ideas. This hurts the extremists who don't want people to listen to each other and who profit from political division.</p>
<p class="articleParagraph enarticleParagraph" >However, others were surprised by this meeting. They had watched the election and listened to right-wing voices call Mamdani a “jihadist” and “communist,” and were convinced that Trump and Mamdani would not get along. However, they tended to be confused by the rhetoric and failed to understand that it is not always reality. Mamdani is not a “jihadist.” He did run as a far-left progressive.</p>
<p class="articleParagraph enarticleParagraph" >President Donald Trump meets with New York City Mayor-elect Zohran Mamdani at the White House in Washington, D.C., U.S., November 21, 2025. (credit: JONATHAN ERNST/REUTERS) Both Trump and Mamdani represent a populist swell of support for new politics on the Left and the Right. It's no surprise that mainstream Republicans and Democrats have been concerned or fearful of this politics. In fact, one might point to the opposite end of the spectrum of the Trump-Mamdani meeting as the appearance of former rivals at the funeral of Dick Cheney. Some see that funeral as representing an American “uniparty,” meaning the fact that moderate Republicans and Democrats tend to come to Washington and quietly agree on most things, even if they run to the Left and Right in elections.</p>
<p class="articleParagraph enarticleParagraph" >The Mamdani-Trump meeting included some discussions about what is best for New York.</p>
<p class="articleParagraph enarticleParagraph" >This included the issues of affordability and energy costs. There were some agreements, it seems, such as an embrace of a FDR-style politics. This is a reminder that while Trump has embraced many causes of the Right, Conservatives, and Far-Right, he is also open to historically Democratic policies. This is because Trump is not an ideological conservative. He's been willing to tear up some Washington sacred cows, such as getting rid of US AID. He has also been willing to confront issues such as conversations about transgender women in women's sports. Certainly, Mamdani would not agree on these issues.</p>
<p class="articleParagraph enarticleParagraph" >However, on issues appealing to working-class Americans and their pocketbooks, they may agree on several points. This is because, when it comes to the criticized “uniparty,” most of them don't seem to care about rising health care or tuition costs. Populists tend to care more about these issues because they channel public resentment over everyday concerns.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani's criticism of IsraelAmong pro-Israel voices, one of the things that has raised eyebrows is that Mamdani is very critical of the recent war in Gaza. This included accusing Israel of genocide, according to numerous headlines. This comes after a campaign in which Mamdani was also accused of excusing the use of phrases such as “globalize the Intifada.”</p>
<p class="articleParagraph enarticleParagraph" >This is in contrast to Trump, who recently hosted freed hostages at the White House. Trump has been passionate about freeing hostages. He also sought to end the war. For this reason, Mamdani's criticisms of the war may not all ruffle Trump's feathers. This is because Trump likely felt the war was not achieving much and that it was important to bring peace. Trump's envoys and other members of the administration have spoken with passion about the civilians in Gaza.</p>
<p class="articleParagraph enarticleParagraph" >Trump believes in the art of the possible. He likes winners, and he likes to see both sides feel they won. Insofar as Mamdani is a winner, Trump assumes that working with him for now will help both Trump and Mamdani and NYC. In time, things may change. Trump has often had falling-outs with people he gravitated toward, such as Elon Musk. The point of the Mamdani meeting was to have a pragmatic meeting and see where the two men could work together.</p>
<p class="articleParagraph enarticleParagraph" >Some Republicans believed that they would be campaigning against Mamdanism in the midterms. Now they wonder if this will be the case. Democrats also appeared concerned that Mamdani might lead to a wave of far-left primary challengers and insurgents. The Mamdani meeting at the White House has left some surprised and unsure of what to do next. A more pragmatic reading of the meeting might see a silver lining in the idea that Americans can bridge gaps and talk policy.</p>
<p class="articleParagraph enarticleParagraph" >Trump has a doctrine of having a door open to different types of leaders. He has embraced the Syrian new transition president, Ahmed al-Sharaa. In both cases, critics called Sharaa and Mamdani “jihadists.” This kind of rhetoric may not be helpful. Trump has shown he can engage with different worldviews and seek to get to a “yes” with them. He did the same thing with the Gaza ceasefire, which critics and skeptics felt would fail.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | gvote : Elections | nanl : Analyses | ncat : Content Types</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States | usdc : Washington DC | use : Northeast U.S. | usny : New York State | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>News</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>The Jerusalem Post</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document JPSTEN0020251122elbm000xd</td></tr></table><br/></div></div><br/><span></span><div id="article-INDOP00020251122elbm000s7" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/indopLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>US politics</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump gloats over ‘traitor’ MTG’s decision to quit as MAGA left reeling</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Erin Keller </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1040 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Independent Online</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>INDOP</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© 2025. Independent Digital News and Media Ltd. All Rights Reserved </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The Georgia firebrand’s upcoming exit from Congress has some MAGA supporters celebrating – but has left others confused at where the movement stands</p>
<p class="articleParagraph enarticleParagraph" >President <span class="colorLinks">Donald Trump [https://www.independent.co.uk/news/world/americas/us-politics/trump-administration-news-today-mamdani-mtg-b2870472.html]</span> has reacted with glee to his former ally <span class="colorLinks">Marjorie Taylor Greene [https://www.independent.co.uk/voices/trump-epstein-maga-tucker-carlson-b2869824.html]</span> ’s decision to <span class="colorLinks">resign from Congress [https://www.independent.co.uk/news/world/americas/us-politics/marjorie-taylor-greene-resign-congress-trump-b2870288.html]</span> , once again calling her a “traitor” and claiming she was quitting because he wouldn’t return her calls.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >In a lengthy <span class="colorLinks">Truth Social [https://truthsocial.com/@realDonaldTrump/posts/115593179521083607]</span> post early Saturday morning, the president called her Marjorie “Traitor” Brown, referencing a previous post in which he said he was changing her surname because “Green grass turns Brown when it begins to ROT!.” He claimed her decision to leave Congress was because she feared a Trump-backed primary election challenger.</p>
<p class="articleParagraph enarticleParagraph" >The decision to leave Congress by the Georgia Republican – one of Trump’s highest profile and most controversial supporters – has left some in the MAGA movement delighted, but others questioning where the movement currently stands.</p>
<p class="articleParagraph enarticleParagraph" >Trump wrote: “Marjorie “Traitor” Brown, because of PLUMMETING Poll Numbers, and not wanting to face a Primary Challenger with a strong Trump Endorsement (where she would have no chance of winning!), has decided to call it “quits.” Her relationship with the WORST Republican Congressman in decades, Tom Massie of Kentucky, also known as Rand Paul Jr. because he votes against the Republican Party (and really good legislation!), did not help her. For some reason, primarily that I refused to return her never ending barrage of phone calls, Marjorie went BAD.”</p>
<p class="articleParagraph enarticleParagraph" >In an abrupt change of tone, the president added: “Nevertheless, I will always appreciate Marjorie, and thank her for her service to our Country! President DJT.”</p>
<p class="articleParagraph enarticleParagraph" >Earlier, Rachel Scott, ABC News Senior Political Correspondent, said she spoke with Trump about Greene’s <span class="colorLinks">resignation [https://www.independent.co.uk/topic/resignation]</span> on the phone late Friday night.</p>
<p class="articleParagraph enarticleParagraph" >“I think it’s great news for the country. It’s great,” Trump told Scott, according to her<span class="colorLinks"> X post [https://x.com/rachelvscott/status/1992056507953754215]</span> .</p>
<p class="articleParagraph enarticleParagraph" >The president reportedly added that Greene did not give him a heads-up before announcing her decision. “It doesn't matter, you know, but I think it's great. I think she should be happy," he said.</p>
<p class="articleParagraph enarticleParagraph" >Greene has recently clashed with Trump over several issues, most intensely over her push to release remaining government files on the late sex trafficker Jeffrey Epstein. The president has fought for months to stop the files being released, calling the demands a “Democrat hoax,” but has agreed to do so in the wake of Republicans led by Greene and Thomas Massie revolting against GOP leadership. Trump was friends with Epstein in the 1990s and early 2000s but has insisted he knew nothing about the financier’s crimes. Trump himself has not been accused of any wrongdoing in relation to the Epstein case.</p>
<p class="articleParagraph enarticleParagraph" >After she criticized Trump for not acting sooner, the president called her a “ranting lunatic” and backed a potential primary challenger.</p>
<p class="articleParagraph enarticleParagraph" >Greene announced her resignation in a video message and a statement on Friday, writing, “I have too much self respect and dignity, love my family way too much, and do not want my sweet district to have to endure a hurtful and hateful primary against me by the President we all fought for, only to fight and win my election while Republicans will likely lose the midterms.”</p>
<p class="articleParagraph enarticleParagraph" >“It’s all so absurd and completely unserious,” she added. “I refuse to be a ‘battered wife’ hoping it all goes away and gets better.”</p>
<p class="articleParagraph enarticleParagraph" >Her final day in office will be January 5.</p>
<p class="articleParagraph enarticleParagraph" >MAGA responds to Greene’s resignation</p>
<p class="articleParagraph enarticleParagraph" >News of Greene’s resignation has delighted and worried different wings of the <span class="colorLinks">MAGA [https://www.independent.co.uk/topic/maga]</span> movement.</p>
<p class="articleParagraph enarticleParagraph" >Massie, a Kentucky Republican who led the bipartisan effort alongside her to release the Epstein files, said he’d miss Greene “tremendously.”</p>
<p class="articleParagraph enarticleParagraph" >“I’m very sad for our country but so happy for my friend Marjorie. I’ll miss her tremendously. She embodies what a true Representative should be,” Massie <span class="colorLinks">wrote [https://x.com/RepThomasMassie/status/1992046487551787209]</span> on X.</p>
<p class="articleParagraph enarticleParagraph" >Right-wing activist Laura Loomer, an influential supporter of the president, criticized Greene for resigning ahead of the midterms.</p>
<p class="articleParagraph enarticleParagraph" >“So she’s deliberately trying to make it so that Republicans are down a vote to screw Trump over ahead of 2026,” Loomer <span class="colorLinks">wrote [https://x.com/LauraLoomer/status/1992042444771221584]</span> on X. “She will probably get a deal with CNN or MSDNC to s***talk Trump all day throughout the midterms. She wants the Democrats to win.”</p>
<p class="articleParagraph enarticleParagraph" >Evan Kilgore, a right-wing commentator, shared a photo of MAGA members <span class="colorLinks">on X [https://x.com/EvanAKilgore/status/1992064216476622937/photo/1]</span> , including Loomer, Sen. Ted Cruz, commentator Ben Shapiro, <span class="companylink">FBI</span> director Kash Patel and Attorney General Pam Bondi, writing, “If this is ‘MAGA’ now… Then I want NOTHING to do with it. I'm out.”</p>
<p class="articleParagraph enarticleParagraph" >Kilgore added in a<span class="colorLinks"> follow-up post [https://x.com/EvanAKilgore/status/1992087257373884577]</span> , “Watching ‘MAGA’ celebrate the resignation of MTG, a woman who has reliability (sic) fought for the American people for 5 years, is disgusting. MAGA is dead.”</p>
<p class="articleParagraph enarticleParagraph" >Loomer herself responded to the first post, writing: ““Now”. I’ve been with Trump since day one. I’m not going anywhere. You don’t get to push me out over your own irrational hatred. What have you ever done to MAGA?”</p>
<p class="articleParagraph enarticleParagraph" >Elsewhere, conservative commentator and conspiracy theorist Candace Owens sharply criticized Trump in her response to the news.</p>
<p class="articleParagraph enarticleParagraph" >“Communications from Trump admin be like: ‘<span class="colorLinks">Marjorie Taylor Greene [https://www.independent.co.uk/topic/marjorie-taylor-greene]</span> is a traitor for demanding a convicted child rapist have his files released. But we are standing by Mike Huckabee who met with a literal treasonous, Israeli spy, Jonathan Pollard,’” Owens <span class="colorLinks">wrote on X [https://x.com/RealCandaceO/status/1992045240316842160]</span> with a clown emoji.</p>
<p class="articleParagraph enarticleParagraph" >Other critics pointed out the unusual contrast between Greene’s resignation and Trump’s surprisingly friendly same-day meeting with New York City mayor-elect<span class="colorLinks"> Zohran Mamdani [https://www.independent.co.uk/news/world/americas/us-politics/trump-mamdani-meeting-white-house-new-york-b2870222.html]</span> ., someone he and other conservatives had previously branded a “communist” and an “Islamist.”</p>
<p class="articleParagraph enarticleParagraph" >“MTG turns on Trump and resigns. Mamdani and Trump are new best friends. I am so confused,” Larry Sabato, political analyst and Director of the University of Virginia's Center for Politics and a Trump critic, wrote <span class="colorLinks">on X [https://x.com/LarrySabato/status/1992043397381529931]</span> .</p>
<p class="articleParagraph enarticleParagraph" >Ron Filipkowski, editor-in-chief of the liberal news site MeidasTouch Network, said <span class="colorLinks">on X [https://x.com/RonFilipkowski/status/1992004609641201996]</span> , “So the new version of MAGA is that Marjorie Taylor Greene is a traitor, Rand Paul is a RINO, and Zohran Mamdani is great. Got it.”</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Americas | Congressman | Donald Trump | MAGA | marjorie taylor greene | resignation | US politics | World</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Independent Digital News and Media Ltd.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document INDOP00020251122elbm000s7</td></tr></table><br/></div></div><br/><span></span><div id="article-AJAZEN0020251122elbm000e3" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/ajazenLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>News</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>‘Cheering for him’: Key takeaways from Trump-Mamdani White House meeting</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Alastair McCready and News Agencies </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1338 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>02:33 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Al Jazeera English</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>AJAZEN</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 Al Jazeera English. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >President Trump and the mayor-elect adopt a markedly warmer tone after months of insults, catching many off guard.</p>
<p class="articleParagraph enarticleParagraph" >United States President Donald Trump lavishly praised New York City mayor-elect Zohran Mamdani after surprisingly cordial talks in the White House on Friday, defying expectations of a potentially tense meeting between the Republican billionaire and the self-proclaimed Democratic socialist.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The warmth displayed came in stark contrast to the barbs the pair have exchanged in recent months. Trump has caricatured Mamdani as an anti-Semitic communist, even threatening to strip him of his US citizenship, while Mamdani called Trump a “despot” in his election victory speech just weeks ago.</p>
<p class="articleParagraph enarticleParagraph" >But the pair appeared to put these seemingly irrevocable differences aside – for one day at least – with Trump describing the “great meeting” as “really productive” when talking to reporters in the Oval Office with Mamdani standing by his side.</p>
<p class="articleParagraph enarticleParagraph" >With many left unsure of what to make of the bizarrely chummy meeting between the political polar opposites, here are a few key takeaways:</p>
<p class="articleParagraph enarticleParagraph" >Finding common ground</p>
<p class="articleParagraph enarticleParagraph" >Trump and Mamdani exuded friendliness in their first get-together since the 34-year-old beat Democratic establishment party figures earlier this month, notably former New York Governor Andrew Cuomo, to become New York City’s mayor-elect.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani said ahead of his meeting with Trump that he was willing to “meet with anyone” to push forward his affordability agenda for the US’s largest city, saying that he and Trump shared some common ground in that they ran campaigns focused on the cost-of-living crisis.</p>
<p class="articleParagraph enarticleParagraph" >“I will speak to everyone so long as it could stand to benefit an economic agenda for New Yorkers. And that’s where I will always make the case,” he said.</p>
<p class="articleParagraph enarticleParagraph" >The approach appears to have paid off, with Trump saying he and Mamdani “agree on a lot more than I would have thought”, as he predicted success for his tenure leading New York.</p>
<p class="articleParagraph enarticleParagraph" >“Some of his ideas are the same ideas I have,” said Trump, adding that some of his supporters also voted for Mamdani, who pitched in, saying “one in 10”.</p>
<p class="articleParagraph enarticleParagraph" >Trump said of Mamdani: “He wants to have a safe New York, and ultimately, a safe New York in a great New York.” Later in the media conference, Trump doubled down on how Mamdani was keen to fight crime — echoing the emphasis on strong law enforcement that is a traditional Republican focus.</p>
<p class="articleParagraph enarticleParagraph" >The US president also suggested that he agreed with Mamdani on housing.</p>
<p class="articleParagraph enarticleParagraph" >“He said some very interesting things. He wants to see houses go up, a lot of apartments built,” Trump said. “People would be shocked, but I want to see the same thing.”</p>
<p class="articleParagraph enarticleParagraph" >“I want to be helping him, not hurting him,” Trump said. “A big help”.</p>
<p class="articleParagraph enarticleParagraph" >Praise and banter</p>
<p class="articleParagraph enarticleParagraph" >But the apparent camaraderie extended beyond policy issues, with Trump also repeatedly praising Mamdani.</p>
<p class="articleParagraph enarticleParagraph" >“I think this mayor can do some things that are going to be really great,” he said at one point.</p>
<p class="articleParagraph enarticleParagraph" >At another point, Trump said: “The better he does, the happier I am. I feel very confident that he can do a very good job.”</p>
<p class="articleParagraph enarticleParagraph" >Trump spoke of Mamdani’s election campaign and how he went from just 1 percent in the polls to upsetting Cuomo, first in the Democratic Party’s primary and then in the actual election. “It’s an amazing thing that he did,” the president said.</p>
<p class="articleParagraph enarticleParagraph" >A reporter asked Trump if he would be comfortable living in New York City under Mamdani’s mayorship.</p>
<p class="articleParagraph enarticleParagraph" >“Yeah, I would, I really would,” Trump responded instantly. “Especially after the meeting. Absolutely.”</p>
<p class="articleParagraph enarticleParagraph" >Towards the end of the media conference, Trump described his impression of Mamdani after their meeting.</p>
<p class="articleParagraph enarticleParagraph" >“I met with a man who is a very rational person. I met with a man who really wants to see New York be great again. I think he wants to make it greater than ever before.”</p>
<p class="articleParagraph enarticleParagraph" >In one striking moment, Trump even gave Mamdani an easy out when the mayor-elect was asked by a reporter if he stood by his previous comments describing the president as a “despot” and “fascist”.</p>
<p class="articleParagraph enarticleParagraph" >“That’s OK, you can just say ‘yes’,” Trump interjected. “It’s easier than explaining it.”</p>
<p class="articleParagraph enarticleParagraph" >While striking a respectful tone when talking about Trump, Mamdani appeared to draw the line at actively praising him, with the compliments largely flowing one way.</p>
<p class="articleParagraph enarticleParagraph" >Breaking from White House and GOP messaging</p>
<p class="articleParagraph enarticleParagraph" >If the plan was to pivot away from boogeyman characterisations of Mamdani, key members of Trump’s administration and the Republican party weren’t given the message.</p>
<p class="articleParagraph enarticleParagraph" >A day before the meeting, White House press secretary Karoline Leavitt said that it “speaks volumes” that a “communist” was visiting the White House.</p>
<p class="articleParagraph enarticleParagraph" >“That’s who the Democratic Party elected as the mayor of the largest city in the country,” she said.</p>
<p class="articleParagraph enarticleParagraph" >Vice President JD Vance also joked on Thursday that he might “have a stomach bug” to avoid meeting Mamdani, who is set to take office on the first day of 2026.</p>
<p class="articleParagraph enarticleParagraph" >Republican Senator Rick Scott also derided Mamdani as a “literal communist” on Friday morning, as he predicted Trump would “school” him at the White House later that day.</p>
<p class="articleParagraph enarticleParagraph" >Trump, however, stayed away from any aggressive talk towards Mamdani, even going as far as to contradict members of his own party when he told reporters that he did not agree with Republican Congresswoman Elise Stefanik’s characterisation of Mamdani as a “jihadist”.</p>
<p class="articleParagraph enarticleParagraph" >Following Trump’s comments, Stefanik, a New York Republican gubernatorial candidate, said, “We’ll have to agree to disagree on this one.”</p>
<p class="articleParagraph enarticleParagraph" >“If he walks like a jihadist, If he talks like a jihadist, If he campaigns like a jihadist, If he supports jihadists, He’s a jihadist,” she wrote on X.</p>
<p class="articleParagraph enarticleParagraph" >Why Trump took a more conciliatory approach in this meeting, starkly breaking from previous Republican messaging on Mamdani, is impossible to tell.</p>
<p class="articleParagraph enarticleParagraph" >But the meeting and the talk of affordability as a shared concern occurred at a time when Trump faces growing scrutiny over rising prices following months of tariffs.</p>
<p class="articleParagraph enarticleParagraph" >Major schisms have appeared in the Republican party and the Trump MAGA movement in recent days and weeks – notably <span class="colorLinks">over the Epstein files scandal [https://www.aljazeera.com/news/2025/11/22/major-maga-figure-marjorie-taylor-greene-resigns-after-trump-clash]</span> and over US support for Israel. On Friday, Republican Congresswoman <span class="colorLinks">Marjorie Taylor Greene [https://www.aljazeera.com/news/2025/11/22/major-maga-figure-marjorie-taylor-greene-resigns-after-trump-clash]</span>, for long one of Trump’s staunchest supporters, and a champion of the MAGA movement, said she would resign from the House of Representatives in January, after a public clash with the US president.</p>
<p class="articleParagraph enarticleParagraph" >Sidestepping Israel</p>
<p class="articleParagraph enarticleParagraph" >One topic which which raised the spectre of creating a more awkward, confrontational atmosphere between Trump and Mamdani was <span class="colorLinks">Israel’s genocidal war in Gaza [https://www.aljazeera.com/news/liveblog/2025/11/21/live-israel-keeps-bombing-gaza-kills-two-in-occupied-east-jerusalem]</span>.</p>
<p class="articleParagraph enarticleParagraph" >Asked by a reporter about previous comments he had made about the <span class="companylink">US government</span>’s complicity in Israel’s assault, including the current administration, Mamdani didn’t shy away from reiterating this criticism – despite an awkward-looking Trump sitting silently next to him.</p>
<p class="articleParagraph enarticleParagraph" >“I have spoken about the Israeli government committing genocide [in Gaza] and I’ve spoken about our government funding it,” he said. It is the first known occasion that Israel has been accused of genocide in Gaza within the walls of the White House, even if from an opponent of the current administration.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, however, quickly pivoted back to his core message of the cost-of-living crisis in New York.</p>
<p class="articleParagraph enarticleParagraph" >“I shared with the president in our meeting about the concerns that many New Yorkers have of wanting their tax dollars to go towards the benefit of New Yorkers and their ability to afford basic dignity,” he said.</p>
<p class="articleParagraph enarticleParagraph" >“I also believe that we have to follow through on international human rights, and I know that still today those are being violated,” Mamdani added, without mentioning Gaza.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">US President Donald Trump and New York City Mayor-elect Zohran Mamdani shake hands as they meet in the Oval Office on November 21, 2025 [Jonathan Ernst/Reuters] [https://www.aljazeera.com/wp-content/uploads/2025/11/2025-11-21T231530Z_1338927259_RC271IAXECMX_RTRMADP_3_USA-TRUMP-MAMDANI-1763791876.jpg]</span>
                  </p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | usdc : Washington DC | use : Northeast U.S. | usny : New York State | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Donald Trump | News | Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Al Jazeera International</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document AJAZEN0020251122elbm000e3</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC75596020251122elbm0000e"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Leftist NY mayor-elect and Trump make nice in White House 3 hours ago</b><div class="leadFields"><a href="javascript:void(0)">The Edition</a>, 10:53 AM, 22 November 2025, 792 words, (English)</div><div class="snippet ensnippet"> Months of sniping melted away Friday as New York&#39;s incoming leftist mayor Zohran Mamdani and President Donald Trump were all smiles at a White House meeting -- promising to set aside their feud and cooperate on the city&#39;s future.</div>
<div>(Document WC75596020251122elbm0000e)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC71053020251122elbm0000x"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  National Politics'We’re going to help him': Trump, Mamdani strike friendly tone at White HouseScripps News Group</b><div class="leadFields"><a href="javascript:void(0)">KRTV Channel 3</a>, 10:42 AM, 22 November 2025, 368 words, (English)</div><div class="snippet ensnippet"> Both leaders said their meeting focused on areas of agreement, including how to make New York City more affordable.President Donald Trump and New York City Mayor-elect Zohran Mamdani held what appeared to be a friendly meeting at the White ...</div>
<div>(Document WC71053020251122elbm0000x)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC74240020251122elbm00007"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  2025 Golden Turkeys </b><div class="leadFields"><a href="javascript:void(0)">Virtual Currency Report</a>, 08:54 PM, 21 November 2025, 2214 words,  Rick Jones, (English)</div><div class="snippet ensnippet"> It’s that time of year again, time for me to give out the Golden Turkeys. As usual, I wait until the Nobels are done so the Turkeys can get the attention that they deserve. I’ve been in consultation with my editorial team, Hagrid and ...</div>
<div>(Document WC74240020251122elbm00007)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-NYPO000020251122elbm0000g" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nypoLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>News</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>THE RED APPLE | ZO THE BIG APPLE OF HIS EYE; Bonds over NY with Don in shockingly nice WH</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Steven Nelson, Craig McCarthy and Matt Troutman </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1038 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>New York Post</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NYPO</td></tr><tr><td align="right" valign="top" class="index"><b>ED</b>&nbsp;</td><td>Late City Final</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>4</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>(c) 2025 N.Y.P. Holdings, Inc. All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >They found comrade ground.</p>
<p class="articleParagraph enarticleParagraph" >Zohran Mamdani's high-stakes White House meeting turned into a Freaky Friday lovefest - as President Trump lauded the socialist mayor-elect and predicted he'll make New York City great again.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >A sitting Trump, with Mamdani standing by his side behind the Resolute Desk, heaped praise on the democratic socialist, jovially touching his arm as he helped him dodge tough questions and predicted his mayoralty will be a success.</p>
<p class="articleParagraph enarticleParagraph" >"I think he wants to make it greater than ever before," Trump told reporters. "And if he can, we'll be out there cheering. I'll be cheering for him."</p>
<p class="articleParagraph enarticleParagraph" >The erstwhile foes' gobsmackingly friendly joint appearance came after a 45-minute closed-door sit-down in the Oval Office, which they both touted as productive and focused on Mamdani's core campaign issue of affordability.</p>
<p class="articleParagraph enarticleParagraph" >"He's different than your typical guy," Trump said, adding Mamdani "has a chance to really do something great for New York."</p>
<p class="articleParagraph enarticleParagraph" >Mamdani notably avoided taking any bait to praise Trump, though he did offer that the president's better-than-expected showing in New York City during 2024's presidential election came because of his own focus on kitchen table issues.</p>
<p class="articleParagraph enarticleParagraph" >The mayor-elect said he wanted to focus on delivering real-world results for New Yorkers, rather than duke it out with Trump over their vast differences.</p>
<p class="articleParagraph enarticleParagraph" >"I think both President Trump and I, we are very clear about our positions and our views, and what I really appreciate about the president is the meeting that we had focused not on places of disagreement, which there are many, and also focused on the shared purpose that we have in serving New Yorkers," he said.</p>
<p class="articleParagraph enarticleParagraph" >Trump agreed.</p>
<p class="articleParagraph enarticleParagraph" >"We have one thing in common. We want this city of ours that we love to do very well," Trump said as the two-faced reporters in a somewhat surreal scene.</p>
<p class="articleParagraph enarticleParagraph" >The president even swooped in when Mamdani - who during the campaign vowed he would be Trump's "worst nightmare" - was pressed by reporters about calling him "fascist" and a "despot."</p>
<p class="articleParagraph enarticleParagraph" >"That's OK, you can just say yes," Trump joked, affectionately patting him on the arm, when Mamdani was asked if he still thought of the president as a "fascist."</p>
<p class="articleParagraph enarticleParagraph" >"I've been called much worse than a despot, so it's not that insulting," Trump added when Mamdani was asked about that past dig.</p>
<p class="articleParagraph enarticleParagraph" >'Rational person'</p>
<p class="articleParagraph enarticleParagraph" >Asked if he believed that the anti-Israel pol was a "jihadist," Trump said he had met with "a very rational person."</p>
<p class="articleParagraph enarticleParagraph" >Trump - who had predicted the demise of the Big <span class="companylink">Apple</span> if "my little communist" Mamdani was elected - said he came away from their meeting feeling "very confident" the lefty upstart can do a good job.</p>
<p class="articleParagraph enarticleParagraph" >"I think he is going to surprise some conservative people, actually, and some very liberal people," he said.</p>
<p class="articleParagraph enarticleParagraph" >Trump even backed off his threat that if Mamdani became mayor, he'd send the National Guard to the city to fight crime.</p>
<p class="articleParagraph enarticleParagraph" >"I expect to be helping him, not hurting him, a big help because I want New York City to be great," said Trump, who has also warned that New York's federal funding could be in jeopardy under Mamdani.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani - who during the campaign vowed he would be Trump's "worst nightmare" - requested the face-to-face, calling it customary for an incoming New York City mayor to meet with the president.</p>
<p class="articleParagraph enarticleParagraph" >Queens native Trump first gave the Astoria assemblyman a tour of the White House, before the two sat down with their respective chiefs of staff, Susie Wiles and Elle Bisgaard-Church, sources said.</p>
<p class="articleParagraph enarticleParagraph" >Bisgaard-Church said afterward the conversation focused on Mamdani's long-shot win and affordability issues such as rent, utility and grocery costs.</p>
<p class="articleParagraph enarticleParagraph" >She said Trump specifically perked up when talking about building housing.</p>
<p class="articleParagraph enarticleParagraph" >"The president felt very interested in a kind of common-sense approach to reduce onerous burdens on the housing and development owners, actually," she said, calling it an area of real agreement over how government can make New Yorkers' lives better.</p>
<p class="articleParagraph enarticleParagraph" >Trump said he shared Mamdani's views that building more housing would help rents come down.</p>
<p class="articleParagraph enarticleParagraph" >"Actually, people would be shocked, but I want to see the same thing," he said.</p>
<p class="articleParagraph enarticleParagraph" >Other topics included a potential <span class="companylink">Con Edison</span> rate hike, with the president pressuring the utility to lower costs.</p>
<p class="articleParagraph enarticleParagraph" >And Trump said Mamdani knows the streets need to be "safe" as he praised his recent decision to keep tough-on-crime <span class="companylink">NYPD</span> Commissioner Jessica Tisch as his top cop.</p>
<p class="articleParagraph enarticleParagraph" >"Maybe more than anything else, he wants to have a safe New York," Trump said of Mamdani.</p>
<p class="articleParagraph enarticleParagraph" >"Ultimately, a safe New York is going to be a great New York," he said. "If you don't have safe streets, it's not going to be a success."</p>
<p class="articleParagraph enarticleParagraph" >The president also didn't take the bait when a reporter asked about Mamdani's promise to arrest Israeli Prime Minister Benjamin Netanyahu if he sets foot in New York City.</p>
<p class="articleParagraph enarticleParagraph" >He said they didn't discuss Netanyahu, although they agreed they wanted peace in the Middle East.</p>
<p class="articleParagraph enarticleParagraph" >"He's got views out there, but who knows, maybe we're going to see what works, or he's going to change," Trump said.</p>
<p class="articleParagraph enarticleParagraph" >"Also, we all change. I change a lot."</p>
<p class="articleParagraph enarticleParagraph" >A meeting with New York City Mayor-elect Zohran Mamdani brought out the breezy side of President Trump. Among his comments:</p>
<p class="articleParagraph enarticleParagraph" >A reporter asks Mamdani about past insults calling Trump "fascist" and a "despot," the president responds playfully:</p>
<p class="articleParagraph enarticleParagraph" >"That's OK, you can just say yes "¦ I've been called much worse than a despot, so it's not that insulting."</p>
<p class="articleParagraph enarticleParagraph" >Trump told the press pool he didn't think Mamdani was a "jihadist."</p>
<p class="articleParagraph enarticleParagraph" >"I met with a man who's a very rational person."</p>
<p class="articleParagraph enarticleParagraph" >Asked if he'd be comfortable returning to live in Mayor Mamdani's New York City:</p>
<p class="articleParagraph enarticleParagraph" >"I would feel very, very comfortable being in New York, and I think much more so after the meeting." </p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>THE RED APPLE</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>N.Y.P. Holdings, Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NYPO000020251122elbm0000g</td></tr></table><br/></div></div><br/><span></span><div id="article-NYTFEED020251122elbm000gp" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nytfeedLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>New York</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>The Surprise Ending to the Trump-Mamdani Buddy Movie Has Heads Spinning</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Dana Rubinstein and Benjamin Oreskes </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1084 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>21 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>08:22 PM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>nytimes.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NYTFEED</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. The New York Times Company. All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Zohran Mamdani and President Trump seemed to cast aside their months of traded insults, a development that seemed good for New York City but odd to some followers.</p>
<p class="articleParagraph enarticleParagraph" >There were smiles and more than a few laughs. Compliments, ranging from genuine to diplomatic, were abundant.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >And when reporters tried to interrupt the unexpected buddy movie that emerged in the White House on Friday, President Trump warmly placed his hand on Zohran Mamdani’s arm and gently advised him to keep it simple in response to a question about whether Mr. Mamdani considered him a fascist.</p>
<p class="articleParagraph enarticleParagraph" >“You can just say yes,” the president said. “It’s easier.”</p>
<p class="articleParagraph enarticleParagraph" >It was an astonishingly affectionate performance that sent heads spinning, as New Yorkers confronted the once-unthinkable possibility that Mr. Mamdani, the democratic socialist mayor-elect of New York City, and the president actually got along.</p>
<p class="articleParagraph enarticleParagraph" >“I mean, it did seem like a little bit of a bromance,” said Nicole Malliotakis, the Republican congresswoman from the conservative stronghold of Staten Island. “Based on the election results, we knew Mamdani was charming, but who thought he’d be able to charm the president?”</p>
<p class="articleParagraph enarticleParagraph" >For weeks, New York leaders have been <span class="colorLinks">bracing for the likelihood [https://www.nytimes.com/2025/11/07/nyregion/nyc-immigration-raids-trump-mamdani.html]</span> of a devastating confrontation between the Trump administration and a City Hall led by Mr. Mamdani. They have gamed out what, precisely, it might look like if Mr. Trump sends federal troops or a surge of immigration enforcement agents into New York City. They have fretted about more funding cuts. They have formed rapid-response groups and enlisted the help of business leaders.</p>
<p class="articleParagraph enarticleParagraph" >They have had reason to worry. Not only has Mr. Trump threatened New York City, but he also personally tried to prevent Mr. Mamdani from winning the mayoral election, even going so far as to urge Republicans to abandon their party nominee in favor of Andrew M. Cuomo, the Democratic former governor.</p>
<p class="articleParagraph enarticleParagraph" >But then the cameras went live on Friday from the Oval Office. There was Mr. Mamdani, standing with a quiet smile by Mr. Trump’s side as the president lavished him with praise; commended his decision to keep the current police commissioner; applauded his pro-housing, pro-affordability inclinations; and helped him swat away unfriendly questions from the conservative press.</p>
<p class="articleParagraph enarticleParagraph" >To hear Mr. Trump tell it, the two men, who occupy starkly opposing positions on Israel and Gaza, even found common ground there.</p>
<p class="articleParagraph enarticleParagraph" >Casting himself as the consummate peacemaker, Mr. Trump said Mr. Mamdani, too, “feels very strongly” about “peace in the Middle East.”</p>
<p class="articleParagraph enarticleParagraph" >Sid Rosenberg, a conservative talk radio host who has interviewed Mr. Trump and whose suggestion that Mr. Mamdani would welcome another Sept. 11 attack became its own story line in the mayor’s race, said he was shocked at the president’s reaction. He posted a video response prefaced by an expletive-colored introduction conveying his disbelief. (He later deleted the video.)</p>
<p class="articleParagraph enarticleParagraph" >“I love Trump and I’m almost never critical of President Trump ever,” Mr. Rosenberg said in an interview. “He meets with people, from the Putins to Kim Jong-un, horrible people, horrible people that want to kill us, he meets with them. That’s how he fixes stuff. I get it.”</p>
<p class="articleParagraph enarticleParagraph" >But, he said, referring to Mr. Mamdani: “For me as a Jew in New York, this guy really rubs me wrong. And to watch them shake hands and smile” made him want to lose his lunch.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani’s ability to win over skeptics and enemies has figured prominently in his political rise, as he has used his retail political skills to charm both taxi drivers and real estate magnates. On Friday, he appeared to have done it again.</p>
<p class="articleParagraph enarticleParagraph" >Ana María Archila, the co-director of New York’s <span class="companylink">Working Families Party</span>, giggled as she watched Mr. Trump’s “relaxed and happy energy with someone he has threatened to deport.” (In July, Mr. Trump threatened to arrest Mr. Mamdani, <span class="colorLinks">adding [https://bsky.app/profile/atrupar.com/post/3lsw5ixjnms2j]</span>, “a lot of people are saying he’s here illegally.” Mr. Mamdani was born in Uganda but is a naturalized citizen.)</p>
<p class="articleParagraph enarticleParagraph" >Ms. Archila also admitted to feeling “a tiny bit of relief” that perhaps some of Mr. Trump’s threats against New York may not come to pass, even though the president avoided discussing specifics.</p>
<p class="articleParagraph enarticleParagraph" >“There is the possibility that maybe this means New York City is not going to get invaded by federal troops on Jan. 1,” she said.</p>
<p class="articleParagraph enarticleParagraph" >In this time of profound national division, the meeting also managed to please Joe Borelli, a pro-Trump Republican and a former councilman from Staten Island.</p>
<p class="articleParagraph enarticleParagraph" >“As a New Yorker, I was proud of both the mayor-elect and the president,” he said. “I think it’s a good lesson for people that the characters you make them out to be aren’t necessarily who they really are.”</p>
<p class="articleParagraph enarticleParagraph" >The event seemed all the more remarkable because Mr. Mamdani — considered by some national Democratic leaders to be too far left to embrace — seemed to gain more ground with the president in one hour than his party has in Mr. Trump’s five years in office.</p>
<p class="articleParagraph enarticleParagraph" >
                     Chuck Schumer, the Democratic Senate minority leader from Brooklyn who never endorsed Mr. Mamdani’s campaign, was succinct in his praise.</p>
<p class="articleParagraph enarticleParagraph" >“Schumer feels a meeting like this can only be good for New York,” his spokesman said.</p>
<p class="articleParagraph enarticleParagraph" >Other reactions were more colorful.</p>
<p class="articleParagraph enarticleParagraph" >“I think JD Vance is jealous,” joked Brian Kilmeade, the Fox News host. “They really get along fantastic.”</p>
<p class="articleParagraph enarticleParagraph" >Ross Barkan, a political reporter who employed Mr. Mamdani as his campaign manager when he ran for the State Senate, wryly <span class="colorLinks">observed [https://x.com/rossbarkan/status/1991984061339033808?s=61&t=e_PKPD5mSSlAeNnsQP5ujA]</span> on social media that “Trump endorsed Mamdani before Schumer did.”</p>
<p class="articleParagraph enarticleParagraph" >Even as many New Yorkers rejoiced in the possibility of a functional relationship between City Hall and the White House, they also questioned how long it might take for Mr. Trump, known for his mercurial nature, to turn on Mr. Mamdani.</p>
<p class="articleParagraph enarticleParagraph" >“I don’t think Trump is a particularly consistent or morally guided actor so we need to prepare for potentially increased federal activity in the city,” said Grace Mausser, the co-chair for the local chapter of the Democratic Socialists of America, the organization that has been central to Mr. Mamdani’s political success.</p>
<p class="articleParagraph enarticleParagraph" >“But overall, Zohran has always been a clear communicator and an effective political actor, and if this leads Trump to not attack the city, I think that’s good,” she added.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gent : Arts/Entertainment | gmovie : Movies | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Mamdani, Zohran | New York City | News | Republican Party | Trump, Donald J | United States Politics and Government</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>The New York Times Company</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NYTFEED020251122elbm000gp</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC42085020251122elbm0030g"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Seattle about to get NY's hammer-and-sickle treatment. Socialism is coming your way</b><div class="leadFields"><a href="javascript:void(0)">FOXNews.com</a>, 10:00 AM, 22 November 2025, 1010 words,  Jason Rantz Fox, (English)</div><div class="snippet ensnippet"> Wilson entered the race with no elected experience but a long r&#233;sum&#233; of influence in Seattle’s activist ecosystem. As head of the Transit Riders Union, she championed policies that kneecapped car infrastructure in favor of buses and bikes. ...</div>
<div>(Document WC42085020251122elbm0030g)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC74334020251122elbm00002"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  'I'll be cheering for him': Takeaways from Trump and Mamdani's surprisingly cordial meeting</b><div class="leadFields"><a href="javascript:void(0)">Graphic</a>, 10:09 AM, 22 November 2025, 1021 words, (English)</div><div class="snippet ensnippet"> US President Donald Trump met New York City&#39;s newly elected mayor Zohran Mamdani at the White House in what was billed as the political showdown of the year - but instead became a praise fest.</div>
<div>(Document WC74334020251122elbm00002)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC45774020251122elbm0000i"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  National NewsTrump and Mamdani meet in Oval Office, say they both care about affordabilityAssociated Press</b><div class="leadFields"><a href="javascript:void(0)">ABC Action News</a>, 10:09 AM, 22 November 2025, 908 words,  Associated Press, (English)</div><div class="snippet ensnippet"> WASHINGTON (AP) — President Donald Trump has called New York City&#39;s Mayor-elect Zohran Mamdani a &quot;100% Communist Lunatic&quot; and a “total nut job.” Mamdani has called Trump’s administration “authoritarian&quot; and described himself as “Donald ...</div>
<div>(Document WC45774020251122elbm0000i)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC48736020251122elbm00016"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Harrop: Newly elected Zohran Mamdani starts to deflate</b><div class="leadFields"><a href="javascript:void(0)">Columbian.com</a>, 06:01 AM, 22 November 2025, 64 words,  Froma Harrop, (English)</div><div class="snippet ensnippet"> The election of Zohran Mamdani as New York City mayor set off — for his fan base, anyway — great expectations of a more “affordable” city. But the democratic socialist hasn’t even been sworn in, and some of his marquee promises are already ...</div>
<div>(Document WC48736020251122elbm00016)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC45280020251122elbm0000f"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  'We have one thing in common': Trump, Mamdani vow to tackle New York City challenges together</b><div class="leadFields"><a href="javascript:void(0)">The Week</a>, 09:20 AM, 22 November 2025, 453 words, (English)</div><div class="snippet ensnippet"> The President and the Mayor-elect heaped praise on each other and termed their White House meeting &quot;productive&quot;In stark contrast to the vitriolic remarks they had made during the mayoral election campaign, US President Donald Trump and New ...</div>
<div>(Document WC45280020251122elbm0000f)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC50737020251122elbm00003"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Binghamton native will become the next mayor of Seattle</b><div class="leadFields"><a href="javascript:void(0)">Pipe Dream</a>, 09:14 AM, 22 November 2025, 886 words,  News Sports, (English)</div><div class="snippet ensnippet"> Katie Wilson, a self-described democratic socialist, defeated the incumbent Democrat with 50.2 percent of the vote. Pipe Dream sat down with Wilson&#39;s parents, both biology professors at Binghamton University.</div>
<div>(Document WC50737020251122elbm00003)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-HNTM000020251122elbm002ec" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/hntmLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Hindustan Times, india-news</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>'Will Rahul Gandhi get the message?': BJP's jibe at Tharoor's Trump-Mamdani meet remark</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>HT News Desk </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>441 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Hindustan Times</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>HNTM</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025.  HT Media Limited.  All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >India, Nov. 22 -- The BJP grabbed onto Shashi Tharoor's remarks on the Trump-Zohran Mamdani meeting, turning his praise for the unusual display of civility into a pointed swipe at the Congress leadership.</p>
<p class="articleParagraph enarticleParagraph" >Tharoor had taken to social media to highlight how the US President and the newly elected New York City mayor, fierce critics of each other during the campaign, set aside their hostility to meet with respect.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >It was this moment of putting the election season behind and focusing on public service that Tharoor celebrated. And BJP spokesperson Shehzad Poonawala quickly echoed the sentiment, using it to nudge the Congress.</p>
<p class="articleParagraph enarticleParagraph" >Poonawala said Tharoor's "cryptic" post was effectively a reminder to his own party to place the nation above the Gandhi family.</p>
<p class="articleParagraph enarticleParagraph" >"Once again Shashi Tharoor reminds Congress to put India First not Parivar To behave democratically and not like sore losers But will Rahul Gandhi get the message ? One more Fatwa loading against Shashi???," he said.</p>
<p class="articleParagraph enarticleParagraph" >Tharoor, for his part, applauded Donald Trump's meeting with Zohran Mamdani as a rare instance of democratic maturity despite their sharp campaign-trail clashes.</p>
<p class="articleParagraph enarticleParagraph" >His takeaway from Friday's interaction was that once elections conclude, political rivals must know how to collaborate.</p>
<p class="articleParagraph enarticleParagraph" >"This is how democracy should work. Fight passionately for your point of view in elections, with no rhetorical holds barred. But once it's over, & the people have spoken, learn to cooperate with each other in the common interests of the nation you are both pledged to serve. I would love to see more of this in India, and am trying to do my part," Tharoor wrote on X on Saturday.</p>
<p class="articleParagraph enarticleParagraph" >Tharoor has often drawn criticism from members of the Congress party for remarks seen as overly generous toward BJP leaders, including past praise for LK Advani and Prime Minister Narendra Modi.</p>
<p class="articleParagraph enarticleParagraph" >Just two days ago, he publicly appreciated Modi's Ramnath Goenka lecture, prompting a sharp reaction from a Congress leader who questioned why Tharoor remained in the party if he believed the BJP's methods were more effective.</p>
<p class="articleParagraph enarticleParagraph" >He also recently authored an article on dynastic politics and its impact on meritocracy, citing the Gandhi-Nehru family as an example, which drew immense criticism from the members of his party.</p>
<p class="articleParagraph enarticleParagraph" >Many emphasized on how dynastic politics was not exclusive to the Congress party.</p>
<p class="articleParagraph enarticleParagraph" >Published by HT Digital Content Services with permission from Hindustan Times.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>CT</b>&nbsp;</td><td><br/>For any query with respect to this article or any other content requirement, please contact Editor at contentservices@htdigital.in </td></tr>
<tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>asiaz : Asia | devgcoz : Emerging Market Countries | dvpcoz : Developing Economies | india : India | sasiaz : South Asia</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>HT Digital Streams Limited</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document HNTM000020251122elbm002ec</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC56288020251122elbm00002"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump meets with NYC mayor-elect</b><div class="leadFields"><a href="javascript:void(0)">Metro Radio</a>, 11:23 AM, 22 November 2025, 180 words, (English)</div><div class="snippet ensnippet"> U.S. President Donald Trump met on Friday with New York City Mayor-elect Zohran Mamdani at the White House, downplaying recent tensions.Speaking to reporters after their meeting, both sides said they had a productive discussion centered ...</div>
<div>(Document WC56288020251122elbm00002)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC93041020251122elbm00002"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Prosecutor seeks review in fake elector case</b><div class="leadFields"><a href="javascript:void(0)">The Journal</a>, 01:00 AM, 22 November 2025, 125 words, (English)</div><div class="snippet ensnippet"> PHOENIX (AP) — Arizona Attorney General Kris Mayes is appealing a ruling that has stalled the criminal case against President Donald Trump’s former chief of staff Mark Meadows, former New York City Mayor Rudy Giuliani and others for trying ...</div>
<div>(Document WC93041020251122elbm00002)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-NYTFEED020251122elbm000b5" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nytfeedLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>CLM</b>&nbsp;</td><td>White House Memo</td></tr>
<tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>U.S.; Politics</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>‘Fascist’? ‘Communist’? For an Afternoon, They Were Just 2 Guys From Queens.</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Shawn McCreesh </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1094 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>21 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>08:05 PM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>nytimes.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NYTFEED</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. The New York Times Company. All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Acid insults were set aside as New York’s mayor-elect and the president promoted their shared goals.</p>
<p class="articleParagraph enarticleParagraph" >There was one moment in particular when Zohran Mamdani seemed like he might have bitten off a little more than he could chew by making his lonely pilgrimage down to the lion’s den that is President Trump’s blinged-out Oval Office.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The 34-year-old mayor-elect of New York was pressed by a reporter on whether he thought his host, who was sitting about four inches away, was really “a fascist.”</p>
<p class="articleParagraph enarticleParagraph" >How terribly awkward.</p>
<p class="articleParagraph enarticleParagraph" >But before Mr. Mamdani could even get out one of his slick and diplomatic answers, the president jumped in to throw him a lifeline.</p>
<p class="articleParagraph enarticleParagraph" >“That’s OK, you could just say, ‘Yes,’” Mr. Trump said, looking highly amused by the whole thing. He waved his hand, as if being called the worst term in the political dictionary was no big deal.</p>
<p class="articleParagraph enarticleParagraph" >“OK, all right,” Mr. Mamdani said with a smile.</p>
<p class="articleParagraph enarticleParagraph" >“It’s easier,” Mr. Trump said. “It’s easier than explaining it.” Chuckling good-naturedly, he reached up and gave Mr. Mamdani a pat on the arm. “I don’t mind,” he added.</p>
<p class="articleParagraph enarticleParagraph" >It was like the oddest screwball buddy comedy in American politics. The “fascist” and the “communist.” The president and the mayor. The old man and the Young Turk.</p>
<p class="articleParagraph enarticleParagraph" >Were these really the same two guys who had spent the last many months flicking acid darts at one another?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump had falsely <span class="colorLinks">claimed [https://www.nytimes.com/2025/07/01/us/politics/trump-zohran-mamdani.html]</span> that Mr. Mamdani, a naturalized U.S. citizen, might be here illegally, and had threatened to have him arrested. He had demonized him as a “communist” who would drive his beloved hometown into the gutter.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani didn’t shy from a scrap. In a memorable zinger from his victory speech earlier this month, he shot back, “So, Donald Trump, since I know you’re watching, I have four words for you: Turn the volume up.”</p>
<p class="articleParagraph enarticleParagraph" >But if there is one thing Mr. Trump respects, it’s a winner. He made it clear Friday that he was impressed Mr. Mamdani had triumphed as an underdog against the political establishment. “He came out of nowhere,” the president said. “What’d you start off at, one or two? I watched, I said, ‘Who is this guy?’”</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump also appreciates a good media spectacle, and he was keenly aware that he had one on his hands. “The press has eaten this thing up,” he marveled to the phalanx of cameras crowded into the Oval Office. “I’ve had a lot of meetings with the heads of major countries, nobody cared. This meeting — you people have gone crazy.”</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani, for his part, was clever about deploying certain facts that would help disarm his host. He made a point of talking about how Mr. Trump had gained votes in New York in the last presidential election, and described talking to Trump voters on Hillside Avenue in Queens and Fordham Road in the Bronx.</p>
<p class="articleParagraph enarticleParagraph" >“When we spoke to those voters who voted for President Trump, we heard them speak about cost of living,” Mr. Mamdani said. “We focus on that same cost of living.”</p>
<p class="articleParagraph enarticleParagraph" >“He said a lot of my voters actually voted for him,” Mr. Trump chuckled, “and I’m OK with that.”</p>
<p class="articleParagraph enarticleParagraph" >The two did a kind of populist pas de deux that would have been unthinkable in a previous political age.</p>
<p class="articleParagraph enarticleParagraph" >For once, there was no talk of crypto, billionaires or a gilded ballroom. It was as though Mr. Mamdani was bringing out in Mr. Trump his original focus on economic issues, one that powered his political rise but which some influential figures in the MAGA movement have lately been accusing Mr. Trump of abandoning.</p>
<p class="articleParagraph enarticleParagraph" >Things took a turn for the surreal when Mr. Trump stepped in to defend Mr. Mamdani from hard-edge questions being flung at him by the conservative media in the room.</p>
<p class="articleParagraph enarticleParagraph" >One such type grilled Mr. Mamdani about why he had flown on a plane to Washington instead of taking a train, noting the latter would have been “greener.”</p>
<p class="articleParagraph enarticleParagraph" >“If he flew, that’s a lot quicker,” Mr. Trump said. He then turned to his guest, adding, “I’ll stick up for you.”</p>
<p class="articleParagraph enarticleParagraph" >The president is in the midst of one of the trickiest periods of his second term, with some members of his own party <span class="colorLinks">beginning to break away [https://www.nytimes.com/2025/11/20/us/politics/congressional-republicans-trump-midterms.html]</span> on certain issues and his poll numbers dipping. He lashed out at reporters this week, even <span class="colorLinks">calling one [https://www.nytimes.com/2025/11/20/business/media/trump-leavitt-reporter-piggy.html]</span> “piggy,” and made <span class="colorLinks">dark threats [https://www.nytimes.com/2025/11/20/us/politics/trump-democrats-sedition-death-punishment.html]</span> against Democratic lawmakers, accusing them of treason, which he said was “punishable by death.”</p>
<p class="articleParagraph enarticleParagraph" >His meeting with Mr. Mamdani was the happiest he had seemed in a while. There are few things that perk him up like talking about the five boroughs, and at times the pair just seemed like two guys from Queens, yukking it up over a couple of steaks at Keens.</p>
<p class="articleParagraph enarticleParagraph" >They talked a lot about the city, commiserating over high <span class="companylink">Con Edison</span> prices (a reference to the local utility that may have escaped many viewers). When Mr. Mamdani was asked about policing, Mr. Trump jumped in to praise him for retaining the commissioner of the N.Y.P.D., Jessica Tisch. He explained that his daughter Ivanka considered Ms. Tisch a “good friend.”</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump said he was surprised to learn that Mr. Mamdani wanted more buildings to be developed in New York. “If I read the newspapers and the stories, I don’t hear that,” he said. (The day after Mr. Mamdani won, the cover of Mr. Trump’s favorite newspaper, The New York Post, featured an illustration of the mayor-elect dressed in red and holding a hammer and sickle aloft.)</p>
<p class="articleParagraph enarticleParagraph" >Who knows how long the warmth between them will last? Mr. Mamdani managed to make it out of the Oval Office without any visible battle scars, which is more than can be said for <span class="colorLinks">some other Democrats [https://www.nytimes.com/2025/04/12/us/politics/gretchen-whitmer-trump-democrats.html]</span> who have tried it.</p>
<p class="articleParagraph enarticleParagraph" >The president said that he was hopeful for his hometown and its new mayor. “I feel very confident that he can do a very good job,” Mr. Trump said.</p>
<p class="articleParagraph enarticleParagraph" >And what a job it is.</p>
<p class="articleParagraph enarticleParagraph" >“By the way, being the mayor of New York City is a big deal,” the president of the United States said. “I always said, you know, one of the things I would have loved to be some day is the mayor of New York City.”</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | gvote : Elections | ncat : Content Types | ncolu : Columns</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Elections, Mayors | Local Government | Mamdani, Zohran | Mayors | New York City | News | Presidential Election of 2024 | Trump, Donald J | United States Politics and Government</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>The New York Times Company</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NYTFEED020251122elbm000b5</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC45333020251122elbm00105"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump lavishes praise on New York Mayor-elect Mamdani at warm White House meeting</b><div class="leadFields"><a href="javascript:void(0)">Pakistan Today</a>, 09:37 AM, 22 November 2025, 950 words, (English)</div><div class="snippet ensnippet"> WASHINGTON: After months of trading insults, US President Donald Trump and incoming New York City Mayor Zohran Mamdani smiled at each other, swapped compliments and pledged to collaborate on tackling crime and affordability in the nation’s ...</div>
<div>(Document WC45333020251122elbm00105)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC62970020251122elbm0000y"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump-Mamdani Oval Office meeting: 4 takeaways from their surprisingly warm exchange</b><div class="leadFields"><a href="javascript:void(0)">Mathrubhumi</a>, 10:11 PM, 21 November 2025, 696 words,  News Desk, (English)</div><div class="snippet ensnippet"> Washington: President Donald Trump welcomed New York City Mayor-elect Zohran Mamdani to the Oval Office on Friday, in a meeting that many expected to be confrontational but turned out to be surprisingly cordial. The gathering, which brought...</div>
<div>(Document WC62970020251122elbm0000y)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-NFINCE0020251122elbm005b7" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nfinceLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>CE Noticias Financieras English</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump met with New York's Muslim mayor-elect: from hatred to friendship and flattery</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1145 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>CE NoticiasFinancieras</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NFINCE</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright © Content Engine LLC </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >U.S. President Donald Trump met Friday with the man who had proudly proclaimed to be "Trump's worst nightmare," but seemed to find the opposite to be true.</p>
<p class="articleParagraph enarticleParagraph" >The Republican leader and New York City Mayor-elect Zohran Mamdani held a warm and friendly meeting, repeatedly talking about their shared goals to help Trump's hometown rather than referring to their explosive differences.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Trump, who in the past had called Mamdani a "100% communist lunatic" and a "complete crackpot," spoke openly about how impressed he was with the man who had said his government was "authoritarian."</p>
<p class="articleParagraph enarticleParagraph" >The president said he was surprised by their "magnificent" meeting and noted about the social democrat: "In fact, I think he's going to surprise some conservative people."</p>
<p class="articleParagraph enarticleParagraph" >Mamdani and Trump indicated that they discussed housing affordability and the cost of food and utilities, as Mamdani successfully tapped into people's frustration with inflation to win elections, just as the president did in the 2024 election.</p>
<p class="articleParagraph enarticleParagraph" >"We're going to help him, so that everybody's dream comes true, to have a strong and very safe New York," the president told reporters with Mamdani at his side in the Oval Office.</p>
<p class="articleParagraph enarticleParagraph" >"What I really appreciate from the president is that the meeting we had was not focused on the points of disagreement, of which there are many, but also on the shared purpose that we have to serve New Yorkers," Mamdani said.</p>
<p class="articleParagraph enarticleParagraph" >The president downplayed Mamdani's criticism of his immigration raids and claims that Trump was behaving like a despot. Instead, Trump said that the responsibility of holding an executive position in government causes a person to change, saying that had been the case for him.</p>
<p class="articleParagraph enarticleParagraph" >At times he even appeared to protect Mamdani, intervening on his behalf at various points when reporters asked him tough questions.</p>
<p class="articleParagraph enarticleParagraph" >For example, when reporters asked Mamdani to clarify his past statements in which he indicated that he thought the president acted like a fascist, Trump noted, "I've been called far worse things than a despot."</p>
<p class="articleParagraph enarticleParagraph" >When a reporter asked if Mamdani stood by his comments that Trump is a fascist, the president interjected before the mayor-elect could fully answer the question.</p>
<p class="articleParagraph enarticleParagraph" >"That's fine. You can just say yes. OK?" expressed Trump. "It's easier. It's easier than explaining it. I don't care."</p>
<p class="articleParagraph enarticleParagraph" >Trump interjected again when a reporter asked Mamdani why he flew to Washington instead of taking a mode of transportation that required less fossil fuels.</p>
<p class="articleParagraph enarticleParagraph" >"I will defend you," Trump expressed.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, who will take office in January, indicated that he sought to meet with Trump to talk about ways to make New York City more affordable. Trump has said he might want to help him, though he has also falsely labeled Mamdani a "communist" and threatened to withhold federal funds from his hometown.</p>
<p class="articleParagraph enarticleParagraph" >But on Friday Trump didn't threaten the mayor with that. He acknowledged that he had said he was prepared to cut off funds or make it harder for New York City to access federal resources if the two failed to "get along."</p>
<p class="articleParagraph enarticleParagraph" >But the president backed off those threats, saying, "We don't want that to happen. I don't think that's going to happen."</p>
<p class="articleParagraph enarticleParagraph" >Trump was influential in this year's mayoral race, and on the eve of the election, he endorsed independent candidate and former Democratic Gov. Andrew Cuomo, predicting that the city had "zero chance of success, or even survival" if Mamdani won. He also questioned the citizenship of Mamdani, who was born in Uganda and became a naturalized U.S. citizen after graduating from college, and said he would arrest him if he followed through on threats to not cooperate with immigration agents in the city.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani beat back a challenge from Cuomo, who he said was a "puppet" of the president, and noted that he, Mamdani, would be "a mayor capable of standing up to Donald Trump and getting results." During a primary debate, he declared, "I am Donald Trump's worst nightmare, a progressive Muslim immigrant who actually fights for the things I believe in."</p>
<p class="articleParagraph enarticleParagraph" >The president, who has long used his political opponents to fire up his supporters, predicted that Mamdani "will turn out to be one of the best things that ever happened to our great Republican Party." Although Mamdani upended the Democratic establishment by defeating Cuomo, and his far-left progressive policies sparked infighting, Trump has repeatedly portrayed the mayor-elect as the face of the Democratic Party.</p>
<p class="articleParagraph enarticleParagraph" >For Mamdani, a meeting with the U.S. president gave the state lawmaker - who until recently was relatively unknown - the opportunity to come face-to-face with the most powerful person in the world.</p>
<p class="articleParagraph enarticleParagraph" >For his part, the meeting gave Trump a high-profile opportunity to talk about affordability at a time when he is under increasing political pressure to demonstrate that he is addressing voters' concerns about the cost of living.</p>
<p class="articleParagraph enarticleParagraph" >"Some of his ideas are really the same ideas I have," the president said of Mamdani on inflationary concerns.</p>
<p class="articleParagraph enarticleParagraph" >The president has had some tense public confrontations in the Oval Office this year, including a heated exchange with Ukrainian President Volodymyr Zelenskyy in February. In May, Trump dimmed the lights while meeting with South African President Cyril Ramaphosa, playing a four-minute video that made widely rejected claims that South Africa is violently persecuting the country's white Afrikaner minority farmers.</p>
<p class="articleParagraph enarticleParagraph" >A senior Trump administration official, who spoke on condition of anonymity so he could describe internal discussions, said Trump had not spent much time planning the meeting with the incoming mayor, but indicated that the president's threats to block the flow of federal dollars to New York remain in place.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani signaled Thursday that he was not worried that the president might try to use the meeting to publicly embarrass him, and said he viewed it as an opportunity to make his case, though he acknowledged having "a lot of disagreements with the president."</p>
<p class="articleParagraph enarticleParagraph" >Instead, the two men avoided a public confrontation in a series of remarkably calm and cordial comments in front of reporters.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, who lives in the borough of Queens - where Trump grew up - has shown an unrelenting attitude as a candidate, as has Trump. During his campaign he appeared to borrow ideas from Trump's strategy manual when he noted during a televised debate with Cuomo that one of the women who had accused the former governor of sexual harassment was in the audience. Cuomo has denied doing anything illegal.</p>
<p class="articleParagraph enarticleParagraph" >But tensions eased Friday, and Trump appeared sympathetic to Mamdani's policies of wanting to build more housing.</p>
<p class="articleParagraph enarticleParagraph" >"People would be surprised, but I want to see the same thing," the president said.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | greg : Regional Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Content Engine LLC</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NFINCE0020251122elbm005b7</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC72931020251122elbm0001m"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump, NYC Mayor-elect Mamdani hold “very productive” oval office meeting</b><div class="leadFields"><a href="javascript:void(0)">Telangana Today</a>, 11:10 PM, 21 November 2025, 1326 words, (English)</div><div class="snippet ensnippet"> US President Donald Trump and New York City Mayor-elect Zohran Mamdani met at the White House Friday, setting aside months of election rhetoric. They discussed crime, housing, and affordability, expressing optimism about working together ...</div>
<div>(Document WC72931020251122elbm0001m)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC73128020251122elbm00007"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  'Trump Is A Fascist?': Reporter Asks Mamdani; Trump Says 'I Don't Mind'</b><div class="leadFields"><a href="javascript:void(0)">Republic</a>, 09:12 AM, 22 November 2025, 488 words, (English)</div><div class="snippet ensnippet"> New York mayor-elect Zohran Mamdani met with US President Donald Trump in a cordial meeting at the Oval Office. Mamdani, who has opposed Trump in the past, was asked by a reporter whether he still thought if Trump is a fascist.</div>
<div>(Document WC73128020251122elbm00007)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-FSTC000020251122elbm000b6" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/fstcLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>News</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>This week in business: A housing plateau collides with an AI reality check</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Emily Price </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1498 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Fast Company</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>FSTC</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 Mansueto Ventures LLC </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >This week, politics, memes, and protest movements kept colliding with the economy, turning everything from Black Friday shopping to stock charts into a referendum on power and attention.</p>
<p class="articleParagraph enarticleParagraph" >Investors who spent the last couple of years riding <span class="colorLinks">AI [https://www.fastcompany.com/section/artificial-intelligence]</span> and crypto gains are getting a reminder that gravity is still in charge, as once-screaming-up charts now introduce terms like “death cross” and “profit-taking.” Retailers are heading into the holidays knowing that some shoppers are planning not to spend at all, on purpose. And on the cultural front, a single insult from the president is now ricocheting around social networks, while a local New York election is being framed as a national story about socialism, faith, and economic justice.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Here is what actually moved the week in business.</p>
<p class="articleParagraph enarticleParagraph" >Housing’s long plateau: <span class="companylink">Moody’s</span> maps a decade of flat “real” home prices</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="companylink">Moody’s</span> Analytics chief economist Mark Zandi <span class="colorLinks">expects the U.S. housing market to spend the next decade slowly working off the excesses of the pandemic era [https://www.fastcompany.com/91443240/housing-market-moodys-home-price-forecast-for-more-than-300-markets-through-2035]</span>, with prices rising roughly in line with inflation and no real gains once you adjust for it. After the massive run-up in prices and the mortgage rate shock, he sees existing home sales staying frozen for years as affordability gradually improves. <span class="companylink">Moody’s</span> projects nominal home prices will climb about 23.5% between December 2025 and December 2035, with modest declines likely in parts of the South and West and more stability in the Northeast and Midwest. Zandi also points to long-term headwinds like restrictive immigration that could limit construction labor, and to higher Treasury yields that may keep mortgage rates closer to 6%.</p>
<p class="articleParagraph enarticleParagraph" >“Quiet, Piggy” turns into a meme war the president cannot control</p>
<p class="articleParagraph enarticleParagraph" >A clip of President Donald Trump saying “Quiet, Piggy” to Bloomberg reporter Catherine Lucey aboard Air Force One <span class="colorLinks">went viral and quickly turned into a memetic insult aimed right back at him [https://www.fastcompany.com/91444310/quiet-piggy-trump-viral-insult-has-already-become-an-anti-maga-clapback]</span>. Users on Bluesky and X are now quote-posting Trump and his allies with the phrase, often pairing it with unflattering photos or AI-generated images of Trump as Miss Piggy or yelling at Miss Piggy. The reaction taps into Trump’s long record of calling women “pigs,” “dogs,” and “slobs,” and his years of attacking journalists in order to discredit negative coverage. That history makes this latest jab feel especially juvenile and very on brand, fueling frustration that fellow reporters did not push him harder in the moment.</p>
<p class="articleParagraph enarticleParagraph" >XRP sinks as profit-taking and macro fears hit crypto again</p>
<p class="articleParagraph enarticleParagraph" >XRP, the token tied to Ripple’s XRP Ledger, <span class="colorLinks">has dropped to around $2.13 [https://www.fastcompany.com/91444912/xrp-price-today-why-is-it-falling-whats-happening-crypto]</span>, more than 26% below where it was three months ago and well off its July peak of $3.65. The decline comes even after the launch of three XRP exchange-traded funds, including Canary Capital’s XRPC, which has already fallen about 11% as large holders reportedly sold 200 million XRP within two days. Analysts say the pullback is part of a broader risk-off mood as investors worry about a possible tech and AI bubble, economic uncertainty, and the odds of future rate cuts. Bitcoin is under similar pressure, recently flashing a “death cross” that has reinforced bearish sentiment and wiped out its gains for 2025.</p>
<p class="articleParagraph enarticleParagraph" >Epstein’s “Bubba” email becomes NSFW merch and a headache for platforms</p>
<p class="articleParagraph enarticleParagraph" >The release of more than 23,000 pages of Jeffrey Epstein’s estate documents <span class="colorLinks">has spawned a wave of NSFW Trump-and-Clinton-themed merchandise [https://www.fastcompany.com/91443564/epstein-bubba-email-donald-trump-bill-clinton-etsy-merch]</span> on <span class="companylink">Etsy</span> and Amazon. Sellers are zeroing in on a 2018 email in which Epstein’s brother jokes about “photos of Trump blowing Bubba,” a line that has sparked online speculation about the two former presidents, even as both deny any wrongdoing and the documents do not explicitly implicate them. The email has become fodder for T-shirts, mugs, bumper stickers, and other items built around suggestive slogans and winks at “Big, Beautiful Bill.” A few designers have pushed into more creative or graphic territory, including artwork styled after the film Brokeback Mountain.</p>
<p class="articleParagraph enarticleParagraph" >Netflix’s 10-for-1 stock split shocks casual chart watchers, not investors</p>
<p class="articleParagraph enarticleParagraph" >Netflix shares <span class="colorLinks">appear to have fallen more than 90% on some charts [https://www.fastcompany.com/91443105/netflix-stock-split-today-why-are-shares-so-low-dont-panic]</span>, dropping from over $1,100 to around $111. But the move comes from a 10-for-1 stock split rather than an actual collapse in value. For existing shareholders, nothing fundamental has changed, since each old share was simply divided into 10, and holders received nine additional shares for every one they already owned. Netflix says the goal is to make shares more accessible to employees in stock purchase and option programs, where a four-digit price can be a psychological and financial barrier. Lower nominal prices can also make the stock more approachable to smaller retail investors who balk at four-figure tickets.</p>
<p class="articleParagraph enarticleParagraph" >Holiday boycotts aim to turn non-spending into a political weapon</p>
<p class="articleParagraph enarticleParagraph" >Two overlapping campaigns, “Mass Blackout” and “We Ain’t Buying It,” are <span class="colorLinks">calling on Americans to sit out Black Friday [https://www.fastcompany.com/91444540/black-friday-protest-boycott-2025-mass-blackout-we-aint-buying-it-target-trump-and-billionaires-this-thanksgiving-holiday-heres-what-to-know]</span> and the surrounding shopping days to protest Trump-era policies and corporate alignment with them. The Mass Blackout boycott urges people to stop shopping, streaming, and even working, if they can, from the Wednesday before Thanksgiving through the day after Cyber Monday—while still supporting small, local businesses with cash. The We Ain’t Buying It boycott focuses on Target, <span class="companylink">Home Depot</span>, and Amazon, citing everything from DEI rollbacks to alleged cooperation with ICE and tax cut lobbying. Organizers frame the actions as economic noncooperation in an economy where the wealth gap keeps widening and the system “works” for the wealthy by design.</p>
<p class="articleParagraph enarticleParagraph" >Bitcoin’s “death cross” deepens anxiety, makes token roughly flat for 2025</p>
<p class="articleParagraph enarticleParagraph" >Bitcoin has <span class="colorLinks">fallen from October highs above $124,000 to around $94,000 [https://www.fastcompany.com/91443183/bitcoin-death-cross-investors-why-btc-price-sinking-meaning]</span>, giving back its year-to-date gains and putting the token firmly in bear market territory. The slide has been accompanied by a classic technical warning sign known as a “death cross,” when short-term moving averages drop below longer-term ones on a chart. That pattern has added to fears that the current downturn could deepen, even as some analysts note that previous death crosses have lined up with local bottoms rather than full-scale collapses. Other cryptocurrencies are following suit, with a major market index down in line with Bitcoin over the past week. The broader backdrop is a mix of profit-taking by long-term holders, institutional outflows, and macro worries that make speculative assets a tougher sell.</p>
<p class="articleParagraph enarticleParagraph" >Zohran Mamdani becomes conservative media’s new favorite villain</p>
<p class="articleParagraph enarticleParagraph" >New York City Mayor-elect <span class="colorLinks">Zohran Mamdani has not taken office yet [https://www.fastcompany.com/91444999/zohran-mamdani-conservative-media-bogeyman]</span>, but conservative media has already cast him as its latest symbol of everything wrong with the left. Commentators on Fox News, <span class="companylink">Newsmax</span>, and elsewhere have called him a communist, a Marxist, and a “jihadist sympathizer,” often blurring the line between socialism and communism while attacking his membership in the Democratic Socialists of America and his Muslim faith. The New York Post ran a string of attention-grabbing covers about him ahead of the election and is now monetizing those images as merch, further cementing his role as a polarizing figure. Right-leaning outlets describe Mamdani’s agenda as fundamentally at odds with American values, while progressive watchdogs say he is being used much like Nancy Pelosi or Alexandria Ocasio-Cortez were before him, as a stand-in for the entire Democratic Party.</p>
<p class="articleParagraph enarticleParagraph" >Verizon cuts 13,000 jobs to “reorient” around customers</p>
<p class="articleParagraph enarticleParagraph" >Verizon is <span class="colorLinks">laying off more than 13,000 employees [https://www.fastcompany.com/91446439/verizon-layoffs-reorient-company]</span>, roughly 20 percent of its non-union management workforce, as part of a major push to streamline operations and free up money to invest in customer experience. In a memo to staff, new CEO Dan Schulman said the company’s cost structure has become a drag, creating friction that slows Verizon down and frustrates customers. The carrier reported about $33.8 billion in third-quarter revenue and continued growth in prepaid wireless subscribers, but it is losing higher-value postpaid lines and facing intense competition from <span class="companylink">AT&T</span>, T-Mobile, and others. Alongside the layoffs, Verizon plans to sharply reduce outsourced labor and has created a $20 million Reskilling and Career Transition Fund to support affected workers.</p>
<p class="articleParagraph enarticleParagraph" >Tech’s roller-coaster week leaves investors dizzy</p>
<p class="articleParagraph enarticleParagraph" >Thursday turned into a full roller coaster for tech investors. <span class="colorLinks">Nvidia’s blowout earnings pushed its stock up nearly 5% [https://www.fastcompany.com/91446979/stock-market-today-ai-bubble-rate-cut-probability-mag-7-tech-latest]</span> early in the day and briefly lifted the entire Magnificent Seven, thanks to better-than-expected revenue, strong profit, and a bullish fourth-quarter forecast. But fears of an AI bubble and fading confidence in a December Fed rate cut quickly erased those gains, sending the major tech names and the Nasdaq composite into sharp intraday swings. By Friday morning, rate-cut odds had risen again, and several of the big players were inching back into positive territory, even as <span class="companylink">Nvidia</span> slipped.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Click to view image. [https://images.fastcompany.com/image/upload/w_1280,q_auto,f_auto,fl_lossy/f_webp,q_auto,c_fit/wp-cms-2/2025/11/p-91447504-the-week-in-business-housing-stocks-crypto-bubba-piggy-nvidia.jpg]</span>
                  </p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IN</b>&nbsp;</td><td><br/>ibnk : Banking/Credit | ifinal : Financial Services | ifmsoft : Financial Technology | itech : Technology | ivicu : Virtual Currencies/Cryptocurrencies</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | gvote : Elections</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>News</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Mansueto Ventures LLC</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document FSTC000020251122elbm000b6</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC92455020251122elbm00007"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Mamdani announces “partnership” with hated would-be dictator Trump</b><div class="leadFields"><a href="javascript:void(0)">World Socialist Web Site</a>, 11:00 PM, 21 November 2025, 1493 words,  Joseph Kishore, (English)</div><div class="snippet ensnippet"> On Friday afternoon, New York City Mayor-elect Zohran Mamdani met with President Donald Trump in the White House, followed by a 30-minute press conference from the Oval Office. The event was a grotesque love-fest, during which Mamdani, a ...</div>
<div>(Document WC92455020251122elbm00007)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-NATHER0020251122elbm0002v" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/natherLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Columnists</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Ghosts of Radicals Past: What NYC’s New Mayor Can Learn from 2015 Greece</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>838 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The National Herald</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NATHER</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© Copyright 2025 - The National Herald, Inc. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >New York City found itself at the epicenter of world politics following the recent election of a 34-year-old relative political newbie to Gracie Mansion.</p>
<p class="articleParagraph enarticleParagraph" >From a journalistic standpoint, this is quite a story, considering hardly anyone knew his name prior to last June’s primary elections. Only months ago, the notion of a self-styled democratic socialist running the center of global capitalism would have been laughable. However, in this polarized era, where political fortunes can shift faster than the rip current in the Rockaways, centrist voices are increasingly drowned out by acerbic rhetoric that relies more on the peripheral route to persuasion (based on emotion and superficial cues) than on reason and facts.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Zoran Mamdani’s meteoric rise seems propelled more by his self-portrayal as the ‘anti-Trump’ than the practicality of his platform. Throughout his campaign, he appeared more interested in campaigning against Donald Trump than his opponents (in part because Andrew Cuomo’s genuine unlikability and Curtis Sliwa’s idiosyncrasies enabled this). Many of the voters who cast their ballot for Mayor-elect Mamdani likely did so misguidedly thinking they were somehow rebuking President Trump. But ironically, Mamdani’s campaign took a central page out of the Trump playbook, capitalizing on voter dissatisfaction with the economy and hazy populist promises of better days.</p>
<p class="articleParagraph enarticleParagraph" >This election was akin to the once (and soon to be) fringe Greek far-left SYRIZA party’s rise to power in 2015. Its young and charismatic leader Alexis Tsipras became Prime Minister at the age of 41 on promises of tearing up the memoranda with which Greece’s creditors had shackled the nation with a single law, and terrorizing the ‘terrorists’ in the EU who were dangling the threat of economic destruction since 2009 if Greece did not capitulate to painful austerity measures. After about six months of chaos, Tsipras went against the very referendum he called for (and handily won), signing a punitive third memorandum with the nation’s creditors, including a superfund controlling many public properties for 99 years. In the process, he even managed to reverse Greece’s decades-old position on neighboring Skopje and recognize their misappropriation of the name ‘Macedonia’ and its derivatives in exchange for next to nothing… He is currently trying to engineer a political comeback by positioning himself more to the center and calling for [sic]… a “new patriotism.”</p>
<p class="articleParagraph enarticleParagraph" >It’s unknown whether Mr. Mamdani’s tenure in office will be reminiscent of Mr. Tsipras’, but is should serve as a lesson, lest the former become President Trump’s puppet, as the latter did for then-German Chancellor Merkel. Despite the high profile of the position, a mayor’s powers are dwarfed by those of the Governor and state legislature. Without their cooperation, many of Mr. Mamdani’s bold proposals will never make it out of the gate. Although the state legislature appears to espouse much of his ideology and he received the endorsement of the Governor, much could change by next year if he doesn’t get off to a strong (and most importantly, rational) start.</p>
<p class="articleParagraph enarticleParagraph" >Everyone knows that the primary job of the mayor is to keep the city safe and clean. This has always separated a good mayor from a poor one. Moreover, handling the largest school system in the United States is also within the purview of New York City’s first citizen.</p>
<p class="articleParagraph enarticleParagraph" >On the other hand, mayors don’t set financial policy. They can’t print money and they can’t curb inflation, so the economic fate of the city will more or less mirror that of the country.</p>
<p class="articleParagraph enarticleParagraph" >While voter turnout was high, it still only accounted for approximately 40 percent of the registered voters in the city. Mr. Mamdani garnered about half the vote, earning him a handy victory albeit with a much narrower margin than most of his predecessors in a solid blue city like New York. To succeed, he must be a mayor to the 8 million residents in the city, not just serve the ‘nomenclatura’ who propelled him to power. His victory photo with the chairman of the <span class="companylink">Open Society</span> and son of (in)famous George Soros has already irked some.</p>
<p class="articleParagraph enarticleParagraph" >In the months to come, Republicans will try to use Mayor-elect Mamdani to spearhead their charge into next year’s critical midterm elections and a competitive governor’s race in New York. The loss of Albany’s support would prove debilitating to Mr. Mamdani’s lofty platform pledges and leave him in a position similar to Mr. Tsipras post-July 2015. On the contrary, tempering ideological ankylosis for practical solutions would enable him to prove that his smooth rhetoric is backed by substance and that he is politically self-luminous; that his luster is not merely a reflection of larger political stars, whether that is Donald Trump or the entities funding the radicalization of the Democratic party.</p>
<p class="articleParagraph enarticleParagraph" >Follow me on X @CTripoulas</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | greg : Regional Politics | gvote : Elections | ncat : Content Types | ncolu : Columns</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>devgcoz : Emerging Market Countries | eecz : European Union Countries | eurz : Europe | greece : Greece | medz : Mediterranean Countries | namz : North America | seurz : Southern Europe | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Columnists</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>The National Herald Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NATHER0020251122elbm0002v</td></tr></table><br/></div></div><br/><span></span><div id="article-STPT000020251122elbm0005o" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/stptLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump and Mamdani go from adversaries to allies after meeting</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Times news services </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1640 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Tampa Bay Times</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>STPT</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>4</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 Times Publishing Company. All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >WASHINGTON — President Donald Trump on Friday met the man who had proudly proclaimed himself “Donald Trump’s worst nightmare,” but he seemed to find the opposite.</p>
<p class="articleParagraph enarticleParagraph" >The Republican president and New York City’s Mayor-elect Zohran Mamdani were warm and friendly, speaking repeatedly of their shared goals to help Trump’s hometown rather than their combustible differences.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Trump, who had in the past called Mamdani a “100% Communist Lunatic” and a “total nut job,” spoke openly of how impressed he was with the man who had called his administration “authoritarian.”</p>
<p class="articleParagraph enarticleParagraph" >“I think he is going to surprise some conservative people, actually,” Trump said of the democratic socialist as Mamdani stood next to him in the Oval Office.</p>
<p class="articleParagraph enarticleParagraph" >The meeting offered political opportunities for both men. For Mamdani, a sit-down offered the state lawmaker — who until recently was relatively unknown — the chance to go head-to-head with the most powerful person in the world.</p>
<p class="articleParagraph enarticleParagraph" >For Trump, it was a high-profile chance to talk about affordability at a time when he’s under increasing political pressure to show he’s addressing voter concerns about the cost of living.</p>
<p class="articleParagraph enarticleParagraph" >Until now, the men have been political foils who galvanized their supporters by taking on each other, and it’s unclear how those backers will react to their genial get-together and complimentary words.</p>
<p class="articleParagraph enarticleParagraph" >“We’re going to be helping him, to make everybody’s dream come true, having a strong and very safe New York,” the president said.</p>
<p class="articleParagraph enarticleParagraph" >“What I really appreciate about the president is that the meeting that we had focused not on places of disagreement, which there are many, and also focused on the shared purpose that we have in serving New Yorkers,” Mamdani said.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani and Trump said they discussed housing affordability and the cost of groceries and utilities, as Mamdani successfully used frustration over inflation to get elected, just as the president did in the 2024 election.</p>
<p class="articleParagraph enarticleParagraph" >“Some of his ideas are really the same ideas that I have,” the president said of Mamdani about inflationary issues.</p>
<p class="articleParagraph enarticleParagraph" >The president brushed aside Mamdani’s criticisms of him over his administration’s deportation raids and claims that Trump was behaving like a despot. Instead, Trump said the responsibility of holding an executive position in the government causes a person to change, saying that had been the case for him.</p>
<p class="articleParagraph enarticleParagraph" >WASHINGTON</p>
<p class="articleParagraph enarticleParagraph" >Journalist’s widow calls for transcript release</p>
<p class="articleParagraph enarticleParagraph" >The widow of <span class="companylink">Washington Post</span> journalist Jamal Kashoggi called Friday for the release of the transcript of a 2019 phone call that President Donald Trump had with Mohammed bin Salman, joining Democratic lawmakers who are raising questions about whether Trump personally benefited from his embrace of the Saudi crown prince.</p>
<p class="articleParagraph enarticleParagraph" >Hanan Elatr Khashoggi appeared on Capitol Hill on Friday morning on the heels of Trump’s dismissal of U.S. intelligence findings that Prince Mohammed most likely had culpability in the October 2018 slaying of her husband. Trump also lavished the Saudi ruler this week with some of Washington’s highest honors for a foreign dignitary, deepening the business and military relationship between the two nations.</p>
<p class="articleParagraph enarticleParagraph" >Saudi intelligence officials and a forensic doctor killed and dismembered Jamal Khashoggi at the Saudi Consulate in Istanbul in 2018.</p>
<p class="articleParagraph enarticleParagraph" >“There is no justification to kidnap him, torture him, to kill him and to cut him to pieces,” Hanan Elatr Khashoggi said Friday during an emotional news conference. “This is a terrorist act.”</p>
<p class="articleParagraph enarticleParagraph" >The demand in Congress for the Trump administration to release the call transcripts is being led by Rep. Eugene Vindman, a freshman Democrat from Virginia who was deputy legal adviser to the National Security Council during Trump’s first term.</p>
<p class="articleParagraph enarticleParagraph" >Vindman, who has reviewed the transcript of the phone call with Prince Mohammed, declined to go into specifics of the classified document Friday, but said it used “the terminology of quid pro quo, the ensuing benefits that the president reaped.”</p>
<p class="articleParagraph enarticleParagraph" >The Democratic lawmakers also pointed out that Trump’s family has extensive business dealings in Saudi Arabia that at times have benefited from the prince’s direct involvement.</p>
<p class="articleParagraph enarticleParagraph" >WASHINGTON</p>
<p class="articleParagraph enarticleParagraph" >Court meets to weigh birthright citizenship</p>
<p class="articleParagraph enarticleParagraph" >The Supreme Court met in private Friday with a key issue on its agenda — President Donald Trump’s birthright citizenship order declaring that children born to parents who are in the United States illegally or temporarily are not American citizens.</p>
<p class="articleParagraph enarticleParagraph" >The justices could say as soon as Monday whether they will hear Trump’s appeal of lower court rulings that have uniformly struck down the citizenship restrictions. They have not taken effect anywhere in the United States.</p>
<p class="articleParagraph enarticleParagraph" >If the court steps in now, the case would be argued in the spring, with a definitive ruling expected by early summer.</p>
<p class="articleParagraph enarticleParagraph" >The birthright citizenship order, which Trump signed on the first day of his second term in the White House, is part of his administration’s broad immigration crackdown. Other actions include immigration enforcement surges in several cities and the first peacetime invocation of the 18th century Alien Enemies Act.</p>
<p class="articleParagraph enarticleParagraph" >The administration is facing multiple court challenges, and the high court has sent mixed signals in emergency orders it has issued. The justices effectively stopped the use of the Alien Enemies Act to rapidly deport alleged Venezuelan gang members without court hearings, while they allowed the resumption of sweeping immigration stops in the Los Angeles area after a lower court blocked the practice of stopping people solely based on their race, language, job or location.</p>
<p class="articleParagraph enarticleParagraph" >The justices also are weighing the administration’s emergency appeal to be allowed to deploy National Guard troops in the Chicago area for immigration enforcement actions. A lower court has indefinitely prevented the deployment.</p>
<p class="articleParagraph enarticleParagraph" >ABUJA, NIGERIA</p>
<p class="articleParagraph enarticleParagraph" >Gunmen abduct</p>
<p class="articleParagraph enarticleParagraph" >more than 200 kids</p>
<p class="articleParagraph enarticleParagraph" >Gunmen attacked a Catholic boarding school in a western region of Nigeria and abducted more than 200 schoolchildren Friday, the <span class="companylink">Christian Association of Nigeria</span> said, in the latest in a spate of abductions in Africa’s most populous country.</p>
<p class="articleParagraph enarticleParagraph" >The attack and abductions took place at St. Mary’s School, a Catholic institution in the Agwara local government’s Papiri community. Attackers seized 215 pupils and students as well as 12 teachers, said Daniel Atori, a spokesperson for the Niger state chapter of CAN.</p>
<p class="articleParagraph enarticleParagraph" >“I just got back to the village tonight after I visited the school where I also met with parents,” said Atori in a statement, adding the association is working “to ensure our children’s safe return.”</p>
<p class="articleParagraph enarticleParagraph" >The Niger State Police Command said the abductions took place in the early hours, and that military and security forces have since been deployed to the community. It described St. Mary’s as a secondary school, which in Nigeria would serve children between the ages of 12 and 17.</p>
<p class="articleParagraph enarticleParagraph" >A satellite image shows that the school compound is attached to an adjoining primary school, with more than 50 classroom and dormitory buildings. It’s located near a major road linking the towns of Yelwa and Mokwa.</p>
<p class="articleParagraph enarticleParagraph" >LOS ANGELES</p>
<p class="articleParagraph enarticleParagraph" >Torrential rains return to Southern California</p>
<p class="articleParagraph enarticleParagraph" >The third storm in just over a week drenched Southern California on Friday and prompted some local flooding but caused no major widespread damage before heading east into the mountains and south toward Mexico’s Baja California Peninsula.</p>
<p class="articleParagraph enarticleParagraph" >The series of storms put Southern California on track for near-record November rainfall, the National Weather Service said. The region has received copious amounts of rain since Nov. 13, more than four times the normal amount that typically falls during the month in downtown Los Angeles, according to weather service reports.</p>
<p class="articleParagraph enarticleParagraph" >Residents were warned before dawn Friday of flash flooding of streets, creeks and streams and possible mudslides in parts of Los Angeles and Orange counties. Some vehicles were stuck in floodwaters near Culver City before dawn, the weather service reported.</p>
<p class="articleParagraph enarticleParagraph" >In coastal Huntington Beach, rainwater rushed through streets like a stream, and one neighborhood flooded after a local pond overflowed, spilling water into the streets and trapping parked cars.</p>
<p class="articleParagraph enarticleParagraph" >By midday, the rain had passed through the coastal region and the sun was shining as the storm shifted east over the mountains, dropping about 3 inches of snow in the resort community of Big Bear with the potential for more into Saturday, said Sebastian Westerink, a meteorologist for the National Weather Service in San Diego.</p>
<p class="articleParagraph enarticleParagraph" >“It is certainly possible we’re going to see a few inches overnight,” Westerink said.</p>
<p class="articleParagraph enarticleParagraph" >No major damage was reported from the latest storm, Westerink said.</p>
<p class="articleParagraph enarticleParagraph" >WASHINGTON</p>
<p class="articleParagraph enarticleParagraph" >Greene says she is resigning from Congress</p>
<p class="articleParagraph enarticleParagraph" >Rep. Marjorie Taylor Greene of Georgia, a once-loyal supporter of President Donald Trump who has become a critic, said Friday she is resigning from Congress in January.</p>
<p class="articleParagraph enarticleParagraph" >Greene, in a more than 10-minute video posted online, explained her decision and said she’s “always been despised in Washington, D.C., and just never fit in.”</p>
<p class="articleParagraph enarticleParagraph" >Greene’s resignation followed a public fallout with Trump in recent months, as the congress member criticized him for his stance on files related to Jeffrey Epstein, along with foreign policy and health care.</p>
<p class="articleParagraph enarticleParagraph" >Trump branded her a “traitor” and “wacky” and said he would endorse a challenger against her when she ran for reelection next year.</p>
<p class="articleParagraph enarticleParagraph" >She said her last day would be Jan. 5, 2026.</p>
<p class="articleParagraph enarticleParagraph" >The White House did not immediately respond to a message seeking comment Friday night.</p>
<p class="articleParagraph enarticleParagraph" >Greene had been closely tied to the Republican president since she launched her political career in 2020.</p>
<p class="articleParagraph enarticleParagraph" >In her video, she underscored her longtime loyalty to Trump except on a few issues, and said it was “unfair and wrong” that he attacked her for disagreeing.</p>
<p class="articleParagraph enarticleParagraph" >“Loyalty should be a two-way street and we should be able to vote our conscience and represent our district’s interest, because our job title is literally ‘representative,’” she said.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gdis : Disasters/Accidents | gflood : Floods/Tidal Waves | gntdis : Natural Disasters | gpir : Politics/International Relations | gpol : Domestic Politics | grisk : Risk News | gwea : Weather</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States | usdc : Washington DC | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Times Publishing Company</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document STPT000020251122elbm0005o</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC62519020251122elbm00018"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  In meeting with Mamdani, Trump repeats claim he solved conflict between India and Pakistan</b><div class="leadFields"><a href="javascript:void(0)">The New Indian Express</a>, 12:20 AM, 22 November 2025, 421 words, (English)</div><div class="snippet ensnippet"> NEW YORK/WASHINGTON: US President Donald Trump has again claimed to have solved the conflict between India and Pakistan, repeating his assertion during a meeting with New York City Mayor-elect Zohran Mamdani in the Oval Office.</div>
<div>(Document WC62519020251122elbm00018)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-USATONL020251122elbm000ru" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/usatonlLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Are the rich fleeing Mamdani’s Manhattan? Not according to the data.</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Swapna Venugopal Ramaswamy </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1973 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>05:06 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>usatoday.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>USATONL</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© Copyright Gannett 2025 All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >NEW YORK − Margaret Flint was 18 when she first moved to Manhattan from her childhood home in Chevy Chase, Maryland, in 1970.</p>
<p class="articleParagraph enarticleParagraph" >She’d just enrolled at Barnard College, and for about four years, she shared an apartment with a classmate on the Upper West Side. While living in Manhattan, she went to law school and got married. She and her husband moved to the suburbs in the early 1990s.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >On Nov. 4, the day <span class="colorLinks">New York City elected a new mayor [https://www.usatoday.com/story/news/politics/2025/11/04/zohran-mamdani-wins-nyc-mayor-election/86311529007/]</span>, Flint signed a contract to buy a two-bedroom apartment for $1.4 million in the same building she had called home as a Barnard student.</p>
<p class="articleParagraph enarticleParagraph" >That night, the <span class="colorLinks">city elected 34-year-old Zohran Mamdani [https://www.usatoday.com/story/news/politics/elections/2025/11/04/nyc-mayor-election-mamdani-vs-cuomo-results/86572353007/]</span>, a member of the <span class="colorLinks">Democratic Socialists of America [https://www.usatoday.com/story/news/politics/2025/11/15/zohran-mamdani-victory-nyc-democratic-socialism/87231501007/]</span> and New York’s first <span class="colorLinks">Muslim and South Asian mayor. [https://www.usatoday.com/story/news/politics/2025/11/05/nyc-mayor-zohran-mamdani-bollywood/87112589007/]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Mamdani, whom <span class="colorLinks">President Donald Trump [https://www.usatoday.com/news/politics/donald-trump/]</span> has derided as a "<span class="colorLinks">Liddle’ Communist, [https://truthsocial.com/@realDonaldTrump/posts/115207991871277413]</span>" campaigned on the promise of raising taxes on corporations and those earning more $1 million per year to pay for free buses and universal childcare. He also previously advocated for defunding the police, which he abandoned during the mayoral campaign. Mamdani, who has pledged to protect Jewish New Yorkers against hate crimes, also drew criticism for his anti-Zionist views and history of pro-Palestinian activism.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Mamdani’s victory in the June Democratic primary [https://www.usatoday.com/story/news/politics/2025/07/01/zohran-mamdani-nyc-mayor-democratic-primary-election/84427903007/]</span> was a strong indication that he would prevail in the general election in the overwhelmingly Democratic city. Soon <span class="colorLinks">news reports [https://nypost.com/2025/10/29/real-estate/nyc-buyers-are-fleeing-amid-fears-of-a-mamdani-win/]</span> quoted real estate agents in Florida and Connecticut claiming wealthy New Yorkers were looking to flee the metropolis.</p>
<p class="articleParagraph enarticleParagraph" >Facebook Moms' groups in the city's wealthiest <span class="colorLinks">enclaves like the Upper East Side [https://www.thecut.com/article/moms-of-the-upper-east-side-facebook-meltdown-mamdani.html]</span> are full of nervous posts about the city's fate. Would the rich flee? Would crime increase?</p>
<p class="articleParagraph enarticleParagraph" >The chatter did not give Flint any pause before she signed on the dotted line.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">New York City Mayoral candidate Zohran Mamdani (R) celebrates alongside his wife Rama Duwaji (L) during an election night event at the Brooklyn Paramount Theater in Brooklyn, New York on November 4, 2025. New Yorkers elected leftist Zohran Mamdani as their next mayor Nov. 4, 2025, broadcasters projected, on a day of key local ballots across the country offering the first electoral judgement of Donald Trump's tumultuous second White House term. [https://www.gannett-cdn.com/authoring/authoring-images/2025/11/20/USAT/87383117007-2244567287.jpg]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >“People are out of their minds if they think they have to leave the city,” Flint, 73, said. “I agree with his policies, and I think that New York should be a place where all sorts of people can live and want to live. And that means that everybody has to pay their fair share.”</p>
<p class="articleParagraph enarticleParagraph" >Flint is not the only affluent person still betting on New York.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">600 West 111 Street, New York [https://www.gannett-cdn.com/authoring/authoring-images/2025/11/21/USAT/87395843007-600-west-111-th-street.jpg]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >A 'false narrative': 'If people were fleeing the city, prices would be falling</p>
<p class="articleParagraph enarticleParagraph" >After <span class="colorLinks">Mamdani became a household name following his primary win [https://www.usatoday.com/story/opinion/columnist/2025/06/24/nyc-mayor-election-mamdani-cuomo-democratic-primary/84335149007/]</span> in June, Manhattan rental prices increased year-over-year at twice the rate of inflation. The rate of increase was even higher in the luxury rental market, according to Jonathan Miller, the president of Miller Samuel Real Estate Appraisers & Consultants, and author of the Elliman report.</p>
<p class="articleParagraph enarticleParagraph" >The overall median rent went up 7.1% to $4,600 from October 2024 to October 2025. The luxury market median rent saw a 20% increase in the same period, going up to $11,995. High earners were undeterred by Mamdani's wide lead in the general election polls through the summer and fall.</p>
<p class="articleParagraph enarticleParagraph" >The median sales price went up to $1.18 million, a 5.8% year-over-year increase in the third quarter, which is from July to September. In the luxury market, sales prices went up 2.8%. And inventory actually fell 16% in the luxury market from October 2024 to October 2025, indicating that there is no flood of New Yorkers selling their homes and leaving town.</p>
<p class="articleParagraph enarticleParagraph" >“Sales are rising faster than supply which is why median prices went up 5.8%. If sales are rising faster than inventory, prices generally go up,” said Miller. “So if people were fleeing the city, prices would be falling.”</p>
<p class="articleParagraph enarticleParagraph" >The reasons for the increase in sales can be attributed in large part to overall gains in the stock market, the expectations of big Wall Street bonuses and declining mortgage rates.</p>
<p class="articleParagraph enarticleParagraph" >Mortgage rates for the week ending Nov. 20 averaged 6.2% for a 30-year conventional, down from 6.8% during the same time last year, according to data from <span class="companylink">Freddie Mac</span>.</p>
<p class="articleParagraph enarticleParagraph" >“I look at evidence-based data as opposed to anecdotes because the plural of anecdotal is not data, it's just more anecdotes,” he said, describing the exodus-from-New York plotline as a “false narrative.”</p>
<p class="articleParagraph enarticleParagraph" >After months of criticizing Mamdani, Trump, a second-generation real estate developer who owns several properties in New York, seemed eager to maintain his ties to the Big <span class="companylink">Apple</span> after meeting the young politician in the White House on Nov. 21.</p>
<p class="articleParagraph enarticleParagraph" >During a <span class="colorLinks">joint appearance at the Oval Office [https://www.usatoday.com/story/news/politics/2025/11/21/trump-mamdani-meeting-live-updates/87387133007/]</span>, Trump was asked by a reporter if he'd be comfortable living in Mamdani's New York.</p>
<p class="articleParagraph enarticleParagraph" >"Yeah, I would, I really would, especially after the meeting," said Trump. "We agree on a lot more than I would have thought. I want him to do a great job, and we’ll help him do a great job.”</p>
<p class="articleParagraph enarticleParagraph" >A couple of weeks after the election, the tone of chatter on <span class="companylink">Facebook</span> groups also changed, with most indicating they were not moving anywhere.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">600 West 111 Street, New York [https://www.gannett-cdn.com/authoring/authoring-images/2025/11/21/USAT/87395842007-600-west-111-street-2.jpg]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Richest New Yorkers far less likely to leave than working and middle-class New Yorkers</p>
<p class="articleParagraph enarticleParagraph" >The data also supports the conclusions of a 2023 report from the Fiscal Policy Institute, which found that the richest New Yorkers are far less likely to move out of New York than working and middle-class New Yorkers in normal, non-pandemic years.</p>
<p class="articleParagraph enarticleParagraph" >Most high-earner migration during COVID-19 was due to city dwellers who could work from home and were looking for more space, rather than tax-related reasons.</p>
<p class="articleParagraph enarticleParagraph" >In fact, the report found that high earning New Yorkers move out of New York State at one-quarter the rate of the rest of the population during typical years.</p>
<p class="articleParagraph enarticleParagraph" >And when New York’s high earners do move, they are more likely to move to other relatively high tax states such as New Jersey and Connecticut.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Ann Cutbill Lenane [https://www.gannett-cdn.com/authoring/authoring-images/2025/11/21/USAT/87395367007-ann-lenane.jpg]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Ann Cutbill Lenane, an agent for <span class="companylink">Douglas Elliman</span>, who specializes in the luxury market, said discussions around the potential increase in taxes have cropped up here and there.</p>
<p class="articleParagraph enarticleParagraph" >“They are talking about it, but they're not saying, 'oh my gosh, I'm not signing this contract,'” said Lenane, who has 40 years of experience in Manhattan and has done $2 billion in sales.</p>
<p class="articleParagraph enarticleParagraph" >Trump tariffs a bigger factor in buyer hesitancy in New York City</p>
<p class="articleParagraph enarticleParagraph" >Lenane says she saw bigger buyer hesitancy around Trump's tariffs raising the cost of construction or renovation as raw materials like lumber are often imported.</p>
<p class="articleParagraph enarticleParagraph" >“What we're having harder time with is apartments that need work because of tariffs and not really having a good sense of what a renovation is going to cost,” she said. “They are also worried about the timeframe and I'm finding that to be the biggest challenge.”</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Matthew Bizzarro has sold apartments in New York city by more than 23 years [https://www.gannett-cdn.com/authoring/authoring-images/2025/11/21/USAT/87395284007-matthew-bizzarro.jpg]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Matthew Bizzarro, who has more than 23 years of experience selling homes in New York City, echoed Lenane’s concern around tariffs.</p>
<p class="articleParagraph enarticleParagraph" >He said he lost five contracts the week that <span class="colorLinks">Trump announced global tariffs [https://www.usatoday.com/story/news/politics/2025/04/02/trump-tariff-announcement-april-2/82774378007/]</span> on all imports in April because of the uncertainty in the market.</p>
<p class="articleParagraph enarticleParagraph" >Did any contracts fall through during election week?</p>
<p class="articleParagraph enarticleParagraph" >“Zero,” he said.</p>
<p class="articleParagraph enarticleParagraph" >Bizzarro said he’s seen an exodus before, but this isn’t one.</p>
<p class="articleParagraph enarticleParagraph" >During COVID, he ended up opening an office in Westchester County as people began looking to decamp from the city.</p>
<p class="articleParagraph enarticleParagraph" >“At one point, I had a hundred listings during COVID, from people just being like, ‘just sell it’, he said.</p>
<p class="articleParagraph enarticleParagraph" >None of that is happening now.</p>
<p class="articleParagraph enarticleParagraph" >“We have 74 contracts right now,” he said. From Nov. 1 to Nov. 15, his contract volume is up 32% compared to the same period last year, he said.</p>
<p class="articleParagraph enarticleParagraph" >Some people who might be sitting on the sidelines are investors who buy building with five to 10 units, he said.</p>
<p class="articleParagraph enarticleParagraph" >“People who buy apartment buildings want to see if the rent freezes will go into effect,” he said, referring to Mamdani's campaign pledge to freeze rents in rent-stabilized apartments. “No one's going to buy a building if you can't make money on it.”</p>
<p class="articleParagraph enarticleParagraph" >A concern about possible increase in crime and loss of services</p>
<p class="articleParagraph enarticleParagraph" >Jacob Goldman, a Manhattan-based realtor, said he has received a few calls from people concerned about Mamdani and who were thinking of selling.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Jacob Goldman, a real estate agent in New York City [https://www.gannett-cdn.com/authoring/authoring-images/2025/11/21/USAT/87400264007-jacob-139-final.JPG]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >“But only very few people have done that. There’s not a mass exodus right now,” he said. “The thing to watch is how will people react to his economic policies. I think it's safe to assume that he's not attracting businesses to New York.”</p>
<p class="articleParagraph enarticleParagraph" >Josie Lee, 59, the owner of a one-bedroom home on the Lower East Side said Mamdani’s election was one of the many factors that played into her listing her apartment this summer.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Josie Lee sold her apartment on the Lower East Side in the second week of November, 2025 [https://www.gannett-cdn.com/authoring/authoring-images/2025/11/21/USAT/87396017007-josie-lee.JPG]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >She signed a contract on her 750-square-foot apartment just after the election. The buyer is a New Yorker in his 30s.</p>
<p class="articleParagraph enarticleParagraph" >Lee, who works in marketing and communications, said she is close to retirement and had been considering a move to a place that would have lush greenery and some more living space.</p>
<p class="articleParagraph enarticleParagraph" >But Mamdani’s primary win persuaded her to speed up the process.</p>
<p class="articleParagraph enarticleParagraph" >She said she was worried about a possible increase in crime, especially given Mamdani’s past rhetoric around defunding the police. She said she fears companies would move away, eroding the tax base and burdening the city residents.</p>
<p class="articleParagraph enarticleParagraph" >“You keep doing that to the tax base of the city, then it's going run out of money,” she said. “Then it creates a cycle of ‘we don't have enough money, let's cut services.’”</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="companylink">Lee</span> is now moving to Fishkill, a small city located on the Hudson River, about 90 minutes north of Manhattan.</p>
<p class="articleParagraph enarticleParagraph" >She said she can still easily go to the city to catch shows, visit museums and meet up with friends.</p>
<p class="articleParagraph enarticleParagraph" >New York is 'resilient': Buzz around an exodus is a 'lot of talk'</p>
<p class="articleParagraph enarticleParagraph" >Jill Prink, an urban landscape designer, who has lived in Manhattan for 25 years, will be closing on her first New York City apartment in the next few weeks.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Jill Prink will be closing on an apartment in Manhattan in December, 2025 [https://www.gannett-cdn.com/authoring/authoring-images/2025/11/21/USAT/87395209007-jill-prink.jpg]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >She said the election of the new mayor did not factor into her decision, adding that New York and New Yorkers are "resilient."</p>
<p class="articleParagraph enarticleParagraph" >Prink said she was excited about renovating her one-bedroom apartment and moving in.</p>
<p class="articleParagraph enarticleParagraph" >As far as the buzz about people looking to move, she said she is not convinced.</p>
<p class="articleParagraph enarticleParagraph" >“I view it as a lot of talk,” she said. “It's very diverse and international here and people from all over come and live here. If there's some people who don't want, there will be others who do want to be in the city.”</p>
<p class="articleParagraph enarticleParagraph" >Swapna Venugopal Ramaswamy is a White House correspondent for <span class="companylink">USA TODAY</span>. You can follow her on X @SwapnaVenugopal</p>
<p class="articleParagraph enarticleParagraph" >This article originally appeared on <span class="companylink">USA TODAY</span>: Are the rich fleeing Mamdani’s Manhattan? Not according to the data.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>ccat : Corporate/Industrial News</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | usdc : Washington DC | use : Northeast U.S. | usny : New York State | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Campaigns & Elections | Coronavirus COVID-19 | Donald Trump | Facebook | Government | Manhattan | New York | NY | Politics | Zohran Mamdani</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Gannett Co., Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document USATONL020251122elbm000ru</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC59819020251122elbm00006"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Former Vice President Kamala Harris’ book tour coming to San Diego in 2026</b><div class="leadFields"><a href="javascript:void(0)">Del Mar Times</a>, 12:00 AM, 22 November 2025, 277 words,  Abby Hamblin, (English)</div><div class="snippet ensnippet"> Getting your Trinity Audio player ready...Former Vice President Kamala Harris’ international tour for her recent book about her 2024 presidential campaign will come to San Diego in the spring.</div>
<div>(Document WC59819020251122elbm00006)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC41159020251122elbm0000h"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Donald Trump commends victory of New York's mayor-elect Zohran Mamdani at White House meeting</b><div class="leadFields"><a href="javascript:void(0)">Radio New Zealand</a>, 08:47 PM, 21 November 2025, 851 words,  Gram Slattery, (English)</div><div class="snippet ensnippet"> US President Donald Trump praised the electoral victory of incoming New York City mayor Zohran Mamdani at the White House on Friday in the first in-person meeting for the political opposites, who have clashed over everything from ...</div>
<div>(Document WC41159020251122elbm0000h)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-TOI0000020251122elbm0007k" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/toiLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>India</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>'Did 8 peace deals': Trump repeats role in India-Pakistan ceasefire during Mamdani meeting; claim made over 60 times</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>TOI News Desk </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>246 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The Times of India</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>TOI</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>(c) 2025 The Times of India Group </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >NEW DELHI: US President Donald Trump on Friday once again claimed credit for helping ease tensions between India and Pakistan, making the assertion more than 60 times to date.The remarks came during a meeting with New York City Mayor-elect Zohran Mamdani at the White House, marking Mamdani’s first formal interaction with the president following his historic election victory.During the Oval Office discussion, Trump referred to the May confrontation between the two nations, saying, “I did eight peace deals of countries, including India and Pakistan,” as quoted by <span class="companylink">ANI</span>. Earlier in the week, Trump claimed he had threatened both countries with 350 per cent tariffs if hostilities continued.India, however, has consistently dismissed any suggestion of third-party mediation. The conflict began after India launched Operation Sindoor on May 7, targeting terror infrastructure in Pakistan and Pakistan-occupied Kashmir in retaliation for the April 22 Pahalgam attack, which killed 26 civilians.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" > After four days of drone and missile exchanges, both sides reached an understanding on May 10 to end hostilities.Friday’s visit also highlighted Mamdani’s historic election as New York City’s first South Asian and first Muslim mayor. He defeated Republican Curtis Sliwa and former New York Governor Andrew Cuomo, who ran as an independent with a last-minute endorsement from Trump.</p>
<p class="articleParagraph enarticleParagraph" >For Reprint Rights: timescontent.com</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gdip : International Relations | gpir : Politics/International Relations | gpol : Domestic Politics | gvote : Elections</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>asiaz : Asia | devgcoz : Emerging Market Countries | dvpcoz : Developing Economies | india : India | namz : North America | pakis : Pakistan | sasiaz : South Asia | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Bennett, Coleman & Co., Ltd.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document TOI0000020251122elbm0007k</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC68256020251122elbm00008"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Takeaways from the Trump-Mamdani White House meeting</b><div class="leadFields"><a href="javascript:void(0)">Al Araby Al Jadeed</a>, 07:15 PM, 21 November 2025, 943 words, (English)</div><div class="snippet ensnippet"> President Donald Trump hosted New York City Mayor-elect Zohran Mamdani at the White House on Friday for a meeting that took place without apparent conflict despite their radically different worldviews. Here are some takeaways from their ...</div>
<div>(Document WC68256020251122elbm00008)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC68256020251122elbm00001"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Mamdani reaffirms Gaza genocide stance in 'warm' Trump meeting</b><div class="leadFields"><a href="javascript:void(0)">Al Araby Al Jadeed</a>, 07:30 AM, 22 November 2025, 602 words, (English)</div><div class="snippet ensnippet"> While Trump and Mamdani sought to avoid thorny topics, the issue of Gaza received brief mention, with Mamdani reaffirming his stance on Israel&#39;s genocide.</div>
<div>(Document WC68256020251122elbm00001)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-PRTRIN0020251122elbm00ci1" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/prtrinLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>NATIONAL</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>This is how democracy should work, hope to see this in India: Tharoor lauds Trump-Mamdani meet</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>475 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Press Trust of India</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>PRTRIN</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. The Press Trust of India Limited. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >New Delhi, Nov 22 (PTI) Congress leader Shashi Tharoor on Saturday lauded the cordial meeting between US President Donald Trump and New York City Mayor-elect Zohran Mamdani, saying this is how democracy should work and hoped to see this happen in India.</p>
<p class="articleParagraph enarticleParagraph" >Seizing the opportunity, the BJP expressed hope that Leader of Opposition in the Lok Sabha Rahul Gandhi would get the message.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Reposting on X a video of the meeting between the US President and the New York City Mayor-elect, Tharoor said, "This is how democracy should work. Fight passionately for your point of view in elections, with no rhetorical holds barred. But once it's over, and the people have spoken, learn to cooperate with each other in the common interests of the nation you are both pledged to serve."</p>
<p class="articleParagraph enarticleParagraph" >"I would love to see more of this in India, and am trying to do my part," the Congress MP from Thiruvananthapuram said.</p>
<p class="articleParagraph enarticleParagraph" >Reacting to Tharoor's remarks, BJP spokesperson Shehzad Poonawalla was all praise of Tharoor for his remarks and hoped Rahul Gandhi would get the message.</p>
<p class="articleParagraph enarticleParagraph" >"Once again, Shashi Tharoor reminds Congress to put India first, not Parivar. To behave democratically and not like sore losers. But will Rahul Gandhi get the message? One more Fatwa loading against Shashi?" Poonawala posed in a post on X.</p>
<p class="articleParagraph enarticleParagraph" >After months of vitriolic attacks against each other during the New York City mayoral election, Trump and Mamdani adopted a mutually warm tone during their first meeting at the White House in Washington DC, with the US president terming it "very productive".</p>
<p class="articleParagraph enarticleParagraph" >Trump also expressed confidence that Mamdani "can do a very good job".</p>
<p class="articleParagraph enarticleParagraph" >"We've just had a great meeting, a really good, very productive meeting. We have one thing in common, we want this city of ours that we love to do very well.</p>
<p class="articleParagraph enarticleParagraph" >"I wanted to congratulate the Mayor. He really ran an incredible race against a lot of smart people, starting with the early primaries, and he beat them easily," Trump said in the Oval Office, as Mamdani stood next to him.</p>
<p class="articleParagraph enarticleParagraph" >When asked if he would feel comfortable living in New York City under a Mamdani administration, Trump responded emphatically. "Yeah, I would, especially after the meeting. Absolutely".</p>
<p class="articleParagraph enarticleParagraph" >He added that they agreed on "a lot more than I would have thought. I want him to do a great job, and we'll help him do a great job. He may have different views. I would feel very, very comfortable being in New York, and I think much more so after the meeting."</p>
<p class="articleParagraph enarticleParagraph" >Mamdani "appreciated" the meeting with Trump, also describing it as a "productive", one focused on a place of shared admiration and love, which is New York City.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>asiaz : Asia | devgcoz : Emerging Market Countries | dvpcoz : Developing Economies | india : India | namz : North America | nyc : New York City | sasiaz : South Asia | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Press Trust Of India Limited</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document PRTRIN0020251122elbm00ci1</td></tr></table><br/></div></div><br/><span></span><div id="article-NDTVIN0020251122elbm0010d" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/ndtvinLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Reviews</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Chatti In NYC Brings Kerala's Toddy Shop Culture To A Global Stage</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>908 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>08:06 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>NDTV</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NDTVIN</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright. 2025.  NDTV Convergence Ltd., New Delhi, India. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >There's a certain unbridled energy I experience each time I walk past Times Square in NYC. That energy moved up an extra notch on November 4 as trends from the city's keenly watched mayoral election started to play out on the big screens that New Yorkers like to call the 'Centre of the Universe'. That's not the only big change that New York City has witnessed in the 2020s. Indian restaurants are having their much-deserved and long-overdue moment in the world's unofficial restaurant capital. Restaurants that have demonstrated that Indian cuisine is way more than just chicken tikka masala and butter naan. Chatti by Regi Mathew, that's a short walk from Times Square, is the latest to join this fast-expanding list.</p>
<p class="articleParagraph enarticleParagraph" >
                        <span class="colorLinks">Latest and Breaking News on NDTV [https://c.ndtvimg.com/2025-11/srh3iv1_chatti_625x300_22_November_25.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350]</span>
                     </p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Photo Credit: Chatti</p>
<p class="articleParagraph enarticleParagraph" >It's no coincidence that it took Chef Regi Mathew to put Kerala's unique toddy show culture under the global spotlight. His Kappa Chakka Kandhari or KCK (that was recognised at the NDTV Food awards this year) in Chennai and Bengaluru has already become a fine showcase for authentic Kerala cuisine. I first met Chef Regi in the late 2000s when he walked me through the concept of a tapas bar (one of the first in India) that he launched in Chennai. He'd spent a long time in Spain studying local recipes, culinary styles and ingredients. Chef Regi briefly made the comparison with Spain's tapas bars and Kerala's toddy shops during that conversation. Except in Kerala, we call them 'touchings'. Delicious local produce from seafood to duck that plays out in small sharing plates, the perfect accompaniment to fresh toddy.</p>
<p class="articleParagraph enarticleParagraph" >It was Tiby Joseph, my schoolmate from Don Bosco Egmore in Chennai, who picked Chatti for our mini-batch reunion. Tiby is a NYC insider of sorts with roots in Kottayam, the very heart of Kerala's unique toddy shop culture. We had to wait a while to be seated; it wasn't just Malayalees or Indians who filled up Chatti on that Tuesday evening after the mayoral election. Chef Regi is proud of the perfect mix of diners that suggests Chatti's appeal transcends Indians in the US. Chatti takes its name from the traditional clay pot central to Kerala's toddy shops and homes.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Latest and Breaking News on NDTV [https://c.ndtvimg.com/2025-11/gd8r21ng_chatti_625x300_22_November_25.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Photo Credit: Chatti</p>
<p class="articleParagraph enarticleParagraph" >The contrast between Regi's upscale, Manhattan restaurant and the earthy toddy shops like Mullapanthal that I've visited in Kerala might seem stark, but there's a common thread. Kerala's toddy shops have long been social equalisers in a state that values equity and free expression. A space where people from all walks of life share a table and engage in conversation over toddy and touchings. It's almost the same in NYC, one of the world's most diverse cities, where Chatti's toddy and touchings offer the perfect glue for New Yorkers with diverse back stories.</p>
<p class="articleParagraph enarticleParagraph" >At the heart of toddy shop culture is a sense of community and sharing a meal and conversation. Chatti's menu is designed for sharing with an array of small plates and family-style dishes. You will find some of the quintessential toddy shop favourites like the duck mappas (a fragrant duck curry from the Kuttanadu region, cooked with coriander powder and coconut milk) and Pearl Spot Parcels or 'Karimeen Pollichathu' (Pearl Spot fish is grilled with shallots and tamarind masala and wrapped in banana leaf). There are also some delicious modern twists, like the Seafood Moilee Soup with bite-sized appams, the perfect start to an extended meal.</p>
<p class="articleParagraph enarticleParagraph" >The breads are among the highlights. There's everything from Nei-Pathiri (deep-fried rice bread from the Malabar region) and my favourite, the spongy vattayappam that is traditionally crafted with rice batter and toddy sap. Most regulars at KCK wrap up their meal with the restaurant's legendary cloud pudding. We're happy to report that this lighter-than-air version of tender coconut pudding has also travelled through the clouds to New York City.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">Latest and Breaking News on NDTV [https://c.ndtvimg.com/2025-11/njeqfbsc_chatti_625x300_22_November_25.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Photo Credit: Chatti</p>
<p class="articleParagraph enarticleParagraph" >It's not just the fresh toddy that makes the trip to NYC. Chatti's beverage menu includes craft cocktails that celebrate Kerala's culinary traditions. We dig the Malayali Old Fashioned, with bourbon, toasted coconut, jaggery caramel, cardamom vermouth and bitters; and the cleverly named Sam Bar, a vodka-based cocktail featuring clarified sambar, with curry leaf foam. Chatti's large bar is one of the design highlights of the restaurant, which is punctuated by earthy tones of green, grey, and copper, creating a warm and inviting atmosphere along with a showstopper laterite wall. Chatti is spread across multiple levels, and the intimate private dining room is one of our favourite spaces in the restaurant.</p>
<p class="articleParagraph enarticleParagraph" >As we wrapped up a meal packed with nostalgia, one of the locals at the next table asked if we had tried the restaurant's Claypot Fish Curry. Chatti doesn't temper down the spices or try and 'sanitise' flavours to appeal to locals in New York. Most dishes taste similar to KCK and also benefit from excellent local produce in NYC. It's that moment that made me realise that India's micro-cuisines are now global superstars with restaurants like Chatti providing the perfect springboard.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gfod : Food/Drink | glife : Living/Lifestyle</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>asiaz : Asia | chenna : Chennai | devgcoz : Emerging Market Countries | dvpcoz : Developing Economies | india : India | kerala : Kerala | namz : North America | nyc : New York City | sasiaz : South Asia | tamil : Tamil Nadu | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Reviews</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>NDTV Convergence Ltd</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NDTVIN0020251122elbm0010d</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC65230020251122elbm0000a"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  'You let us down!' Trump fans rebel against president over comments that 'betray the base'</b><div class="leadFields"><a href="javascript:void(0)">Raw Story</a>, 08:03 PM, 21 November 2025, 843 words,  David McAfee, (English)</div><div class="snippet ensnippet"> Donald Trump on Friday met with the man who was elected mayor of New York City, and concluded that despite previous attacks from both parties, Zohran Mamdani is a &quot;rational person.&quot; That provoked outrage with Trump&#39;s biggest fans.</div>
<div>(Document WC65230020251122elbm0000a)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC45307020251122elbm00003"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump lavishes praise on Mandani at White House meeting, says may move back to NewYork</b><div class="leadFields"><a href="javascript:void(0)">Ya Libnan</a>, 06:44 AM, 22 November 2025, 928 words, (English)</div><div class="snippet ensnippet"> Washington- After months of trading insults, U.S. President Donald Trump and incoming New York City mayor Zohran Mamdani smiled at each other, swapped compliments and pledged to collaborate on tackling crime and affordability in the ...</div>
<div>(Document WC45307020251122elbm00003)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-NYDN000020251122elbm00015" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nydnLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Main</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Don does a 180: instead of ripping Zoh, vows aid Name-calling and threats set aside after meet at White House; now, it’s a bizarre bromance</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Chris Sommerfeldt </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1225 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>New York Daily News</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NYDN</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>CS.5</td></tr><tr><td align="right" valign="top" class="index"><b>VOL</b>&nbsp;</td><td>ISSN:2692-1251</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© 2025 Daily News, New York.  Provided by ProQuest Information and Learning.  All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >During an extraordinarily cordial meeting at the White House Friday, President Trump showered NYC Mayor-elect Zohran Mamdani with compliments and vowed to be “a big help” to his incoming administration — sparking perhaps the most improbable bromance in American politics.</p>
<p class="articleParagraph enarticleParagraph" >The sympatico tone was a shocking turnaround for Trump, who has for months smeared Mamdani as “a communist” and threatened to slash federal funding for New York, flood the city with ICE agents and take other punitive steps in response to the incoming mayor’s election. Trump has even toyed with the idea of deporting Mamdani, a naturalized U.S. citizen born in Uganda.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >But speaking to reporters in the Oval Office on Friday afternoon after a more than hour-long sitdown with Mamdani, Trump did not reiterate his deportation musings, said he’s no longer looking to make good on the funding threat and admitted he was “actually surprised” by how “rational” the soon-to-be mayor is and how much they agree on.</p>
<p class="articleParagraph enarticleParagraph" >The city receives nearly $8 billion in federal funding every year for a variety of programs. Trump’s reversal on that front is a gift to Mamdani as he prepares to take office Jan. 1 with hopes of enacting an ambitious affordability agenda.</p>
<p class="articleParagraph enarticleParagraph" >“We’re going to be helping him to make everybody’s dream come true, having a strong and very safe New York,” the Queens-born president, seated behind the Resolute Desk, told reporters as Mamdani stood next to him following what marked their first-ever face-to-face confab.</p>
<p class="articleParagraph enarticleParagraph" >“I’ll be cheering for him,” Trump said.</p>
<p class="articleParagraph enarticleParagraph" >Both men told reporters their discussion revolved mostly around the issue of making New York City more affordable, which Mamdani placed at the heart of his mayoral campaign.</p>
<p class="articleParagraph enarticleParagraph" >“Some of his ideas really are the same ideas that I have,” Trump said.</p>
<p class="articleParagraph enarticleParagraph" >“I feel very confident that he can do a very good job,” Trump continued before shaking Mamdani’s hand and telling reporters he’d be “very, very comfortable” with the idea of living in the city under the mayor’s new administration.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, a democratic socialist who has accused Trump of holding fascist leanings, returned the favor by suggesting he and the Republican commander-in-chief could re-create what President Franklin D. Roosevelt and Mayor Fiorello LaGuardia did in implementing “New Deal” reforms in the city in the 1930s.</p>
<p class="articleParagraph enarticleParagraph" >“Thinking about what it can look like when the federal government and New York City government work together to deliver on affordability, it can be transformative,” said Mamdani.</p>
<p class="articleParagraph enarticleParagraph" >In an especially remarkable moment, Trump interrupted Mamdani after a reporter asked the mayor-elect if he still considers the president “a fascist.”</p>
<p class="articleParagraph enarticleParagraph" >“That’s okay, you can just say yes,” Trump butted in as Mamdani began answering the question. “It’s easier than explaining it,” Trump added with a chuckle while patting Mamdani on the arm.</p>
<p class="articleParagraph enarticleParagraph" >“Okay, alright … yes,” Mamdani then told the reporter while flashing a smile.</p>
<p class="articleParagraph enarticleParagraph" >City Comptroller Brad Lander, a progressive Democrat and close ally of Mamdani, remarked in a real-time post on X: “Pretty sure Zohran just charmed Donald Trump into agreeing that he’s a fascist.”</p>
<p class="articleParagraph enarticleParagraph" >Trump played similarly nice when asked if he’s offended by the fact that Mamdani has labeled him a “despot.”</p>
<p class="articleParagraph enarticleParagraph" >“I’ve been called much worse than a despot,” he said, “so it’s not that insulting.”</p>
<p class="articleParagraph enarticleParagraph" >The closest Trump got to knocking Mamdani came when he was asked if still</p>
<p class="articleParagraph enarticleParagraph" >considers him “a communist.”</p>
<p class="articleParagraph enarticleParagraph" >“He’s got views that are a little out there,” he said without elaborating before adding: “He’s going to change also … I change a lot, I changed a lot from when I first came into office.”</p>
<p class="articleParagraph enarticleParagraph" >Even on the issue of immigration enforcement, Trump staked out agreement despite Mamdani having repeatedly condemned the president’s “mass deportation” efforts in New York and arguing that ICE has become a rogue agency under the president’s leadership.</p>
<p class="articleParagraph enarticleParagraph" >On top of threats of federal funding cuts, Trump has for months said he will deploy thousands of ICE agents and U.S. troops to the city once Mamdani takes office to “clean up” the five boroughs. The commander in chief did not repeat that threat Friday and said he and Mamdani agree on a need to deport immigrants who commit serious crimes, the mayor-elect noting the city can under local sanctuary laws cooperate with ICE on deportation cases involving individuals convicted of various offenses.</p>
<p class="articleParagraph enarticleParagraph" >“We’re going to work together, we’re going to make sure that if they’re horrible people there, we want to get them out, I think he wants to get them out, maybe more than I do,” Trump said.</p>
<p class="articleParagraph enarticleParagraph" >On yet another lightning rod issue — the war in Gaza — Trump did not object as Mamdani said Israel is committing a “genocide” against Palestinians funded by “our government.” Previously, Trump has accused Mamdani, the first Muslim elected New York City mayor, of fostering antisemitism by criticizing Israel.</p>
<p class="articleParagraph enarticleParagraph" >It remained to be seen Friday night how a more genial footing between Trump and Mamdani might play with their respective bases of support — or if the making nice nice will last.</p>
<p class="articleParagraph enarticleParagraph" >Trump’s hard-right supporters have pushed for arresting or otherwise punishing Mamdani over what they see as his “radical left-wing agenda.” Meantime, Mamdani can run the risk of being seen as soft on Trump by his supporters, who voted for the mayor-elect in part because of his commitment to fighting the president.</p>
<p class="articleParagraph enarticleParagraph" >According to a Mamdani transition team official, their meeting was also attended by his incoming chief of staff Elle Bisgaard-Church, who is, like the mayor-elect, a dues-paying member of the Democratic Socialists of America.</p>
<p class="articleParagraph enarticleParagraph" >On affordability, their meeting focused on how to drive down the cost of groceries and build more housing, both men said. They also talked about public safety, and Trump praised Mamdani for retaining <span class="companylink">NYPD</span> Commissioner Jessica Tisch at the helm of the police department, calling her a “great” pick who’s a “a good friend of some of the people in my family.”</p>
<p class="articleParagraph enarticleParagraph" >“He wants to see no crime, he wants to see housing being built, he wants to see rents coming down — all things that I agree with,” Trump said.</p>
<p class="articleParagraph enarticleParagraph" >The strange political bedfellows didn’t get into a lot of particulars onhow exactly Trump’s administration will help advance Mamdani’s agenda, which centers on promises to expand subsidized childcare in the city, freeze rent for rent-stabilized tenants, make public buses free and launch city-run grocery stores.</p>
<p class="articleParagraph enarticleParagraph" >They did delve into some specifics on the issue of utility costs, with Trump agreeing with Mamdani that <span class="companylink">Con Edison</span>, New York’s main power supplier, should lower their electricity rates.</p>
<p class="articleParagraph enarticleParagraph" >“We’ve gotten fuel prices way down, but it hasn’t shown up in <span class="companylink">Con Edison</span>, and we’re going to have to talk to them. We’re sending them fuel at a much lower price than it was a year ago, which is true, we have to get <span class="companylink">Con Edison</span> to start lowering the rates,” Trump said.</p>
<p class="articleParagraph enarticleParagraph" >That prompted Mamdani to chime in.</p>
<p class="articleParagraph enarticleParagraph" >“Absolutely,” he said.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IN</b>&nbsp;</td><td><br/>i1 : Energy | i16 : Electricity/Gas Utilities | i16101 : Electric Power Generation | ieutil : Electric Utilities | iutil : Utilities</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>c13 : Regulation/Government Policy | c341 : Government Aid/Grants | ccat : Corporate/Industrial News | e21 : Government Finance | e211 : Government Budget/Taxation | ecat : Economic News | gcat : Political/General News | gcom : Society/Community | gcrim : Crime/Legal Action | gimm : Human Migration | gpir : Politics/International Relations | gpol : Domestic Politics | greg : Regional Politics | gvote : Elections | ncat : Content Types | nfact : Factiva Filters | nfcpin : C&E Industry News Filter</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>asiaz : Asia | israel : Israel | meastz : Middle East | medz : Mediterranean Countries | namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>News | Newspapers | Tribune Publishing Company, LLC</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Tribune Interactive, LLC.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NYDN000020251122elbm00015</td></tr></table><br/></div></div><br/><span></span><div id="article-MONECT0020251122elbm000ru" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/monectLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>world</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>‘I did 8 peace deals’: Trump again touts role in India-Pakistan ceasefire during Mamdani meet</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>306 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Moneycontrol.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>MONECT</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. <span class="colorLinks">www.moneycontrol.com [http://www.moneycontrol.com]</span>
               </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The comments came during his meeting with New York City Mayor-elect Zohran Mamdani at the White House</p>
<p class="articleParagraph enarticleParagraph" >US President Donald Trump on Friday again claimed credit for helping reduce tensions between India and Pakistan -- a statement he has now made more than 60 times.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The comments came during his meeting with New York City Mayor-elect Zohran Mamdani at the White House -- marking Mamdani’s first formal interaction with the president after his landmark election win.</p>
<p class="articleParagraph enarticleParagraph" >“I did eight peace deals of countries, including India and Pakistan,” Trump reiterated, as per <span class="companylink">ANI</span>, referring to the May standoff between the two countries.</p>
<p class="articleParagraph enarticleParagraph" >His remarks were in line with similar statements he has made throughout the past few months. Earlier this week, he claimed he threatened both India and Pakistan with 350 per cent tariffs if they did not halt hostilities, insisting he played a decisive role in ending the confrontation between the two nuclear-armed neighbours.</p>
<p class="articleParagraph enarticleParagraph" >India has repeatedly dismissed suggestions of any third-party involvement.</p>
<p class="articleParagraph enarticleParagraph" >On May 7, New Delhi launched Operation Sindoor, striking terror infrastructure in Pakistan and Pakistan-occupied Kashmir in response to the April 22 Pahalgam attack that left 26 civilians dead. After four days of intense drone and missile exchanges, both countries reached an understanding on May 10 to halt the hostilities.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani's appearance at the White House came soon after his historic victory as Mayor of New York City, which made him the first South Asian and first Muslim to lead the largest city in the United States.</p>
<p class="articleParagraph enarticleParagraph" >Widely viewed as the favourite throughout the campaign, he defeated Republican Curtis Sliwa and former New York Governor Andrew Cuomo, who mounted an independent run and received a last-minute endorsement from Trump hours.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gdip : International Relations | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>asiaz : Asia | devgcoz : Emerging Market Countries | dvpcoz : Developing Economies | india : India | namz : North America | nyc : New York City | pakis : Pakistan | sasiaz : South Asia | usa : United States | usdc : Washington DC | use : Northeast U.S. | usny : New York State | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>world</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Network18 Media & Investments Ltd.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document MONECT0020251122elbm000ru</td></tr></table><br/></div></div><br/><span></span><div id="article-NYDN000020251122elbm00008" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nydnLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Opinion</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>NYC’s matching funds fueled Mamdani’s success</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>789 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>New York Daily News</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NYDN</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>CS.20</td></tr><tr><td align="right" valign="top" class="index"><b>VOL</b>&nbsp;</td><td>ISSN:2692-1251</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© 2025 Daily News, New York.  Provided by ProQuest Information and Learning.  All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Zohran Mamdani’s insurgent win has spawned endless political analysis. But so far, the punditry has missed a crucial factor that made his unlikely bid for mayor possible in the first place: New York City’s longstanding, public matching funds program, one of the last gasps in a post <span class="companylink">Citizens United</span> world against the influence of big money in politics. The program has been widely recognized as a model for the country.</p>
<p class="articleParagraph enarticleParagraph" >Nearly 40 years after the program’s inception, mayoral candidates can now receive $8 for every $1 donated by individual New Yorkers, up to $250 per donor. The matching ratio allowed Mamdani to hit the spending limit in both the primary and general elections — freeing the candidate to campaign for votes instead of dollars. In what other system would a candidate be able to tell supporters not to donate any more money to his campaign?</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Former Gov. Andrew Cuomo, Republican Curtis Sliwa, and outgoing Mayor Adams also chose to participate in the matching funds program. Their participation provided an incentive for their campaigns to seek out small dollar donors, thus pushing all four campaigns to make their case to a broader audience, not just to moneyed interests. The major contenders, Mamdani and Cuomo, had 52,560 small donations and 7,772 respectively.</p>
<p class="articleParagraph enarticleParagraph" >In the end, the candidates raised $6.7 million (Adams), $6 million (Cuomo), $4 million (Mamdani), and $1.5 million (Sliwa) in private donations. In turn, they received about $13.1 million (Mamdani), $8 million (Cuomo), $5.3 million (Sliwa), and none (Adams) in public matching funds. The discrepancy between private donations and public funds comes down to different types of donations: donations under $250 from New York City residents are eligible for public match, whereas larger donations and out-of-towners are not.</p>
<p class="articleParagraph enarticleParagraph" >The final fundraising figures also tell a story about accountability and transparency. While Adams raised plenty of private donations, the Campaign Finance Board repeatedly found his campaign was not eligible for matching funds on the grounds of 1) failure to submit adequate documentation and 2) reason to believe the campaign broke the law. No candidate is entitled to public funds; they must all follow the rules. In the end, Adams dropped out of the mayoral race after the deadline to be removed from the ballot.</p>
<p class="articleParagraph enarticleParagraph" >For candidates who do heed the program’s rules, it can be transformational. Matching funds yielded the resources Mamdani needed to attain his high visibility and win the primary and then similarly set him up to become known widely enough to propel him to win the general election. Even with a generationally popular candidate, both these successes were by no means predictable.</p>
<p class="articleParagraph enarticleParagraph" >While matching funds provide an important counterbalance to big money, “independent” spending remains a factor. Both Mamdani and Cuomo benefitted from super PAC spending, but that spending strongly favored Cuomo by millions of dollars.</p>
<p class="articleParagraph enarticleParagraph" >Still, despite an influx of spending in support of Cuomo from billionaire backers like former Mayor Mike Bloomberg and hedge fund manager Bill Ackman, as well as businesses like <span class="companylink">DoorDash</span> and <span class="companylink">Airbnb</span>, Mamdani was able to raise enough money — almost seven times more — from small donors and millions more in public funding — to spend competitively on his campaign through matching funds.</p>
<p class="articleParagraph enarticleParagraph" >It is very possible, even likely, that Mamdani and his grassroots movement would have lost against so much big money, were it not for the public funds he received.</p>
<p class="articleParagraph enarticleParagraph" >The result in this election was that, while moneyed interests were in play, New Yorkers with fewer dollars to spare still had a reason to participate in the lead-up to Election Day, armed with the knowledge that their small donations could have a big impact. Past city elections demonstrate that New York’s program has increased the breadth both of donors and of candidates, by making it easier for candidates who are not connected to wealthy donors to run for office and by increasing civic participation.</p>
<p class="articleParagraph enarticleParagraph" >Cuomo, aided by outsized super PAC spending and by far greater name recognition, could not overcome the power of thousands of small donors whose contributions yielded millions of dollars in public matching funds. This election, in which Mamdani received more than five times as many small contributions as did Cuomo, reflects these phenomena.</p>
<p class="articleParagraph enarticleParagraph" >There are many factors that go into a winning campaign; individual candidate quality, policy positions, and messaging, to name a few. But money is a powerful tool that can squash insurgent candidates quickly. The matching funds system not only gives them a fighting chance — it even makes it possible for them to win.</p>
<p class="articleParagraph enarticleParagraph" >Gordon was the founding executive director of the New York City Campaign Finance Board from 1988 to 2006.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>CO</b>&nbsp;</td><td><br/>ctzutd : Citizens United</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gcns : National/Public Security | gcrim : Crime/Legal Action | gpir : Politics/International Relations | gpol : Domestic Politics | grisk : Risk News | gterr : Terrorism | gvote : Elections | ncat : Content Types | nedc : Commentaries/Opinions | nfact : Factiva Filters | nfcpex : C&E Executive News Filter</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>News | Newspapers | Tribune Publishing Company, LLC</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Tribune Interactive, LLC.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NYDN000020251122elbm00008</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC42085020251122elbm002gy"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump’s childhood home hits market for $2.3M after $500K renovation</b><div class="leadFields"><a href="javascript:void(0)">FOXNews.com</a>, 07:15 AM, 22 November 2025, 495 words, (English)</div><div class="snippet ensnippet"> Quotes displayed in real-time or delayed by at least 15 minutes. Market data provided by Factset. Powered and implemented by FactSet Digital Solutions. Legal Statement.</div>
<div>(Document WC42085020251122elbm002gy)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC50690020251122elbm00003"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Wait. Whaaat?!: Marjorie Taylor Greene Quits Congress – Trump Lavishes Praise on Mamdani | WATCH</b><div class="leadFields"><a href="javascript:void(0)">EURweb</a>, 02:08 AM, 22 November 2025, 840 words,  Fisher Jack, (English)</div><div class="snippet ensnippet"> *Welp! We didn’t have either of these situations on our bingo card. Rep. Marjorie Taylor Greene is stepping down from Congress after a bitter feud with Donald Trump.</div>
<div>(Document WC50690020251122elbm00003)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC82569020251122elbm0000x"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Election Over, Feud Over! Donald Trump Meets 'Communist Lunatic' Zohran Mamdani For First Time After Victory - What Does It Mean?</b><div class="leadFields"><a href="javascript:void(0)">Zee News (India)</a>, 09:33 PM, 21 November 2025, 516 words,  Zee Media Bureau, (English)</div><div class="snippet ensnippet"> Trump and Mamdani White House Meeting: They called each other names. They hurled insults. They threatened destruction. During the New York City mayoral election, US President Donald Trump branded Zohran Mamdani a &quot;100% communist lunatic&quot; ...</div>
<div>(Document WC82569020251122elbm0000x)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC45242020251122elbm0000j"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Trump brushes off ‘fascist’ jab as he and Mamdani debate Israel and Gaza</b><div class="leadFields"><a href="javascript:void(0)">Yedioth Ahronoth</a>, 07:01 AM, 22 November 2025, 650 words,  Dennis Bihler, (English)</div><div class="snippet ensnippet"> In their first meeting since Zohran Mamdani’s surprise election as New York City’s next mayor, U.S. President Donald Trump and Mamdani held an unexpectedly warm joint appearance at the White House on Friday, where Middle East policy, ...</div>
<div>(Document WC45242020251122elbm0000j)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC45242020251122elbm0000v"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  North American Jews confront rising antisemitism</b><div class="leadFields"><a href="javascript:void(0)">Yedioth Ahronoth</a>, 07:01 AM, 22 November 2025, 1099 words, (English)</div><div class="snippet ensnippet"> More than 2,000 Jewish leaders from across North America, the largest number since before the pandemic, gathered this week in Washington for the annual General Assembly of the Jewish Federations of North America (JFNA). This year’s GA was ...</div>
<div>(Document WC45242020251122elbm0000v)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-LBA0000020251122elbm00a6q" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/lbaLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>REUTERS NEWS SCHEDULE AT 11:00 a.m. GMT/ 6:00 a.m. ET</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>841 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>06:00 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Reuters News</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>LBA</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 Thomson Reuters. All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Here are the top stories and upcoming coverage plans for Reuters text service as of 11:00 a.m. GMT/ 6:00 a.m. ET. For a full schedule of news and events, go to our editorial calendar on Reuters Connect.</p>
<p class="articleParagraph enarticleParagraph" >TOP STORIES</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >GLOBAL</p>
<p class="articleParagraph enarticleParagraph" >CHINA-JAPAN</p>
<p class="articleParagraph enarticleParagraph" >China takes spat with Japan over Taiwan to <span class="companylink">UN</span>, vows to defend itself</p>
<p class="articleParagraph enarticleParagraph" >BEIJING, Nov 22 (Reuters) - China has taken its widening spat with Japan to the United Nations, accusing Tokyo of threatening "an armed intervention" over Taiwan and vowing to defend itself in its strongest language yet in the two-week-old dispute.</p>
<p class="articleParagraph enarticleParagraph" >USA-TRUMP-VENEZUELA-AIRLINES</p>
<p class="articleParagraph enarticleParagraph" >US warns airlines of potential hazards when flying over Venezuela</p>
<p class="articleParagraph enarticleParagraph" >WASHINGTON, Nov 21 (Reuters) - The <span class="companylink">U.S. Federal Aviation Administration</span> warned major airlines on Friday of a "potentially hazardous situation" when flying over Venezuela and urged them to exercise caution.</p>
<p class="articleParagraph enarticleParagraph" >U.S.</p>
<p class="articleParagraph enarticleParagraph" >USA-TRUMP-GREENE</p>
<p class="articleParagraph enarticleParagraph" >MAGA favorite Marjorie Taylor Greene to resign after split with Trump</p>
<p class="articleParagraph enarticleParagraph" >WASHINGTON, Nov 21 (Reuters) - Saying she refused to be a “battered wife,” U.S. Representative Marjorie Taylor Greene announced on Friday she was resigning from the House of Representatives in the wake of a dramatic falling out with President Donald Trump.</p>
<p class="articleParagraph enarticleParagraph" >USA-TRUMP-MAMDANI</p>
<p class="articleParagraph enarticleParagraph" >Trump lavishes praise on New York's mayor-elect Mamdani at warm White House meeting</p>
<p class="articleParagraph enarticleParagraph" >WASHINGTON, Nov 21 (Reuters) - After months of trading insults, U.S. President Donald Trump and incoming New York City mayor Zohran Mamdani smiled at each other, swapped compliments and pledged to collaborate on tackling crime and affordability in the nation's biggest city at an unexpectedly friendly meeting at the White House on Friday.</p>
<p class="articleParagraph enarticleParagraph" >BUSINESS</p>
<p class="articleParagraph enarticleParagraph" >LILLY-STOCKS</p>
<p class="articleParagraph enarticleParagraph" >Lilly becomes first drugmaker to hit $1 trillion valuation on weight-loss demand</p>
<p class="articleParagraph enarticleParagraph" >Nov 21 (Reuters) - <span class="companylink">Eli Lilly</span> (LLY.N), hit $1 trillion in market value on Friday, making it the first drugmaker to enter the exclusive club dominated by tech giants and underscoring its rise as a weight-loss powerhouse.</p>
<p class="articleParagraph enarticleParagraph" >USA-ECONOMY-<span class="companylink">PMI</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >US manufacturing slows in November as high prices curb demand</p>
<p class="articleParagraph enarticleParagraph" >WASHINGTON, Nov 21 (Reuters) - U.S. factory activity slowed to a four-month low in November as higher prices because of tariffs on imports restrained demand, leading to a piling up of unsold goods that could hinder growth in the overall economy.</p>
<p class="articleParagraph enarticleParagraph" >ENTERTAINMENT</p>
<p class="articleParagraph enarticleParagraph" >MUSIC-MEGHAN-TRAINOR</p>
<p class="articleParagraph enarticleParagraph" >Meghan Trainor turns cyberbullying into new single 'Still Don't Care'</p>
<p class="articleParagraph enarticleParagraph" >LOS ANGELES, Nov 21 (Reuters) - Singer-songwriter Meghan Trainor traversed new terrain with her song "Still Don't Care," which explores her experiences being cyberbullied on social media. "Still Don't Care," part of her upcoming "Toy with Me" album, directly addresses the online backlash the "All About That Bass" singer has received about her weight loss.</p>
<p class="articleParagraph enarticleParagraph" >PEOPLE-ORNELLA-VANONI</p>
<p class="articleParagraph enarticleParagraph" >Ornella Vanoni, Italian singer made world-famous by 'Ocean's Twelve', dies at 91</p>
<p class="articleParagraph enarticleParagraph" >MILAN, Nov 21 (Reuters) - Four steps separated Ornella Vanoni from the life she craved: the four steps leading up to the stage of Milan's Piccolo Teatro.</p>
<p class="articleParagraph enarticleParagraph" >SPORTS</p>
<p class="articleParagraph enarticleParagraph" >MOTOR-F1-LASVEGAS</p>
<p class="articleParagraph enarticleParagraph" >F1 leader Norris on pole in wet Las Vegas with Piastri fifth</p>
<p class="articleParagraph enarticleParagraph" >LAS VEGAS, Nov 21 (Reuters) - Formula One championship leader Lando Norris swept to a stunning pole position for the Las Vegas Grand Prix in a wet and slippery qualifying on Friday with McLaren teammate and closest title rival Oscar Piastri only fifth.</p>
<p class="articleParagraph enarticleParagraph" >SPORT-BOXING-JAKE-PAUL</p>
<p class="articleParagraph enarticleParagraph" >Jake Paul 'ready to die' to upset Anthony Joshua</p>
<p class="articleParagraph enarticleParagraph" >November 22 - Jake Paul says he's willing to go where most fighters won't. At the first faceoff in Miami, the size gap was glaring with the 6-foot-6 Anthony Joshua towering over the 6-foot-1 Paul, but the message from the smaller man was louder.</p>
<p class="articleParagraph enarticleParagraph" >UPCOMING</p>
<p class="articleParagraph enarticleParagraph" >ARTS / CULTURE / ENTERTAINMENT</p>
<p class="articleParagraph enarticleParagraph" >AWARDS-GOLDENHORSE/ (PIX) (TV) </p>
<p class="articleParagraph enarticleParagraph" >Taiwan holds Golden Horse awards in star-studded ceremony</p>
<p class="articleParagraph enarticleParagraph" >Taiwan hosts the Golden Horse awards, the Chinese-speaking world's version of the Oscars, in a star-studded ceremony in Taipei</p>
<p class="articleParagraph enarticleParagraph" >22 Nov 10:00 ET / 15:00 GMT</p>
<p class="articleParagraph enarticleParagraph" >BUSINESS / ECONOMICS</p>
<p class="articleParagraph enarticleParagraph" >USA-FED/COLLINS </p>
<p class="articleParagraph enarticleParagraph" >Federal Reserve's Collins gives closing remarks at <span class="companylink">Boston Fed</span> economic conference</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="companylink">Federal Reserve Bank of Boston</span> President Susan Collins gives brief, informal closing remarks before the "U.S. Economy in a Changing Landscape" conference at the <span class="companylink">Federal Reserve Bank of Boston</span>.</p>
<p class="articleParagraph enarticleParagraph" >22 Nov 11:55 ET / 16:55 GMT</p>
<p class="articleParagraph enarticleParagraph" >CHINA-TONGA/ </p>
<p class="articleParagraph enarticleParagraph" >King of Tonga visits China</p>
<p class="articleParagraph enarticleParagraph" >At the invitation of Chinese President Xi Jinping, King Tupou VI of Tonga will pay a state visit to China from November 21 to 27.</p>
<p class="articleParagraph enarticleParagraph" >23 Nov</p>
<p class="articleParagraph enarticleParagraph" >POLITICS / INTERNATIONAL AFFAIRS</p>
<p class="articleParagraph enarticleParagraph" >BOSNIA-ELECTION/SERBS (PIX) (TV) </p>
<p class="articleParagraph enarticleParagraph" >Bosnia's Serb Republic hold an early presidential election</p>
<p class="articleParagraph enarticleParagraph" >Bosnia's autonomous Serb Republic holds an early presidential election called by the state election authorities after Milorad Dodik, the region's former president, was banned from holding a political office for six years for defying rulings of international envoy and constitutional court, and removed from job.</p>
<p class="articleParagraph enarticleParagraph" >23 Nov </p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RF</b>&nbsp;</td><td><br/>Released: 2025-11-22T12:00:04.000Z </td></tr>
<tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gdip : International Relations | gfitn : Physical/Mental Fitness | ghea : Health | glife : Living/Lifestyle | gpir : Politics/International Relations | gwelss : Weight Management | nadv : Advisories | ncal : Calendar of Events | ncat : Content Types | nfact : Factiva Filters | nfce : C&E Exclusion Filter | niwe : IWE Filter | nrgn : Routine General News</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>apacz : Asia Pacific | asiaz : Asia | boston : Boston | china : China | chinaz : Greater China | devgcoz : Emerging Market Countries | dvpcoz : Developing Economies | easiaz : East Asia | lvegas : Las Vegas | namz : North America | taiwan : Taiwan | usa : United States | use : Northeast U.S. | usma : Massachusetts | usnew : New England | usnv : Nevada | usw : Western U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPC</b>&nbsp;</td><td><br/>DED | LANG:en | SERVICE:ABX | SERVICE:AFA | SERVICE:BNX | SERVICE:CSA | SERVICE:FUN | SERVICE:GNS | SERVICE:LBY | SERVICE:RAST | SERVICE:REULB | SERVICE:REUVF | SERVICE:RLF | SERVICE:RVES | SERVICE:RWS | SERVICE:RWSA | SERVICE:UCDPTEST</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Previews | REUTERS | REUTERS-SCHEDULE/ | Schedule | SCHEDULE</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Reuters News & Media Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document LBA0000020251122elbm00a6q</td></tr></table><br/></div></div><br/><span></span><div id="article-NYTFEED020251122elbm0025z" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nytfeedLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>CLM</b>&nbsp;</td><td>Maureen Dowd</td></tr>
<tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Opinion</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Piggy Gets Polite</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Maureen Dowd </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1231 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>07:00 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>nytimes.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NYTFEED</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. The New York Times Company. All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Step by slimy step, President Trump has made us numb to his crudeness and cruelty.</p>
<p class="articleParagraph enarticleParagraph" >The solipsistic Trump, with the parasitic tech emperors and the internet itself, is degrading American values, making honor and integrity seem anachronistic.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Still, some moments shock as beyond the pale. Whatever the pale is anymore.</p>
<p class="articleParagraph enarticleParagraph" >On Air Force One recently, Trump cut off Catherine Lucey, a Bloomberg News journalist pressing him about the release of Epstein files that could further implicate Trump in the lurid mess. Stabbing his finger at her face, the President of the United States snapped at Lucey: “Quiet! Quiet, piggy.”</p>
<p class="articleParagraph enarticleParagraph" >The press secretary, Karoline Leavitt, later preposterously explained, “The president being frank and open and honest to your faces, rather than hiding behind your backs, is, frankly, a lot more respectful than what you saw in the last administration.”</p>
<p class="articleParagraph enarticleParagraph" >It was nauseating, if not surprising. Trump loves to call people who annoy him “pigs” and “dogs,” and in the case of his inamorata Stormy Daniels, “horseface.”</p>
<p class="articleParagraph enarticleParagraph" >It was misogynistic, but Trump bullies both men and women, attacking their looks and character and hurling nasty, intensely personal epithets and nicknames. He mocked Chris Christie, <span class="colorLinks">once an ally [https://www.nytimes.com/2023/06/06/us/politics/christie-trump-friendship.html]</span>, as “a fat pig,” “a slob” and “sloppy.”</p>
<p class="articleParagraph enarticleParagraph" >When I interviewed him decades ago in his more appropriate incarnation as a flashy developer hogging attention in New York, he would rate the looks of supermodels and actresses, dropping snap judgments like, “Sadly, Heidi Klum is no longer a 10.” Sometimes, he sent me pictures of female journalists from newspapers, commenting with a Sharpie scrawl on who he thought looked good or bad.</p>
<p class="articleParagraph enarticleParagraph" >Politicians were never insult comics before Trump. But in the 2016 primaries he learned sneering deflected from substance.</p>
<p class="articleParagraph enarticleParagraph" >Trump followed up his “Quiet, piggy” moment by berating another female journalist, Mary Bruce of ABC News, who asked Saudi Arabia’s crown prince, Mohammed bin Salman, during his appearance with the president, about his culpability in the dismemberment of the <span class="companylink">Washington Post</span> columnist Jamal Khashoggi. U.S. intelligence concluded the prince gave the order.</p>
<p class="articleParagraph enarticleParagraph" >“You don’t have to embarrass our guest by asking a question like that,” Trump chided Bruce. When she later asked why Trump was waiting for Congress to release the Epstein files when he could do it unilaterally, he called her question “a horrible, insubordinate, and just a terrible question.” He added that Brendan Carr, the chairman of the F.C.C., should look into revoking ABC’s broadcast license.</p>
<p class="articleParagraph enarticleParagraph" >Trump even defamed Khashoggi, saying that a lot of people didn’t like him and noting cavalierly that “things happen.”</p>
<p class="articleParagraph enarticleParagraph" >Yes, Things Happen when you have no morals and your family is doing lucrative business deals with the Saudis.</p>
<p class="articleParagraph enarticleParagraph" >By contrast, Trump was his most charming self on Friday in his “fascist vs. socialist” meeting with Mayor-elect Zohran Mamdani of New York. He had blasted Mamdani earlier as a “Communist” and “JEW HATER” and threatened to withhold federal funding for New York and send in troops. But by the end of their Oval news conference, the two were so lovey-dovey, a Fox News anchor warned that JD Vance might have to move over for Mamdani. And Trump, who once warned that wealthy New Yorkers and businesses would flee if the democratic socialist were elected, dramatically flipped, saying he would feel very comfortable moving back to Gotham under this mayor.</p>
<p class="articleParagraph enarticleParagraph" >(“It was a Great Honor meeting Zohran Mamdani, the new Mayor of New York City!” Trump <span class="colorLinks">gushed [https://truthsocial.com/@realDonaldTrump/posts/115590382865392804]</span> in a bromance-y Truth Social post featuring pictures of the pair on a colonnade and posing in front of F.D.R.’s portrait.)</p>
<p class="articleParagraph enarticleParagraph" >It just proved that Trump admires charismatic winners more than he cares about ideology — or consistency. Mamdani was prepared, focusing on their common ground while flattering Trump by noting his election statistics and hometown roots, and avoiding Dear Leader fawning. He strategically embraced Trump as he touted the affordability issue, which the billionaire president loved. Seeing Americans restive at his fixation on foreign conflicts, Trump is feigning a newfound interest in grocery prices.</p>
<p class="articleParagraph enarticleParagraph" >The president was so taken with Mamdani, he even jovially told him, in response to a Fox News reporter’s question, to go ahead and repeat his campaign claim that Trump is “a fascist.” The president also defended Mamdani from the incendiary falsehood of Elise Stefanik, the Republican who’s running for governor of New York, that the Muslim mayor-elect is a “jihadist.”</p>
<p class="articleParagraph enarticleParagraph" >Stefanik, a Trump henchwoman, broke away from the president on this issue, doubling down and posting Friday evening that Mamdani is “Kathy Hochul’s jihadist.”</p>
<p class="articleParagraph enarticleParagraph" >Unfortunately, we don’t get to see this genial Trump very much these days. He’s mean when he’s cornered, like the snapping turtle I had as a pet when I was a child. Republicans got creamed in the recent elections. To extend the porcine metaphor, Trump’s <span class="colorLinks">polls are dropping [https://www.nytimes.com/interactive/polls/donald-trump-approval-rating-polls.html]</span>, to use a Dave Barry phrase, “like a pig out of a helicopter.”</p>
<p class="articleParagraph enarticleParagraph" >The president, ordinarily a master at recasting reality, had to give up his ludicrous attempt to paint the Epstein files as a Democratic hoax. Labeling Marjorie Taylor Greene, his former acolyte who now says she identifies with the Epstein victims, a “traitor” backfired.</p>
<p class="articleParagraph enarticleParagraph" >Friday night Greene <span class="colorLinks">announced [https://x.com/mtgreenee/status/1992037226415554642?s=46&t=wDkAeEio1xA8FChQOuHP3g]</span> in a social media post that she was leaving Congress and said she didn’t want to face a “hateful” primary stirred by Trump.</p>
<p class="articleParagraph enarticleParagraph" >“Standing up for American women who were raped at 14, trafficked and used by rich powerful men,” she wrote, “should not result in me being called a traitor and threatened by the President of the United States, whom I fought for.”</p>
<p class="articleParagraph enarticleParagraph" >She added, “I refuse to be a ‘battered wife’ hoping it all goes away and gets better.”</p>
<p class="articleParagraph enarticleParagraph" >And Trump’s jeering post about Representative Thomas Massie of Kentucky, the Republican cosponsor of the bill to get the files released, wasn’t well received. Trump <span class="colorLinks">mocked [https://truthsocial.com/@realDonaldTrump/posts/115551054294277065]</span> Massie, a widower, for marrying again 16 months after his wife died. “Boy, that was quick!” This coming from the man who went straight from cheating with Marla Maples during his Ivana marriage to marrying her at the Plaza a year later.</p>
<p class="articleParagraph enarticleParagraph" >Maligning members of his own party raised questions about why he was so desperate to hide the files of a child molester who was once his pal; the two bonded over their leering predilection for young women.</p>
<p class="articleParagraph enarticleParagraph" >In a rare show of rebellion, Republicans refused to bend the knee and pretend that it was OK to shield a sexual pervert and give his accomplice, Ghislane Maxwell, treats in prison and pardon dreams just because Trump didn’t want the details of his involvement with Epstein to surface.</p>
<p class="articleParagraph enarticleParagraph" >In emails Democrats released, Epstein wrote that “Trump had spent hours at my house” with one of the victims and that he believed Trump knew more than he had acknowledged, and called Trump “evil beyond belief.” You know you’re in trouble when someone evil beyond belief calls you evil beyond belief.</p>
<p class="articleParagraph enarticleParagraph" >The Times is committed to publishing <span class="colorLinks">a diversity of letters [https://www.nytimes.com/2019/01/31/opinion/letters/letters-to-editor-new-york-times-women.html]</span> to the editor. We’d like to hear what you think about this or any of our articles. Here are some <span class="colorLinks">tips [https://help.nytimes.com/hc/en-us/articles/115014925288-How-to-submit-a-letter-to-the-editor]</span>. And here’s our email: <span class="colorLinks">letters@nytimes.com [mailto:letters@nytimes.com]</span>.</p>
<p class="articleParagraph enarticleParagraph" >Follow the <span class="companylink">New York Times</span> Opinion section on <span class="colorLinks">Facebook [https://www.facebook.com/nytopinion]</span>, <span class="colorLinks">Instagram [https://www.instagram.com/nytopinion/]</span>, <span class="colorLinks">TikTok [https://www.tiktok.com/@nytopinion]</span>, <span class="colorLinks">Bluesky [https://bsky.app/profile/nytopinion.nytimes.com]</span>, <span class="colorLinks">WhatsApp [https://www.whatsapp.com/channel/0029VaN8tdZ5vKAGNwXaED0M]</span> and <span class="colorLinks">Threads [https://www.threads.net/@nytopinion]</span>.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | ncat : Content Types | ncolu : Columns | nedc : Commentaries/Opinions | nfact : Factiva Filters | nfcpex : C&E Executive News Filter</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Epstein, Jeffrey E (1953- ) | Mamdani, Zohran | Mohammed bin Salman (1985- ) | Op-Ed | Trump, Donald J | United States Politics and Government</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>The New York Times Company</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NYTFEED020251122elbm0025z</td></tr></table><br/></div></div><br/><span></span><div id="article-DHLD000020251122elbm0001d" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/dhldLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>1,MNW</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump and Mamdani go from adversaries to allies</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Associated Press </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>335 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Daily Herald</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>DHLD</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>7</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 Daily Herald </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >WASHINGTON — President Donald Trump on Friday met the man who had proudly proclaimed himself “Donald Trump’s worst nightmare,” but he seemed to find the opposite.</p>
<p class="articleParagraph enarticleParagraph" >The Republican president and New York City’s Mayor-elect Zohran Mamdani were warm and friendly, speaking repeatedly of their shared goals to help Trump’s hometown rather than their combustible differences.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Trump, who had in the past called Mamdani a “100% Communist Lunatic” and a “total nut job,” spoke openly of how impressed he was with the man who had called his administration “authoritarian.”</p>
<p class="articleParagraph enarticleParagraph" >“I think he is going to surprise some conservative people, actually,” Trump said of the democratic socialist as Mamdani stood next to him in the Oval Office.</p>
<p class="articleParagraph enarticleParagraph" >The meeting offered political opportunities for both men. For Mamdani, a sit-down offered the state lawmaker, who until recently was relatively unknown, the chance to go head-to-head with the most powerful person in the world.</p>
<p class="articleParagraph enarticleParagraph" >For Trump, it was a high-profile chance to talk about affordability at a time when he’s under increasing political pressure to show he’s addressing voter concerns about the cost of living.</p>
<p class="articleParagraph enarticleParagraph" >Until now, the men have been political foils who galvanized their supporters by taking on each other, and it’s unclear how those backers will react to their genial get-together and complimentary words.</p>
<p class="articleParagraph enarticleParagraph" >“We’re going to be helping him, to make everybody’s dream come true, having a strong and very safe New York,” the president said.</p>
<p class="articleParagraph enarticleParagraph" >“What I really appreciate about the president is that the meeting that we had focused not on places of disagreement, which there are many, and also focused on the shared purpose that we have in serving New Yorkers,” Mamdani said.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani and Trump said they discussed housing affordability and the cost of groceries and utilities, as Mamdani successfully used frustration over inflation to get elected, just as the president did in the 2024 election.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | ncat : Content Types | nfact : Factiva Filters | nfce : C&E Exclusion Filter | niwe : IWE Filter | nnam : News Agency Materials</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Paddock Publications, Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document DHLD000020251122elbm0001d</td></tr></table><br/></div></div><br/><span></span><div id="article-CNBCTV0020251122elbm000b5" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/cnbctvLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>india</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>'This is how democracy should work': Shashi Tharoor on Trump-Mamdani meet</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>CNBC-TV18 </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>459 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>CNBC TV18</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>CNBCTV</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 TV18 Broadcast Ltd. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Congress MP Shashi Tharoor on Saturday, November 22, praised the meeting between United States President Donald Trump and New York City Mayor Zohran Mamdani. Sharing his views on the social media platform X, he said that it reflected how democratic politics should function - where political opponents fight hard during elections but cooperate after the mandate is clear.</p>
<p class="articleParagraph enarticleParagraph" >Despite their previous disagreements during New York’s mayoral campaign, Trump and Mamdani had a warm and productive meeting at the White House on Friday.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Responding to a clip from the meeting, Tharoor tweeted, "This is how democracy should work. Fight passionately for your point of view in elections, with no rhetorical holds barred. But once it’s over, & the people have spoken, learn to cooperate with each other in the common interests of the nation you are both pledged to serve."</p>
<p class="articleParagraph enarticleParagraph" >The Congress MP further said that he'd love to see more of this in India, adding that he was trying to do his part.</p>
<p class="articleParagraph enarticleParagraph" >Tharoor's comments come amid tensions within the Congress party, with some leaders criticising his praise for Prime Minister Narendra Modi's speech at the Ramnath Goenka Lecture. Earlier in a post on X, Tharoor said that Modi's Ramnath Goenka Lecture served as both an economic outlook and a “cultural call to action".</p>
<p class="articleParagraph enarticleParagraph" >"PM Modi said he’d been accused of being in “election mode” all the time, but he was really in “emotional mode” to redress the problems of the people. A significant part of the speech was dedicated to overturning Macaulay's 200-year legacy of "slave mentality." PM Modi appealed for a 10-year national mission to restore pride in India’s heritage, languages, and knowledge systems, he added.</p>
<p class="articleParagraph enarticleParagraph" >His comments sparked controversy within the Congress party, with Sandeep Dikshit labelling him a "hypocrite" and Supriya Shrinate finding nothing "praiseworthy" in PM Modi's speech.</p>
<p class="articleParagraph enarticleParagraph" >The Trump-Mamdani meeting was a surprising turn of events, given their previous bitter exchanges. Trump had labelled Mamdani a "lunatic communist", but their Oval Office meeting was surprisingly good.</p>
<p class="articleParagraph enarticleParagraph" >Following the meeting, the President stated that the meeting was very “productive” and that New York would “hopefully have a great mayor.”</p>
<p class="articleParagraph enarticleParagraph" >"I feel very confident that he can do a very good job…I think he is going to surprise some conservative people, actually. And some very liberal people, he won't surprise them because they already like him," he added.</p>
<p class="articleParagraph enarticleParagraph" >Meanwhile, Mamdani also appreciated the meeting with Trump, adding, "And as he said, it was a productive meeting focused on a place of shared admiration and love, which is New York City and the need to deliver affordability to New Yorkers."</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | gvote : Elections</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Network18 Media & Investments Ltd.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document CNBCTV0020251122elbm000b5</td></tr></table><br/></div></div><br/><span></span><div id="article-SMHHOL0020251122elbm0018h" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/smhholLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>NSW</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Long-term government the only solution to musical chairs</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>964 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>05:00 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>smh.com.au</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>SMHHOL</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright © 2025 Fairfax Media Publications Pty Limited. <span class="colorLinks">www.smh.com.au [http://www.smh.com.au]</span>. Not available for redistribution </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Sean Kelly’s column relating to “long-term government” is pertinent, especially regarding reforming governments (“<span class="colorLinks">There’s one fight Anthony Albanese always tries to avoid picking” [https://www.smh.com.au/national/there-s-one-fight-anthony-albanese-always-tries-to-avoid-picking-20251110-p5n92b.html]</span>, November 16). Reforming governments resemble a game of musical chairs. Kevin Rudd and Julia Gillard introduced emission reforms only to have them curtailed by Tony Abbott. Similarly, Donald Trump on election curtailed all of Joe Biden’s attempts to deal with global warming and emissions. Unless Anthony Albanese wins several terms, any incoming conservative government will once again undo Labor’s work on emissions and renewable energy. The Coalition has already issued a statement to this effect. There will be a pause until a Labor reforming government is re-elected to start the whole process of change once again. Kearney is correct.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" > There will be no change without long-term government, only musical chairs.</p>
<p class="articleParagraph enarticleParagraph" >Ray Armstrong, Tweed Heads</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">The Albanese government steers clear of upsetting those with assets. Michael Howard [https://static.ffx.io/images/$zoom_0.553%2C$multiply_1.0582%2C$ratio_1.5%2C$width_756%2C$x_0%2C$y_126/t_crop_custom/q_86%2Cf_auto/3fad5d3616799eb5d7d8b3415f0047735fd96b13b63255504c8f3c035bdc8008]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Sean Kelly outlines in great detail where the Albanese government is failing struggling Australians, something that the Labor Party once prided itself in. The explanation is sadly simple. Albanese and company are terrified of offending big business on any front, be it health, housing, education, climate and energy supply. Until they are prepared to grow a spine nothing will change.Ross Hudson, Mount Martha (Vic)</p>
<p class="articleParagraph enarticleParagraph" >Respect starts at home</p>
<p class="articleParagraph enarticleParagraph" >In his thoughtful opinion piece concerning gay men lured by teenagers through dating apps then viciously assaulted (“<span class="colorLinks">Gay hate 2025-style: victims lured via dating sites [https://www.smh.com.au/politics/federal/idk-what-to-do-teens-share-their-thoughts-after-test-driving-the-social-media-ban-20250916-p5mvc7.html]</span>”, November 16), Nicholas Stewart points to the need for police to continue their efforts to prevent these crimes and the role of schools in presenting curriculums addressing “toxic masculinity and empathy failure”. But he makes no mention of the responsibility of parents to raise their children to have respect for the rights of others. Have we simply given up on parental responsibility?John Ure, Mount Hutton</p>
<p class="articleParagraph enarticleParagraph" >I refer to the sad article written by Nicholas Stewart in the Sun-Herald. The treatment of the LGBTQ community is a sad indictment on all who care about liberty. It seems that intolerance is the one thing that drives extremists. “Live and let live” seems to be fading away as a rationale for life.Pasquale Vartuli, Wahroonga</p>
<p class="articleParagraph enarticleParagraph" >Refreshing read</p>
<p class="articleParagraph enarticleParagraph" >Reading about someone like Charles Zhao using his brilliance for the greater good by inventing a 3D-printed chip to fast-track stroke prevention treatment, and dedicating his future to developing even more effective test kits, goes some way to restoring one’s faith in human nature (“<span class="colorLinks">This tiny chip can detect your chances of a stroke [https://www.smh.com.au/national/this-tiny-chip-can-predict-your-risk-of-stroke-20251106-p5n8ct.html]</span>”, November 16), which certainly took a knock from reading about <span class="companylink">Waverley Council</span> kowtowing to millionaires and approving the removal of trees that impinge on their sea views (“<span class="colorLinks">Waverley Council to trade trees for ocean views [https://www.smh.com.au/national/nsw/eastern-suburbs-council-votes-to-trade-native-trees-for-ocean-views-20251113-p5nf80.html]</span>”, November 16).</p>
<p class="articleParagraph enarticleParagraph" >Anne Ring, Coogee</p>
<p class="articleParagraph enarticleParagraph" >Crisis by Coalition</p>
<p class="articleParagraph enarticleParagraph" >In her weekly essay that attempts to shore up the crumbling foundations of Australia’s right, Parnell McGuinness’ latest skewering of those allegedly responsible for doing nought about housing seems more a stream of random thoughts than a serious piece of writing (“<span class="colorLinks">Meet the forever-renter generation [https://www.smh.com.au/national/the-forever-renter-generation-they-re-the-ones-who-voted-teal-and-mamdani-20251114-p5nfka.html]</span>”, November 16). So much so she even elevates the princess of passe, Kathy Lette, to the status of political analysis in her “inoculation against pessimism” grab regarding Zohran Mamdani’s election victory in New York City. Mamdani’s election platform was so much wider and more nuanced than that of McGuinness’s confected housing blame shift. Simplistically believing that the Boomers’ faux outrage actually exists rather than real concern doesn’t cut it. What is hypocritical is to ignore that the housing crisis is a direct result of Coalition taxation policies that favoured individuals with capital and assets and disadvantaged those on wage incomes. In particular, John Howard reducing CGT liabilities by 50 per cent. McGuinness would do well to look into her bottom drawer for an appropriate T-shirt that celebrates John Howard’s reign of punishing policies, rather than a paint-by-numbers analysis of a complex issue.</p>
<p class="articleParagraph enarticleParagraph" >Rob Asser, Balmain East</p>
<p class="articleParagraph enarticleParagraph" >Bravo Parnell, who gives a clear view of the state of the present generation of frustrated renters. It’s clearly a byproduct of capitalism, which a democracy needs to moderate. It’s a big challenge for a social democratic party and is Albo’s biggest on the domestic front. Fiddling at the edges won’t cut it.Richard Hambly, Potts Point</p>
<p class="articleParagraph enarticleParagraph" >Stick to what you know</p>
<p class="articleParagraph enarticleParagraph" >Rachel Ward’s views on vaccines, and the link to autism, and Robert Kennedy Jr’s dangerous agenda with US health being a force for good show that science and the opinions of medical experts are essentially being ignored (“‘<span class="colorLinks">Free radical’: Filmmaker farmer on vaccines RFK Jr and her new project [https://www.smh.com.au/national/free-radical-filmmaker-farmer-rachel-ward-on-vaccines-rfk-jr-and-her-new-paddock-to-plate-project-20251113-p5nf36.html]</span>”, November 16). Such a view lacks all credibility. Rachel Ward should stick to acting and farming.John Cotterill, Kingsford</p>
<p class="articleParagraph enarticleParagraph" >I’m afraid “paying the rent” didn’t work for me, Fitzy. Once I read that Rachel Ward loved what JFK Jnr stands for, I simply turned the page.</p>
<p class="articleParagraph enarticleParagraph" >John Clear, North Parramatta</p>
<p class="articleParagraph enarticleParagraph" >Reject the royals</p>
<p class="articleParagraph enarticleParagraph" >As a staunch Australian republican I welcome the news that more Aussies are voicing their support for a republic due to the British royal family crisis involving the former Prince Andrew – now just plain Andrew Mountbatten-Windsor – because of his scandalous friendship with the late sex offender Jeffrey Epstein (“<span class="colorLinks">Republic support surges to record level [https://www.smh.com.au/politics/federal/republic-support-surges-to-record-level-but-we-still-like-king-charles-despite-andrew-furore-20251111-p5nec8.html]</span>”, November 16).</p>
<p class="articleParagraph enarticleParagraph" >Eric Palm Gympie Qld* To submit a letter to the Sydney Morning Herald, email letters@smh.com.au. Click <span class="colorLinks">here [https://www.smh.com.au/letters-tips]</span> for tips on how to submit letters.</p>
<p class="articleParagraph enarticleParagraph" >* The Opinion newsletter is a weekly wrap of views that will challenge, champion and inform.<span class="colorLinks"> Sign up here. [https://login.myfairfax.com.au/signup_newsletter/10147?channel_key=zHE9EWDHf1XPuz3Phk0YIg&callback_uri=https%3A%2F%2Fwww.smh.com.au]</span>
                  </p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RF</b>&nbsp;</td><td><br/>YXJ0aWNsZTo2ZGJkZjUzMC0zYzEwLTQyODAtODc1ZS1kY2FlN2RkNDQ3ZTQ </td></tr>
<tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gclimt : Climate Change | genv : Natural Environment | gglobe : Global/World Issues | gpir : Politics/International Relations | gpol : Domestic Politics | ncat : Content Types | nedc : Commentaries/Opinions | nfact : Factiva Filters | nfcpex : C&E Executive News Filter</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>apacz : Asia Pacific | ausnz : Australia/Oceania | austr : Australia | nswals : New South Wales</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>For subscribers | National | Opinion | SMH letters</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Fairfax Media Management Pty Limited</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document SMHHOL0020251122elbm0018h</td></tr></table><br/></div></div><br/><span></span><div id="article-NFINCE0020251122elbm00454" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nfinceLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>CE Noticias Financieras English</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Mamdani, Trump pledge to work together for New York City</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>836 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>CE NoticiasFinancieras</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NFINCE</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright © Content Engine LLC </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Washington and New York, New York's democratic socialist mayor-elect and America's anti-left president surprised everyone at their first meeting at the White House by declaring - after months of mutual attacks - that they will work together to create a safe, prosperous and more affordable city for all.</p>
<p class="articleParagraph enarticleParagraph" >"We agree on a lot more than I would have thought. I want him to do a great job, and we'll help him do a great job," Donald Trump told the media sitting at the Oval Office desk with his guest standing beside him after the private meeting with whom he had called until today "a 100 percent communist lunatic." He added, "I think it's going to really surprise some conservative people."</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Zohran Mamdani, who has called Trump a "despot," said he was grateful to the president for "a productive meeting focused on a place of shared admiration and love, New York City (Trump was born and raised there), and the need to make it affordable for New Yorkers," an expression that was the central message that carried him to victory.</p>
<p class="articleParagraph enarticleParagraph" >High expectations</p>
<p class="articleParagraph enarticleParagraph" >During the lengthy media session, Trump marveled at the enormous interest in the meeting between the two, which, he said, surpassed many of his White House meetings with foreign heads of state.</p>
<p class="articleParagraph enarticleParagraph" >The U.S. president has always measured the real power of politicians, and today he made it clear that he was impressed with the way Mamdani won an election in which he was initially an unknown, as well as with the conversation they had.</p>
<p class="articleParagraph enarticleParagraph" >Trump indicated that he hoped to be "a big help" to efforts to improve his hometown and that he would have "absolutely" no problem living there under a Mamdani administration, which was a dramatic turn in his warnings to try to stop his guest's win by characterizing him as an "existential" threat to the city.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani was asked if he now regrets calling Trump a despot, but he avoided answering and his host shielded him by stating that "I've been called much worse things."</p>
<p class="articleParagraph enarticleParagraph" >The mandarin continued to interject hostile questions from conservative media against the mayor-elect, and when Mamdani was asked if he still considered Trump a "fascist," Trump interrupted and told his guest that it was easier for him to just say yes, so he wouldn't have to explain. The mayor-elect followed his instruction.</p>
<p class="articleParagraph enarticleParagraph" >Focus on proposals</p>
<p class="articleParagraph enarticleParagraph" >Mamdani kept the focus on his promises and proposals for the city and avoided falling into provocations or rhetorical disputes, repeatedly thanking the president for his willingness to help the city. But he did not back down from his positions or hide his perspectives, reiterating that he is a democratic socialist.</p>
<p class="articleParagraph enarticleParagraph" >When a reporter pointed out that Mamdani had accused the <span class="companylink">U.S. government</span> of genocide in Gaza, he did not hesitate to clarify that "I have spoken about the government of Israel committing genocide and I have spoken about the financing of that by our government". It is worth remembering that he was standing next to Benjamin Netanyahu's government's main ally in the world.</p>
<p class="articleParagraph enarticleParagraph" >The meeting surprised those who expected a conflictive encounter. Trump once again exhibited his political agility by creating a spectacle that provokes national attention, measuring the power of other politicians -Mamdani managed to defeat the political and economic leadership in New York and part of the national one- and apparently deciding that his friendliness with a dissident leader of the Democratic Party serves to nurture divisions within that political force.</p>
<p class="articleParagraph enarticleParagraph" >But nothing is predictable with this presidency, and that friendliness can turn into something else - including reversing threats to send federal troops to New York, among others - with the swiftness of a single tweet, as leaders at home and abroad know from their experiences with the president.</p>
<p class="articleParagraph enarticleParagraph" >A change in rhetoric</p>
<p class="articleParagraph enarticleParagraph" >The specter of a "socialist" in Washington continues to alarm many. Indeed, White House spokeswoman Karoline Leavitt announced Thursday that "tomorrow we have a communist coming to the White House because that's who the Democratic Party elected as mayor of the largest city in the country."</p>
<p class="articleParagraph enarticleParagraph" >Republicans, including Trump, have taken to defining Democrats as "radical leftists" under the control of socialists - whom they sometimes identify as "communists" - since the current president's campaign to date.</p>
<p class="articleParagraph enarticleParagraph" >For some reason, Trump, in his meeting with Mamdani, did not use that rhetoric. Rather, he praised him as "a different politician."</p>
<p class="articleParagraph enarticleParagraph" >However, his party still remains on message that "socialism" continues to threaten the country. The House passed a resolution yesterday morning by a vote of 285 to 98 "condemning socialism." Some 86 Democrats joined all Republicans in approving the symbolic measure.</p>
<p class="articleParagraph enarticleParagraph" >Apparently, the motivation was Democratic Socialist Mamdani's visit to Washington. But its effect is perhaps the opposite of the desired one, a recognition of the potential political force that Mamdani and his allies represent in the United States.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | usdc : Washington DC | use : Northeast U.S. | usny : New York State | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Content Engine LLC</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NFINCE0020251122elbm00454</td></tr></table><br/></div></div><br/><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC45913020251122elbm000b5"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Zohran Mamdani’s Next Act</b><div class="leadFields"><a href="javascript:void(0)">New York Magazine</a>, 05:00 AM, 22 November 2025, 1298 words, (English)</div><div class="snippet ensnippet"> By Errol Louis, a columnist for New York Magazine and the longtime host of “Inside City Hall” on Spectrum News NY1.Save this article to read it later.</div>
<div>(Document WC45913020251122elbm000b5)</div><br/></td></tr>
						</table>
					</div>
				</div><div id="carryOver">
				<div id="carryOverHeadlines">
				<table cellpadding="0" cellspacing="0" border="0" class="headlines"><tr class="headline" data-accno="WC42085020251122elbm00233"><td valign="top"><img title="HTML" src="../img/html.gif"/><b class="printheadline enHeadline">  Doubling Down: Top House Democrat says focus on high prices ‘absolutely going to continue’</b><div class="leadFields"><a href="javascript:void(0)">FOXNews.com</a>, 05:00 AM, 22 November 2025, 1060 words,  Paul Steinhauser Fox, (English)</div><div class="snippet ensnippet"> House Democrats need to flip just three GOP-held seats in 2026 to win back control of the chamber for the first time in four years.&quot;We&#39;re going to hold Republicans accountable for their policies that are hurting American families,&quot; Rep. ...</div>
<div>(Document WC42085020251122elbm00233)</div><br/></td></tr>
						</table>
					</div>
				</div><span></span><div id="article-EURONEN020251122elbm00001" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/euronenLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump and Mamdani surprisingly go from adversaries to allies in Oval Office meeting</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>839 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Euronews</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>EURONEN</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 Euronews All Rights Reserved </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >US President Donald Trump on Friday met the man who had proudly proclaimed himself “Donald Trump’s worst nightmare” but seemed to find the opposite in what turned out to be a very cordial meeting between the two.</p>
<p class="articleParagraph enarticleParagraph" >Speaking repeatedly of their shared goals to help New York rather than their combustible differences, Trump and New York City’s Mayor-elect Zohran Mamdani were warm and friendly.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Trump, who had in the past called Mamdani a “100% Communist Lunatic” and a “total nut job,” spoke openly of how impressed he was with the man who had called his administration “authoritarian.”</p>
<p class="articleParagraph enarticleParagraph" >“I think he is going to surprise some conservative people, actually,” Trump said of the democratic socialist as Mamdani stood next to him in the Oval Office.</p>
<p class="articleParagraph enarticleParagraph" >The meeting offered political opportunities for both men. For Mamdani, a sit-down offered the state lawmaker—who until recently was relatively unknown—the chance to go head-to-head with the most powerful person in the world.</p>
<p class="articleParagraph enarticleParagraph" >Trump brushes off Mamdani's 'fascist' criticism</p>
<p class="articleParagraph enarticleParagraph" >Both discussed housing affordability and the cost of groceries and utilities, as Mamdani successfully used frustration over inflation to get elected, just as the president did in the 2024 election.</p>
<p class="articleParagraph enarticleParagraph" >“Some of his ideas are really the same ideas that I have,” Trump said of Mamdani about inflationary issues.</p>
<p class="articleParagraph enarticleParagraph" >The president brushed aside Mamdani’s criticisms of him over his administration’s deportation raids and claims that Trump was behaving like a despot.</p>
<p class="articleParagraph enarticleParagraph" >Instead, Trump said the responsibility of holding an executive position in the government causes a person to change, saying that had been the case for him.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">President Donald Trump listens as New York City Mayor-elect Zohran Mamdani speaks in the Oval Office of the White House, Friday, Nov. 21, 2025, in Washington. (AP Photo/Evan V (Evan Vucci/Copyright 2025 The AP. All rights reserved) [https://images.euronews.com/articles/stories/09/55/75/80/808x539_cmsv2_19724ebb-30b2-566f-8c87-8eed91c7b246-9557580.jpg]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >When reporters asked Mamdani to clarify his past statements indicating that he thought the president was acting like a fascist, Trump said, “I’ve been called much worse than a despot.”</p>
<p class="articleParagraph enarticleParagraph" >And when a reporter asked if Mamdani stood by his comments that Trump is a fascist, Trump interjected before the mayor-elect could fully answer the question.</p>
<p class="articleParagraph enarticleParagraph" >“That’s OK. You can just say yes. OK?” Trump said. “It’s easier. It’s easier than explaining it. I don’t mind.”</p>
<p class="articleParagraph enarticleParagraph" >“We’re going to be helping him to make everybody’s dream come true, having a strong and very safe New York,” the president said.</p>
<p class="articleParagraph enarticleParagraph" >All about making New York City affordable</p>
<p class="articleParagraph enarticleParagraph" >For Trump, it was a high-profile chance to talk about affordability at a time when he’s under increasing political pressure to show he’s addressing voter concerns about the cost of living.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, who takes office in January, said he sought the meeting with Trump to talk about ways to make New York City more affordable. Trump has said he may want to help him out — although he has also falsely labelled Mamdani as a “communist” and threatened to yank federal funds from the city.</p>
<p class="articleParagraph enarticleParagraph" >But Trump on Friday didn’t sling that at the mayor. He acknowledged that he had said he had been prepared to cut off funding or make it harder for New York City to access federal resources if the two had failed to “get along,” only to pull back from those threats during the meeting.</p>
<p class="articleParagraph enarticleParagraph" >“We don’t want that to happen,” Trump said. “I don’t think that’s going to happen.”</p>
<p class="articleParagraph enarticleParagraph" >With some dramatic public Oval Office faceoffs this year, including an infamously heated exchange with Ukrainian President Volodymyr Zelenskyy in February and an embarrassing video clip showing disputed claims of white genocide for South African President Cyril Ramaphosa, many had feared the worst.</p>
<p class="articleParagraph enarticleParagraph" >Related</p>
<p class="articleParagraph enarticleParagraph" >* <span class="colorLinks">Actress Debra Messing faces backlash after calling Zohran Mamdani a 'jihadist' [https://www.euronews.com/culture/2025/11/06/actress-debra-messing-faces-backlash-after-calling-zohran-mamdani-a-jihadist]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >* <span class="colorLinks">Fact check: Would Zohran Mamdani's policies be 'normal' in Europe? [https://www.euronews.com/my-europe/2025/11/12/fact-check-would-zohran-mamdanis-policies-be-normal-in-europe]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Ahead of the meeting, Mamdani said Thursday that he was not concerned about the president potentially trying to use the meeting to publicly embarrass him and said he saw it as a chance to make his case, even while acknowledging “many disagreements with the president.”</p>
<p class="articleParagraph enarticleParagraph" >“What I really appreciate about the president is that the meeting that we had focused not on places of disagreement, which there are many, and also focused on the shared purpose that we have in serving New Yorkers,” Mamdani said.</p>
<p class="articleParagraph enarticleParagraph" >Ultimately, both men avoided a public confrontation in a remarkably calm and cordial series of comments in front of news reporters.</p>
<p class="articleParagraph enarticleParagraph" >With tensions subdued, Trump seemed sympathetic to Mamdani’s policies to build more housing.</p>
<p class="articleParagraph enarticleParagraph" >“People would be shocked, but I want to see the same thing,” the president said.</p>
<p class="articleParagraph enarticleParagraph" >
                     <span class="colorLinks">President Donald Trump listens as New York City Mayor-elect Zohran Mamdani speaks in the Oval Office of the White House, Friday, Nov. 21, 2025, in Washington. (AP Photo/Evan V (Evan Vucci/Copyright 2025 The AP. All rights reserved) [https://images.euronews.com/articles/stories/09/55/75/80/800x450_cmsv2_27958c62-6ea8-537a-9937-b143de6e4861-9557580.jpg]</span>
                  </p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>New York | United States | Zohran Mamdani</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Euronews</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document EURONEN020251122elbm00001</td></tr></table><br/></div></div><br/><span></span><div id="article-STTEN00020251122elbm001xh" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/sttenLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Foreign</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>New York Mayor-elect Mamdani receives surprising praise from Trump*** TRANSLATED ***</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Minja Viitanen </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>386 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>STT</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>STTEN</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. STT, for more information see <span class="colorLinks">https://stt.fi [https://stt.fi]</span>
               </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The president said he was confident that the 34-year-old incoming mayor would be able to do a good job.</p>
<p class="articleParagraph enarticleParagraph" >US President Donald Trump and New York City Mayor-elect Zohran Mamdani met at the White House local time on Friday.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The duo, who spoke during Mamdan's election campaign, seemed in good spirits, and Trump, who had previously criticized Mamdan, went out of his way to praise his guest.</p>
<p class="articleParagraph enarticleParagraph" >According to the news channel CNN, Trump said after the meeting, which lasted about half an hour, that Mamdan has the opportunity to do great things for New York.</p>
<p class="articleParagraph enarticleParagraph" >"We will help him realize everyone's dream, a strong and very safe New York," Trump said.</p>
<p class="articleParagraph enarticleParagraph" >The president, who is from New York, seemed to have changed his opinion about the future mayor of the big city.</p>
<p class="articleParagraph enarticleParagraph" >"I'm very confident that he can do a good job. I think he's going to surprise some conservative people," Trump said.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani wants cooperation</p>
<p class="articleParagraph enarticleParagraph" >Mamdani also described the meeting as productive. According to the future mayor, the two shared their admiration and love for the largest city in the United States.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani campaigned strongly against Trump. Mamdani has since softened his tone and emphasized his desire to work with Trump to address the rising cost of living.</p>
<p class="articleParagraph enarticleParagraph" >After the two met face-to-face, the reporter asked Mamdani if he still believed Trump was a fascist. In his victory speech, Mamdani vowed, among other things, to oppose Trump's fascism.</p>
<p class="articleParagraph enarticleParagraph" >The future mayor started to answer the question, but Trump interrupted him, saying the word didn't bother him.</p>
<p class="articleParagraph enarticleParagraph" >– That's okay. He can say that, Trump said with a smile.</p>
<p class="articleParagraph enarticleParagraph" >Trump called a communist</p>
<p class="articleParagraph enarticleParagraph" >The meeting between the two was expected to be potentially explosive. Trump has previously called Mamdani a communist and suggested that he should be deported from the country. Mamdani was born in Uganda.</p>
<p class="articleParagraph enarticleParagraph" >The president has also previously warned that he will make life difficult for the 34-year-old mayor. He has threatened, among other things, to cut federal funding to New York City and send National Guard troops to New York once Mamdani's mayoral term begins.</p>
<p class="articleParagraph enarticleParagraph" >*** DISCLAIMER: THIS IS AN AUTOMATED TRANSLATION FROM FINNISH ***</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | greg : Regional Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Foreign</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Oy Suomen Tietotoimisto</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document STTEN00020251122elbm001xh</td></tr></table><br/></div></div><br/><span></span><div id="article-STTEN00020251122elbm001up" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/sttenLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Foreign</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>New York Mayor-elect Mamdani receives surprising praise from Trump – "He's going to surprise some conservatives"*** TRANSLATED ***</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Minja Viitanen </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>507 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>STT</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>STTEN</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. STT, for more information see <span class="colorLinks">https://stt.fi [https://stt.fi]</span>
               </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The president said he was confident that the 34-year-old incoming mayor would be able to do a good job.</p>
<p class="articleParagraph enarticleParagraph" >US President Donald Trump and Zohran Mamdani, the Democrat elected mayor of New York, have met at the White House.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The duo, who spoke during Mamdan's election campaign, seemed in good spirits, and Trump, who had previously criticized Mamdan, who describes himself as a social democrat, was quick to praise his guest.</p>
<p class="articleParagraph enarticleParagraph" >According to the news channel CNN, Trump said after the meeting, which lasted about half an hour, that Mamdan has the opportunity to do great things for New York.</p>
<p class="articleParagraph enarticleParagraph" >"We will help him realize everyone's dream, a strong and very safe New York," Trump said.</p>
<p class="articleParagraph enarticleParagraph" >The president, who is from New York, seemed to have changed his opinion about the future mayor of the big city.</p>
<p class="articleParagraph enarticleParagraph" >"I'm very confident that he can do a good job," Trump said.</p>
<p class="articleParagraph enarticleParagraph" >"I think he's going to surprise some conservative people," he continued.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani wants cooperation</p>
<p class="articleParagraph enarticleParagraph" >Mamdani also described the meeting as very productive. According to the future mayor, the two shared their admiration and love for the largest city in the United States.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani campaigned strongly against Trump, and in his victory speech he looked into the camera and addressed the message directly to Trump. Mamdani has since softened his tone and emphasized that he wants to work with Trump to curb the rising cost of living.</p>
<p class="articleParagraph enarticleParagraph" >After the two met face-to-face, the reporter asked Mamdani if he still believed Trump was a fascist. Mamdani vowed in his victory speech, among other things, to oppose Trump's fascism.</p>
<p class="articleParagraph enarticleParagraph" >The future mayor started to answer the question, but Trump interrupted him, saying the word didn't bother him.</p>
<p class="articleParagraph enarticleParagraph" >– That's okay. He can say that, Trump said with a smile.</p>
<p class="articleParagraph enarticleParagraph" >The meeting was expected to be explosive.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani was virtually unknown at the start of his campaign, but he eventually became the first mayoral candidate to receive more than a million votes in New York City since 1969. Mamdani focused his campaign on the high cost of living for New Yorkers, offering relief through free public transportation, rent control, and publicly run grocery stores.</p>
<p class="articleParagraph enarticleParagraph" >The meeting between the two was expected to be potentially explosive, as was the case with Ukrainian President Volodymyr Zelensky's visit earlier this year, when Vice President JD Vance began lecturing Zelensky in front of the world's media.</p>
<p class="articleParagraph enarticleParagraph" >Trump, 79, has previously called Mamdani a communist and suggested that he should be deported from the country. Mamdani was born in Uganda.</p>
<p class="articleParagraph enarticleParagraph" >The president has also previously warned that he will make life difficult for the 34-year-old mayor. He has threatened, among other things, to cut federal funding to New York City and send National Guard troops to New York once Mamdani's mayoral term begins.</p>
<p class="articleParagraph enarticleParagraph" >*** DISCLAIMER: THIS IS AN AUTOMATED TRANSLATION FROM FINNISH ***</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | greg : Regional Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Foreign</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Oy Suomen Tietotoimisto</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document STTEN00020251122elbm001up</td></tr></table><br/></div></div><br/><span></span><div id="article-NYTF000020251122elbm0004f" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nytfLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>National Desk; SECTA</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>After Abrupt Halt, Citizenship Ceremonies Are Back On in Upstate New York</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Ana Ley </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>589 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The New York Times</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NYTF</td></tr><tr><td align="right" valign="top" class="index"><b>ED</b>&nbsp;</td><td>Late Edition - Final</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>16</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 The New York Times Company.  All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >At least seven counties had been affected by the interruption in celebrations for people who were becoming naturalized citizens.</p>
<p class="articleParagraph enarticleParagraph" >The <span class="companylink">U.S. Citizenship and Immigration Services</span> agency, which had canceled naturalization ceremonies in several upstate New York counties, has reinstated the celebrations after an appeal from a congressman who said ''the decision shouldn't have happened.''</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The agency had said on Tuesday that county courts did not meet federal requirements to conduct naturalization ceremonies, and that it had chosen to stop them as a result. At the time, Matthew J. Tragesser, a spokesman for the agency, said that applicants whose naturalization ceremonies had been scheduled would receive new appointments and that their naturalization processes would continue elsewhere.</p>
<p class="articleParagraph enarticleParagraph" >But on Friday, Representative Mike Lawler, a Republican whose district includes parts of Westchester County, said that he had spoken with Joseph B. Edlow, the director of the citizenship agency, urging him to reverse the decision. He said that Mr. Edlow had done so on Thursday afternoon.</p>
<p class="articleParagraph enarticleParagraph" >''When you have people who actively choose to want to become American citizens and swear an allegiance to this country, it's a wonderful moment and that's something that we should celebrate,'' Mr. Lawler said in a telephone interview.</p>
<p class="articleParagraph enarticleParagraph" >Officials with the citizenship agency did not respond to questions about the restoration of the ceremonies, including why they had changed their mind.</p>
<p class="articleParagraph enarticleParagraph" >At least seven counties had been affected by the interruption, said Timothy C. Idoni, the clerk in Westchester County, where officials have held such ceremonies for more than 40 years. Mr. Idoni said that Mr. Lawler had notified his office that the ceremonies had been restored, but as of Friday morning, he had not heard from federal officials by that afternoon.</p>
<p class="articleParagraph enarticleParagraph" >''They were wrong on the law,'' Mr. Idoni wrote in an email. ''New York state courts are most certainly qualified to do naturalizations.''</p>
<p class="articleParagraph enarticleParagraph" >Mr. Lawler -- whose wife emigrated from Moldova and is a naturalized citizen -- had written a letter to Mr. Edlow a week ago calling the policy change ''deeply concerning for new citizens and their families.'' Mr. Lawler said that he had spoken with Mr. Edlow twice since then and had received notice from the agency about 5 p.m. Thursday that it had made the change by mistake.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Idoni said that canceling the ceremonies would complicate the naturalization process for some immigrants.</p>
<p class="articleParagraph enarticleParagraph" >It would mean that they would have to travel to 26 Federal Plaza in Lower Manhattan to complete the final citizenship requirements and to receive naturalization certificates instead of participating in celebratory events arranged by their communities. The building in Manhattan has offices for the citizenship agency as well as for <span class="companylink">Immigration and Customs Enforcement</span>, whose agents have arrested immigrants after court appearances as the Trump administration has sought to raise deportation numbers.</p>
<p class="articleParagraph enarticleParagraph" >Officials in New York City are bracing for a federal immigration crackdown. On Tuesday, President Trump's top border adviser said that he would deploy the National Guard or more immigration agents to New York City, repeating a threat that took on added weight after the election of Zohran Mamdani as mayor. Mr. Mamdani has vowed to resist the Trump administration's efforts to deport New Yorkers.</p>
<p class="articleParagraph enarticleParagraph" >Speaking on Fox News, the official, Thomas Homan, said that he was targeting New York City because of its so-called sanctuary policies, which prevent local law enforcement officers from cooperating with federal immigration authorities on most matters.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>CO</b>&nbsp;</td><td><br/>uscis : United States Citizenship and Immigration Services</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gcom : Society/Community | gimm : Human Migration | gpir : Politics/International Relations</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>National Desk</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>The New York Times Company</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NYTF000020251122elbm0004f</td></tr></table><br/></div></div><br/><span></span><div id="article-NYTF000020251122elbm0004e" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nytfLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Foreign Desk; SECT</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump and Mamdani's News Conference: Read the Transcript</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By The New York Times </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>6716 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The New York Times</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NYTF</td></tr><tr><td align="right" valign="top" class="index"><b>ED</b>&nbsp;</td><td>The New York Times on the Web</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 The New York Times Company.  All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >President Trump and Zohran Mamdani, the mayor-elect of New York City, spoke to the news media after their first face-to-face meeting.</p>
<p class="articleParagraph enarticleParagraph" >President Trump and Zohran Mamdani, the mayor-elect of New York City, spoke to reporters after they met at the White House on Friday afternoon.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Here is a transcript of their comments, lightly edited for clarity.</p>
<p class="articleParagraph enarticleParagraph" >President Trump: Thank you very much. We've just had a great meeting -- a really good, a very productive meeting. We have one thing in common: We want this city of ours that we love to do very well. And I want to congratulate the mayor.</p>
<p class="articleParagraph enarticleParagraph" >He really ran an incredible race against a lot of smart people. Starting with the early primaries against some very tough people, very smart people, and he beat them and beat them easily. And I congratulated him. And we talked about some things, and very strong in common, like housing and getting housing built. Food and prices, and the price of oil is coming way down.</p>
<p class="articleParagraph enarticleParagraph" >Anything I do is going to be good for New York. If I can get prices down, it's good for New York. And we've got them down, way down from last year. We have, as you know -- I've been saying to a lot of people, <span class="companylink">Walmart</span> said that Thanksgiving this year is exactly 25 percent less than last year, so that is good for New York. Good for everybody.</p>
<p class="articleParagraph enarticleParagraph" >But I just want to congratulate. I think, hopefully, you'll have a really great mayor. The better he does, the happier I am. There is no difference in party. There is no difference in anything, and we're going to be helping him to make everybody's dream come true. Having a strong and very safe New York, and congratulations, Mr. Mayor.</p>
<p class="articleParagraph enarticleParagraph" >Zohran Mamdani: Thank you, Mr. President.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Thank you.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I appreciate it.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Please.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I appreciated the meeting with the president, and as he said, it was a productive meeting focused on a place of shared admiration and love, which is New York City. And the need to deliver affordability to New Yorkers, the eight and a half million people who call our city their home, who are struggling to afford life in the most expensive city in the United States of America.</p>
<p class="articleParagraph enarticleParagraph" >We spoke about rent. We spoke about groceries. We spoke about utilities. We spoke about the different ways in which people are being pushed out, and I appreciated the time with the president. I appreciate the conversation, and I look forward to working together to deliver that affordability for New Yorkers.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Thank you very much. Any questions?</p>
<p class="articleParagraph enarticleParagraph" >Reporter: I have a question for you and then also one for the mayor-elect.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Sure.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: For you, you refer to Mr. Mamdani as a ''communist.'' Can you describe why you feel that way, and also, will you do anything to stop him from arresting Prime Minister Netanyahu if he visits New York?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Well, we didn't discuss your second part of the question. And on your first part, he's got views out there, but who knows -- I mean, we're going to see what works.</p>
<p class="articleParagraph enarticleParagraph" >He's going to change also. We all change. I changed a lot, changed a lot from when I first came to office. It's now quite a while ago, it's quite a while. My first term was great, we had the greatest economy in the history of our country, and we're doing even better now.</p>
<p class="articleParagraph enarticleParagraph" >We're doing much better now than we did even in the first term. And I can tell you, some of my views have changed. We had discussions on some things. I am not going to discuss what they were, but I feel very confident that he can do a very good job.</p>
<p class="articleParagraph enarticleParagraph" >I think -- I think he's going to be, I think he's going to surprise some conservative people, actually. And some very liberal people, he won't surprise them, because they already like him.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Mr. Mamdani, it sounds like you had a productive discussion, but just days ago you referred to President Trump as a despot who betrayed the country. You said, ''I'll be his worst nightmare'' and accused him of having a fascist agenda. Are you planning to retract any of these remarks in order to improve your relationship?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I think both President Trump and I, we are very clear about our positions and our views. And what I really appreciate about the president is the meeting that we had focused not on places of disagreement, which there are many, and also focused on the shared purpose that we have in serving New Yorkers.</p>
<p class="articleParagraph enarticleParagraph" >And frankly, that is something that could transform the lives of eight and a half million people who are currently struggling under a cost-of-living crisis, with one in four living in poverty. And the meeting came back again and again to what it could look like to lift those New Yorkers out of struggle and start to deliver them the city that they can do more than just struggle to afford it, but also start to live in.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: I've been called much worse than a despot. It's not that insulting. Maybe -- I think he'll change his mind after we get to working together. Yes, please.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: I would like to ask you a question about the Middle East regarding -- do you think that <span class="companylink">Hezbollah</span> and Lebanon is not in a good position? And Lebanon now is the final unresolved after Gaza and Syria. Given your assessment, what do you say for Lebanese today? [inaudible] in the state in Lebanon, and what is your next move to push toward disarmament of <span class="companylink">Hezbollah</span>?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Sure, well, we're pushing for total disarmament of <span class="companylink">Hamas</span>, and frankly, everybody else. We actually have peace in the Middle East.</p>
<p class="articleParagraph enarticleParagraph" >As you know, the king of Saudi Arabia just left yesterday, and we had some great meetings, and he's made a contribution toward the United States of more than a trillion dollars. We have now over $20 trillion coming in. No country has ever had anything like that. Not even close. If you go to $2 trillion or $1 trillion, it's a lot. We have $20 or $21 trillion.</p>
<p class="articleParagraph enarticleParagraph" >I think that <span class="companylink">Hezbollah</span> has been a problem in Lebanon, a big problem. We're working with Lebanon. We're working with everybody in the Middle East. That's another thing I think we have in common -- we want to see peace in the Middle East. And we actually have now, for the first time, peace in the Middle East after 3,000 years. And now we're going to refine it, and I think you're going to see some very positive things happen.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: What is the potential for an invite to the Lebanese president to the White House?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Oh sure. Oh, I would do that. Absolutely. And if the mayor would like to be here for that meeting -- because I know he feels very strongly. I think you feel very, very strongly about peace in the Middle East.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: We desperately want it, and that's something that I shared with the president. When I spoke to New Yorkers who had voted for the president last November on Hillside Avenue and Fordham Road, I asked them why. I heard, again and again, two major reasons. One was that they want an end to forever wars -- they wanted an end to the taxpayers' dollars we had funding violations of human rights, and they wanted to address the cost-of-living crisis. And I appreciated the chance to discuss both of those things.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: He said a lot of my voters actually voted for him.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: One in 10.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: And I'm OK with that.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Mr. President, you threatened to send federal troops to New York City. You both have differences when it comes to ICE agents in New York City. Mr. Mamdani called <span class="companylink">ICE</span> a rogue government entity. I wonder how you reconcile your differences on both of those issues?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: I think we're going to work them out. And I think that, if we have known murderers and known drug dealers and some very bad people, you know, we want to get them out, and the mayor wants to have peace.</p>
<p class="articleParagraph enarticleParagraph" >We discussed this at great length, actually. Maybe more than anything else. He wants to have a safe New York. Ultimately, a safe New York is going to be a great New York. If it's not safe, no matter how well we do with pricing and with anything else -- we can talk about anything you want. If you don't have safe streets, it's not going to be a success.</p>
<p class="articleParagraph enarticleParagraph" >So we're going to work together, and we're going to make sure that if they are horrible people, then we want to get them out. I think he wants to get them out, maybe more than I do. So we'll work together. We discussed it at great length. Yes, please.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: First of all, for the mayor-elect: You're both from different parts of the political perspective. You're both populist, though, and I just wonder to what extent the president's campaign styles -- his techniques, his social media use -- inspired any part of your campaign?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: Well, I actually told the president that, you know, so much of the focus of our campaign has been on the cost-of-living crisis, and when we asked those New Yorkers who had voted for the president -- when we saw an increase in his numbers in New York City, that came back to the same issue. Cost of living. Cost of living. Cost of living.</p>
<p class="articleParagraph enarticleParagraph" >And they spoke about the cost of groceries, the cost of rent, the cost of Con Ed, the cost of child care. And too often, politicians are looking to lecture to New Yorkers what they should care about, as opposed to listen. And when we spoke to those voters who voted for President Trump, we heard them speak about cost of living. We focused on that same cost of living, and that's where I'm really looking forward to delivering for New Yorkers in partnership with the president on the affordability agenda.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: I think we have to work a little bit -- we talked about <span class="companylink">Con Edison</span>. We have to work a little bit on getting the prices -- because you know, we have gotten fuel prices way down, but it hasn't shown up in <span class="companylink">Con Edison</span>. And we're going to have to talk to them. If we're sending them fuel at a much lower price than it was a year ago, which is true, we have to get <span class="companylink">Con Edison</span> to start lowering their rates.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: Absolutely.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Last week, you told me you were pushing ahead with your plans to sue BBC for up to $5 billion. You were going to speak to Prime Minister Starmer as well. Is there any progress or any updates on those issues?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Well, we get along very well with the prime minister. We made a deal with U.K. I like him. He's a fine person, and, you know, I think they have some big energy problems. You know, they have got windmills all over the place. They're going to have to start using other methods, because their energy is out of control. Talking about in the U.K. It's out of control.</p>
<p class="articleParagraph enarticleParagraph" >And he's got that problem. He's got a big immigration problem, as you know, and he's got a big energy problem, and we talk about it. He's a good man. The prime minister is a good man.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Have you had have a chance to speak this week?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: I haven't spoken to him this week.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Mr. President, have you spoken to President Zelensky, or do you intend to speak?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: I've spoken with their people. We have a plan. It's horrible what's happening -- it's a war that should never have happened. It would never have happened if I was president, and it's a shame. I felt they should have acted quicker.</p>
<p class="articleParagraph enarticleParagraph" >But it's a cold winter, and a lot of the, a lot of the -- you talk about utilities -- but a lot of the big energy-producing plants have been under attack, to put it mildly, to put it nicely. Yeah, we have a way of getting peace, or we think we have a way of getting peace. He's going to have to approve it. It's so sad. So many people.</p>
<p class="articleParagraph enarticleParagraph" >You know, last month they lost 25,000 soldiers. This is something -- we haven't seen anything like this since the Second World War. And they are averaging six or seven thousand a week between the two of them -- dead soldiers, and it goes on and on. And, I think they are getting reasonably close, but -- I don't want to predict. I would have said that would have been one of my early ones.</p>
<p class="articleParagraph enarticleParagraph" >I did eight peace deals of countries, including India, Pakistan. You could even go -- in fact, they are coming here in a week or two -- go to the Congo and Rwanda. That was one -- 10 million people dead, and we worked something out on that. But so many.</p>
<p class="articleParagraph enarticleParagraph" >And the one I thought would have been for me, because I have a very good relationship with President Putin -- I thought that would have been maybe quicker, but it does take two to tango, and now, we just see all the death. And, you know, it doesn't affect us other than the fact that we don't want to see all of those people dead. Really, it's on the other side of the ocean, and it's a war that should have never happened. It did happen.</p>
<p class="articleParagraph enarticleParagraph" >I blame the person also sitting right behind this desk. This is a war that should have never happened, and it wouldn't have happened if I were president, but we're trying to save a lot of lives. They are losing -- they are losing 25 -- think of that -- 25,000 lives over the last short period of time. That's Ukrainian and Russian.</p>
<p class="articleParagraph enarticleParagraph" >And it's a shame.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: I want to ask the mayor-elect about a House resolution, just passed overwhelmingly, to condemn socialism -- including with 86 Democrats, all of House Dem leadership and the minority leader, Hakeem Jeffries, despite his endorsement of you. What's your reaction to that?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I have to be honest with you, I focus very little on resolutions. Frankly, I've been focusing --</p>
<p class="articleParagraph enarticleParagraph" >Reporter: It's against socialism.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I understand. I think that the focus is on the work at hand. I can tell you, I am someone who is a democratic socialist, I have been very open about that. And I know that there might be differences about ideology, but the place of agreement is the work that needs to be done to make New York City affordable. That's what I look forward to.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: He asked about your comment calling the president a fascist, and your answer was, ''President Trump and I have been clear in our positions and views.'' Are you affirming that you think President Trump is a fascist?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I've spoken about --</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: That's OK. You can just say it. That's easier. It's easier than explaining it. I don't mind.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: And Mr. President, I wanted to ask you also about this Ukraine plan.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Yeah.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: President Zelensky said today that his country would risk either giving up a partner or giving up his dignity. There has been criticism that this deal --</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: You mean that he doesn't like it?</p>
<p class="articleParagraph enarticleParagraph" >Reporter: It's unclear. He was sort of --</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: He'll have to like it, and if he doesn't like it, then you know, they should just keep fighting, I guess. You know.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: The suggestion that you made, though, was that if he doesn't accept it, that the U.S. would pull back its support for Ukraine.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Well, at some point he's going to have to accept something. You know, he hasn't accepted. You remember, right in the Oval Office, not so long ago, I said, ''You don't have the cards.'' Don't forget, I inherited this war. This war would never have happened. I inherited this war.</p>
<p class="articleParagraph enarticleParagraph" >And I thought he should have made a deal a year ago. Two years ago. The ultimate deal would have been if it never started -- that would have been a good deal. That could have been done too, if you had the right president, but you didn't have the right president.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Mr. President, the cost of living is something you and Mr. Mamdani seem to agree on. Democrats have run New York City for a long time. Mr. Mamdani, do you see Democrat policies specifically as being the problem -- and I'd like that be a question that both of you could answer -- in New York City?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: Look, I think that there are many things in our city where we have to own the responsibility of it. Things that existed long before the president was the president. And those are also part of the message of our campaign -- was to take on a broken politics of the past.</p>
<p class="articleParagraph enarticleParagraph" >And I ran against a number of candidates who represented different versions of that past. And what we found, time and again, is that working people were left behind in the politics of our city. And what we are looking to do is put those people right back at the heart of our politics so that we don't have a situation where we're in the wealthiest city in the history of the world and yet one in five can't even afford 2 dollars and 90 cents for a MetroCard.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: You know, we had some interesting conversation, and some of his ideas really are the same ideas that I have. A big thing on cost. The new word is ''affordability.'' Another word, it's just groceries. It's sort of an old-fashioned word, but it's very accurate. They are coming down. They are coming down.</p>
<p class="articleParagraph enarticleParagraph" >You know, we had -- both of us -- we had the highest inflation in the history of our country the last four years under the Biden administration. And we've got inflation down to a normal number. It will go even a little lower than that.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Mr. Mamdani often talks about New York City being covered by international law, that they will follow international law, doesn't often talk about the U.S. Constitution. What is your response to that?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Well, I don't know what you're referring to in terms -- it could be covered by international law, local law. It's covered by a lot of laws, but it's covered by U.S. law. Are you referring to anything in particular?</p>
<p class="articleParagraph enarticleParagraph" >Reporter: You just said that they're a city that endorses and enforces international law. Is that at odds with --</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: No, I don't know. Would you want to -- have you? Would you want to respond?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: Yeah, I think what I've shared with the president is our desire to not only follow the laws of our own city laws that protect New Yorkers, but also a desire for consistency in our politics across the board, and that's something we've talked about and something that I know many New Yorkers want.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Would you work with ICE then?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: We discussed ICE and New York City, and I spoke about how the laws that we have in New York City allow for New York City government to speak to the federal administration for about 170 serious crimes. The concerns that many New Yorkers have are around the enforcement of immigration laws on New Yorkers across the five boroughs, and most recently, we're talking about a mother and her two children, how this has very little to do with what that is.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: What we did is, we discussed crime. More than ICE, per se, we discussed crime. And he doesn't want to see crime, and I don't want to see crime, and I have very little doubt that we're not going to get along on that issue. And he wants to -- and he said some things that were very interesting, very interesting, as to housing construction, and he wants to see houses go up. He wants to see a lot of houses created, a lot of apartments built, et cetera. You know, we actually -- people would be shocked, but I want to see the same thing.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: I want to know, one of the policies as well that Mayor-elect Mamdani talked a number of times about on the campaign was shifting the tax burden for property taxes from what he called minority communities to white-based communities, and putting more taxes on white people. I also noticed in your acceptance speech you didn't mention -- you didn't mention anything about America or Christians or white people in general, and so, I didn't know if that was one of the policies that you guys had spoken about?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: We focused on affordability. We focused on the cost-of-living crisis. What I will say is that I'm very much interested in property tax reform because what we see right now in New York City is a system that is so inequitable that it can't even stand up in court. And the president and I spoke about the importance of not only building more housing but also making sure that regulation of housing is something that is manageable to actually get through and not the cause of yet another wait that we see in our city --</p>
<p class="articleParagraph enarticleParagraph" >Reporter: To be clear, you're continuing this idea of race-based property taxes.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: No, to be very clear</p>
<p class="articleParagraph enarticleParagraph" >Reporter: It's what you said --</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: No, the use of the term was a description of neighborhoods, not a description of intent.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: So you intend to tax the whiter neighborhoods more.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: No, we intend to create a fair property tax system, because we want a New York City that is not only fair and equitable, but also one that every New Yorker can afford.</p>
<p class="articleParagraph enarticleParagraph" >[Indistinguishable voices]</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Please go ahead.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Mr. Mamdani, anti-Israel protesters just targeted a synagogue in New York. Are you concerned about Jewish New Yorkers feeling welcome and safe in the city? And President Trump, you threatened to cut off federal funding to New York City. What policies would prompt you to do that? Would that be city-run grocery stores? Would it be something else?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Well, I think if we didn't get along, whether it's cut off or just make it a little bit difficult or not give as much, we want to see -- I use the term, we don't want good money going after bad. We just -- we don't want that to happen. I don't think that's going to happen.</p>
<p class="articleParagraph enarticleParagraph" >I did say, you know, subject to what policies are being set. We had a meeting today that actually surprised me. He wants to see no crime. He wants to see housing being built. He wants to see rents coming down, all the things that I agree with. We may disagree on how we get there. The rent coming down -- I think one of the things I really gleaned very, very much today, he would like to see them come down ideally by building a lot of additional housing. That's the ultimate way. He agrees with that, and so do I.</p>
<p class="articleParagraph enarticleParagraph" >But, if I read the newspapers, and the stories -- I don't hear that. But I heard him say it today. I think that's a very positive step. Now, I don't expect -- I expect to be helping him, not hurting him. A big help, because I want New York City to be great.</p>
<p class="articleParagraph enarticleParagraph" >Look, I love New York City. It's where I come from. I spent a lot of years there. Now I'm right here. We took a big step back with the mayor that we had, named de Blasio. I thought it was a tremendous setback for the city.</p>
<p class="articleParagraph enarticleParagraph" >I think this mayor can do some things that are going to be really great.</p>
<p class="articleParagraph enarticleParagraph" >[Cross talk]</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Go ahead.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: You're a billionaire. You have a different address nowadays than you used to. You used to call New York City home. Would you feel comfortable living in New York City under a Mamdani administration?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Yes, I would -- especially after the meeting. Absolutely.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: What makes you comfortable?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: We agree on a lot more than I would have thought. I think he's -- I want him to do a great job, and we'll help him do great job. You know, he may have different views, but in many ways, you know -- we were discussing, when Bernie Sanders was out of the race, I picked up a lot of his votes, and people had no idea, because he was strong on not getting ripped off in trade and lots of the things that I practiced, and been very successful on.</p>
<p class="articleParagraph enarticleParagraph" >Tariffs, a lot of things. Bernie Sanders and I agreed on much more than people thought, and when he was put out of the race -- I think quite unfairly, if you want to know the truth -- many of the Bernie Sanders voters voted for me, and I felt very comfortable frankly seeing that and saying that. And you know, it just turned out to be a statistical truth. But, no, I feel very comfortable. I would feel very, very comfortable being in New York, and I think much more so after the meeting. Yes, please.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: I have a question for you. But a very quick one for the mayor. Why did you fly here? Aren't trains greener?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I will use every form of transit, and I want to make sure that they are all affordable in New York City, and that's why making buses and fast and free is centerpiece of our campaign.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: There is a bus --</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Well, but I know -- if he flew, that's a lot quicker, too. You know, I mean -- he's working very hard. For him to be -- that's a long, that's a very -- that's a very long drive. I'll stick up for you. You know the plane takes you 30 minutes and driving takes you longer.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Mr. President, I wonder if you could clear up some confusion around a <span class="companylink">Washington Post</span> report. There is an explosive report that the Coast Guard is no longer going to characterize swastika and nooses as hate symbols. D.H.S. called that a lie and fake news. Can you clear up?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: I don't know anything about it. When was this written?</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Yesterday.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Well, look, the Coast Guard is an incredible group of people. I know them very well. We just ordered a lot of new Coast Guard cutters. Beautiful. They make the most magnificent ship. They look like yachts with lots of guns on them. So I don't know. I haven't seen any report like that, but certainly we want them to remain a great force, and they are.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: You did the peace in all the nine months around the world. I would like to ask Mr. Mamdani: You've accused the <span class="companylink">U.S. government</span> of committing genocide in Gaza while President Trump is working on this. Why -- why that?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I have spoken about the Israeli government committing genocide, and I have spoken about our government funding it. And I shared with the president in our meeting about the concern that many New Yorkers have of wanting their tax dollars to go toward the benefit of New Yorkers and their ability to afford basic dignity.</p>
<p class="articleParagraph enarticleParagraph" >And what we see right now, we're in the ninth consecutive year of more than a hundred thousand school children being homeless in our city, and there is a desperate need not only for the following of human rights but also the following through on the promises we've made New Yorkers, and I appreciated the meeting we had and the work that we can do.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Do you agree that President Trump did do a peace and worked hard to make the peace, because he worked hard to do the peace in the Middle East and everywhere? Do you agree with that?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I appreciate all efforts toward peace, and I shared with President Trump, when I spoke to Trump voters on Hillside Avenue -- including one of whom was a pharmacist that spoke about how President Trump's father actually went to that pharmacy not too far from Jamaica Estates -- that people were tired of seeing our tax dollars fund endless wars. And I also believe that we have to follow through on the international human rights, and I know that still today, those are being violated, and that continues to be work that has to be done no matter where we're speaking of.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Thank you, Mr. President. Do you view the mayor-elect as a true leader of the Democratic Party, and do you think Leader Schumer and Leader Jeffries should have to follow his lead?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Well, look, I hope they have great leaders. This is a man that right now I think is focused on New York City. I really think he has a chance to do a great job. We're going to help him. But I really think he has a chance to do a great job, but I'll let you answer that. Do you consider yourself the leader of the Democrats? I think it's more appropriate for him.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I consider myself the next mayor of New York City, and I keep my horizons firmly on New York City, and I appreciate the meeting with the president, which focused, again, on the five boroughs and whether New Yorkers can afford to live there.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: By the way, being the mayor of New York City is a big deal. I always said, you know, one of the things I would have loved to be some day is the mayor of New York City. Being the mayor of New York -- and especially now, because I think you're really at a turning point, one way or the other. It could go great, or it can go in a different direction, and I think you really have a chance to make it great.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Mr. President, you said you grew up in New York City. Mr. Mamdani, does New York City love President Trump?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: New York City loves a future that is affordable. And I can tell you that there were more New Yorkers who voted for President Trump in the most recent presidential election because of that focus on cost of living, and I'm looking forward to working together to deliver on that affordability agenda.</p>
<p class="articleParagraph enarticleParagraph" >President Trump: Got a lot. I got a lot of votes. One more, go ahead. One or two more. Go ahead.</p>
<p class="articleParagraph enarticleParagraph" >[Inaudible]</p>
<p class="articleParagraph enarticleParagraph" >I tell you, the press has eaten this thing up. You know, I've had a lot of meetings with the heads of major countries -- nobody cared. This meeting, that you people have gone crazy. You know, outside, you have hundreds of people waiting. This is just a small little group -- for some reason, the press has found this to be a very interesting meeting. The biggest people in the world, they come over from countries -- nobody cares. But they did care about this meeting, and it was a great meeting. Go ahead.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Yeah, Mr. President. I was going to ask you exactly that: Why do you think there is so more -- you know, so much excitement around this?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Because I think he's different. I think he's different. And that can be in a very positive way, but I think he's different than, you know, your typical guy who runs, wins, becomes mayor, maybe, and nothing exciting.</p>
<p class="articleParagraph enarticleParagraph" >Because he has a chance to really do something great for New York. New York is at a very critical point. And he does need the help of the federal government to really succeed. We're going to be helping him. But he's different than, you know, your average candidate. He came out of nowhere. I said, he's a great campaign manager standing over there. He came out of -- he came out of nowhere.</p>
<p class="articleParagraph enarticleParagraph" >What did you start off at, 1 or 2? And then I'd watch and say, ''Who is this guy?'' He was at 1. Then he was at 3. Then he was at 5. Then he was at 9. Then he went up to 17. I said, ''Hm, let's get a little bit of trust there, right?'' And then all of a sudden, he wins a primary that nobody expected he was going to win. It's a great -- a great tribute, and it's an amazing thing that he did.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I'll just add -- I'm sorry, I'll just add one thing to what the president said. One thing I also appreciated is, in our meeting, to appreciate a portrait of F.D.R., and the incredible work that was done with the New Deal and also in thinking about what it can look like when the federal government and New York City government work together to deliver on affordability -- it can be transformative.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: You know, we have a great portrait of F.D.R. that I found in the vaults, that was missing for years. I found it, and I put it up. He's a Democrat -- to the best of my knowledge, he's a Democrat, and when the mayor saw that portrait, he said, ''Sir, do you mind if I have a picture taken by that portrait?'' It's an amazing portrait -- hope the picture comes out good -- but it's an amazing portrait in the cabinet room. So he's a big fan of the New Deal, I guess, and of F.D.R.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: You said you both spoke about crime. There are many police officers set to come off the rolls at the end of this year in New York City. Are you going to allow those police to be replaced with police officers, actual cops, and are you going to require that that happens -- will there be some consequence?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Well, I hope it happens, but again, that's going to be ultimately the mayor's decision.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: What's your answer?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: That I look forward to delivering public safety with the N.Y.P.D., and I've said over the course of our campaign that we have the number of police officers today, they are the ones --</p>
<p class="articleParagraph enarticleParagraph" >Reporter: What's that number?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: That's budgeted about a 35,000 head count. And I think the key thing is that we have to make it easier for police to focus on police work -- not ask them to respond to 200,000 mental health calls a year.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: So is that a reduction from what you're at right now? Are you committing to maintaining the same level of cops?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I've committed over the course of the campaign to maintain the 35,000. That's the head count that we have through the campaign --</p>
<p class="articleParagraph enarticleParagraph" >Reporter: And not replace them with caseworkers, social workers?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: No, I've said that's the head count that we want. What we need to do is make sure they can focus on serious crime.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: And he just retained a great police commissioner, I believe, right?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: Yes, yes, we did. Commissioner Tisch.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: If the newspapers are correct.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: That one they are correct about.</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: He retained, I think, somebody that is a -- she's a good friend of some of the people in my family, of Ivanka, and they say she's really good and competent. And he just retained her, so that's a good sign.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Are there small topics that you see that you're disagreeing on in the future? And do you think you'll have more meetings with this?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: There will be topics that we disagree on, and I think we'll probably come to a conclusion. And ultimately, he'll convince me, or I'll convince him. You know, it's for the good of New York. Ultimately it's for the good of New York. I don't care about affiliations or parties or anything else. I want to see -- if this city could be unbelievable, if he could be a spectacular success, I would be very happy.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Do you think you guys will meet more in the future, too?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: Excuse me?</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Do you think you will meet again in the future, you know, throughout the initial --</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: I think we will. I think we will. I hope we do. I enjoyed the meeting. We had a great meeting. Please.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Mr. President, Republican Elise Stefanik has campaigned multiple times by calling Zohran Mamdani a jihadist. Do you think you're standing next to a jihadist right now in the Oval Office?</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: No, I don't. But she's out there campaigning. You know, you say things sometimes in a campaign.</p>
<p class="articleParagraph enarticleParagraph" >Reporter: Isn't that sort of --</p>
<p class="articleParagraph enarticleParagraph" >Mr. Trump: She's a very capable person, but you really have to ask her about that. But I don't particular -- I think I met with a -- I've met with a man who is a very rational person. I met with a man who wants to see -- really wants to see New York be great again.</p>
<p class="articleParagraph enarticleParagraph" >I can say, again, because New York was great. You know, when I came down to Washington initially, the city was so hot. It was doing great. We were having some telltale signs of problems. We had a mayor that was not doing a great job, but still, it was moving along.</p>
<p class="articleParagraph enarticleParagraph" >And it went bad. It went, you know, pretty bad. And he can, I think it's been at lower points, but it went pretty bad. I think he can bring it back. Now the question is, will he bring it back all the way? Will he bring it back greater than ever before? Which is -- I guarantee, that's his wish. I think he wants to make it greater than ever before.</p>
<p class="articleParagraph enarticleParagraph" >And if he can, we'll be out there cheering. I'll be cheering for him. OK. Thank you very much, everybody.</p>
<p class="articleParagraph enarticleParagraph" >Thank you very much.</p>
<p class="articleParagraph enarticleParagraph" >[Inaudible reporter questions]</p>
<p class="articleParagraph enarticleParagraph" >Mr. Mamdani: I care very deeply about Jewish safety, and I look forward to rooting out antisemitism across the five boroughs and protecting Jewish New Yorkers and every New Yorker who calls the city home.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | greg : Regional Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Foreign Desk</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>The New York Times Company</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NYTF000020251122elbm0004e</td></tr></table><br/></div></div><br/><span></span><div id="article-NYTF000020251122elbm00032" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/nytfLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>CLM</b>&nbsp;</td><td>GUEST ESSAY</td></tr>
<tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Editorial Desk; SECTA</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>The First Madam President Is Still Coming</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Gail Collins </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1163 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The New York Times</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>NYTF</td></tr><tr><td align="right" valign="top" class="index"><b>ED</b>&nbsp;</td><td>Late Edition - Final</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>23</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 The New York Times Company.  All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Did you notice that when we went to the polls this month, voters in New Jersey and Virginia elected female candidates for governor?</p>
<p class="articleParagraph enarticleParagraph" >Big news! Come January, America will have women running 14 states and they. ...</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Hey, wait a minute. We're going to celebrate the fact that this country has reached the historic moment when 28 percent of its governors are female?</p>
<p class="articleParagraph enarticleParagraph" >That's actually kind of depressing.</p>
<p class="articleParagraph enarticleParagraph" >I started my journalistic career in Connecticut covering Ella Grasso, who in 1974 became the first woman not succeeding her husband ever elected governor in the United States. She was nationally known for her motherly demeanor in public, and I always cherished the story about a minor bill she opposed that contrasted with that image. The bill, to allow bow-and-arrow hunting on Sundays, somehow passed, and shortly after, Grasso came up behind one of the sponsors at an event and whispered in his ear: ''If I go walking on Sunday and if I get an arrow in my ass, I know who's going to come and pull it out.''</p>
<p class="articleParagraph enarticleParagraph" >Always figured Grasso would be followed by a flood of talented women chosen to run their states. Sigh. Well, it's been more like a high-quality drizzle. But the story got a couple of new pages this month when in New Jersey Mikie Sherrill, a Democrat, beat the Republican Jack Ciattarelli for governor by a whopping 57 percent to 43 percent, and in Virginia, another Democrat, Abigail Spanberger, won and will become the first female governor in the state's history. Her election was pretty much preordained, given that Virginia's citizens were reeling from President Trump's reign of terror when it comes to laying off federal workers.</p>
<p class="articleParagraph enarticleParagraph" >In Virginia it was actually an all-female contest. In another era we might have been excited about the Republican, Winsome Earle-Sears, who's the first female lieutenant governor and first Black woman elected to state office there. But truth be told, she didn't run a terrific campaign and she had to do it under that Trump cloud.</p>
<p class="articleParagraph enarticleParagraph" >New Jersey was way more interesting. Sherrill had a theoretically tough opponent in Ciattarelli, a former state legislator who'd been the Republican nominee in 2021 and ran a very close race against the incumbent governor, Phil Murphy.</p>
<p class="articleParagraph enarticleParagraph" >Ciattarelli had a very well-funded campaign, centered on the inevitable promise to reduce property taxes. But he ran into disaster during a debate in October when asked to rate the Trump administration. Sherrill's heart must have been singing when Ciattarelli volunteered that he'd give the president an A.</p>
<p class="articleParagraph enarticleParagraph" >Shudder.</p>
<p class="articleParagraph enarticleParagraph" >Sherrill ran a very good campaign. Unlike many, many major political candidates of both sexes, she actually could boast about her military service, and a picture of the naval helicopter she once flew showed up pretty much everywhere.</p>
<p class="articleParagraph enarticleParagraph" >But her biggest boost came from Trump, who didn't seem overly concerned about promoting Ciattarelli's chances. Imagine how the Republican candidate for governor of New Jersey must have felt when -- soon before the election -- Trump announced he wanted to cancel a long-awaited, in-progress rail tunnel under the Hudson River that would make life easier for many, many New Jersey commuters.</p>
<p class="articleParagraph enarticleParagraph" >Really, just to show he doesn't like Chuck Schumer or New York City's incoming leftie mayor? What a guy. Thanks in part to the president, Sherrill, as governor-elect, has helped make history.</p>
<p class="articleParagraph enarticleParagraph" >Americans chose the first female governor in 1924. Two, actually.</p>
<p class="articleParagraph enarticleParagraph" >Nellie Tayloe Ross was the wife of the governor of Wyoming, who died suddenly while in office. She was deeply unenthusiastic about stepping into her husband's shoes, but the Democrats wanted to keep control of the government by getting her to fill out the term.</p>
<p class="articleParagraph enarticleParagraph" >Kind of interesting, isn't it, that the story of women fighting prejudice against their running for office begins with a woman who fought the people who wanted to give her one? But after winning a special election, Ross really got into being governor -- especially having the chance to help poor farmers, miners and female workers. She ran for re-election in 1926, but lost.</p>
<p class="articleParagraph enarticleParagraph" >She was later named the first female director of the U.S. Mint. Ross died at 101 in 1977. Just saying.</p>
<p class="articleParagraph enarticleParagraph" >And then there was Miriam Ferguson, who got elected governor of Texas at the same time Ross was taking over Wyoming. Ferguson, who was known as Ma, also succeeded her husband, but she had a slightly different story, since James Ferguson was still alive, just impeached.</p>
<p class="articleParagraph enarticleParagraph" >Ma Ferguson dedicated her term to pardoning criminals -- an average of 100 a month. This was either a very early example of American women's attempts to reform the penal system or a series of rewards for convicts who managed to come up with large enough bribes.</p>
<p class="articleParagraph enarticleParagraph" >Probably the latter, and if so, not one of the shining chapters in our story about women's road to the White House. The Ferguson campaign did promise that if Ma was elected, voters would be getting ''two governors for the price of one.'' Which is eerily similar to what Bill Clinton said in 1992, when his presidential campaign marketed his then-very-popular wife, Hillary, and promised voters they'd be getting, yeah, ''two for the price of one.''</p>
<p class="articleParagraph enarticleParagraph" >Anyhow, about our new female governors. Sherrill won't be the first woman to run New Jersey -- remember Christine Todd Whitman -- but she's already been mentioned in predictions about presidential candidates in 2028.</p>
<p class="articleParagraph enarticleParagraph" >Yeah, yeah, it's a long time away. But we've got a lot to think about as we prepare. How do we squash the prejudice against female presidential nominees, which has always been with us, but became even worse after Kamala Harris got whomped by Donald Trump?</p>
<p class="articleParagraph enarticleParagraph" >(By the way, who would like to be the first person to tell Harris to drop all her fantasies about running again? Do I see a show of hands?)</p>
<p class="articleParagraph enarticleParagraph" >Don't worry -- since there will be real primaries next time around, voters will get to see lots of possibilities among the smart, hard-working and principled governors, members of Congress and other strong female politicians.</p>
<p class="articleParagraph enarticleParagraph" >Can't wait to see who else pops up near the front. It can't come soon enough.</p>
<p class="articleParagraph enarticleParagraph" >Gail Collins, a contributing Opinion writer, worked for The Times for 30 years, as a member of the editorial board, as the editorial page editor and as an Opinion columnist from 2007 until earlier this year.</p>
<p class="articleParagraph enarticleParagraph" >The Times is committed to publishing a diversity of letters to the editor. We'd like to hear what you think about this or any of our articles. Here are some tips . And here's our email: letters@nytimes.com .</p>
<p class="articleParagraph enarticleParagraph" >Follow the <span class="companylink">New York Times</span> Opinion section on <span class="companylink">Facebook</span>, <span class="companylink">Instagram</span>, TikTok, Bluesky, <span class="companylink">WhatsApp</span> and Threads.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | gvote : Elections | ncat : Content Types | ncolu : Columns | nedc : Commentaries/Opinions | nedi : Editorials | nfact : Factiva Filters | nfcpex : C&E Executive News Filter</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States | use : Northeast U.S. | usnj : New Jersey</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Editorial Desk | Op-Ed</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>The New York Times Company</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document NYTF000020251122elbm00032</td></tr></table><br/></div></div><br/><span></span><div id="article-ATIBNS0020251122elbm0008d" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/atibnsLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>'You can just say yes': Trump gives jaw-dropping answer on fascism to Mamdani!</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>India Blooms News Service </td></tr>
<tr><td align="right" valign="top" class="index"><b>CR</b>&nbsp;</td><td>Distributed by Contify.com </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>401 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>India Blooms News Service</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>ATIBNS</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright © 2025 India Blooms, distributed by Contify.com </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Washington DC/IBNS: A surprise intervention from his staunch opponent US President Donald Trump saved New York City's new and first Muslim Mayor-elect Zohran Mamdani from a question on whether he affirms the Republican is a "fascist".</p>
<p class="articleParagraph enarticleParagraph" >During the press briefing at the White House, a journalist asks Mamdani, "Are you affirming that you think President Trump is a fascist?"</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >"I've spoken about," Mamdani said as he tried to answer the question.</p>
<p class="articleParagraph enarticleParagraph" >But Trump, who was seated beside, interrupted Mamdani and jokingly said, "That's okay. You can just say yes. That's easier."</p>
<p class="articleParagraph enarticleParagraph" >Mamdani says, "Okay, alright," prompting the President to pat on the Mayor-elect's arms and add, "It's easier than explaining it. I don't mind."</p>
<p class="articleParagraph enarticleParagraph" >Q: "Are you affirming that you think President Trump is a fascist?"<span class="colorLinks">@ZohranKMamdani [https://twitter.com/ZohranKMamdani?ref_src=twsrc%5Etfw]</span>: "I've spoken about."</p>
<p class="articleParagraph enarticleParagraph" >President Trump: "That's okay. You can just say yes."</p>
<p class="articleParagraph enarticleParagraph" >Mamdani: "Okay. Alright."</p>
<p class="articleParagraph enarticleParagraph" >Trump: "It's easier than explaining it. I don't mind." <span class="colorLinks">pic.twitter.com/7VgsbGUelX [https://t.co/7VgsbGUelX]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >— CSPAN (@cspan) <span class="colorLinks">November 21, 2025 [https://twitter.com/cspan/status/1991974111350817250?ref_src=twsrc%5Etfw]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Trump on Friday called his meeting with New York Mayor-elect Zohran Mamdani “very productive,” signalling an end to the sharp exchanges that had marked the election campaign.</p>
<p class="articleParagraph enarticleParagraph" >Throughout the NYC Mayoral election campaign, Trump had backed Democratic former Governor Andrew Cuomo, who ran as an independent but lost to Mamdani, the clear winner. Trump had also threatened to cut federal funding to New York if Mamdani prevailed and repeatedly labelled him a “communist.”</p>
<p class="articleParagraph enarticleParagraph" >Asked if he would feel comfortable staying in New York in the future, Trump told CNN: “I really would – especially after the meeting.”</p>
<p class="articleParagraph enarticleParagraph" >“We agree on a lot more than I really thought,” the President said, adding: “We’ve just had a great meeting — a really good, very productive meeting. We have one thing in common, which is we want this city of ours that we love to do very well.”</p>
<p class="articleParagraph enarticleParagraph" >Trump said he congratulated Mamdani and discussed shared priorities, including housing, rising food prices, and declining oil prices.</p>
<p class="articleParagraph enarticleParagraph" >Extending a warm welcome, Trump said he expected Mamdani to be a “great Mayor.”</p>
<p class="articleParagraph enarticleParagraph" >“The better he does, the happier I am. I will say there’s no difference in party,” Trump said.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani will take office on January 1.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>India Blooms News Service</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document ATIBNS0020251122elbm0008d</td></tr></table><br/></div></div><br/><span></span><div id="article-MONECT0020251122elbm000e0" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/monectLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>world</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>
                           Shashi Tharoor lauds Trump-Mamdani meeting, hopes for similar civility in India: ‘This is how democracy should work’</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>367 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Moneycontrol.com</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>MONECT</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. <span class="colorLinks">www.moneycontrol.com [http://www.moneycontrol.com]</span>
               </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Tharoor praised the Trump-Mamdani interaction as a model for political rivals to cooperate once voters have spoken.</p>
<p class="articleParagraph enarticleParagraph" >Congress MP Shashi Tharoor on Saturday praised the interaction between US President Donald Trump and New York City Mayor-Elect Zohran Mamdani, calling it a reflection of a mature political culture where opponents contest fiercely during elections but work together once the public has delivered its verdict.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Sharing his views on X, Tharoor wrote, “This is how democracy should work. Fight passionately for your point of view in elections, with no rhetorical holds barred. But once it’s over, and the people have spoken, learn to cooperate with each other in the common interests of the nation you are both pledged to serve."</p>
<p class="articleParagraph enarticleParagraph" >He added that he would “love to see more of this in India" and was “trying to do his part" to encourage the same political civility.</p>
<p class="articleParagraph enarticleParagraph" >This is how democracy should work. Fight passionately for your point of view in elections, with no rhetorical holds barred. But once it’s over, & the people have spoken, learn to cooperate with each other in the common interests of the nation you are both pledged to serve. I… <span class="colorLinks">https://t.co/NwXPZyhn20 [https://t.co/NwXPZyhn20]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >— Shashi Tharoor (@ShashiTharoor) <span class="colorLinks">November 22, 2025 [https://twitter.com/ShashiTharoor/status/1992111711147671981?ref_src=twsrc%5Etfw]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Tharoor’s remarks come at a time when the Congress has adopted a sharper tone against the BJP and Prime Minister Narendra Modi. His recent comments at the Ramnath Goenka Lecture, where he described the PM’s speech as both an economic outlook and a “cultural call to action,” drew criticism from some within his own party, highlighting internal discomfort over perceived praise for the government.</p>
<p class="articleParagraph enarticleParagraph" >The Trump–Mamdani meeting itself followed a heated pre-election phase where both leaders exchanged harsh words online and in public speeches. However, when they finally met after Mamdani requested a meeting at the White House, visuals showed a surprisingly friendly interaction, turning a bitter standoff into a moment of cooperation.</p>
<p class="articleParagraph enarticleParagraph" >It was this shift, political adversaries putting aside their hostility to prioritise governance, that Tharoor highlighted as an example for India’s political leadership to emulate.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | gvote : Elections</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>asiaz : Asia | devgcoz : Emerging Market Countries | dvpcoz : Developing Economies | india : India | sasiaz : South Asia</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>world</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Network18 Media & Investments Ltd.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document MONECT0020251122elbm000e0</td></tr></table><br/></div></div><br/><span></span><div id="article-DTMD000020251122elbm0002x" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/dtmdLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>News</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Experts: Free child care in NYC feasible; Mamdani plan will require big changes</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Madeline Mitchell, USA TODAY </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1070 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The Daily Times</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>DTMD</td></tr><tr><td align="right" valign="top" class="index"><b>ED</b>&nbsp;</td><td>1; ESN</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>A2</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© Copyright Gannett 2025 All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Rebecca Bailin pays $32,000 a year for her five-month-old's all-day child care in New York City.</p>
<p class="articleParagraph enarticleParagraph" >That's higher than the national average, but not unusual. <span class="companylink">Care.com</span>'s 2025 Cost of Care Report found many parents spend 22% of their household income on child care.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Along with being a parent, Bailin is executive director of New Yorkers United for Child Care, a nonprofit that started organizing parents, grandparents and anyone else in favor of free child care in 2023.</p>
<p class="articleParagraph enarticleParagraph" >"People are spending enormous amounts and they can't make it work, but they don't have a choice," Bailin said. Families tell her they feel embarrassed to share how much they pay for child care, "because there's this real feeling that it's your fault. That you weren't savvy enough."</p>
<p class="articleParagraph enarticleParagraph" >But with mayor-elect Zohran Mamdani taking over, Bailin said she's hopeful their shared dream of free child care will come true.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani won over New Yorkers with the promise of a more affordable city. The idea of universal child care sparked interest among residents and out-of-state folks alike, as child care remains the highest cost for most American families besides rent. In nearly every state, the cost of child care for two kids is more than rent, according to an analysis from <span class="companylink">Child Care Aware of America</span>.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani's plan will require big changes to New York's current child care system, an estimated $6billion and hundreds more child care workers. Those workers are already stretched thin and paid too little, experts say. Even among those who agree universal child care is the ultimate goal, there's disagreement over how to achieve it.</p>
<p class="articleParagraph enarticleParagraph" >Still, with Mamdani's election, some advocates say New York City is closer than ever to making free child care a reality, though it won't be easy, and it won't happen overnight.</p>
<p class="articleParagraph enarticleParagraph" >If everything goes well, child care policy experts say New York could establish a free child care infrastructure across the state in about five years.</p>
<p class="articleParagraph enarticleParagraph" >"This is a policy that can absolutely happen," said Alyson Silkowski, a senior policy advisor for the liberal think tank New America's New Practice Lab. "It seems, for the first time, that the political stars are almost in alignment."</p>
<p class="articleParagraph enarticleParagraph" >About 174,000 children in 104,000 New York families received child care assistance in 2024, according to the state. A mix of federal, state and local dollars contribute to child care assistance programs.</p>
<p class="articleParagraph enarticleParagraph" >To get to universal free child care, subsidy programs will have to be scaled up, meaning some families who don't have free child care now, could by this time next year, Silkowski said.</p>
<p class="articleParagraph enarticleParagraph" >Child care advocates disagree on who should gain access first.</p>
<p class="articleParagraph enarticleParagraph" >Bailin proposed a process that scales by age, adding more families to the program starting with preschool and working down to infants. She suggests first expanding the city's universal preschool program to more families and more neighborhoods.</p>
<p class="articleParagraph enarticleParagraph" >Other advocates say it's better to scale by need. The current income-based system is flawed, Marcou-O'Malley said. But it addresses the needs of families with multiple children.</p>
<p class="articleParagraph enarticleParagraph" >Bailin argues that economic eligibility systems are stigmatizing and difficult to navigate.</p>
<p class="articleParagraph enarticleParagraph" >"It shouldn't be a complicated system of income tests to prove your worth," she said. "We all need this."</p>
<p class="articleParagraph enarticleParagraph" >However the expansion happens, experts agree that in scaling the system, child care workers' pay will also need to be scaled up to account for the child care workforce shortage.</p>
<p class="articleParagraph enarticleParagraph" >Silkowski said free child care will cost $6billion for New York City and upwards of $14billion for the state.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani can do a lot on his own next year, she said, to identify money in the city's budget to add child care seats and waive copays on child care vouchers.</p>
<p class="articleParagraph enarticleParagraph" >But experts agree that the city will need to partner with the state, which means that universal free child care relies on Mamdani's ability to get along with New York Gov. Kathy Hochul.</p>
<p class="articleParagraph enarticleParagraph" >The plan will likely include adjusting the state's tax system and raising taxes on corporations and the ultra-wealthy, said Marina Marcou-O'Malley of the Alliance for Quality Education. Silkowski said there's also a possibility the city or state will ask employers to contribute.</p>
<p class="articleParagraph enarticleParagraph" >Marcou-O'Malley believes Hochul may prove to be New York's biggest obstacle to universal free child care. Recently, Hochul pumped the brakes on another one of Mamdani's campaign promises: free buses.</p>
<p class="articleParagraph enarticleParagraph" >She "time and time again has said publicly that she's not willing to consider raising revenue," Marcou-O'Malley said.</p>
<p class="articleParagraph enarticleParagraph" >Right now, New York City businesses − which generate most of the state's revenues − are doing well.</p>
<p class="articleParagraph enarticleParagraph" >"But I don't know what Washington is going to do," Hochul said at a Nov.17 media briefing. "Are they going to try and jam us up for another $3billion in Medicaid costs? This is the uncertainty which makes it challenging to do what we're doing."</p>
<p class="articleParagraph enarticleParagraph" >However, Hochul has stated publicly that she supports universal free child care, and she's invested significant state funds to expand child care subsidy programs, said Silkowski, who previously worked as an assistant policy director for Hochul.</p>
<p class="articleParagraph enarticleParagraph" >Bailin argues the city can no longer afford not to pay for child care: "We are losing a tax base because people are fleeing New York. We are losing workers because people can't work or they have to cut their hours. They can't put down roots, they can't buy homes, they can't pay off debt."</p>
<p class="articleParagraph enarticleParagraph" >It's safe to say other cities and states will be looking to New York to see if and how universal free child care pans out.</p>
<p class="articleParagraph enarticleParagraph" >"People are excited about the idea," said Shoshana Hershkowitz, campaign manager for the Empire State Campaign for Child Care. Universal child care "is really popular and has appeal across all sorts of political lines and demographics."</p>
<p class="articleParagraph enarticleParagraph" >It's not just about affordability, she said. It's about the developmental well-being of kids: "Those first three years, as far as brain development, are so crucial."</p>
<p class="articleParagraph enarticleParagraph" >This coverages is supported by a partnership with Pivotal and Journalism Funding Partners. Funders do not provide editorial input.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | glife : Living/Lifestyle | gparen : Parenting/Parenthood | ncat : Content Types | nfact : Factiva Filters | nfce : C&E Exclusion Filter | niwe : IWE Filter | nnam : News Agency Materials</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Gannett Co., Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document DTMD000020251122elbm0002x</td></tr></table><br/></div></div><br/><span></span><div id="article-UWIR000020251122elbm000ky" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/uwirLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Hopkins Political Union hosts debate about the future of party platforms</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>880 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>U-Wire</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>UWIR</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© 2025, M2 Communications. All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >
                        <span class="companylink">Johns Hopkins University</span> ; Baltimore, MD - news</p>
<p class="articleParagraph enarticleParagraph" >By JULIA SCHAGER</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >On Tuesday, Nov. 11, the Hopkins Political Union hosted an open-forum debate on the future of the Democratic and Republican parties. The organization, formed in 2024 in collaboration with the Stavros Niarchos Foundation Agora Institute and the Heterodox Academy, aims to promote thoughtful political dialogue among students.</p>
<p class="articleParagraph enarticleParagraph" >Aneesh Swaminathan, the president of HPU and the College Republicans, began the event with remarks about the importance of building a campus community where diverse perspectives are welcome. Next, moderator Dylan Faulkner Selterman, an associate teaching professor in the Department of Psychological and Brain Sciences, and Mary Bruce, the assistant director of public programming at the SNF Agora Institute, described the structure of the event and encouraged attendees to participate respectfully. Bruce then asked the audience what it means to have a good debate. One student responded.</p>
<p class="articleParagraph enarticleParagraph" >“Being open to new information, even if it contradicts your own beliefs, absolutely,” they said.</p>
<p class="articleParagraph enarticleParagraph" >The debate was structured around two resolutions. The first concerned whether democratic socialism is the future of the Democratic Party. Two members on opposing sides of the resolution gave speeches framing the major factors involved, starting with Swaminathan.</p>
<p class="articleParagraph enarticleParagraph" >“Mamdani proves that democratic socialist ideas aren't just slogans – they're winnable and workable. He had the highest election turnout since 1969,” he said.</p>
<p class="articleParagraph enarticleParagraph" >Another member of the club then gave an alternative viewpoint, claiming that democratic socialism is not the future of the party.</p>
<p class="articleParagraph enarticleParagraph" >“The [Democratic] Party should stop treating ideas such as democratic socialism as a dirty word and allow candidates to best represent their constituency in order to expand the Big Ten coalition, which empowers the party and better integrate the youth progressives into the party,” he said.</p>
<p class="articleParagraph enarticleParagraph" >The discussion was then extended to include the audience, who took turns sharing their opinions with a two-minute limit. Students expressed concerns about the rising tide of populism. Others focused on whether voters in metropolitan areas like New York City can represent national Democrats. However, some communicated hope about the benefits of expanded social programs.</p>
<p class="articleParagraph enarticleParagraph" >The second contention regarded whether MAGA Republicans are here to stay, referring to the camp of pro-Trump Republicans and the vitality of their policy base. This contention was introduced first by junior Timothy Allen.</p>
<p class="articleParagraph enarticleParagraph" >“When the right conditions are met, the vaguely defined populist movement that Trump created will in fact, be quite easy to adapt for his successors,” he said. “While it may seem at this moment that Trump dominates the Republican Party such that nobody can replace him, the movement to conservatism underpinned by a set of policy principles – isolationism, fiscal conservatism and Christian nationalism – brought together through a terribly flexible populism.”</p>
<p class="articleParagraph enarticleParagraph" >Swaminathan followed up with his own introduction.</p>
<p class="articleParagraph enarticleParagraph" >“I'm skeptical because I believe there is a great threat, in my humble opinion, to the [Make America Great Again ] movement and socially conservative moral vision that comes from the alt-right,” he said. “An open question, I believe, remains: will the movement's tenacity prove sufficient to hold this coalition together, and, more importantly, to build upon it towards a coherent governing vision that outclassed its founding personality?”</p>
<p class="articleParagraph enarticleParagraph" >The floor was opened once again for comments from attendees. Some expressed the difficulty of maintaining a movement with such a wide-ranging set of policy ideas, noting the recent fracturing of relations among right-wing public figures such as Ben Shapiro and Tucker Carlson following the death of political activist Charlie Kirk. Others commented on the recent blue wave in November elections and the potential receding support for MAGA Republicans from centrist voters.</p>
<p class="articleParagraph enarticleParagraph" >During this part of the discussion, issues regarding whether alt-right groups should feel represented by the MAGA Republicans became central to the debate. Some students were adamant that over half of voters in the 2024 presidential election could not have supported white nationalism. Other students cited controversial immigration policy and support from alt-right groups as proof of a permanent shift in Republican ideology.</p>
<p class="articleParagraph enarticleParagraph" >In an interview with the News-Letter, Selterman explained the inspiration for the event.</p>
<p class="articleParagraph enarticleParagraph" >“Research has shown that one of the big reasons for political polarization in America is pluralistic ignorance, which is to say that people misunderstand each other by overestimating disagreement,” he wrote. “HPU provides a common space for students to thoughtfully listen and engage constructively.”</p>
<p class="articleParagraph enarticleParagraph" >Selterman also commented on the discourse of the event itself. “In the event, students spoke about their concerns, their predictions, and critiques of mainstream political movements,” he wrote. “They also spoke to each other by challenging each other's viewpoints.”</p>
<p class="articleParagraph enarticleParagraph" >In an interview with The News-Letter, sophomore Rania Dey Meyer commented on what motivated her to attend the event.</p>
<p class="articleParagraph enarticleParagraph" >“I did think there were pretty diverse opinions,” she said. “The discussions got off topic very quickly, and a lot of people were debating not about whether democratic socialism is the future of the party but whether or not it’s good.”</p>
<p class="articleParagraph enarticleParagraph" >The <span class="companylink">HPU</span> will continue to hosts debates of this nature throughout the year, focused on timely issues and the political concerns of Hopkins students.</p>
<p class="articleParagraph enarticleParagraph" >Have a tip or story idea?</p>
<p class="articleParagraph enarticleParagraph" >Let us know!</p>
<p class="articleParagraph enarticleParagraph" >((Distributed for UWIRE via M2 Communications (<span class="colorLinks">www.m2.co.uk [http://www.m2.co.uk]</span>))</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gedu : Education | gpir : Politics/International Relations | gpol : Domestic Politics | guni : University/College</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Normans Media Ltd</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document UWIR000020251122elbm000ky</td></tr></table><br/></div></div><br/><span></span><div id="article-UWIR000020251122elbm000kd" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/uwirLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Columbia considers expanding undergraduate enrollment by up to 20 percent</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>2996 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>U-Wire</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>UWIR</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© 2025, M2 Communications. All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >
                        <span class="companylink">Columbia University ; New York</span>, NY - news</p>
<p class="articleParagraph enarticleParagraph" >By Matt Luo</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Columbia is considering expanding undergraduate enrollment in Columbia College and the School of Engineering and Applied Science by up to 20 percent, according to an Oct. 31 email to faculty from the policy and planning committee of the Faculty of Arts and Sciences obtained by Spectator.</p>
<p class="articleParagraph enarticleParagraph" >The University anticipates finalizing its decision before releasing early decision admissions results mid-December, according to the email. Its consideration is part of a wave of policy proposals responding to recent shifts in higher education and growing programming concerns within the University.</p>
<p class="articleParagraph enarticleParagraph" >Facing losses of up to $100 million each month of the COVID-19 pandemic, Columbia launched an inquiry during the 2021-22 academic year into expanding its undergraduate population by between 5 and 20 percent. The inquiry resulted in nine faculty reports, which recommended postponing expansion considerations and focusing first on improving “areas of campus life associated with peer-to-peer connection.” At the time, the FAS agreed to postpone expansion discussions.</p>
<p class="articleParagraph enarticleParagraph" >“In the ensuing years, there have been efforts to address these recommendations,” Ivan Corwin, professor of mathematics and chair of the policy and planning committee, wrote in the email.</p>
<p class="articleParagraph enarticleParagraph" >Corwin declined Spectator’s request for an interview.</p>
<p class="articleParagraph enarticleParagraph" >The FAS is an administrative and budgetary unit that includes Columbia College and the School of General Studies. The policy and planning committee is “the only body elected to represent the Faculty of Arts and Sciences to the Arts and Sciences and university leadership,” according to its web page.</p>
<p class="articleParagraph enarticleParagraph" >“Expansion is now being reconsidered,” Corwin wrote in the email. “The exact percent growth in the CC and SEAS student population is not yet determined, though 20% seems to be the upper limit under consideration.”</p>
<p class="articleParagraph enarticleParagraph" >Columbia is not considering an expansion of General Studies, according to Michael Thaddeus, professor of mathematics. A University spokesperson did not respond to a Spectator inquiry about whether Columbia was considering an expansion of General Studies.</p>
<p class="articleParagraph enarticleParagraph" >The University enrolled its largest ever incoming undergraduate class this fall. The Columbia College and SEAS class of 2029 totalled 1,806 first-year students, an increase of about 20 percent from the 1,499 students enrolled in the class of 2028. One proposed plan for expansion involves maintaining the expanded enrollment of the class of 2029 for all future classes.</p>
<p class="articleParagraph enarticleParagraph" >Discover more</p>
<p class="articleParagraph enarticleParagraph" >Journalism courses online</p>
<p class="articleParagraph enarticleParagraph" >University Sports Merchandise</p>
<p class="articleParagraph enarticleParagraph" >Arts Culture Magazine</p>
<p class="articleParagraph enarticleParagraph" >NYC Mayor election merchandise</p>
<p class="articleParagraph enarticleParagraph" >Alumni Networking Platform</p>
<p class="articleParagraph enarticleParagraph" >Film festival tickets local</p>
<p class="articleParagraph enarticleParagraph" >Columbia University Apparel</p>
<p class="articleParagraph enarticleParagraph" >New York City</p>
<p class="articleParagraph enarticleParagraph" >Student Exchange Programs</p>
<p class="articleParagraph enarticleParagraph" >Financial literacy workshops</p>
<p class="articleParagraph enarticleParagraph" >Columbia’s undergraduate enrollment first increased due to pandemic-related deferrals and leaves of absence in the 2020-21 academic year. Combined enrollment in Columbia College and SEAS peaked at 6,779 in the fall of 2021, rising from 6,182 in 2020. A report from the 2022 expansion inquiry suggested that the stresses caused by this “unintended over yield” would be “instructive” in determining the effects of expansion.</p>
<p class="articleParagraph enarticleParagraph" >Most students who enrolled in fall 2021 graduated in spring 2025. Acting University President Claire Shipman, CC ’86, <span class="companylink">SIPA</span> ’94, cited “the graduation of what was our largest class last spring” as one of the factors the University took into consideration when deciding whether to expand the class of 2029.</p>
<p class="articleParagraph enarticleParagraph" >A University spokesperson told Spectator that Columbia had not made any official decision regarding further undergraduate expansion, and that it was still examining the academic and operational factors that expansion would necessitate.</p>
<p class="articleParagraph enarticleParagraph" >The University first brought the policy and planning committee into these discussions on Oct. 20. “To my understanding, considerations around expansion were only initiated in late summer, after some other issues for Columbia were resolved,” Corwin wrote in the email to faculty.</p>
<p class="articleParagraph enarticleParagraph" >Shipman addressed Columbia’s decision-making process to enlarge the class of 2029 at a University Senate plenary on Friday, specifically mentioning research funding and international student enrollment as “two big risk factors” the University considered.</p>
<p class="articleParagraph enarticleParagraph" >President Donald Trump’s administration canceled $400 million in grants and contracts to Columbia on March 7, shortly before the University released regular decision admissions to the class of 2029 on March 27, admitting 2,557 students. In July, Columbia struck a $221 million deal with the federal government to restore funding. By August, the University announced that it had admitted 2,946 students, suggesting that Columbia relied heavily on its waitlist over the spring and summer.</p>
<p class="articleParagraph enarticleParagraph" >“The decision about whether to expand the number of students for this coming year is one that needs to be made on a rather short timeframe given that early acceptance decisions are due in roughly a month,” Corwin wrote.</p>
<p class="articleParagraph enarticleParagraph" >The number of students Columbia admitted through regular and early decision rose from 2,319 in the 2023-24 admissions cycle to 2,577 in the 2024-25 cycle. However, the number of students admitted off the waitlist this year is about 60 percent more than the growth in the number of students admitted in regular and early decision, suggesting the University primarily used its waitlist to expand the first-year class.</p>
<p class="articleParagraph enarticleParagraph" >A University spokesperson declined to comment on the record about subsets of the admissions pool.</p>
<p class="articleParagraph enarticleParagraph" >“When we looked at where we had some bench of deep, deep excellence, we had students on the waiting list,” Shipman said at the plenary.</p>
<p class="articleParagraph enarticleParagraph" >All students admitted this year received offers before the end of June, a University official confirmed to Spectator.</p>
<p class="articleParagraph enarticleParagraph" >Columbia agreed to “examine its business model and take steps to decrease financial dependence on international student enrollment” in its July settlement with the federal government. About 39 percent of University enrollment comes from international students—the highest percentage in the Ivy League. This distribution varies dramatically between Columbia’s schools. The Graduate School of Arts and Sciences and the School of Professional Studies, both of which fall under the FAS, are majority international, as is the graduate division of SEAS.</p>
<p class="articleParagraph enarticleParagraph" >The FAS has historically faced financial strain as the University’s central administration increased demands on its budget to fund projects such as the Manhattanville campus. With economic contributions to Columbia from international students estimated at $903 million per year in 2023, or over 60 percent of the University’s net tuition revenue, even a small decrease in its international student enrollment would have drastic implications for the FAS budget.</p>
<p class="articleParagraph enarticleParagraph" >In 2024, 15 percent of the Columbia College student body consisted of international students, and 22 percent of the undergraduate division of SEAS were international students, some of the lowest proportions out of any of the University’s schools.</p>
<p class="articleParagraph enarticleParagraph" >“We are heavily international, … so a big decrease in that population is not only bad for the community, because I think we value who we are as a community when we’re international, but it affects us. We’re a tuition-driven institution as well,” Shipman said at the plenary.</p>
<p class="articleParagraph enarticleParagraph" >Shipman confirmed in an Oct. 8 email that “nearly all” international students were able to arrive on campus this fall.</p>
<p class="articleParagraph enarticleParagraph" >“It’s very clear to me that … we need to understand how we can think about raising money to support Arts and Sciences more robustly as this centerpiece of our undergraduate life,” Shipman said at the plenary.</p>
<p class="articleParagraph enarticleParagraph" >Columbia’s July settlement with the federal government saw “almost 99 percent” of its grants restored by October. Still, Columbia experienced a 63.1 percent decrease in its operating surplus for fiscal year 2025 and is facing a decline in international student applications for the upcoming admissions cycle.</p>
<p class="articleParagraph enarticleParagraph" >Shipman did not mention the University’s financial constraints or concerns about international students when she announced the increased size of the class of 2029. Rather, Shipman wrote in an Aug. 29 email welcoming the class that the University decided to expand its undergraduate enrollment due to “a high volume of outstanding applications” and “a positive response to our initial offers of admission.”</p>
<p class="articleParagraph enarticleParagraph" >“Growth of our student body, if done right and with the guidance and involvement of our faculty, could be a wonderful opportunity for A&S,” Corwin wrote. “We can both expand the scope of our offerings as well as the reach of whose lives we impact.”</p>
<p class="articleParagraph enarticleParagraph" >Michael J. Schmidtberger, CC ’82, Law ’85, chair of the Columbia College Board of Visitors, wrote in a statement to Spectator that expansion considerations were taking place in the context of “the challenges and opportunities presented by AI” and other challenges in higher education. The board would remain committed to “academic excellence and the student experience.”</p>
<p class="articleParagraph enarticleParagraph" >“Board of Visitors leadership supports a comprehensive strategic planning process for undergraduate education, including consideration of increasing the enrollment of the College, and stands ready to help with that effort,” Schmidtberger wrote.</p>
<p class="articleParagraph enarticleParagraph" >The Columbia College Board of Visitors—composed of 34 members who are largely Columbia College alumni—is an independent, self-governing advisory group to the dean of Columbia College.</p>
<p class="articleParagraph enarticleParagraph" >Thaddeus, acting president of the Columbia chapter of the <span class="companylink">American Association of University Professors</span>, expressed dissatisfaction with the communication he received from the University regarding an expansion of Columbia College and SEAS.</p>
<p class="articleParagraph enarticleParagraph" >“The idea that we’re just going to grow them by 20 percent for what is, transparently, revenue generating reasons, the faculty should be upset about that, and right now, we’re just not hearing much from the faculty because they don’t know what’s going on,” Thaddeus said.</p>
<p class="articleParagraph enarticleParagraph" >Thaddeus noted that Corwin’s email was “literally the only communication that we’ve had from anyone about this” and that, to his knowledge, the University did not consult faculty about the decision to expand the first-year class over the summer.</p>
<p class="articleParagraph enarticleParagraph" >“The decision that was made this summer was made by me,” Shipman said at the plenary.</p>
<p class="articleParagraph enarticleParagraph" >Several student leaders told Spectator they only found out about Columbia’s plans to further expand undergraduate enrollment when Spectator requested an interview with them. When Columbia expanded the class of 2029 over the summer, members of the student councils said they were only informed after the University introduced Wien Hall as a first-year dorm option and relocated about 160 General Studies students from their housing.</p>
<p class="articleParagraph enarticleParagraph" >“I feel like student leaders still don’t have enough information, even though we have a mountain of information, more than the general student body,” Sam Cano Cabrera, CC ’26, president of Columbia College Student Council, told Spectator. “I think the communication is not really student-centered. It’s more administratively or institutionally centered.”</p>
<p class="articleParagraph enarticleParagraph" >The University planned to include Wien as an option for first-year housing before the 2025-26 housing selection process opened. However, due to the increased size of the first-year class, the University relocated sophomores, juniors, and seniors who had already selected Wien into 600 W. 113th St., known as Nuss, and 503 W. 121st St., known as The Fairholm. Wien is now classified as housing “mostly or only first-year students,” according to the Columbia Housing website. Nuss and The Fairholm had previously been set aside in part for General Studies and graduate students, according to three accounts from student leaders.</p>
<p class="articleParagraph enarticleParagraph" >“There’s a really big and real concern from students that they’re seen by the University more as money to be made than students to be taught in a community to be instilled,” Cano Cabrera said.</p>
<p class="articleParagraph enarticleParagraph" >Columbia announced that it had increased the financial aid budget for the class of 2029 to $66 million—22 percent more than the previous year—to match the 20 percent increase in enrollment. The total average amount in grants and scholarships per financial aid recipient was $77,908 for the class of 2029, rising $1,643 from $76,265 for the class of 2028. Columbia College’s estimated total cost of attendance, not including travel expenses, rose $3,518 from $92,742 in 2024-25 to $96,260 in 2025-26.</p>
<p class="articleParagraph enarticleParagraph" >“They should have been consulting myself and the CCSC president,” Janie Zhang, SEAS ’26, president of the Engineering Student Council, told Spectator. “Undergraduate students are the ones that would be most impacted by this change, and so it’d be better if we had more student voices.”</p>
<p class="articleParagraph enarticleParagraph" >Even before the University started considering expansion, Columbia’s facilities and physical space were under immense stress. When the expansion study group resulting from the 2021-22 inquiry decided to postpone its discussions, it made “aiming to reevaluate the timing and feasibility of any expansion” contingent upon the completion of renovations for Uris Hall, which was expected to increase space available for FAS schools by about 20 percent.</p>
<p class="articleParagraph enarticleParagraph" >The Business School, which previously occupied Uris, officially moved to a new location on the Manhattanville campus in 2022, which had taken nearly 20 years and $6.3 billion to build.</p>
<p class="articleParagraph enarticleParagraph" >The expansion working group said in its 2022 report that the Morningside campus was “stretched to the breaking point in accommodating students in Core classes, particularly Lit Hum and CC.” The Uris renovation, which the University expected to complete by fall 2025, has not started.</p>
<p class="articleParagraph enarticleParagraph" >A University official confirmed to Spectator that Columbia has made 16 classrooms in Uris available to the FAS since the winter of 2022 and moved the psychology department to the eighth floor of Uris. The University plans to open a new 12,000-square-foot, two-floor computer science learning center in the space vacated by the psychology department in Schermerhorn Hall by fall 2026, according to the official.</p>
<p class="articleParagraph enarticleParagraph" >The University has also opened new classrooms in Riverside Church and sought to optimize classroom space by scheduling classes to be more evenly distributed throughout the day. Ten departments in FAS attempted to implement a 40 percent distributional cap on courses scheduled to start between 10 a.m. to 2 p.m. for the spring 2026 semester in a pilot program designed to limit overlapping course offerings. Eight departments met this target, according to the official.</p>
<p class="articleParagraph enarticleParagraph" >Columbia has long struggled to schedule enough courses to accommodate all its students and to find appropriate classrooms for these courses. Faculty committees have attempted to curb “bunching,” the practice of departments scheduling many classes around the same peak times, for years.</p>
<p class="articleParagraph enarticleParagraph" >In the Core Curriculum, Columbia raised the enrollment cap in University Writing sections from 14 to 16 this fall and shortened the weekly Frontiers of Science lecture by 15 minutes when it added an additional lecture section. There has been no indication that the University plans to revisit the enrollment caps in other Core classes.</p>
<p class="articleParagraph enarticleParagraph" >The expansion study group also suggested that the University was not meeting student needs in either dining or housing at the time, though it acknowledged that developments in these two areas were “difficult to assess” due to the immediate impacts of the pandemic.</p>
<p class="articleParagraph enarticleParagraph" >“I don’t think we have enough resources currently to support the student body that we have,” Cano Cabrera said. “If we were to continue to expand, I think the quality of life for a student here and the quality of education would decrease.”</p>
<p class="articleParagraph enarticleParagraph" >Columbia has considered long-term plans to make improvements and expand capacity in certain facilities, regardless of whether or not it moves ahead with expansion plans. Shipman wrote that in expanding the class of 2029, the University made “careful adjustments to the resources that support our students,” including increasing the number of faculty and advisors, optimizing classroom space, and expanding dining options.</p>
<p class="articleParagraph enarticleParagraph" >Since the expansion inquiry in the 2021-22 academic year, the University has opened a new undergraduate dorm at 611 W. 112th St., formerly the historic Maranamay hotel, and several new dining halls, including Grace Dodge Dining Hall at Teachers College. The Maranamay has capacity for fewer than 200 students. Hartley Hall, which will not be available for housing selection until fall 2027 due to ongoing renovations, has capacity for under 250 students.</p>
<p class="articleParagraph enarticleParagraph" >The University has also partnered with Envision Strategies, a consulting company specializing in food services, to develop a 10-year strategic plan for Columbia Dining in consultation with student leaders.</p>
<p class="articleParagraph enarticleParagraph" >“We’re talking about renovations, new building requirements, probably within the next 10 to 20 years,” Cano Cabrera said.</p>
<p class="articleParagraph enarticleParagraph" >Robert Kasdin, senior executive vice president, who returned to his role at Columbia following a 10-year hiatus, is leading efforts to examine the operational feasibility of expansion, including the necessary measures to increase housing and dining capacity.</p>
<p class="articleParagraph enarticleParagraph" >Dafne Sarfati, SEAS ’26, University senator and student affairs committee member, told Spectator that Columbia Dining limited graduate student access to dining halls amid the expansion of the first-year class this fall. Unlike its undergraduate dining plans, Columbia’s new graduate student dining plans cannot be used at John Jay Dining Hall, Ferris Booth Commons, or JJ’s Place.</p>
<p class="articleParagraph enarticleParagraph" >“If they do decide to expand the class size, all these solutions or these fixes that they’re implementing aren’t going to take effect until many years down the road,” Zhang said. “It just doesn’t seem sustainable to increase the size now.”</p>
<p class="articleParagraph enarticleParagraph" >Corwin wrote in his email that the Office of the Provost formed a small committee on undergraduate enrollments and instructional needs composed of representatives from Arts and Sciences, SEAS, the Core Curriculum, and advising to consider the “instructional implications of expansion and what is needed to ensure that we maintain and enhance the quality of our offerings.”</p>
<p class="articleParagraph enarticleParagraph" >“I am not opposed to planned growth,” Brian Krisberg, CC ’81, Law ’84, former president of the Columbia College Alumni Association and former chair of the Columbia Alumni Association board of directors, told Spectator. “What I am opposed to is unplanned growth. And at this point, what seems to be on the table is unplanned growth.”</p>
<p class="articleParagraph enarticleParagraph" >“Any growth must be preceded by a written understanding of how Columbia College students’ needs and interests will be enhanced,” he said.</p>
<p class="articleParagraph enarticleParagraph" >Staff Writer Matt Luo can be contacted at matt.luo@columbiaspectator.com. Follow Spectator on X @ColumbiaSpec.</p>
<p class="articleParagraph enarticleParagraph" >Want to keep up with breaking news? Subscribe to our email newsletter and like Spectator on <span class="companylink">Facebook</span>.</p>
<p class="articleParagraph enarticleParagraph" >((Distributed for UWIRE via M2 Communications (<span class="colorLinks">www.m2.co.uk [http://www.m2.co.uk]</span>))</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>CO</b>&nbsp;</td><td><br/>colunv : Columbia University</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gedu : Education | guni : University/College</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Normans Media Ltd</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document UWIR000020251122elbm000kd</td></tr></table><br/></div></div><br/><span></span><div id="article-PRTRIN0020251122elbm005xx" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/prtrinLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>NATIONAL</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>HIGHLIGHTS</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>516 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Press Trust of India</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>PRTRIN</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025. The Press Trust of India Limited. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >New Delhi, Nov 22 (PTI) Following are the top stories at 1.30 pm:</p>
<p class="articleParagraph enarticleParagraph" >NATION</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >MDS12 TN-CONG-DMK-PANEL (12.31 PM)</p>
<p class="articleParagraph enarticleParagraph" >**** 2026 polls: Cong appoints panel for seat-sharing talks with DMK, ends claims on aligning with TVK</p>
<p class="articleParagraph enarticleParagraph" >Chennai: Congress President Mallikarjun Kharge has constituted a 5-member committee to hold seat-sharing parleys with DMK for the 2026 Assembly election, Tamil Nadu Congress Committee President K Selvaperunthagai said on Saturday. ****</p>
<p class="articleParagraph enarticleParagraph" >DEL4 DISASTER MANAGEMENT-MEETING (11.03 AM)</p>
<p class="articleParagraph enarticleParagraph" >**** India to work closely with APDIM, regional partners to reduce disaster risks across Asia-Pacific</p>
<p class="articleParagraph enarticleParagraph" >New Delhi: India has reaffirmed its commitment to strengthening regional cooperation on disaster risk reduction, working closely with Asian and Pacific Centre for Development of Disaster Information Management (APDIM) and regional partners to reduce disaster and climate risks across Asia-Pacific, a government statement said Saturday. ****</p>
<p class="articleParagraph enarticleParagraph" >BOM3 MP-BLOS-DEATH (11.13 AM)</p>
<p class="articleParagraph enarticleParagraph" >**** Two BLOs die across two districts in MP; kin allege SIR survey work pressure</p>
<p class="articleParagraph enarticleParagraph" >Raisen/Damoh (MP): Two teachers-cum-Booth Level Officers (BLOs) tasked with conducting voter list survey for the Special Intensive Revision (SIR) died of "illness" in Raisen and Damoh districts of Madhya Pradesh on Friday, officials said. ****</p>
<p class="articleParagraph enarticleParagraph" >CAL4 WB-BLO-DEATH (12.28 PM)</p>
<p class="articleParagraph enarticleParagraph" >**** BLO found dead in Bengal's Nadia, family claims SIR work-related stress</p>
<p class="articleParagraph enarticleParagraph" >Kolkata: A woman working as a Booth Level Officer (BLO) in West Bengal's Nadia district was found dead at her residence on Saturday morning, with her family members claiming that she had been under considerable SIR work-related stress and died by suicide, police said. ****</p>
<p class="articleParagraph enarticleParagraph" >CAL5 BH-SPEAKER-LEADERS (12.42 PM)</p>
<p class="articleParagraph enarticleParagraph" >**** Lobbying intensified for post of Bihar assembly Speaker</p>
<p class="articleParagraph enarticleParagraph" >Patna: A day after Bihar Chief Minister Nitish Kumar allocated the portfolios among the state ministers, lobbying has intensified for the post of Speaker in the assembly, sources in the ruling NDA said on Saturday. ****</p>
<p class="articleParagraph enarticleParagraph" >DEL5 SPACE-AGNIKUL (11.53 AM)</p>
<p class="articleParagraph enarticleParagraph" >**** Space startup Agnikul raises Rs 150 crore to fund reusable rockets</p>
<p class="articleParagraph enarticleParagraph" >New Delhi: Space startup <span class="companylink">Agnikul Cosmos</span> on Saturday said it has raised Rs 150 crore in a fresh funding round at over half-a-billion dollar valuation, which would be used to build resusable launch vehicles. ****</p>
<p class="articleParagraph enarticleParagraph" >MDS13 AP-SAIBABA-LD PRESIDENT (1.00 PM)</p>
<p class="articleParagraph enarticleParagraph" >**** Sri Sathya Sai Baba inspired millions to follow path of service: President</p>
<p class="articleParagraph enarticleParagraph" >Puttaparthi (Andhra Pradesh): President Droupadi Murmu on Saturday said that revered spiritual leader Sri Sathya Sai Baba inspired millions of people to follow the path of service. ****</p>
<p class="articleParagraph enarticleParagraph" >CAL2 MN-ARREST (9.28 AM)</p>
<p class="articleParagraph enarticleParagraph" >**** Four militants among 5 arrested in Manipur</p>
<p class="articleParagraph enarticleParagraph" >Imphal: Security forces arrested four militants belonging to various proscribed outfits in Manipur for their alleged involvement in extortion activities, police said on Saturday. ****</p>
<p class="articleParagraph enarticleParagraph" >FOREIGN</p>
<p class="articleParagraph enarticleParagraph" >FGN13 US-TRUMP-INDOPAK (9.40 AM)</p>
<p class="articleParagraph enarticleParagraph" >**** In meeting with Mamdani, Trump repeats claim he solved conflict between India and Pakistan</p>
<p class="articleParagraph enarticleParagraph" >New York/Washington: US President Donald Trump has again claimed to have solved the conflict between India and Pakistan, repeating his assertion during a meeting with New York City Mayor-elect Zohran Mamdani in the Oval Office. By Yoshita Singh ****</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | ncat : Content Types | nfact : Factiva Filters | nfce : C&E Exclusion Filter | niwe : IWE Filter | nsum : News Digests</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>asiaz : Asia | delhi : Delhi | devgcoz : Emerging Market Countries | dvpcoz : Developing Economies | india : India | madhya : Madhya Pradesh | ndelh : New Delhi | sasiaz : South Asia | tamil : Tamil Nadu | wbeng : West Bengal</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Press Trust Of India Limited</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document PRTRIN0020251122elbm005xx</td></tr></table><br/></div></div><br/><span></span><div id="article-THEPRT0020251122elbm0002x" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/theprtLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Newsmaker of the Week</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Royals to Republicans—Epstein files have exposed fault lines across power circles</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Keshav Padmanabhan </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1243 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>12:41 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>ThePrint</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>THEPRT</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 Printline Media Pvt. Ltd. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Donald Trump, who has nurtured the MAGA movement for the last decade, has been perceived to have lost control over the movement, particularly with the release of Epstein’s records.</p>
<p class="articleParagraph enarticleParagraph" >
                        Jeffrey Epstein, the late convicted sex offender, in his death has done what the Democrats have so far failed to do — push US President Donald Trump to reverse policy. Epstein has dethroned a British royal, forced a former Harvard president into a mini-sabbatical, and opened a Pandora’s box with potential investigations into American banking firms.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Some of the most well–known power brokers, scientists, academicians, government officials, diplomats, and businesspersons have all come under scrutiny half a decade after Epstein was found dead in his prison cell in New York City while awaiting trial.</p>
<p class="articleParagraph enarticleParagraph" >Trump’s abrupt reversal — agreeing to release the Epstein files after months of refusal — and the political shock it triggered in Washington are why the release is ThePrint’s Newsmaker of the Week.</p>
<p class="articleParagraph enarticleParagraph" >The documents have put the spotlight on institutional failures, unsettled global elites, and exposed a fault line inside the Republican Party, making this disclosure one of the most consequential document drops of the year.</p>
<p class="articleParagraph enarticleParagraph" >An inflection point for Trump</p>
<p class="articleParagraph enarticleParagraph" >Last week, the US House Oversight Committee released almost 23,000 pages of records that were obtained from the dead financier’s estate. The release came after the House Democrats on the Oversight Committee first dropped emails indicating that the US President knew more of Epstein’s activities than previously revealed. Trump spent months denying any knowledge of Epstein’s sex-trafficking ring, calling the allegations a “hoax.”</p>
<p class="articleParagraph enarticleParagraph" >“I want you to realise that that dog that hasn’t barked is Trump…[Victim] spent hours at my house with him, he has never once been mentioned,” Epstein wrote in an email to long-time confidante Ghislaine Maxwell in 2011. The email was one of the three released by the Democrats in the House Oversight Committee.</p>
<p class="articleParagraph enarticleParagraph" >The subsequent <span class="colorLinks">emails and records [https://oversight.house.gov/release/oversight-committee-releases-additional-epstein-estate-documents/]</span> published by the House Oversight Committee on 12 November set off a scramble to understand the reach of Epstein. The release of his emails has been a major issue plaguing the Trump presidency over the summer. A number of Republicans, led primarily by Representative Thomas Massie, have argued for the release of Epstein’s files held by the <span class="companylink">US government</span>. Trump attempted to persuade Republican lawmakers to back away from a measure demanding the <span class="companylink">US Justice Department</span> to release the Epstein files. However, on Tuesday, Trump backtracked.</p>
<p class="articleParagraph enarticleParagraph" >The call to release Epstein’s emails and records — a call originally from the political Right — became a part of Trump’s ‘Make America Great Again! (MAGA)’ movement, and has since come to find almost unanimous support in the <span class="companylink">US Congress</span>. Trump, who has nurtured the MAGA movement for the last decade, has been perceived to have lost control over the movement in the last few months, particularly with the release of Epstein’s records.</p>
<p class="articleParagraph enarticleParagraph" >Trump signed the legislation on Wednesday, authorising his administration to release files concerning Epstein, bowing to pressure from his own party, the larger MAGA movement, and possibly showing the first weakness after almost eleven months of continued success in governing the US. For Trump, the moment is an inflection point over his control over the MAGA movement.</p>
<p class="articleParagraph enarticleParagraph" >The best example of the pressure the release of Epstein’s files has had on the President’s control over the Republican Party is <span class="colorLinks">his split [https://www.washingtonpost.com/politics/2025/11/20/marjorie-taylor-greene-trump-maga-georgia/]</span> with Representative Marjorie Taylor Greene. Taylor Greene, who has been one of the staunchest supporters of Trump, was also one of the loudest voices calling for the release of Epstein’s files.</p>
<p class="articleParagraph enarticleParagraph" >The administration’s attempt to deflect the legislation got to the point where House Speaker Mike Johnson <span class="colorLinks">refused to swear-in [https://www.nytimes.com/2025/11/11/us/politics/adelita-grijalva-swearing-in-congress.html]</span> Representative Adelita Grijalva for over 50 days, after she won a special election on 23 September for a seat held by her late father Raúl Grijalva in Arizona. Adelita Grijalva had promised to sign on to a bi-partisan petition to force the vote in the House demanding the <span class="companylink">US Justice Department</span> to release the Epstein files.</p>
<p class="articleParagraph enarticleParagraph" >Johnson defended his decision saying that the delay was due to the House being in recess. However, Grijalva’s signature would have been the 218th, and the last one, on the petition required to force the House vote.</p>
<p class="articleParagraph enarticleParagraph" >Trump’s reluctance to release the files for months is interesting given that the American President had been good friends with the convicted sex offender in the late 1990s and early 2000s. However, Karoline Leavitt, the White House Press Secretary, last week defended Trump. She stated that the President and Epstein’s friendship ended after Trump kicked the dead financier out of his club — Mar-a-Lago — for being a “pedophile and a creep” almost two decades ago.</p>
<p class="articleParagraph enarticleParagraph" >In the middle of the storm around Epstein, his closest confidante Maxwell, who was found guilty of child sex trafficking in 2021 and sentenced to 20 years imprisonment in 2022, was potentially seeking a <span class="colorLinks">commutation of her sentence [https://www.nbcnews.com/news/us-news/whistleblower-provided-house-democrats-ghislaine-maxwell-documents-spe-rcna244418]</span> from Trump. According to reports, Maxwell was moved to a different prison in August, days after meeting with Todd Blanche, the Deputy Attorney General.</p>
<p class="articleParagraph enarticleParagraph" >Also read: <span class="colorLinks">Why the US Congress put its foot down on releasing the Jeffrey Epstein files [https://theprint.in/world/why-the-us-congress-put-its-foot-down-on-releasing-the-jeffrey-epstein-files/2787957/]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Epstein’s continued links to powerful men</p>
<p class="articleParagraph enarticleParagraph" >Epstein was eventually convicted as a sex offender in 2008 in a plea deal. However, despite the conviction, the financier maintained his links with influential individuals, especially Andrew Mountbatten-Windsor, UK’s King Charles III’s brother.</p>
<p class="articleParagraph enarticleParagraph" >Andrew gave up all his royal titles including the Duke of York over his ties to Epstein.</p>
<p class="articleParagraph enarticleParagraph" >Epstein’s net, however, went far and wide. Even after getting convicted, he remained in touch with several prominent personalities until his arrest in 2019 on federal sex trafficking charges. Lawrence H Summers, former Treasury Secretary under President Bill Clinton and president of <span class="companylink">Harvard University</span>, remained in touch with Epstein until at least mid-2019.</p>
<p class="articleParagraph enarticleParagraph" >Summers, a well–known economist, apologised for his continued friendship with Epstein and will now no longer teach at Harvard. However, given that he is a tenured professor, he cannot be easily removed from his job at the university. Summers and Epstein exchanged <span class="colorLinks">at least 86 emails [https://edition.cnn.com/2025/11/19/us/jeffrey-epstein-emails-congress-trump-invs-vis]</span> in the decade leading up to Epstein’s death by suicide in 2019.</p>
<p class="articleParagraph enarticleParagraph" >Ehud Barak, former Prime Minister of Israel, met Epstein in early 2003 and remained in touch with the financier long after his original conviction in 2008. Between 2013 and 2017, Barak and Epstein discussed regional geopolitics in their emails.</p>
<p class="articleParagraph enarticleParagraph" >
                     Peter Mandelson, the Labour Party power-broker in the UK, was fired as ambassador to the US by Prime Minister Keir Starmer earlier this year due to his connection to Epstein. Mandelson stayed in touch with Epstein till at least 2016.</p>
<p class="articleParagraph enarticleParagraph" >Apart from these leaders, <span class="companylink">JPMorgan Chase</span> — the largest bank in the US — is coming under the scanner with Democratic politicians calling for a review of how the bank handled Epstein’s money. It was only after Epstein’s death that the bank revealed almost $1.3 billion in suspicious transactions <span class="colorLinks">related to the financier.  [https://www.nytimes.com/2025/11/20/us/politics/jeffrey-epstein-jpmorgan-chase-ron-wyden.html]</span>
                  </p>
<p class="articleParagraph enarticleParagraph" >Long after his death, Epstein continues to impact those around him, given that for over a decade after his first conviction, prominent personalities did not cut their ties with him.</p>
<p class="articleParagraph enarticleParagraph" >Views are personal.</p>
<p class="articleParagraph enarticleParagraph" >(Edited by Aamaan Alam Khan)</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gcrim : Crime/Legal Action | gpir : Politics/International Relations | gpol : Domestic Politics | grape : Sex Crimes</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>eurz : Europe | namz : North America | nordz : Northern Europe | uk : United Kingdom | usa : United States | weurz : Western Europe</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Printline Media Pvt. Ltd.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document THEPRT0020251122elbm0002x</td></tr></table><br/></div></div><br/><span></span><div id="article-HNTM000020251122elbm001bd" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/hntmLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>Hindustan Times, india-news</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>
                           Shashi Tharoor's message for Congress? On Trump-Mamdani meet, MP says 'this is how democracy should work'</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>HT News Desk </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>557 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Hindustan Times</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>HNTM</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025.  HT Media Limited.  All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >India, Nov. 22 -- Congress MP Shashi Tharoor on Saturday reacted to United States President Donald Trump's meeting with New York City mayor Zohran Mamdani.</p>
<p class="articleParagraph enarticleParagraph" >While both Trump and Mamdani had taken potshots at each other in the lead-up to the mayoral elections in New York, the Friday meeting between them at the White House was laced with bonhomie.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Responding to a clip from the meeting, Tharoor said that "this is how democracy should work", while adding that he would "love to see more of this in India."</p>
<p class="articleParagraph enarticleParagraph" >"Fight passionately for your point of view in elections, with no rhetorical holds barred. But once it's over, & the people have spoken, learn to cooperate with each other in the common interests of the nation you are both pledged to serve," Tharoor said, adding that he was trying to do his part to achieve the same equation in India.</p>
<p class="articleParagraph enarticleParagraph" >Following the meeting, at the press interaction in the Oval Office, Trump said the meeting was very "productive", adding that New York would "hopefully have a great mayor."</p>
<p class="articleParagraph enarticleParagraph" >Trump was generous in his praise for Mamdani, saying he was "confident" that the Democrat would do a "good job", and adding that he would "surprise some Conservative people."</p>
<p class="articleParagraph enarticleParagraph" >On a reporter's question to Mamdani on whether he would reaffirm that Trump was a "fascist", the US President quipped that the NYC mayor could reply in the affirmative. "That's okay, you can say it. It's easier than explaining it. I don't mind," Trump said.</p>
<p class="articleParagraph enarticleParagraph" >Some of Tharoor's remarks have ruffled feathers within the Congress party, the latest being the Thiruvananthapuram MP's praise for Prime Minister Narendra Modi.</p>
<p class="articleParagraph enarticleParagraph" >In a post on X, Tharoor said Prime Minister Narendra Modi's Ramnath Goenka Lecture served as both an economic outlook and a cultural call to action. He added that he was "glad" to be in the audience during the speech "despite battling a bad cold and cough."</p>
<p class="articleParagraph enarticleParagraph" >His statements drew sharp criticism from his own party, with Congress leader Sandeep Dikshit calling him a "hypocrite". Another party leader, Supriya Shrinate, said she found nothing "praiseworthy" in the PM's speech.</p>
<p class="articleParagraph enarticleParagraph" >Tharoor also miffed his party leaders with an article for international media organisation Project Syndicate, headlined 'Indian Politics Are a Family Business'. In the piece, Tharoor highlighted that dynastic politics prevails across the political spectrum, and called it a "grave threat" to Indian democracy.</p>
<p class="articleParagraph enarticleParagraph" >Following the Bihar Assembly election results, Tharoor said there would have to be "have to be some very serious introspection". "I don't just mean introspection, sitting and thinking, but also studying what went wrong, what were the tactical, messaging or organisational mistakes," he said, while also adding that he was not invited to campaign in Bihar.</p>
<p class="articleParagraph enarticleParagraph" >"I was not invited to campaign in Bihar and therefore, I cannot give you any first-hand information. But I've been talking to people..." he said, adding that he had got a sense of what needed to be analysed.</p>
<p class="articleParagraph enarticleParagraph" >Published by HT Digital Content Services with permission from Hindustan Times.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>CT</b>&nbsp;</td><td><br/>For any query with respect to this article or any other content requirement, please contact Editor at contentservices@htdigital.in </td></tr>
<tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | gvote : Elections</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>asiaz : Asia | devgcoz : Emerging Market Countries | dvpcoz : Developing Economies | india : India | namz : North America | sasiaz : South Asia | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>HT Digital Streams Limited</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document HNTM000020251122elbm001bd</td></tr></table><br/></div></div><br/><span></span><div id="article-DJDN000020251122elbm0001o" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/djdnLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump and Mamdani Set Aside Differences -- WSJ</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1148 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>ET</b>&nbsp;</td><td>02:33 AM</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Dow Jones Newswires</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>DJDN</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>A4</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright © 2025, Dow Jones & Company, Inc. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >At White House meeting, tensions ease after months of mutual antagonism</p>
<p class="articleParagraph enarticleParagraph" >By Natalie Andrews and James Fanelli</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >WASHINGTON -- President Trump and New York City Mayor-elect Zohran Mamdani, two singular forces in U.S. politics who have spent months antagonizing one another, set aside their differences -- for now -- following a meeting at the White House on Friday.</p>
<p class="articleParagraph enarticleParagraph" >"I feel very confident that he can do a very good job," Trump told reporters after the meeting. "I think he is going to surprise some conservative people."</p>
<p class="articleParagraph enarticleParagraph" >Both men largely avoided directly criticizing each other in front of live television cameras. "I appreciated the time with the president," Mamdani said, standing in the Oval Office next to Trump, who was seated at his desk.</p>
<p class="articleParagraph enarticleParagraph" >When a reporter asked about Mamdani's previous comment calling Trump a despot, the president quipped, "I've been called much worse than a despot, so it's not that insulting."</p>
<p class="articleParagraph enarticleParagraph" >Pressed on whether he believed that Trump was a fascist, the president interjected before the mayor-elect could answer, "That's OK. You can just say 'yes.' It's easier than explaining it. I don't mind," Trump said, while tapping him on the arm.</p>
<p class="articleParagraph enarticleParagraph" >The detente reflected a calculation by both men that they had more to gain by working together than by being at odds. Mamdani leaves Washington having defused for now Trump's threat to cut off federal funding to New York, a move that would have been devastating for the country's most populous city. And Trump has eased tensions with an influential up-and-coming politician at a time when the president's polling is on the downturn.</p>
<p class="articleParagraph enarticleParagraph" >In another gift to Mamdani, Trump dismissed concerns from wealthy New Yorkers and some Republicans that Mamdani would wreak havoc on the city. Trump told reporters he would feel comfortable living in New York, adding, "and I think much more so after the meeting."</p>
<p class="articleParagraph enarticleParagraph" >The two men have cultivated loyal followings while espousing polar opposite views of the world, and they have used one another as foils to galvanize their base. But even before the meeting, Trump and Mamdani each signaled they would seek to lower the temperature. In an interview with Fox News Radio earlier Friday, Trump said he expected their discussion to be "quite civil."</p>
<p class="articleParagraph enarticleParagraph" >In a sign of the spectacle surrounding the visit, a large group of Trump administration staff stood atop a staircase at the Eisenhower Executive Office Building to watch Mamdani's arrival, and dozens of reporters gathered outside the West Wing.</p>
<p class="articleParagraph enarticleParagraph" >"For some reason, the press has found this to be a very interesting meeting," Trump said. "The biggest people in the world, they come all over from countries, nobody cares."</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, a Democratic socialist who rose from obscurity over the past year on a message of affordability and taxing the wealthy, has been called a communist and an antisemite by Trump. The president previously threatened to withhold federal funding and deploy National Guard troops to New York City if Mamdani were elected. He backed former New York Gov. Andrew Cuomo, a moderate Democrat and Mamdani's main rival in the mayoral race.</p>
<p class="articleParagraph enarticleParagraph" >The mayor-elect has accused Trump of being a despot -- and has delighted in getting under the president's skin. " Donald Trump, since I know you're watching, I have four words for you, turn the volume up," Mamdani, 34 years old, said during his election night victory speech earlier this month.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, who enters office Jan. 1, has taken a more measured tone since he won this month's mayoral election, offering to work with elected officials from both sides of the aisle. On Thursday, he dismissed speculation that Trump would seek to embarrass him. "I'm not concerned about this meeting," he said. "I view this meeting as an opportunity to make my case."</p>
<p class="articleParagraph enarticleParagraph" >Ahead of his meeting with Trump, Mamdani called Senate Minority Leader Chuck Schumer (D., N.Y.) asking for advice, according to a person familiar with the conversation.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani sought the meeting to press Trump on the city's affordability crisis, an issue he said resonates with both his supporters and Trump voters.</p>
<p class="articleParagraph enarticleParagraph" >Some Republican lawmakers and political strategists have encouraged Trump to focus on the high cost of living, warning that the GOP could face deep losses in next year's midterm elections if voters believe the president isn't taking their concerns about prices seriously. Trump has bristled at the notion that he hasn't done enough on the issue, pointing to efforts to attract foreign investment.</p>
<p class="articleParagraph enarticleParagraph" >Vice President JD Vance on Thursday asked for patience on the economy. "We get it and we hear you, and we know that there's a lot of work to do, " Vance said during a Breitbart News event. "As much progress as we've made, it's going to take a little time for Americans to feel that."</p>
<p class="articleParagraph enarticleParagraph" >Robert Wolf, former chairman and chief executive of <span class="companylink">UBS Americas</span> and informal adviser to Mamdani, said he had a 45-minute <span class="companylink">Zoom</span> call with the mayor-elect on Thursday in advance of the White House meeting. One point of discussion was that Mamdani and Trump share the view that a vibrant New York City economy strengthens the nation.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani's outreach to Trump has heartened the city's business community, Wolf added.</p>
<p class="articleParagraph enarticleParagraph" >Both Trump and Mamdani jabbed at one another throughout the mayoral race. "I am Donald Trump's worst nightmare as a progressive Muslim immigrant who actually fights for the things that I believe in," Mamdani said during a mayoral debate.</p>
<p class="articleParagraph enarticleParagraph" >Trump has raised concerns about the effect Mamdani's policies will have on the local economy and public safety. Those concerns echo those of some members of the city's business community. Mamdani wants to freeze rent, expand free child care and create a free bus service, while increasing taxes on corporations and the city's wealthiest.</p>
<p class="articleParagraph enarticleParagraph" >Some Mamdani supporters feared Trump would seize the meeting as a chance to belittle the mayor-elect, much as he did with Ukrainian President Volodymyr Zelensky during an Oval Office visit earlier this year. During that tense conversation, Trump and Vance rebuked Zelensky on live television.</p>
<p class="articleParagraph enarticleParagraph" >But Trump took a different tack this time.</p>
<p class="articleParagraph enarticleParagraph" >"I met with a man who is a very rational person," Trump said after Friday's sit-down with the mayor-elect. "I met with a man who really wants to see New York be great again."</p>
<p class="articleParagraph enarticleParagraph" >Write to Natalie Andrews at natalie.andrews@wsj.com and James Fanelli at james.fanelli@wsj.com</p>
<p class="articleParagraph enarticleParagraph" >This article is being republished as part of our daily reproduction of WSJ.com articles that also appeared in the U.S. print edition of The Wall Street Journal (November 22, 2025).</p>
<p class="articleParagraph enarticleParagraph" >(END) Dow Jones Newswires</p>
<p class="articleParagraph enarticleParagraph" >November 22, 2025 02:33 ET (07:33 GMT)</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | m14 : Commodity Markets | mcat : Commodity/Financial Market News | ncat : Content Types | ncmac : Commodities Asset Class News | nenac : Energy Asset Class News | nfact : Factiva Filters | nfce : C&E Exclusion Filter | nfiac : Fixed Income Asset Class News | niwe : IWE Filter | nrmf : Routine Market/Financial News</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | usdc : Washington DC | use : Northeast U.S. | usny : New York State | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Dow Jones & Company, Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document DJDN000020251122elbm0001o</td></tr></table><br/></div></div><br/><span></span><div id="article-J000000020251122elbm00020" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/jLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>U.S. News: Trump and Mamdani Set Aside Differences --- At White House meeting, tensions ease after months of mutual antagonism</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>By Natalie Andrews and James Fanelli </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>719 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The Wall Street Journal</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>J</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>A4</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 Dow Jones & Company, Inc. All Rights Reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >WASHINGTON -- President Trump and New York City Mayor-elect Zohran Mamdani, two singular forces in U.S. politics who have spent months antagonizing one another, set aside their differences -- for now -- following a meeting at the White House on Friday.</p>
<p class="articleParagraph enarticleParagraph" >"I feel very confident that he can do a very good job," Trump told reporters after the meeting. "I think he is going to surprise some conservative people."</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Both men largely avoided directly criticizing each other in front of live television cameras. "I appreciated the time with the president," Mamdani said, standing in the Oval Office next to Trump, who was seated at his desk.</p>
<p class="articleParagraph enarticleParagraph" >When a reporter asked about Mamdani's previous comment calling Trump a despot, the president quipped, "I've been called much worse than a despot, so it's not that insulting."</p>
<p class="articleParagraph enarticleParagraph" >Pressed on whether he believed that Trump was a fascist, the president interjected before the mayor-elect could answer, "That's OK. You can just say 'yes.' It's easier than explaining it. I don't mind," Trump said, while tapping him on the arm.</p>
<p class="articleParagraph enarticleParagraph" >The detente reflected a calculation by both men that they had more to gain by working together than by being at odds. Mamdani leaves Washington having defused for now Trump's threat to cut off federal funding to New York, a move that would have been devastating for the country's most populous city. And Trump has eased tensions with an influential up-and-coming politician at a time when the president's polling is on the downturn.</p>
<p class="articleParagraph enarticleParagraph" >In another gift to Mamdani, Trump dismissed concerns from wealthy New Yorkers and some Republicans that Mamdani would wreak havoc on the city. Trump told reporters he would feel comfortable living in New York, adding, "and I think much more so after the meeting."</p>
<p class="articleParagraph enarticleParagraph" >The two men have cultivated loyal followings while espousing polar opposite views of the world, and they have used one another as foils to galvanize their base. But even before the meeting, Trump and Mamdani each signaled they would seek to lower the temperature.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, a Democratic socialist who rose from obscurity over the past year on a message of affordability and taxing the wealthy, has been called a communist and an antisemite by Trump. The president previously threatened to withhold federal funding and deploy National Guard troops to New York City if Mamdani were elected. He backed former New York Gov. Andrew Cuomo, a moderate Democrat and Mamdani's main rival in the mayoral race. The mayor-elect has accused Trump of being a despot -- and has delighted in getting under the president's skin. "Donald Trump, since I know you're watching, I have four words for you, turn the volume up," Mamdani, 34 years old, said during his election night victory speech earlier this month.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, who enters office Jan. 1, has taken a more measured tone since he won this month's mayoral election, offering to work with elected officials from both sides of the aisle.</p>
<p class="articleParagraph enarticleParagraph" >Ahead of his meeting with Trump, Mamdani called Senate Minority Leader Chuck Schumer (D., N.Y.) asking for advice, according to a person familiar with the conversation.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani sought the meeting to press Trump on the city's affordability crisis, an issue he said resonates with both his supporters and Trump voters.</p>
<p class="articleParagraph enarticleParagraph" >Some Republican lawmakers and political strategists have encouraged Trump to focus on the high cost of living, warning that the GOP could face deep losses in next year's midterm elections if voters believe the president isn't taking their concerns about prices seriously. Trump has bristled at the notion that he hasn't done enough on the issue, pointing to efforts to attract foreign investment.</p>
<p class="articleParagraph enarticleParagraph" >Robert Wolf, former chairman and chief executive of <span class="companylink">UBS Americas</span> and informal adviser to Mamdani, said he had a 45-minute <span class="companylink">Zoom</span> call with the mayor-elect on Thursday in advance of the White House meeting. One point of discussion was that Mamdani and Trump share the view that a vibrant New York City economy strengthens the nation.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani's outreach to Trump has heartened the city's business community, Wolf added.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | gvote : Elections</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPC</b>&nbsp;</td><td><br/>EXE | LLM | LOC | NND | UCPP | UCPR | USG | USN</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Dow Jones & Company, Inc.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document J000000020251122elbm00020</td></tr></table><br/></div></div><br/><span></span><div id="article-TPUNC00020251122elbm0008e" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/tpuncLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump, Mamdani pledge cooperation after White House meeting</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>426 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The Punch</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>TPUNC</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2015 - Punch Newspapers </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >United States President Donald Trump and New York City Mayor-elect Zohran Mamdani have held talks at the White House, expressing hope for a productive and cordial relationship despite their history of mutual criticism.</p>
<p class="articleParagraph enarticleParagraph" >Speaking to reporters after their meeting on Friday, Trump praised Mamdani, the politician he once labelled a “jihadist” and threatened to strip of US citizenship, for his successful campaign and strong emphasis on cost-of-living issues.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >“We’ve just had a great meeting, a really productive meeting. We have one thing in common: we want this city of ours that we love to do very well,” said Trump, who grew up in New York, adding that Mamdani ran an “incredible race” and defeated his rivals “easily.”</p>
<p class="articleParagraph enarticleParagraph" >“I appreciated the meeting with the president, and as he said, it was a productive meeting focused on a place of shared admiration and love, which is New York City,” Mamdani said, noting that he raised issues such as rent, utilities and grocery costs.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, a democratic socialist who has embraced New York’s identity as a global community and strongly defended Palestinian rights, is politically at odds with Trump, whose nativist platform has portrayed immigrants as a domestic threat and previously included a ban on Muslims entering the United States.</p>
<p class="articleParagraph enarticleParagraph" >Asked about areas of disagreement with Trump, particularly on immigration enforcement, Mamdani said he hoped they could still work together toward shared goals.</p>
<p class="articleParagraph enarticleParagraph" >He referenced a video he shared in November 2024, in which he discussed affordability issues and US involvement in foreign conflicts with Trump voters after the 2024 presidential election.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani said he now hopes to find common ground on ending US “forever wars” and reducing the cost of living.</p>
<p class="articleParagraph enarticleParagraph" >“I think both President Trump and I are very clear about our positions and our views. And what I really appreciate about the president is that our meeting focused not on areas of disagreement of which there are many but on our shared purpose of serving New Yorkers,” Mamdani said.</p>
<p class="articleParagraph enarticleParagraph" >“That’s something that could transform the lives of 8.5 million people who are currently facing a cost-of-living crisis, with one in four living in poverty,” he added.</p>
<p class="articleParagraph enarticleParagraph" >With polls showing growing concern over the state of the US economy, Trump has recently spoken more positively about Mamdani’s focus on cost-of-living issues, despite their previous acrimony.</p>
<p class="articleParagraph enarticleParagraph" >“He said a lot of my voters actually voted for him,” Trump told reporters. “And I’m OK with that.”</p>
<p class="articleParagraph enarticleParagraph" >Al Jazeera</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gcom : Society/Community | gimm : Human Migration | gpir : Politics/International Relations | gpol : Domestic Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States | use : Northeast U.S. | usny : New York State</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>news</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Punch Nigeria Limited</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document TPUNC00020251122elbm0008e</td></tr></table><br/></div></div><br/><span></span><div id="article-WP00000020251122elbm0001g" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/wpLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>A-Section</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump and Mamdani, long foes, emerge from meeting as allies</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Natalie Allison </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1773 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The Washington Post</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>WP</td></tr><tr><td align="right" valign="top" class="index"><b>ED</b>&nbsp;</td><td>FINAL</td></tr><tr><td align="right" valign="top" class="index"><b>PG</b>&nbsp;</td><td>A01</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025, The Washington Post Co. All Rights Reserved </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >President Donald Trump and New York Mayor-elect Zohran Mamdani buried their proverbial hatchets Friday, appearing together in the Oval Office after a meeting each described as the beginning of a warm relationship - despite months of slinging insults and hammering each other's policies.</p>
<p class="articleParagraph enarticleParagraph" >The two men with roots in Queens looked into the cameras and spoke about their shared hopes for New York, emphasized common populist ideals and pledged to work closely together, a sense of agreement that ran afoul of nearly everything their respective political bases have come to expect from them. The president even declared that he would finally feel comfortable moving back to New York with the 34-year-old democratic socialist running city hall.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >It was as if Trump, seated at the Resolute Desk, hadn't just called Mamdani a "communist lunatic" and a "stupid person," and Mamdani, now standing over his right shoulder, hadn't recently referred to the president as a "despot" with a "fascist agenda."</p>
<p class="articleParagraph enarticleParagraph" >"I've been called much worse than a despot," Trump explained to a reporter who asked about the recent jab, one of many questions about their past disagreements that they shrugged off. "So it's not that insulting."</p>
<p class="articleParagraph enarticleParagraph" >It was a remarkable scene that revealed the Republican president's recognition of the political potency of Mamdani's focus on economic policies that benefit the working class. Trump's approval rating has tanked in recent weeks to its lowest point this term, according to a <span class="companylink">Washington Post</span> average of national polls since October, fueled in part by frustrations over the economy. The president has faced criticism from some in his base who say he has not focused enough on the cost-of-living issues he campaigned on fixing and has instead spent too much time on foreign policy matters.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, whose resounding victory Trump acknowledged, for his part had clearly made efforts to flatter the president, conceding that Trump had increased his support among New Yorkers in the 2024 election.</p>
<p class="articleParagraph enarticleParagraph" >"He said a lot of my voters actually voted for him," Trump said.</p>
<p class="articleParagraph enarticleParagraph" >"One in 10," Mamdani interrupted, seeking to correct the record.</p>
<p class="articleParagraph enarticleParagraph" >"And I'm okay with that," Trump added.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani shared that when he spoke with Trump voters on Hillside Avenue in Queens and Fordham Road in the Bronx, they said they supported the president because they wanted to "end forever wars" and address the cost of living, which Mamdani described as a crisis.</p>
<p class="articleParagraph enarticleParagraph" >"We have to get <span class="companylink">Con Edison</span> to start lowering their rates," Trump announced in the Oval Office.</p>
<p class="articleParagraph enarticleParagraph" >"Absolutely," Mamdani said, nodding in agreement.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani, Trump explained, had shared some ideas "that were very interesting."</p>
<p class="articleParagraph enarticleParagraph" >"He wants to see houses go up, he wants to see a lot of houses created, a lot of apartments built, etc." Trump said. "People would be shocked, but I want to see the same thing."</p>
<p class="articleParagraph enarticleParagraph" >Trump repeatedly stuck up for Mamdani as the mayor-elect faced pointed questions from the press corps, at one point urging him not to bother explaining to reporters why he had called Trump a fascist, and at another point defending the climate-conscious politician's decision to take a plane, rather than a train or bus, to Washington.</p>
<p class="articleParagraph enarticleParagraph" >"We agree on a lot more than I thought," Trump said. "I want him to do a great job, and we'll help him do a great job."</p>
<p class="articleParagraph enarticleParagraph" >There were signs earlier in the day that the conversation might not devolve into name-calling and disagreements.</p>
<p class="articleParagraph enarticleParagraph" >Trump sought to tone down his rhetoric about Mamdani ahead of the meeting, predicting during a Fox News interview Friday morning that it would "be quite civil." When the host tried to bait Trump with a comment Mamdani had directed at the president, he acknowledged that the smack talk had gone both ways.</p>
<p class="articleParagraph enarticleParagraph" >"Well, I would say I'm a little hard, too, in all fairness," he said, adding that Mamdani "ran a good race." Trump endorsed former New York governor Andrew M. Cuomo (D) just before Election Day.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani explained this week that an Oval Office meeting between the president and the mayor of the nation's largest city is customary. But the stakes are high for New York. Trump throughout the mayoral race threatened to withhold federal funding for the city if Mamdani won - and even said he'd have Mamdani prosecuted if he did not go along with the president's agenda. Mamdani, meanwhile, is seeking to limit the Trump administration's interference as he tries to execute on ambitious campaign promises like free child care and freezing rent prices.</p>
<p class="articleParagraph enarticleParagraph" >Both major political parties are wrestling with their identities ahead of the midterms and the 2028 presidential election, though strategists on both sides understand that economic relief remains voters' top priority. Mamdani has been kept at arms' length by prominent fellow Democrats nationwide, who believe that socialist ideals will be off-putting to swing voters despite a focus on affordability. And in spite of warnings from Trump and other conservatives about the ruinous effects of progressive governance, populist voices in the Republican Party have claimed that the GOP isn't doing enough to keep the working-class voters who joined Trump's coalition.</p>
<p class="articleParagraph enarticleParagraph" >Trump has repeatedly referred to the mayor-elect as a "communist," a description White House press secretary Karoline Leavitt echoed Thursday. Mamdani identifies as a democratic socialist, a wing of the Democratic Party focused on drastically reducing economic inequality.</p>
<p class="articleParagraph enarticleParagraph" >While Trump had long signaled that he believes Mamdani's brand of politics will be a turnoff to swing voters in the midterms, other Republicans - even officials in the White House - have acknowledged that Mamdani's laser focus on economic issues has resonated with many people. James Blair, the White House's deputy chief of staff for legislative, political and public affairs, said in an interview with Politico this month that Mamdani did "so well" because "he relentlessly focused on affordability."</p>
<p class="articleParagraph enarticleParagraph" >"People talk about communists, they can say all these things, but the fact is he was talking about the cost of living," Blair said.</p>
<p class="articleParagraph enarticleParagraph" >In July, two months before he was killed, top Trump ally and conservative influencer Charlie Kirk told <span class="companylink">The Washington Post</span> that the Republican Party needed to improve its own economic policies, warning about the "Mamdani effect": that many young voters would be attracted to pledges like Mamdani's to make everyday life more affordable, costing conservatives the gains they made with Gen Z in the 2024 election.</p>
<p class="articleParagraph enarticleParagraph" >But Republicans overall have largely focused on framing Mamdani and his policies as an existential threat to the country. Hours before the mayor-elect walked into the White House, the House passed a resolution denouncing socialism, with Republicans backing the measure unanimously. Democrats split their vote, though 23 fewer members voted in favor of it compared with 2023, when the chamber took up the same resolution.</p>
<p class="articleParagraph enarticleParagraph" >"They are grasping at straws," Rep. Becca Balint (D-Vermont) told The Post. "They have nothing. They keep tacking back to the same tired tropes, whether it's socialism, whether it's beating up on trans kids, it's just like the same thing over and over."</p>
<p class="articleParagraph enarticleParagraph" >GOP lawmakers, meanwhile, had hoped Trump's meeting with Mamdani would show a stark contrast between the two men's policies.</p>
<p class="articleParagraph enarticleParagraph" >"I think we need to restate for the people of this country just how dangerous socialism is, how disastrous it has been for the people of the countries in which it has been implemented, and it has its proper place in the ash bin of history," Rep. Ben Cline (R-Virginia) said in an interview ahead of the Oval Office meeting.</p>
<p class="articleParagraph enarticleParagraph" >Some Republicans privately griped afterward about Trump's praise of Mamdani, with one suggesting he had sold out his own party.</p>
<p class="articleParagraph enarticleParagraph" >Before their meeting Friday, Trump leaned into "birther" conspiracies in talking about Mamdani, suggesting falsely that the mayor-elect, a naturalized U.S. citizen who was born in Uganda, is "here illegally." Mamdani moved to New York as a child. Those conspiracies resemble Trump's previous attempted smears against Barack Obama. Trump this year also suggested arresting Mamdani if he tried to prevent federal immigration agents from conducting raids in New York.</p>
<p class="articleParagraph enarticleParagraph" >The president, who was raised in Queens and launched his real estate development career in Manhattan, called New York home for most of his life until officially making Palm Beach, Florida, his primary residence in 2019. At the time, the president announced that he had made the decision after being "treated very badly" by the political leaders in New York.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani's meeting was the latest example of high-profile Democrats walking a tightrope of establishing goodwill with and seeking favorable outcomes from the president in the Oval Office, while proving to their anti-Trump political bases that they stood up to him.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani's foray appeared to go better than most others.</p>
<p class="articleParagraph enarticleParagraph" >New York Gov. Kathy Hochul this spring compared her meeting with Trump to the movie "Rambo," stating that she "didn't draw first blood," while Michigan Gov. Gretchen Whitmer faced embarrassment after the White House called her into the Oval Office at the same time Trump was staging a photo op to sign an executive order targeting political enemies. At one point, Whitmer was photographed covering her face with file folders.</p>
<p class="articleParagraph enarticleParagraph" >And last month, House Minority Leader Hakeem Jeffries and Senate Minority Leader Charles E. Schumer, both Democrats from New York, were photographed in the Oval Office next to "Trump 2028" caps and a grinning and pointing president, an image that Trump and Republicans later mocked. The two Democrats were there with Republican congressional leaders to try to reach a deal to stop the government shutdown, though the two sides failed to come to a consensus then. Trump later posted an AI-doctored video of Schumer and Jeffries speaking to reporters outside the White House.</p>
<p class="articleParagraph enarticleParagraph" >Before the cameras Friday, Trump built up Mamdani as he sent off the young mayor-elect.</p>
<p class="articleParagraph enarticleParagraph" >"By the way, being the mayor of New York City is a big deal. I always said, you know, one of the things I would have loved to be someday is the mayor of New York City," Trump said. "I think you're at a really a turning point one way or the other - it could go great, or it can go in a different direction. And I think you really have a chance to make it great."</p>
<p class="articleParagraph enarticleParagraph" >Trump shook Mamdani's hand, giving it a playful slap.</p>
<p class="articleParagraph enarticleParagraph" >Kadia Goba and Hannah Knowles contributed to this report. </p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>CT</b>&nbsp;</td><td><br/>
                  <span class="colorLinks">http://www.washingtonpost.com [http://www.washingtonpost.com]</span>
               </td></tr>
<tr><td align="right" valign="top" class="index"><br/><b>RF</b>&nbsp;</td><td><br/>WP20251122TRUMPMAMDANI </td></tr>
<tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | greg : Regional Politics | ncat : Content Types | npag : Page One Stories</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | usdc : Washington DC | use : Northeast U.S. | usny : New York State | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>National-Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Washington Post</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document WP00000020251122elbm0001g</td></tr></table><br/></div></div><br/><span></span><div id="article-TIMNOW0020251122elbm0008i" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/timnowLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>world</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>In Mamdani-Trump White House Meeting, A Mention Of India-Pakistan Conflict</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>620 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Times Now</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>TIMNOW</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>Copyright 2025 Bennett, Coleman & Co. Ltd. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >The Mamdani-Trump meeting at the White House seemed warm and friendly. Mamdani flew to Washington DC for his first meeting with Trump in the White House on Friday. Trump said he “enjoyed” the meeting, which he described as “great.”</p>
<p class="articleParagraph enarticleParagraph" >
                        <span class="colorLinks">Click to view image. [https://images.timesnownews.com/thumb/msid-153188366,imgsize-67812,width-1280,height-720/153188366.jpg]</span> United States President Donald Trump met the man who had proudly proclaimed himself "Trump's worst nightmare", New York City's Mayor-elect Zohran Mamdani. As the two met, the situation seemed opposite. During the meeting, Trump once again made the mention of India-Pakistan conflict, repeating his assertion of solving the conflict.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >With Mamdani standing next to him, Trump repeated his claim that he solved the May conflict between India and Pakistan. "I did eight peace deals of countries, including India and Pakistan,” he said.</p>
<p class="articleParagraph enarticleParagraph" >Since May 10, when Trump announced on social media that India and Pakistan had agreed to a “full and immediate” ceasefire after a “long night” of talks mediated by Washington, he has repeated his claim over 60 times that he “helped settle” the tensions between India and Pakistan.</p>
<p class="articleParagraph enarticleParagraph" >India has consistently denied any third-party intervention. India launched Operation Sindoor on May 7, targeting terror infrastructure in Pakistan and Pakistan-occupied Kashmir in retaliation for the April 22 Pahalgam attack that killed 26 civilians. India and Pakistan reached an understanding on May 10 to end the conflict after four days of intense cross-border drone and missile strikes.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani-Trump Meeting</p>
<p class="articleParagraph enarticleParagraph" >Mamdani flew to Washington DC for his first meeting with Trump in the White House on Friday. The Mamdani-Trump meeting at the White House seemed warm and friendly.</p>
<p class="articleParagraph enarticleParagraph" >Trump said he “enjoyed” the meeting, which he described as “great.” Trump, who had in the past called Mamdani a "100 per cent Communist Lunatic" and a "total nut job," spoke openly of how impressed he was with the man who had called his administration "authoritarian".</p>
<p class="articleParagraph enarticleParagraph" >Standing besides Trump, Mamdani was asked whether he still stood by that characterisation. The reporter was referring to Mamdani calling him a "fascist".</p>
<p class="articleParagraph enarticleParagraph" >Responding to it, Mamdani said, "I've spoken about it..." However, Trump quickly interjected, saying, "That's okay. You can just say yes. It's easier than explaining it. I don't mind."</p>
<p class="articleParagraph enarticleParagraph" >Trump jumped in again when a reporter asked Mamdani why he flew to Washington instead of taking transportation that used less fossil fuels."I'll stick up for you," Trump said.</p>
<p class="articleParagraph enarticleParagraph" >"We're going to be helping him, to make everybody's dream come true, having a strong and very safe New York," the US President told reporters with Mamdani beside him in the Oval Office.</p>
<p class="articleParagraph enarticleParagraph" >"What I really appreciate about the president is that the meeting that we had focused not on places of disagreement, which there are many, and also focused on the shared purpose that we have in serving New Yorkers," Mamdani said.</p>
<p class="articleParagraph enarticleParagraph" >Mamdani emerged victorious in the closely-watched battle for New York City Mayor, becoming the first South Asian and Muslim to be elected to sit at the helm of the largest city in the US.</p>
<p class="articleParagraph enarticleParagraph" >He had been the front-runner in the NYC Mayoral election for months and defeated Republican nominee Curtis Sliwa and political heavyweight former New York State Governor Andrew Cuomo, who ran as an independent candidate and was officially endorsed by Trump just hours before the elections.</p>
<p class="articleParagraph enarticleParagraph" >Indian-descent Mamdani is the son of renowned filmmaker Mira Nair and <span class="companylink">Columbia University</span> professor Mahmood Mamdani. He was born and raised in Kampala, Uganda and moved to New York City with his family when he was 7. Mamdani became a naturalised US citizen only recently, in 2018.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gdip : International Relations | gpir : Politics/International Relations</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>asiaz : Asia | devgcoz : Emerging Market Countries | dvpcoz : Developing Economies | india : India | namz : North America | nyc : New York City | pakis : Pakistan | sasiaz : South Asia | usa : United States | usdc : Washington DC | use : Northeast U.S. | usny : New York State | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Zoom Entertainment Network Limited</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document TIMNOW0020251122elbm0008i</td></tr></table><br/></div></div><br/><span></span><div id="article-INDOP00020251122elbm0000p" class="article" ><div class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/indopLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>US politics</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump predicts Mamdani will be ‘really great mayor’ for NYC as duo stumps the press in White House love-fest</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Andrew Feinberg </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>1003 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>Independent Online</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>INDOP</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>© 2025. Independent Digital News and Media Ltd. All Rights Reserved </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Self-avowed socialist who has called Trump a ‘despot’ and ‘fascist’ and president who has called Mamdani ‘communist’ were all smiles after meeting for the first time</p>
<p class="articleParagraph enarticleParagraph" >After months of attacking <span class="colorLinks">New York City [https://www.independent.co.uk/topic/new-york-city]</span> Mayor-elect <span class="colorLinks">Zohran Mandani [https://www.independent.co.uk/topic/zohran-mamdani]</span> as a “communist," President <span class="colorLinks">Donald Trump [https://www.independent.co.uk/topic/donald-trump]</span> now says the Democratic Socialist will be “a really great mayor” for his home city after a closed-door meeting at the White House.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >Seated behind his desk in the Oval Office while Mamdani stood next to him during what became a half-hour love-fest between the two men on Friday, <span class="colorLinks">Trump told reporters he’d congratulated his hometown’s next chief executive [https://www.independent.co.uk/news/world/americas/us-politics/trump-news-today-democrats-sedition-epstein-live-updates-b2869660.html]</span> and pledged to help him bring prices down for New Yorkers.</p>
<p class="articleParagraph enarticleParagraph" >“I think you're going to have, hopefully, a really great mayor — the better he does, the happier I am,” Trump said.</p>
<p class="articleParagraph enarticleParagraph" >“I will say there's no difference in party. There's no difference in anything, and we're going to be helping him to make everybody's dream come true, having a strong and very safe New York.”</p>
<p class="articleParagraph enarticleParagraph" >For his part, Mamdani described the meeting as “productive” and “focused on a place of shared admiration and love” between him and Trump — New York City — and “the need to deliver affordability to New Yorkers, the eight and a half million people who call our city their home, who are struggling to afford life in the most expensive city in the United States of America.”</p>
<p class="articleParagraph enarticleParagraph" >“We spoke about rent, we spoke about groceries, we spoke about utilities. We spoke about the different ways in which people are being pushed out. And I appreciated the time with the President. I appreciated the conversation. I look forward to working together to deliver that affordability for New Yorkers,” Mamdani said.</p>
<p class="articleParagraph enarticleParagraph" >The astonishingly convivial photo opportunity then morphed into a question-and-answer session with White House reporters and select <span class="colorLinks">MAGA [https://www.independent.co.uk/topic/maga]</span> influencers who were brought into the room to witness the moment, with multiple questioners attempting to bait the men into attacking each other.</p>
<p class="articleParagraph enarticleParagraph" >Asked about his previous comments calling Mamdani a “communist” — including one posted to Truth Social just one day ago — Trump implied that Mamdani’s views might change in the future and predicted that the youngest mayor-elect in New York history “is going to surprise some conservative people.”</p>
<p class="articleParagraph enarticleParagraph" >When the mayor-elect was similarly pressed on past comments in which he’d called Trump a “despot,” the president jumped to Mamdani’s defense by telling reporters: “I've been called much worse than a despot, so it's not that insulting.”</p>
<p class="articleParagraph enarticleParagraph" >And after another reporter pushed Mamdani to say whether he was “affirming” prior comments in which he <span class="colorLinks">referred to the president as a “fascist,” [https://www.independent.co.uk/news/world/americas/us-politics/trump-mamdani-oval-office-fascist-b2870226.html]</span> Trump came to the rescue once more and implied that he did not have a problem with the attack.</p>
<p class="articleParagraph enarticleParagraph" >“That’s OK — you can just say ‘yes,’” Trump said.</p>
<p class="articleParagraph enarticleParagraph" >Trump and Mamdani would continue to take questions for roughly 28 surreal minutes, during which the president repeatedly showed surprising affection for the 34-year-old, marking a complete 180-degree <span class="colorLinks">reversal from the vitriol [https://www.independent.co.uk/news/world/americas/us-politics/trump-mamdani-new-york-mayor-b2857470.html]</span> he’d shown towards the soon-to-be former New York State assemblyman dating back to his improbable <span class="colorLinks">victory over former governor Andrew Cuomo [https://www.independent.co.uk/news/world/americas/us-politics/mamdani-nyc-mayoral-race-win-b2858770.html]</span> in the city’s July mayoral Democratic primary.</p>
<p class="articleParagraph enarticleParagraph" >After Mamdani shocked the nation — and the world — by defeating the three-term ex-governor in what would become the first of two matchups between him and the scion of a storied Empire State political dynasty, Trump seized on the future mayor’s avowed <span class="colorLinks">Bernie Sanders [https://www.independent.co.uk/topic/bernie-sanders]</span> -style socialist politics to make him the focus of attacks against both him and the Democratic Party writ large.</p>
<p class="articleParagraph enarticleParagraph" >He even threatened on multiple occasions to pull federal funds from his birthplace, leading some Republican figures to float outlandish ways of denying him the mayoralty if he won the November general election — with some pushing for federal authorities to strip Mamdani of his naturalized citizenship.</p>
<p class="articleParagraph enarticleParagraph" >But in a surprising twist of events, Trump announced that he would sit down with the mayor-elect this week, writing in a Truth Social post on Thursday that “Communist Mayor of New York City, Zohran ‘Kwame’ Mamdani” <span class="colorLinks">had requested the meeting [https://www.independent.co.uk/news/world/americas/us-politics/trump-mamdani-meeting-oval-office-b2868761.html]</span> .</p>
<p class="articleParagraph enarticleParagraph" >And as they faced the assembled press afterwards, the president appeared genuine in the affable feelings he showed for Mamdani and expressed what seemed like admiration at the throngs of journalists who’d flocked to the White House to cover their sit-down.</p>
<p class="articleParagraph enarticleParagraph" >“He's different than you know, your average candidate — he came out of nowhere,” Trump said, referring to Mamdani’s shock primary victory four months ago.</p>
<p class="articleParagraph enarticleParagraph" >“And then, all of a sudden, he wins a primary that nobody expected he was going to win. It's a great, great tribute. It's an amazing thing that he did.”</p>
<p class="articleParagraph enarticleParagraph" >He acknowledged that there would inevitably be “topics” on which he and Mamdani would have disagreements, but suggested that they would be able to settle those differences “for the good of New York.”</p>
<p class="articleParagraph enarticleParagraph" >“I don't care about affiliations or parties or anything else. I want to see if this city could be unbelievable. If he could be a spectacular success, I'd be very happy,” he said.</p>
<p class="articleParagraph enarticleParagraph" >He also told reporters that he’d be “comfortable” living in his hometown under a Mamdani administration despite his past criticisms.</p>
<p class="articleParagraph enarticleParagraph" >“We agree on a lot more than I would have thought — I want him to do a great job, and we'll help him do a great job,” he said.</p>
<p class="articleParagraph enarticleParagraph" >After the press conference, Trump wrote on Truth Social that it was a “great honor” to meet Mamdani.</p>
<p class="articleParagraph enarticleParagraph" >White House Press Secretary Karoline Leavitt later told Fox News’ Sean Hannity, “Maybe Mayor Mamdani will go back to New York and maybe he learned a few things from President Trump today.”</p>
<p class="articleParagraph enarticleParagraph" >Rachel Dobkin contributed to this reporting.</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | greg : Regional Politics</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | nyc : New York City | usa : United States | usdc : Washington DC | use : Northeast U.S. | usny : New York State | uss : Southern U.S.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>IPD</b>&nbsp;</td><td><br/>Americas | Donald Trump | US politics | World | Zohran Mamdani</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Independent Digital News and Media Ltd.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document INDOP00020251122elbm0000p</td></tr></table><br/></div></div><br/><span></span><div id="article-ECTIM00020251122elbm00009" class="lastarticle" ><div id="lastArticle" class="article enArticle"><p><img src="https://logos-factiva-com.ezproxy.cul.columbia.edu/ectimLogo.gif" onerror="this.style.display='none';"/></p>
<table cellpadding="1" cellspacing="1" border="0"><tr><td align="right" valign="top" class="index"><b>SE</b>&nbsp;</td><td>New Updates</td></tr>
<tr><td align="right" valign="top" class="index"><b>HD</b>&nbsp;</td><td><span class='enHeadline'>Trump strikes a surprising tone, says it's okay for Mamdani to call him a ‘fascist’. Watch video</span>
</td></tr><tr><td align="right" valign="top" class="index"><b>BY</b>&nbsp;</td><td>Trending Desk </td></tr>
<tr><td align="right" valign="top" class="index"><b>WC</b>&nbsp;</td><td>633 words</td></tr><tr><td align="right" valign="top" class="index"><b>PD</b>&nbsp;</td><td>22 November 2025</td></tr><tr><td align="right" valign="top" class="index"><b>SN</b>&nbsp;</td><td>The Economic Times</td></tr><tr><td align="right" valign="top" class="index"><b>SC</b>&nbsp;</td><td>ECTIM</td></tr><tr><td align="right" valign="top" class="index"><b>LA</b>&nbsp;</td><td>English</td></tr><tr><td align="right" valign="top" class="index"><b>CY</b>&nbsp;</td><td>(c) 2025 The Times of India Group. All rights reserved. </td></tr>
<tr><td align="right" valign="top" class="index"><p><b>LP</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" >President Donald Trump joked that it was okay for New York City mayor-elect Zohran Mamdani to call him a 'fascist' during his highly anticipated Oval Office meeting on Friday. Donald Trump struck a surprising tone, saying he would be "okay" if Mamdani continued to call him a "fascist", a label Mamdani had used previously during campaign rallies. During their 45-minute minute, Mamdani and Trump said they agreed on a lot of subjects, especially the issue of affordability. The left Democrat was asked by reporters. whether he would walk back his past attack on the Republican president. “I’ve spoken about…,” Mamdani started to answer — before Trump interjected.“That’s OK,” Trump said, patting Mamdani on the arm. “You can just say yes,” the president joked. “It’s easier than explaining.”&mdash; RapidResponse47 (@RapidResponse47) ALSO READ: Interstellar comet 3I/ATLAS image release: <span class="companylink">NASA</span> faces backlash; Harvard scientist says 'no new insights'.</p>
</td></tr><tr><td align="right" valign="top" class="index"><p><b>TD</b>&nbsp;</p></td><td><p class="articleParagraph enarticleParagraph" > Check detailsTrump calls meeting with Mamdani 'very productive'President Trump described his meeting with Zohran Mamdani at the Oval Office as "great" and "very productive," according to CNN. Trump, a New York native, congratulated Mamdani on his election victory and said the two leaders found common ground on several key issues, including housing development and rising food prices."We've just had a great meeting, a really good, very productive meeting. One thing in common, we want this city of ours that we love to do very well," the president said. "And I congratulated him, and we talked about some things in very strong common, like housing and getting housing built, and food prices. The price of oil is coming way down," President Trump told reporters, as per CNN.Trump also extended a gesture of goodwill toward Mamdani, suggesting he may even defy expectations across the political spectrum.ALSO READ: Ivy League degree not needed: <span class="companylink">Instagram</span> CEO Adam Mosseri reveals two qualities required for world-class AI engineers"I think you're going to have, hopefully, a really great mayor. The better he does, the happier I am. I will say there's no difference in party. I think he is going to surprise some conservative people, actually, and some very liberal people," President Trump said as per CNN.Trump defended MamdaniIn another lighthearted moment, Trump appeared to nearly defend Mamdani when the Democratic Socialists of American member was asked about calling the GOP leader a “despot.” “I’ve been called much worse than a despot, so it’s not that insulting,” Trump said when Mamdani was asked about his past dig.ALSO READ: Satya Nadella's stark warning on AI to his employees in internal memo, <span class="companylink">Microsoft</span> CEO says 'we need to rapidly rethink...'Asked whether he would retract his remarks calling Trump a despot in the hopes of improving their relationship, Mamdani said: “I think both President Trump and I, we are very clear about our positions and our views, and what I really appreciate about the President is the meeting that we had focused not on places of disagreement, which there are many, and also focused on the shared purpose that we have in serving New Yorkers.”“And frankly, that is something that could transform the lives of eight and a half million people who are currently struggling under a cost of living crisis, with one in four living in poverty,” he continued. “And the meeting came back again and again to what it could look like to lift those New Yorkers out of struggle and start to deliver them a city that they could do more than just struggle to afford it, but actually start to live in it.”</p>
<p class="articleParagraph enarticleParagraph" >For Reprint Rights: timescontent.com</p>
</td></tr><tr><td align="right" valign="top" class="index"><br/><b>NS</b>&nbsp;</td><td><br/>gcat : Political/General News | gpir : Politics/International Relations | gpol : Domestic Politics | gspace : Space</td></tr><tr><td align="right" valign="top" class="index"><br/><b>RE</b>&nbsp;</td><td><br/>namz : North America | usa : United States</td></tr><tr><td align="right" valign="top" class="index"><br/><b>PUB</b>&nbsp;</td><td><br/>Bennett, Coleman & Co., Ltd.</td></tr><tr><td align="right" valign="top" class="index"><br/><b>AN</b>&nbsp;</td><td><br/>Document ECTIM00020251122elbm00009</td></tr></table><br/></div></div><br/></div></div><span><div id="pageFooter"><table width="100%" cellspacing="0" cellpadding="0" border="0" class="footerBG">
	<tr>
		<td nowrap="nowrap" width="100%" align="right"><span class="copyright">&copy; 2025 Factiva, Inc.  All rights reserved.</span></td>
		<td><div class="ftright">&nbsp;</div></td>
	</tr>
</table>
<span class='shadowL'></span><span class='shadowR'></span></div><noscript><img src="http://om.dowjoneson.com/b/ss/djfactivatesting/1/H.22.1--NS/0" height="1" width="1" border="0" alt="" /></noscript></span><script type="text/javascript">
//<![CDATA[
jQuery(document).ready (function(){
try { InitializeOmniture('djfactiva');}catch (ex) {}
try {DJOmniture.Property.SessionId = "mpgviMmM_GY3TCYJSGFTDCMTGGI2DIYRUHBRGEOBRGNSGIMTBHBTGGZRVGM4Q";DJOmniture.Property.UserId_Ns = "E6OO2HVCQHVPFGQJS4YZ7OYDUQ";DJOmniture.Property.AccountId = "";DJOmniture.Property.FullURL = "https://global-factiva-com.ezproxy.cul.columbia.edu/hp/printsavews.aspx?ppstype=Article&pp=Print&hc=All";DJOmniture.Property.AccessCode = "0086";DJOmniture.Property.PageName = "PageNameNotSet";DJOmniture.Property.SearchType = "";DJOmniture.Property.FilterType = "";DJOmniture.Property.FilterValue = "";DJOmniture.Property.Type = "";DJOmniture.Property.ProfileName = "";DJOmniture.Property.ReportType = "";DJOmniture.Property.DataRange = "";DJOmniture.Property.FormatType = "";DJOmniture.Property.AccessionNumber = "";DJOmniture.Property.ContentType = "";DJOmniture.Property.ArticleType = "";DJOmniture.Property.Headline = "";DJOmniture.Property.Author = "";DJOmniture.Property.WordCount = "";DJOmniture.Property.PublicationDate = "";DJOmniture.Property.Source = "";DJOmniture.Property.BaseLanguage = "";DJOmniture.Property.ScreeningType = "";DJOmniture.Property.ScreeningValue = "";DJOmniture.Property.FactivaPageId = "";DJOmniture.Property.Channel = "";DJOmniture.Property.Area = "";DJOmniture.Property.Section = "";DJOmniture.Property.SearchQueryLength = "";}catch (ex) {}
});
//]]>
</script><table id="tmpJQueryTarget" border="0">
	<tr>

	</tr>
</table>

<script type="text/javascript">
//<![CDATA[
(function() {var fn = function() {$get('PageScriptManager_HiddenField').value = '';Sys.Application.remove_init(fn);};Sys.Application.add_init(fn);})();//]]>
</script>

<script src="https://global-factiva-com.ezproxy.cul.columbia.edu/CombineScriptsHandler.ashx?_TSM_HiddenField_=PageScriptManager_HiddenField&amp;_TSM_CombinedScripts_=%3b%3bAjaxControlToolkit%2c+Version%3d3.0.30930.28736%2c+Culture%3dneutral%2c+PublicKeyToken%3d28f01b0e84b6d53e%3aen-US%3ab0eefc76-0092-471b-ab62-f3ddc8240d71%3a865923e8%3bfactiva.com.ui%3aen-US%3ae646eb98-cdf8-4fce-ba1a-cebd47fe8530%3a84690f9d%3bEMG.Toolkit.Web%2c+Version%3d2.0.0.22%2c+Culture%3dneutral%2c+PublicKeyToken%3dnull%3aen-US%3ade23b191-cd1d-4c31-b7c2-c71e4d22ee9a%3a78e334ee%3a28617db2%3a235de37a%3a35bc484f%3a360cd5dc%3bAjaxControlToolkit%2c+Version%3d3.0.30930.28736%2c+Culture%3dneutral%2c+PublicKeyToken%3d28f01b0e84b6d53e%3aen-US%3ab0eefc76-0092-471b-ab62-f3ddc8240d71%3a91bd373d%3bEMG.Toolkit.Web%2c+Version%3d2.0.0.22%2c+Culture%3dneutral%2c+PublicKeyToken%3dnull%3aen-US%3ade23b191-cd1d-4c31-b7c2-c71e4d22ee9a%3a312433fe%3aa74d42b0" type="text/javascript"></script>
<script type="text/javascript">
//<![CDATA[
Sys.Application.add_init(function() {
    $create(EMG.Toolkit.Web.TableSorterBehavior, {"debug":true,"headers":"{0: { sorter: false}, 3: {sorter: false}}","id":"_jqueryPlgn","sortList":"[0,1], [1,1]","widgetZebra":"[\u0027zebra\u0027]"}, null, null, $get("tmpJQueryTarget"));
});
//]]>
</script>
</form><script type='text/javascript'>if(document.getElementById('carryOverHeadlines')){document.getElementById('carryOverHeadlines').style.display = 'block';}$(document).ready(function(){setTimeout(function(){window.print();}, 1000);});</script><script type='text/javascript'>framesViewNotReqd = false;modalEnabled = true;RequestFromModal=false;RequestFromIPad=false;SnapshotBaseUrl='https://snapshot-factiva-com.ezproxy.cul.columbia.edu';</script>
</body>
</html> """

In [2]:
import glob # used to find all the file paths that match a specified pattern
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

create new factiva folder

In [4]:
import os

# ✅ Give your folder a clear name — e.g., use your initials or project topic
FOLDER_NAME = "factiva_ner_project"

# Build the full path
DRIVE_ROOT = "/content/drive/MyDrive"
path = os.path.join(DRIVE_ROOT, FOLDER_NAME)

# Create the folder if it doesn’t exist
os.makedirs(path, exist_ok=True)

print(f"✅ Folder ready at: {path}")

✅ Folder ready at: /content/drive/MyDrive/factiva_ner_project

Next, you want to save the contents of the `html_code` variable into a `.htm` file:

In [9]:

# Write the HTML code to the file
with open("/content/drive/MyDrive/factiva_ner_project/factiva.htm", "w") as file:
    file.write(html_code)


# # For a list of variables with HTML content
# html_list = [html_code1, html_code2, html_code3]  # Replace with your actual variables

# # Iterate over the list and write each HTML content to a separate file
# for i, html_code in enumerate(html_list):
#     file_path = f"/content/drive/MyDrive/Factiva/factiva_{i}.htm"  # Replace with your path
#     with open(file_path, 'w') as file:
#         file.write(html_code)

In the following line, you will look for all `.htm` files in your Factiva folder (and its subfolders, if any) located at the specified path on your Google Drive and return them as a list.

- glob.glob is a function that finds all the files that match a specific pattern. In this case, it looks for files inside a folder called Factiva that have the .htm extension.
- The part `/content/drive/MyDrive/Factiva/*.htm` is the path where it will look for the files. You would replace this with the path where your own files are located. The *.htm means it will find all files ending with .htm (which are likely HTML files).
- recursive = True allows the function to search within subdirectories inside the Factiva folder as well.

In [10]:
files = glob.glob("/content/drive/MyDrive/factiva_ner_project/factiva.htm", recursive = True) #replace with your path

In [11]:
files

['/content/drive/MyDrive/factiva_ner_project/factiva.htm']

The following `for loop` starts with an empty list. It then goes through each HTML file in the files list, reads any tables found in those files, and adds them to the empty_list.

In this case, the goal is to have a list where each element is a dataframe, not a list of lists. Since `pd.read_html()` returns a list of dataframes for each file, `extend` is used to merge those dataframes directly into `empty_list` so that it contains all the dataframes in one flat structure.

If you used `append`, you would end up with a nested structure where each element is a list of dataframes, which is likely not what you want.

In [12]:
empty_list = []
for file in files:
    data = pd.read_html(file, index_col = 0) #reads the HTML content of the file and tries to find any tables inside it.
    empty_list.extend(data) # The extend() method is used to add the data (which is a list of dataframes) from the current file to empty_list.

In [13]:
empty_list

[                           1
 0
 Dow Jones Factiva  Dow Jones,
                                                      1
 0
 HD               Munis steady, issuance falls to $1.2B
 BY                                     Christina Baker
 WC                                          1182 words
 PD                                    24 November 2025
 SN                                      The Bond Buyer
 SC                                               BBYER
 VOL                                  Vol.397, No.36411
 LA                                             English
 CY                © 2025 Arizent. All rights reserved.
 LP   Municipals were steady Friday ahead of a paltr...
 TD   The muni market is slowing, Barclays analysts ...
 NS   m12 : Debt/Bond Markets | mcat : Commodity/Fin...
 RE          namz : North America | usa : United States
 PUB                                            Arizent
 AN                  Document BBYER00020251121elbo00007,
 Empty DataFrame
 Columns: []
 Index: [Trump and Mamdani go from adversaries to allies after White House meetingLincoln Daily News, 12:08 PM, 22 November 2025, 1151 words, MICHELLE L. PRICE, (English) WASHINGTON (AP) — President Donald Trump on Friday met the man who had proudly proclaimed himself “Donald Trump's worst nightmare,” but he seemed to find the opposite. (Document WC44555020251122elbm0000g)],
 Empty DataFrame
 Columns: []
 Index: [Trump to meet 'communist' Mayor of New York City Zohran Mamdani at White House on FridayIndia TV News, 12:08 PM, 22 November 2025, 437 words, (English) Mamdani emerged victorious in the closely-watched battle for New York City Mayor, becoming the first South Asian and Muslim to be elected to sit at the helm of the largest city in the US. (Document WC57785020251122elbm0001h)],
                                                      1
 0
 SE                                   Editorial-Opinion
 HD                              The Trump-Mamdani show
 BY                                  By Editorial Board
 WC                                           786 words
 PD                                    22 November 2025
 SN                                  washingtonpost.com
 SC                                               WPCOM
 LA                                             English
 CY   Copyright 2025, The Washington Post Co. All Ri...
 LP   What are a few deportation threats among frien...
 TD   "The better he does, the happier I am," Trump ...
 NS   gcat : Political/General News | gpir : Politic...
 RE   namz : North America | usa : United States | u...
 IPD    Editorial | Opinion | opinions | the-posts-view
 PUB                                    Washington Post
 AN                  Document WPCOM00020251122elbl00001,
                                                      1
 0
 SE                                                News
 HD   Trump and New York City mayor-elect Zohran Mam...
 BY                                     Khushboo Razdan
 WC                                           617 words
 PD                                    22 November 2025
 SN                                            scmp.com
 SC                                              SCMCOM
 LA                                             English
 CY             (c) 2025 scmp.com. All rights reserved.
 LP   Their first meeting brought unexpected warmth,...
 TD   “Some of his ideas are the same as my ideas,” ...
 NS   gcat : Political/General News | gpir : Politic...
 RE   namz : North America | nyc : New York City | u...
 PUB        South China Morning Post Publishers Limited
 AN                  Document SCMCOM0020251122elbm00003,
 Empty DataFrame
 Columns: []
 Index: [House Dem in pro-Trump district reveals top issue for his battleground votersFOXNews.com, 12:01 PM, 22 November 2025, 898 words, (English) This material may not be published, broadcast, rewritten, or redistributed. ©2025 FOX News Network, LLC. All rights reserved. Quotes displayed in real-time or delayed by at least 15 minutes. Market data provided by Factset. Powered and ... (Document WC42085020251122elbm003ee)],
                                                      1
 0
 SE                                               Music
 HD   The Weird Mystery of Olivia Nuzzi’s Teenage Po...
 BY                                    By Rob Sheffield
 WC                                          1502 words
 PD                                    22 November 2025
 SN                                       Rolling Stone
 SC                                               NAPRS
 LA                                             English
 CY   Rolling Stone is a part of Penske Media Corpor...
 LP   The controversial journalist reportedly had a ...
 TD   Olivia Nuzzi is no stranger to controversy. Th...
 NS   c16 : Bankruptcy | cactio : Corporate Actions ...
 RE          namz : North America | usa : United States
 IPD  Britney Spears | Lady Gaga | Music | Music Fea...
 PUB                           Penske Media Corporation
 AN                  Document NAPRS00020251122elbm0005l,
                                                      1
 0
 SE                                            Briefing
 HD                                         Pushing Off
 BY                                   By Melissa Kirsch
 WC                                          2118 words
 PD                                    22 November 2025
 ET                                            06:22 AM
 SN                                         nytimes.com
 SC                                             NYTFEED
 LA                                             English
 CY   Copyright 2025. The New York Times Company. Al...
 LP   Thanksgiving’s this coming week. How can we ke...
 TD   The holiday season has its own engine, one tha...
 NS   gcat : Political/General News | glife : Living...
 RE          namz : North America | usa : United States
 IPD  Autumn (Season) | briefing | Christmas | Holid...
 PUB                         The New York Times Company
 AN                  Document NYTFEED020251122elbm00209,
 Empty DataFrame
 Columns: []
 Index: [Trump praises Mamdani in Oval Office meeting "I think he is going to surprise some conservative people, actually," the President said.TVNZ, 11:45 AM, 22 November 2025, 13654 words, (English) President Donald Trump has called New York City's Mayor-elect Zohran Mamdani a "100% Communist Lunatic" and a "total nut job." Mamdani has called Trump’s administration "authoritarian" and described himself as "Donald Trump’s worst ... (Document WC41160020251122elbm0000n)],
 Empty DataFrame
 Columns: []
 Index: [Air New Zealand cabin crew to strike in December Around 1250 E tū cabin crew across the international, domestic, and regional fleets will...TVNZ, 11:45 AM, 22 November 2025, 11797 words, (English) Air NZ cabin crew will strike on next month after months of negotiations failed to secure a fair deal on pay and conditions.Around 1250 E tū cabin crew across the international, domestic, and regional fleets will stop work for 24 hours on ... (Document WC41160020251122elbm0000c)],
 Empty DataFrame
 Columns: []
 Index: [Tone shifts in Washington: Trump praises Mamdani after White House talks, vows support for a ‘safe New York’The Statesman, 02:51 AM, 22 November 2025, 490 words, (English) US President Donald Trump struck a noticeably calmer tone on Friday as he welcomed New York City mayor-elect Zohran Mamdani to the White House. The meeting marked a shift from the tense exchanges that defined the long and bitter mayoral ... (Document WC43537020251122elbm0001g)],
                                                      1
 0
 HD   How Zohran Mamdani's NYC victory could make a ...
 BY                                         Alex Nicoll
 WC                                          1136 words
 PD                                    22 November 2025
 ET                                            07:46 AM
 SN                                    Business Insider
 SC                                              BIZINS
 LA                                             English
 CY                         Copyright 2025. Insider Inc
 LP   * Incoming NYC Mayor Mamdani's embrace of soci...
 TD   * This comes after a banner year for ultra-lux...
 IN   i834 : Real Estate Agents/Brokers | i85 : Real...
 RE   miami : Miami | namz : North America | nyc : N...
 IPD  Finance | luxury-real-estate | Real Estate | z...
 PUB                                       Insider Inc.
 AN                  Document BIZINS0020251122elbm0008e,
 Empty DataFrame
 Columns: []
 Index: [Renewed commitment: New York Governor Kathy Hochul welcomes Trump-Mamdani meetingWebIndia123.com, 10:47 PM, 21 November 2025, 419 words, (English) New York Governor Kathy Hochul on Friday issued a strongly worded statement after President Donald Trump met Mayor-Elect Zohran Mamdani, voicing approval of the President's "renewed commitment" to the state while condemning Islamophobic ... (Document WC56775020251122elbm0003p)],
 Empty DataFrame
 Columns: []
 Index: [Trump-Mamdani MeetingKPIX-TV5, 11:39 AM, 22 November 2025, 3246 words, Renee Anderson, (English) Jesse Zanger is the managing editor of CBSNewYork.com. Jesse has previously worked for the Fox News Channel and Spectrum News NY1. He covers regional news around the Tri-State Area, with a particular focus on breaking news and extreme ... (Document WC42295020251122elbm00002)],
 Empty DataFrame
 Columns: []
 Index: [Mamdani set to meet with President Trump at White House today New York City Mayor-elect Zohran Mamdani is set to meet with President Trump...WCBS TV, 11:35 AM, 22 November 2025, 635 words, (English) Christina Fan joined CBS News New York as a general assignment reporter in spring of 2019.Jessica Moore is an Emmy Award-winning anchor for the weekend evening newscasts on CBS News New York and New York 55. Moore joined the stations in ... (Document WC57089020251122elbm0000c)],
 Empty DataFrame
 Columns: []
 Index: [What's at stake in the Trump-Mamdani meeting? Political analysis New York City Mayor-elect Zohran Mamdani is sitting down with President...WCBS TV, 11:35 AM, 22 November 2025, 806 words, (English) Jesse Zanger is the managing editor of CBSNewYork.com. Jesse has previously worked for the Fox News Channel and Spectrum News NY1. He covers regional news around the Tri-State Area, with a particular focus on breaking news and extreme ... (Document WC57089020251122elbm00009)],
 Empty DataFrame
 Columns: []
 Index: [Trump-Mamdani meeting marked by surprising moments of praise President Trump and NYC Mayor-elect Zohran Mamdani have hurled attacks at each...WCBS TV, 11:36 AM, 22 November 2025, 1077 words, (English) Joe Walsh is a senior editor for digital politics at CBS News. Joe previously covered breaking news for Forbes and local news in Boston.President Trump's meeting with incoming New York City Mayor Zohran Mamdani on Friday was not expected to... (Document WC57089020251122elbm0000n)],
 Empty DataFrame
 Columns: []
 Index: [What Trump and Mamdani have said about each other ahead of White House meeting President Trump has called Zohran Mamdani "my little...WCBS TV, 11:36 AM, 22 November 2025, 1404 words, (English) Kathryn Watson is a politics reporter for CBS News Digital, based in Washington, D.C.Update: President Trump and Mayor-elect Mamdani struck a positive tone in their meeting. Read the latest here. Our earlier story is below. (Document WC57089020251122elbm00012)],
 Empty DataFrame
 Columns: []
 Index: [New York Rep. Nydia Velázquez won't seek reelection in 2026 Velázquez, 72, says she will retire after her 16th term in office. She...WCBS TV, 11:36 AM, 22 November 2025, 395 words, (English) Jesse Zanger is the managing editor of CBSNewYork.com. Jesse has previously worked for the Fox News Channel and Spectrum News NY1. He covers regional news around the Tri-State Area, with a particular focus on breaking news and extreme ... (Document WC57089020251122elbm00013)],
 Empty DataFrame
 Columns: []
 Index: [Takeaways from Trump and Mamdani visit: Both men get something they want, GOP loses a punching bagThe Times Herald, 07:20 PM, 21 November 2025, 963 words, (English) Trump seemed thoroughly impressed with Mamdani, describing him as “a very rational man” who “wants to see New York be great again.”The two had called each other “fascist” and “communist,” but when President Donald Trump and New York City ... (Document WC44933020251122elbm0000h)],
 Empty DataFrame
 Columns: []
 Index: [Mamdani, Trump find common ground during first meeting at White HouseUpdated 2 hours agoABC 7, 05:47 AM, 22 November 2025, 734 words, the Associated Press, (English) NEW YORK (WABC) -- New York City Mayor-elect Zohran Mamdani is heading home on Saturday after his highly anticipated meeting with President Donald Trump at the White House. (Document WC42290020251122elbm003mm)],
 Empty DataFrame
 Columns: []
 Index: [As the two leaders stood together, Trump once again referred to the May standoff between India and Pakistan, saying, "I...Deccan Chronicle, 05:10 AM, 22 November 2025, 457 words, (English) Washington: US President Donald Trump again repeated his long-standing claim that he played a central role in helping ease the conflict between India and Pakistan. He made the remarks during his meeting with New York City Mayor-elect Zohran... (Document WC44949020251122elbm000bv)],
                                                      1
 0
 SE                                             Fashion
 HD   Less politics, more makeup: the unraveling of ...
 BY                                      Carter Sherman
 WC                                          1786 words
 PD                                    22 November 2025
 ET                                            11:03 AM
 SN                                        The Guardian
 SC                                                GRDN
 LA                                             English
 CY   © Copyright 2025. The Guardian. All rights res...
 LP   The folding of the progressive youth-focused m...
 TD   The story garnered more than 1.3m hits, making...
 CO   cnast : Conde Nast Publications Inc | newhse :...
 IN   i475 : Printing/Publishing | i4752 : Magazine ...
 NS   gcat : Political/General News | gcom : Society...
 RE          namz : North America | usa : United States
 PUB                      Guardian News & Media Limited
 AN                  Document GRDN000020251122elbm002pj,
                                                      1
 0
 HD               California Clears Path for Gig Unions
 BY                                 C. Jarrett Dieterle
 WC                                           699 words
 PD                                    22 November 2025
 SN                                          Reason.com
 SC                                               RECOM
 LA                                             English
 CY                            © 2025 Reason Foundation
 LP   Even after the Prop 22 rebuke, California is p...
 TD   In October, California lawmakers passed a bill...
 CO   ubrib : Uber International B.V. | ubrti : Uber...
 IN   i722 : Taxi/Limousine Services | iecom : E-com...
 NS   c42 : Staff/Personnel | ccat : Corporate/Indus...
 RE   namz : North America | usa : United States | u...
 IPD  Big Government | California | Collective Barga...
 PUB                                  Reason Foundation
 AN                  Document RECOM00020251122elbm00002,
                                                      1
 0
 SE                                   National-Politics
 HD   What Trump and Mamdani have said about each ot...
 BY                                  By Victoria Bisset
 WC                                          1297 words
 PD                                    22 November 2025
 SN                                  washingtonpost.com
 SC                                               WPCOM
 LA                                             English
 CY   Copyright 2025, The Washington Post Co. All Ri...
 LP   For months, President Donald Trump repeatedly ...
 TD   Here's what Trump and Mamdani have previously ...
 NS   gcat : Political/General News | gpir : Politic...
 RE   namz : North America | nyc : New York City | u...
 IPD                                           politics
 PUB                                    Washington Post
 AN                  Document WPCOM00020251122elbm001uq,
                                                      1
 0
 HD   What lessons can be learned from the Trump-Mam...
 WC                                           943 words
 PD                                    22 November 2025
 SN                                           jpost.com
 SC                                              JPSTEN
 LA                                             English
 CY   © 2025, Jpost.com (The Jerusalem Post online e...
 LP   United States President Donald Trump met with ...
 TD   For some observers of Trump and Mamdani, the m...
 NS   gcat : Political/General News | gpir : Politic...
 RE   namz : North America | usa : United States | u...
 IPD                                               News
 PUB                                 The Jerusalem Post
 AN                  Document JPSTEN0020251122elbm000xd,
                                                      1
 0
 SE                                         US politics
 HD   Trump gloats over ‘traitor’ MTG’s decision to ...
 BY                                         Erin Keller
 WC                                          1040 words
 PD                                    22 November 2025
 SN                                  Independent Online
 SC                                               INDOP
 LA                                             English
 CY   © 2025. Independent Digital News and Media Ltd...
 LP   The Georgia firebrand’s upcoming exit from Con...
 TD   In a lengthy Truth Social [https://truthsocial...
 NS   gcat : Political/General News | gpir : Politic...
 RE          namz : North America | usa : United States
 IPD  Americas | Congressman | Donald Trump | MAGA |...
 PUB            Independent Digital News and Media Ltd.
 AN                  Document INDOP00020251122elbm000s7,
                                                      1
 0
 SE                                                News
 HD   ‘Cheering for him’: Key takeaways from Trump-M...
 BY                 Alastair McCready and News Agencies
 WC                                          1338 words
 PD                                    22 November 2025
 ET                                            02:33 AM
 SN                                  Al Jazeera English
 SC                                              AJAZEN
 LA                                             English
 CY                  Copyright 2025 Al Jazeera English.
 LP   President Trump and the mayor-elect adopt a ma...
 TD   The warmth displayed came in stark contrast to...
 NS   gcat : Political/General News | gpir : Politic...
 RE   namz : North America | nyc : New York City | u...
 IPD                     Donald Trump | News | Politics
 PUB                           Al Jazeera International
 AN                  Document AJAZEN0020251122elbm000e3,
 Empty DataFrame
 Columns: []
 Index: [Leftist NY mayor-elect and Trump make nice in White House 3 hours agoThe Edition, 10:53 AM, 22 November 2025, 792 words, (English) Months of sniping melted away Friday as New York's incoming leftist mayor Zohran Mamdani and President Donald Trump were all smiles at a White House meeting -- promising to set aside their feud and cooperate on the city's future. (Document WC75596020251122elbm0000e)],
 Empty DataFrame
 Columns: []

Let's create a variable, `frames`, which contains a dataframe where all relevant dataframes (those containing 'HD' in their index) are combined and flipped.

In the next line of code, we will accomplish the following:
- Look through all the dataframes in `empty_list` and selects only the ones where `HD` is found in the index.
- Concatenate those dataframes side by side (combining their columns).
- Finally, transpose the resulting dataframe, flipping the rows and columns, and assigning it to the variable `frames`.


Breaking it down:
- `[l for l in empty_list if 'HD' in l.index.values]:`
1. This is a list comprehension. It goes through each item `l` in `empty_list` (which contains dataframes).
2. For each dataframe `l`, it checks if `'HD'` is present in the index values of that dataframe `(l.index.values)`.
3. If `'HD'` is found in the index of a dataframe, that dataframe is included in the resulting list. If `'HD'` is not found, that dataframe is ignored.

- `pd.concat([...], axis=1)`:

1. this concatenates (joins) all the dataframes that contain `'HD'` in their index. The `axis=1` argument means the dataframes will be concatenated side by side, meaning their columns will be combined.The result is a new dataframe where the data from each matching dataframe is merged by columns.

- `.T`:
1. This is a shorthand for "transpose," which flips the rows and columns of the resulting dataframe.
2. After concatenating the dataframes side by side, `.T` switches the rows and columns, so what were previously columns are now rows, and vice versa.

In [14]:
frames = pd.concat([l for l in empty_list if 'HD' in l.index.values], axis=1).T

In [15]:
frames

,HD,BY,WC,PD,SN,SC,VOL,LA,CY,LP,...,ET,IN,CO,ED,PG,CT,CLM,RF,IPC,CR
1,"Munis steady, issuance falls to $1.2B",Christina Baker,1182 words,24 November 2025,The Bond Buyer,BBYER,"Vol.397, No.36411",English,© 2025 Arizent. All rights reserved.,Municipals were steady Friday ahead of a paltr...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The Trump-Mamdani show,By Editorial Board,786 words,22 November 2025,washingtonpost.com,WPCOM,NaN,English,"Copyright 2025, The Washington Post Co. All Ri...",What are a few deportation threats among frien...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Trump and New York City mayor-elect Zohran Mam...,Khushboo Razdan,617 words,22 November 2025,scmp.com,SCMCOM,NaN,English,(c) 2025 scmp.com. All rights reserved.,"Their first meeting brought unexpected warmth,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The Weird Mystery of Olivia Nuzzi’s Teenage Po...,By Rob Sheffield,1502 words,22 November 2025,Rolling Stone,NAPRS,NaN,English,Rolling Stone is a part of Penske Media Corpor...,The controversial journalist reportedly had a ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Pushing Off,By Melissa Kirsch,2118 words,22 November 2025,nytimes.com,NYTFEED,NaN,English,Copyright 2025. The New York Times Company. Al...,Thanksgiving’s this coming week. How can we ke...,...,06:22 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,How Zohran Mamdani's NYC victory could make a ...,Alex Nicoll,1136 words,22 November 2025,Business Insider,BIZINS,NaN,English,Copyright 2025. Insider Inc,* Incoming NYC Mayor Mamdani's embrace of soci...,...,07:46 AM,i834 : Real Estate Agents/Brokers | i85 : Real...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Less politics, more makeup: the unraveling of ...",Carter Sherman,1786 words,22 November 2025,The Guardian,GRDN,NaN,English,© Copyright 2025. The Guardian. All rights res...,The folding of the progressive youth-focused m...,...,11:03 AM,i475 : Printing/Publishing | i4752 : Magazine ...,cnast : Conde Nast Publications Inc | newhse :...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,California Clears Path for Gig Unions,C. Jarrett Dieterle,699 words,22 November 2025,Reason.com,RECOM,NaN,English,© 2025 Reason Foundation,"Even after the Prop 22 rebuke, California is p...",...,NaN,i722 : Taxi/Limousine Services | iecom : E-com...,ubrib : Uber International B.V. | ubrti : Uber...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,What Trump and Mamdani have said about each ot...,By Victoria Bisset,1297 words,22 November 2025,washingtonpost.com,WPCOM,NaN,English,"Copyright 2025, The Washington Post Co. All Ri...","For months, President Donald Trump repeatedly ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,What lessons can be learned from the Trump-Mam...,NaN,943 words,22 November 2025,jpost.com,JPSTEN,NaN,English,"© 2025, Jpost.com (The Jerusalem Post online e...",United States President Donald Trump met with ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Trump gloats over ‘traitor’ MTG’s decision to ...,Erin Keller,1040 words,22 November 2025,Independent Online,INDOP,NaN,English,© 2025. Independent Digital News and Media Ltd...,The Georgia firebrand’s upcoming exit from Con...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,‘Cheering for him’: Key takeaways from Trump-M...,Alastair McCready and News Agencies,1338 words,22 November 2025,Al Jazeera English,AJAZEN,NaN,English,Copyright 2025 Al Jazeera English.,President Trump and the mayor-elect adopt a ma...,...,02:33 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,THE RED APPLE | ZO THE BIG APPLE OF HIS EYE; B...,"Steven Nelson, Craig McCarthy and Matt Troutman",1038 words,22 November 2025,New York Post,NYPO,NaN,English,"(c) 2025 N.Y.P. Holdings, Inc. All rights rese...",They found comrade ground. Zohran Mamdani's hi...,...,NaN,NaN,NaN,Late City Final,4,NaN,NaN,NaN,NaN,NaN
1,The Surprise Ending to the Trump-Mamdani Buddy...,By Dana Rubinstein and Benjamin Oreskes,1084 words,21 November 2025,nytimes.com,NYTFEED,NaN,English,Copyright 2025. The New York Times Company. Al...,Zohran Mamdani and President Trump seemed to c...,...,08:22 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,'Will Rahul Gandhi get the message?': BJP's ji...,HT News Desk,441 words,22 November 2025,Hindustan Times,HNTM,NaN,English,Copyright 2025. HT Media Limited. All rights r...,"India, Nov. 22 -- The BJP grabbed onto Shashi ...",...,NaN,NaN,NaN,NaN,NaN,For any query with respect to this article or ...,NaN,NaN,NaN,NaN
1,"‘Fascist’? ‘Communist’? For an Afternoon, They...",By Shawn McCreesh,1094 words,21 November 2025,nytimes.com,NYTFEED,NaN,English,Copyright 2025. The New York Times Company. Al...,Acid insults were set aside as New York’s mayo...,...,08:05 PM,NaN,NaN,NaN,NaN,NaN,White House Memo,NaN,NaN,NaN
1,Trump met with New York's Muslim mayor-elect: ...,NaN,1145 words,22 November 2025,CE NoticiasFinancieras,NFINCE,NaN,English,Copyright © Content Engine LLC,U.S. President Donald Trump met Friday with th...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,This week in business: A housing plateau colli...,Emily Price,1498 words,22 November 2025,Fast Company,FSTC,NaN,English,Copyright 2025 Mansueto Ventures LLC,"This week, politics, memes, and protest moveme...",...,NaN,ibnk : Banking/Credit | ifinal : Financial Ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ghosts of Radicals Past: What NYC’s New Mayor ...,NaN,838 words,22 November 2025,The National Herald,NATHER,NaN,English,"© Copyright 2025 - The National Herald, Inc.",New York City found itself at the epicenter of...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Trump and Mamdani go from adversaries to allie...,Times news services,1640 words,22 November 2025,Tampa Bay Times,STPT,NaN,English,Copyright 2025 Times Publishing Company. All R...,WASHINGTON — President Donald Trump on Friday ...,...,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN
1,Are the rich fleeing Mamdani’s Manhattan? Not ...,Swapna Venugopal Ramaswamy,1973 words,22 November 2025,usatoday.com,USATONL,NaN,English,© Copyright Gannett 2025 All Rights Reserved.,NEW YORK − Margaret Flint was 18 when she firs...,...,05:06 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,'Did 8 peace deals': Trump repeats role in Ind...,TOI News Desk,246 words,22 November 2025,The Times of India,TOI,NaN,English,(c) 2025 The Times of India Group,NEW DELHI: US President Donald Trump on Friday...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"This is how democracy should work, hope to see...",NaN,475 words,22 November 2025,Press Trust of India,PRTRIN,NaN,English,Copyright 2025. The Press Trust of India Limited.,"New Delhi, Nov 22 (PTI) Congress leader Shashi...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Chatti In NYC Brings Kerala's Toddy Shop Cultu...,NaN,908 words,22 November 2025,NDTV,NDTVIN,NaN,English,"Copyright. 2025. NDTV Convergence Ltd., New De...",There's a certain unbridled energy I experienc...,...,08:06 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Don does a 180: instead of ripping Zoh, vows a...",Chris Sommerfeldt,1225 words,22 November 2025,New York Daily News,NYDN,ISSN:2692-1251,English,"© 2025 Daily News, New York. Provided by ProQu...",During an extraordinarily cordial meeting at t...,...,NaN,i1 : Energy | i16 : Electricity/Gas Utilities ...,NaN,NaN,CS.5,NaN,NaN,NaN,NaN,NaN
1,‘I did 8 peace deals’: Trump again touts role ...,NaN,306 words,22 November 2025,Moneycontrol.com,MONECT,NaN,English,Copyright 2025. www.moneycontrol.com [http://w...,The comments came during his meeting with New ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NYC’s matching funds fueled Mamdani’s success,NaN,789 words,22 November 2025,New York Daily News,NYDN,ISSN:2692-1251,English,"© 2025 Daily News, New York. Provided by ProQu...",Zohran Mamdani’s insurgent win has spawned end...,...,NaN,NaN,ctzutd : Citizens United,NaN,CS.20,NaN,NaN,NaN,NaN,NaN
1,REUTERS NEWS SCHEDULE AT 11:00 a.m. GMT/ 6:00 ...,NaN,841 words,22 November 2025,Reuters News,LBA,NaN,English,Copyright 2025 Thomson Reuters. All Rights Res...,Here are the top stories and upcoming coverage...,...,06:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,Released: 2025-11-22T12:00:04.000Z,DED | LANG:en | SERVICE:ABX | SERVICE:AFA | SE...,NaN
1,Piggy Gets Polite,By Maureen Dowd,1231 words,22 November 2025,nytimes.com,NYTFEED,NaN,English,Copyright 2025. The New York Times Company. Al...,"Step by slimy step, President Trump has made u...",...,07:00 AM,NaN,NaN,NaN,NaN,NaN,Maureen Dowd,NaN,NaN,NaN
1,Trump and Mamdani go from adversaries to allies,Associated Press,335 words,22 November 2025,Daily Herald,DHLD,NaN,English,Copyright 2025 Daily Herald,WASHINGTON — President Donald Trump on Friday ...,...,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN
1,'This is how democracy should work': Shashi Th...,CNBC-TV18,459 words,22 November 2025,CNBC TV18,CNBCTV,NaN,English,Copyright 2025 TV18 Broadcast Ltd.,"Congress MP Shashi Tharoor on Saturday, Novemb...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Long-term government the only solution to musi...,NaN,964 words,22 November 2025,smh.com.au,SMHHOL,NaN,English,Copyright © 2025 Fairfax Media Publications Pt...,Sean Kelly’s column relating to “long-term gov...,...,05:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,YXJ0aWNsZTo2ZGJkZjUzMC0zYzEwLTQyODAtODc1ZS1kY2...,NaN,NaN
1,"Mamdani, Trump pledge to work together for New...",NaN,836 words,22 November 2025,CE NoticiasFinancieras,NFINCE,NaN,English,Copyright © Content Engine LLC,"Washington and New York, New York's democratic...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Trump and Mamdani surprisingly go from adversa...,NaN,839 words,22 November 2025,Euronews,EURONEN,NaN,English,Copyright 2025 Euronews All Rights Reserved,US President Donald Trump on Friday met the ma...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,New York Mayor-elect Mamdani receives surprisi...,Minja Viitanen,386 words,22 November 2025,STT,STTEN,NaN,English,"Copyright 2025. STT, for more information see ...",The president said he was confident that the 3...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,New York Mayor-elect Mamdani receives surprisi...,Minja Viitanen,507 words,22 November 2025,STT,STTEN,NaN,English,"Copyright 2025. STT, for more information see ...",The president said he was confident that the 3...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"After Abrupt Halt, Citizenship Ceremonies Are ...",By Ana Ley,589 words,22 November 2025,The New York Times,NYTF,NaN,English,Copyright 2025 The New York Times Company. All...,At least seven counties had been affected by t...,...,NaN,NaN,uscis : United States Citizenship and Immigrat...,Late Edition - Final,16,NaN,NaN,NaN,NaN,NaN
1,Trump and Mamdani's News Conference: Read the ...,By The New York Times,6716 words,22 November 2025,The New York Times,NYTF,NaN,English,Copyright 2025 The New York Times Company. All...,"President Trump and Zohran Mamdani, the mayor-...",...,NaN,NaN,NaN,The New York Times on the Web,NaN,NaN,NaN,NaN,NaN,NaN
1,The First Madam President Is Still Coming,By Gail Collins,1163 words,22 November 2025,The New York Times,NYTF,NaN,English,Copyright 2025 The New York Times Company. All...,Did you notice that when we went to the polls ...,...,NaN,NaN,NaN,Late Edition - Final,23,NaN,GUEST ESSAY,NaN,NaN,NaN
1,'You can just say yes': Trump gives jaw-droppi...,India Blooms News Service,401 words,22 November 2025,India Blooms News Service,ATIBNS,NaN,English,"Copyright © 2025 India Blooms, distributed by ...",Washington DC/IBNS: A surprise intervention fr...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Distributed by Contify.com
1,"Shashi Tharoor lauds Trump-Mamdani meeting, ho...",NaN,367 words,22 November 2025,Moneycontrol.com,MONECT,NaN,English,Copyright 2025. www.moneycontrol.com [http://w...,Tharoor praised the Trump-Mamdani interaction ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Experts: Free child care in NYC feasible; Mamd...,"By Madeline Mitchell, USA TODAY",1070 words,22 November 2025,The Daily Times,DTMD,NaN,English,© Copyright Gannett 2025 All Rights Reserved.,"Rebecca Bailin pays $32,000 a year for her fiv...",...,NaN,NaN,NaN,1; ESN,A2,NaN,NaN,NaN,NaN,NaN
1,Hopkins Political Union hosts debate about the...,NaN,880 words,22 November 2025,U-Wire,UWIR,NaN,English,"© 2025, M2 Communications. All rights reserved.","Johns Hopkins University ; Baltimore, MD - new...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Columbia considers expanding undergraduate enr...,NaN,2996 words,22 November 2025,U-Wire,UWIR,NaN,English,"© 2025, M2 Communications. All rights reserved.","Columbia University ; New York, NY - news By M...",...,NaN,NaN,colunv : Columbia University,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HIGHLIGHTS,NaN,516 words,22 November 2025,Press Trust of India,PRTRIN,NaN,English,Copyright 2025. The Press Trust of India Limited.,"New Delhi, Nov 22 (PTI) Following are the top ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Royals to Republicans—Epstein files have expos...,Keshav Padmanabhan,1243 words,22 November 2025,ThePrint,THEPRT,NaN,English,Copyright 2025 Printline Media Pvt. Ltd.,"Donald Trump, who has nurtured the MAGA moveme...",...,12:41 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Shashi Tharoor's message for Congress? On Trum...,HT News Desk,557 words,22 November 2025,Hindustan Times,HNTM,NaN,English,Copyright 2025. HT Media Limited. All rights r...,"India, Nov. 22 -- Congress MP Shashi Tharoor o...",...,NaN,NaN,NaN,NaN,NaN,For any query with respect to this article or ...,NaN,NaN,NaN,NaN
1,Trump and Mamdani Set Aside Differences -- WSJ,NaN,1148 words,22 November 2025,Dow Jones Newswires,DJDN,NaN,English,"Copyright © 2025, Dow Jones & Company, Inc.","At White House meeting, tensions ease after mo...",...,02:33 AM,NaN,NaN,NaN,A4,NaN,NaN,NaN,NaN,NaN
1,U.S. News: Trump and Mamdani Set Aside Differe...,By Natalie Andrews and James Fanelli,719 words,22 November 2025,The Wall Street Journal,J,NaN,English,"Copyright 2025 Dow Jones & Company, Inc. All R...",WASHINGTON -- President Trump and New York Cit...,...,NaN,NaN,NaN,NaN,A4,NaN,NaN,NaN,EXE | LLM | LOC | NND | UCPP | UCPR | USG | USN,NaN
1,"Trump, Mamdani pledge cooperation after White ...",NaN,426 words,22 November 2025,The Punch,TPUNC,NaN,English,Copyright 2015 - Punch Newspapers,United States President Donald Trump and New Y...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Trump and Mamdani, long foes, emerge from meet...",Natalie Allison,1773 words,22 November 2025,The Washington Post,WP,NaN,English,"Copyright 2025, The Washington Post Co. All Ri...",President Donald Trump and New York Mayor-elec...,...,NaN,NaN,NaN,FINAL,A01,http://www.washingtonpost.com [http://www.wash...,NaN,WP20251122TRUMPMAMDANI,NaN,NaN
1,"In Mamdani-Trump White House Meeting, A Mentio...",NaN,620 words,22 November 2025,Times Now,TIMNOW,NaN,English,"Copyright 2025 Bennett, Coleman & Co. Ltd.",The Mamdani-Trump meeting at the White House s...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Trump predicts Mamdani will be ‘really great m...,Andrew Feinberg,1003 words,22 November 2025,Independent Online,INDOP,NaN,English,© 2025. Independent Digital News and Media Ltd...,Self-avowed socialist who has called Trump a ‘...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Trump strikes a surprising tone, says it's oka...",Trending Desk,633 words,22 November 2025,The Economic Times,ECTIM,NaN,English,(c) 2025 The Times of India Group. All rights ...,President Donald Trump joked that it was okay ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Take a look at the columns in our `frames` dataframe. The columns correspond to the index on the left column of the print view of articles in Factiva.

In [16]:
frames.columns

Index(['HD', 'BY', 'WC', 'PD', 'SN', 'SC', 'VOL', 'LA', 'CY', 'LP', 'TD', 'NS',
       'RE', 'PUB', 'AN', 'SE', 'IPD', 'ET', 'IN', 'CO', 'ED', 'PG', 'CT',
       'CLM', 'RF', 'IPC', 'CR'],
      dtype='object', name=0)

Next, let's rename certain columns to more meaningful or readable names (e.g., 'HD' becomes 'Headline', 'PD' becomes 'Publication_Date', etc.) and select only the relevant columns we want to keep.

In [18]:
frames.rename(columns = {'HD': 'Headline',
                         'PD': 'Publication_Date','SN': 'Source_Name', 'LP': 'Lead Paragraph',
                          'TD': 'Body',
                         'BY':'Author_Name'}, inplace=True)

frames = frames[['Headline', 'Publication_Date', 'Source_Name', 'Lead Paragraph', 'Body', 'Author_Name']]

/tmp/ipython-input-2291918199.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frames.rename(columns = {'HD': 'Headline',

Let's make sure our `Publication_Date` column is in datetime format.

In [19]:
frames['Publication_Date'] = pd.to_datetime(frames['Publication_Date'])
frames.sort_values(by='Publication_Date', inplace=True)

Next, we want to combine the text from the `Lead Paragraph` and the `Body` columns so we have the full article in a single cell.

In [20]:
frames['CombinedText'] = frames['Lead Paragraph'] + " " + frames['Body']

In [21]:
frames

,Headline,Publication_Date,Source_Name,Lead Paragraph,Body,Author_Name,CombinedText
1,The Surprise Ending to the Trump-Mamdani Buddy...,2025-11-21,nytimes.com,Zohran Mamdani and President Trump seemed to c...,And when reporters tried to interrupt the unex...,By Dana Rubinstein and Benjamin Oreskes,Zohran Mamdani and President Trump seemed to c...
1,"‘Fascist’? ‘Communist’? For an Afternoon, They...",2025-11-21,nytimes.com,Acid insults were set aside as New York’s mayo...,The 34-year-old mayor-elect of New York was pr...,By Shawn McCreesh,Acid insults were set aside as New York’s mayo...
1,'This is how democracy should work': Shashi Th...,2025-11-22,CNBC TV18,"Congress MP Shashi Tharoor on Saturday, Novemb...","Responding to a clip from the meeting, Tharoor...",CNBC-TV18,"Congress MP Shashi Tharoor on Saturday, Novemb..."
1,Long-term government the only solution to musi...,2025-11-22,smh.com.au,Sean Kelly’s column relating to “long-term gov...,There will be no change without long-term gove...,NaN,Sean Kelly’s column relating to “long-term gov...
1,"Mamdani, Trump pledge to work together for New...",2025-11-22,CE NoticiasFinancieras,"Washington and New York, New York's democratic...","Zohran Mamdani, who has called Trump a ""despot...",NaN,"Washington and New York, New York's democratic..."
1,Trump and Mamdani surprisingly go from adversa...,2025-11-22,Euronews,US President Donald Trump on Friday met the ma...,"Trump, who had in the past called Mamdani a “1...",NaN,US President Donald Trump on Friday met the ma...
1,New York Mayor-elect Mamdani receives surprisi...,2025-11-22,STT,The president said he was confident that the 3...,"The duo, who spoke during Mamdan's election ca...",Minja Viitanen,The president said he was confident that the 3...
1,New York Mayor-elect Mamdani receives surprisi...,2025-11-22,STT,The president said he was confident that the 3...,"The duo, who spoke during Mamdan's election ca...",Minja Viitanen,The president said he was confident that the 3...
1,"After Abrupt Halt, Citizenship Ceremonies Are ...",2025-11-22,The New York Times,At least seven counties had been affected by t...,The agency had said on Tuesday that county cou...,By Ana Ley,At least seven counties had been affected by t...
1,Trump and Mamdani's News Conference: Read the ...,2025-11-22,The New York Times,"President Trump and Zohran Mamdani, the mayor-...","Here is a transcript of their comments, lightl...",By The New York Times,"President Trump and Zohran Mamdani, the mayor-..."
1,The First Madam President Is Still Coming,2025-11-22,The New York Times,Did you notice that when we went to the polls ...,"Hey, wait a minute. We're going to celebrate t...",By Gail Collins,Did you notice that when we went to the polls ...
1,'You can just say yes': Trump gives jaw-droppi...,2025-11-22,India Blooms News Service,Washington DC/IBNS: A surprise intervention fr...,"""I've spoken about,"" Mamdani said as he tried ...",India Blooms News Service,Washington DC/IBNS: A surprise intervention fr...
1,Trump and Mamdani go from adversaries to allies,2025-11-22,Daily Herald,WASHINGTON — President Donald Trump on Friday ...,"Trump, who had in the past called Mamdani a “1...",Associated Press,WASHINGTON — President Donald Trump on Friday ...
1,NYC’s matching funds fueled Mamdani’s success,2025-11-22,New York Daily News,Zohran Mamdani’s insurgent win has spawned end...,"Former Gov. Andrew Cuomo, Republican Curtis Sl...",NaN,Zohran Mamdani’s insurgent win has spawned end...
1,Experts: Free child care in NYC feasible; Mamd...,2025-11-22,The Daily Times,"Rebecca Bailin pays $32,000 a year for her fiv...","Along with being a parent, Bailin is executive...","By Madeline Mitchell, USA TODAY","Rebecca Bailin pays $32,000 a year for her fiv..."
1,Hopkins Political Union hosts debate about the...,2025-11-22,U-Wire,"Johns Hopkins University ; Baltimore, MD - new...","On Tuesday, Nov. 11, the Hopkins Political Uni...",NaN,"Johns Hopkins University ; Baltimore, MD - new..."
1,Columbia considers expanding undergraduate enr...,2025-11-22,U-Wire,"Columbia University ; New York, NY - news By M...",Columbia is considering expanding undergraduat...,NaN,"Columbia University ; New York, NY - news By M..."
1,HIGHLIGHTS,2025-11-22,Press Trust of India,"New Delhi, Nov 22 (PTI) Following are the top ...",MDS12 TN-CONG-DMK-PANEL (12.31 PM) **** 2026 p...,NaN,"New Delhi, Nov 22 (PTI) Following are the top ..."
1,Royals to Republicans—Epstein files have expos...,2025-11-22,ThePrint,"Donald Trump, who has nurtured the MAGA moveme...","Some of the most well–known power brokers, sci...",Keshav Padmanabhan,"Donald Trump, who has nurtured the MAGA moveme..."
1,Shashi Tharoor's message for Congress? On Trum...,2025-11-22,Hindustan Times,"India, Nov. 22 -- Congress MP Shashi Tharoor o...","Responding to a clip from the meeting, Tharoor...",HT News Desk,"India, Nov. 22 -- Congress MP Shashi Tharoor o..."
1,Trump and Mamdani Set Aside Differences -- WSJ,2025-11-22,Dow Jones Newswires,"At White House meeting, tensions ease after mo...",WASHINGTON -- President Trump and New York Cit...,NaN,"At White House meeting, tensions ease after mo..."
1,U.S. News: Trump and Mamdani Set Aside Differe...,2025-11-22,The Wall Street Journal,WASHINGTON -- President Trump and New York Cit...,Both men largely avoided directly criticizing ...,By Natalie Andrews and James Fanelli,WASHINGTON -- President Trump and New York Cit...
1,"Trump, Mamdani pledge cooperation after White ...",2025-11-22,The Punch,United States President Donald Trump and New Y...,"“We’ve just had a great meeting, a really prod...",NaN,United States President Donald Trump and New Y...
1,"Trump and Mamdani, long foes, emerge from meet...",2025-11-22,The Washington Post,President Donald Trump and New York Mayor-elec...,"It was as if Trump, seated at the Resolute Des...",Natalie Allison,President Donald Trump and New York Mayor-elec...
1,"In Mamdani-Trump White House Meeting, A Mentio...",2025-11-22,Times Now,The Mamdani-Trump meeting at the White House s...,"With Mamdani standing next to him, Trump repea...",NaN,The Mamdani-Trump meeting at the White House s...
1,"Shashi Tharoor lauds Trump-Mamdani meeting, ho...",2025-11-22,Moneycontrol.com,Tharoor praised the Trump-Mamdani interaction ...,"Sharing his views on X, Tharoor wrote, “This i...",NaN,Tharoor praised the Trump-Mamdani interaction ...
1,Piggy Gets Polite,2025-11-22,nytimes.com,"Step by slimy step, President Trump has made u...","Still, some moments shock as beyond the pale. ...",By Maureen Dowd,"Step by slimy step, President Trump has made u..."
1,"Trump strikes a surprising tone, says it's oka...",2025-11-22,The Economic Times,President Donald Trump joked that it was okay ...,Check detailsTrump calls meeting with Mamdani ...,Trending Desk,President Donald Trump joked that it was okay ...
1,Trump predicts Mamdani will be ‘really great m...,2025-11-22,Independent Online,Self-avowed socialist who has called Trump a ‘...,Seated behind his desk in the Oval Office whil...,Andrew Feinberg,Self-avowed socialist who has called Trump a ‘...
1,The Trump-Mamdani show,2025-11-22,washingtonpost.com,What are a few deportation threats among frien...,"""The better he does, the happier I am,"" Trump ...",By Editorial Board,What are a few deportation threats among frien...
1,Trump and New York City mayor-elect Zohran Mam...,2025-11-22,scmp.com,"Their first meeting brought unexpected warmth,...","“Some of his ideas are the same as my ideas,” ...",Khushboo Razdan,"Their first meeting brought unexpected warmth,..."
1,The Weird Mystery of Olivia Nuzzi’s Teenage Po...,2025-11-22,Rolling Stone,The controversial journalist reportedly had a ...,Olivia Nuzzi is no stranger to controversy. Th...,By Rob Sheffield,The controversial journalist reportedly had a ...
1,Pushing Off,2025-11-22,nytimes.com,Thanksgiving’s this coming week. How can we ke...,"The holiday season has its own engine, one tha...",By Melissa Kirsch,Thanksgiving’s this coming week. How can we ke...
1,How Zohran Mamdani's NYC victory could make a ...,2025-11-22,Business Insider,* Incoming NYC Mayor Mamdani's embrace of soci...,* This comes after a banner year for ultra-lux...,Alex Nicoll,* Incoming NYC Mayor Mamdani's embrace of soci...
1,"Less politics, more makeup: the unraveling of ...",2025-11-22,The Guardian,The folding of the progressive youth-focused m...,"The story garnered more than 1.3m hits, making...",Carter Sherman,The folding of the progressive youth-focused m...
1,California Clears Path for Gig Unions,2025-11-22,Reason.com,"Even after the Prop 22 rebuke, California is p...","In October, California lawmakers passed a bill...",C. Jarrett Dieterle,"Even after the Prop 22 rebuke, California is p..."
1,What Trump and Mamdani have said about each ot...,2025-11-22,washingtonpost.com,"For months, President Donald Trump repeatedly ...",Here's what Trump and Mamdani have previously ...,By Victoria Bisset,"For months, President Donald Trump repeatedly ..."
1,What lessons can be learned from the Trump-Mam...,2025-11-22,jpost.com,United States President Donald Trump met with ...,"For some observers of Trump and Mamdani, the m...",NaN,United States President Donald Trump met with ...
1,Trump gloats over ‘traitor’ MTG’s decision to ...,2025-11-22,Independent Online,The Georgia firebrand’s upcoming exit from Con...,In a lengthy Truth Social [https://truthsocial...,Erin Keller,The Georgia firebrand’s upcoming exit from Con...
1,‘Cheering for him’: Key takeaways from Trump-M...,2025-11-22,Al Jazeera English,President Trump and the mayor-elect adopt a ma...,The warmth displayed came in stark contrast to...,Alastair McCready and News Agencies,President Trump and the mayor-elect adopt a ma...
1,THE RED APPLE | ZO THE BIG APPLE OF HIS EYE; B...,2025-11-22,New York Post,They found comrade ground. Zohran Mamdani's hi...,"A sitting Trump, with Mamdani standing by his ...","Steven Nelson, Craig McCarthy and Matt Troutman",They found comrade ground. Zohran Mamdani's hi...
1,'Will Rahul Gandhi get the message?': BJP's ji...,2025-11-22,Hindustan Times,"India, Nov. 22 -- The BJP grabbed onto Shashi ...",It was this moment of putting the election sea...,HT News Desk,"India, Nov. 22 -- The BJP grabbed onto Shashi ..."
1,Trump met with New York's Muslim mayor-elect: ...,2025-11-22,CE NoticiasFinancieras,U.S. President Donald Trump met Friday with th...,"Trump, who in the past had called Mamdani a ""1...",NaN,U.S. President Donald Trump met Friday with th...
1,This week in business: A housing plateau colli...,2025-11-22,Fast Company,"This week, politics, memes, and protest moveme...",Here is what actually moved the week in busine...,Emily Price,"This week, politics, memes, and protest moveme..."
1,Ghosts of Radicals Past: What NYC’s New Mayor ...,2025-11-22,The National Herald,New York City found itself at the epicenter of...,Zoran Mamdani’s meteoric rise seems propelled ...,NaN,New York City found itself at the epicenter of...
1,Trump and Mamdani go from adversaries to allie...,2025-11-22,Tampa Bay Times,WASHINGTON — President Donald Trump on Friday ...,"Trump, who had in the past called Mamdani a “1...",Times news services,WASHINGTON — President Donald Trump on Friday ...
1,Are the rich fleeing Mamdani’s Manhattan? Not ...,2025-11-22,usatoday.com,NEW YORK − Margaret Flint was 18 when she firs...,"On Nov. 4, the day New York City elected a new...",Swapna Venugopal Ramaswamy,NEW YORK − Margaret Flint was 18 when she firs...
1,'Did 8 peace deals': Trump repeats role in Ind...,2025-11-22,The Times of India,NEW DELHI: US President Donald Trump on Friday...,After four days of drone and missile exchanges...,TOI News Desk,NEW DELHI: US President Donald Trump on Friday...
1,"This is how democracy should work, hope to see...",2025-11-22,Press Trust of India,"New Delhi, Nov 22 (PTI) Congress leader Shashi...",Reposting on X a video of the meeting between ...,NaN,"New Delhi, Nov 22 (PTI) Congress leader Shashi..."
1,Chatti In NYC Brings Kerala's Toddy Shop Cultu...,2025-11-22,NDTV,There's a certain unbridled energy I experienc...,Photo Credit: Chatti It's no coincidence that ...,NaN,There's a certain unbridled energy I experienc...
1,"Don does a 180: instead of ripping Zoh, vows a...",2025-11-22,New York Daily News,During an extraordinarily cordial meeting at t...,But speaking to reporters in the Oval Office o...,Chris Sommerfeldt,During an extraordinarily cordial meeting at t...
1,‘I did 8 peace deals’: Trump again touts role ...,2025-11-22,Moneycontrol.com,The comments came during his meeting with New ...,The comments came during his meeting with New ...,NaN,The comments came during his meeting with New ...
1,REUTERS NEWS SCHEDULE AT 11:00 a.m. GMT/ 6:00 ...,2025-11-22,Reuters News,Here are the top stories and upcoming coverage...,GLOBAL CHINA-JAPAN China takes spat with Japan...,NaN,Here are the top stories and upcoming coverage...
1,"Munis steady, issuance falls to $1.2B",2025-11-24,The Bond Buyer,Municipals were steady Friday ahead of a paltr...,"The muni market is slowing, Barclays analysts ...",Christina Baker,Municipals were steady Friday ahead of a paltr...

Let's reset the index so it's the standard [0:] index, in ascending order.

In [22]:
df = frames.reset_index()

In [23]:
save_path = os.path.join(path, "factiva.csv")
df.to_csv(save_path, index=False)

Next, we will us a code that loops through each row in the DataFrame `df`, creates a unique text file for each row, and writes the content from the `CombinedText` column into that file. If the `CombinedText` value is missing (i.e., `NaN`), it writes an empty string instead. The filenames are generated dynamically based on the row index.

In essence, it saves the text content from each row in the DataFrame as individual text files.

1. **`for index, row in df.iterrows():`**
   - This line starts a loop over each row in the DataFrame `df`.
   - `df.iterrows()` is a pandas function that allows you to loop through the DataFrame row by row.
   - `index` represents the row number (starting from 0), and `row` contains the data for that specific row in the form of a pandas Series.

2. **`file_name = f"{path}/text_file_{index + 1}.txt"`**
   - This line generates a unique filename for each row.
   - The `f"{path}/text_file_{index + 1}.txt"` uses an f-string to create a file name based on the `index` (plus 1 to make it start at 1 instead of 0).
   - `path` is a variable that contains the directory where the file will be saved (it should be defined earlier in the code).
   - For example, for the first row (index 0), this would create a filename like `"path/to/directory/text_file_1.txt"`.

3. **`with open(file_name, 'w') as file:`**
   - This opens a file with the name `file_name` in write mode (`'w'`), allowing the program to write data into it.
   - The `with` statement ensures the file is properly closed after writing, even if an error occurs.

4. **`text_content = str(row['CombinedText']) if pd.notnull(row['CombinedText']) else ''`**
   - This checks the value in the `'CombinedText'` column for the current row.
   - **`pd.notnull(row['CombinedText'])`** checks if the value is **not** `NaN` (i.e., it’s not missing).
   - If the value is **not** `NaN`, it converts the value to a string using `str(row['CombinedText'])`.
   - If the value is `NaN`, it sets `text_content` to an empty string (`''`).
   - This ensures that no matter what value is in the `CombinedText` column, you will have valid text to write to the file (either the text itself or an empty string).

5. **`file.write(text_content)`**
   - This writes the `text_content` (the string version of the `CombinedText` value) to the file.
   - If the `CombinedText` was `NaN`, it writes an empty string; otherwise, it writes the actual content from that column.

In [ ]:
for index, row in df.iterrows():
    file_name = f"{path}/factiva/text_file_{index + 1}.txt"  # Create a unique filename for each row
    with open(file_name, 'w') as file:
        text_content = str(row['CombinedText']) if pd.notnull(row['CombinedText']) else ''  # Convert to string and handle NaN
        file.write(text_content)  # Write the text content to the file